# MP2 Part 1 — Commit retrieval (gelkhoda)
Retrieves all WoC commits for my 10 assigned projects plus GitHub stats.
Run top to bottom (Colab or hydra). Retrieval is cached per project in `cache/`, so a crash can simply be re-run.

In [1]:
!python -m pip install -q -U python-woc pandas matplotlib requests tqdm

In [1]:
NETID = 'gelkhoda'
GH_TOKEN = ''   # optional GitHub personal access token (avoids the 60 req/hr limit)
WOC_KEY = ''    # optional WoC API key

import os, time, re, requests
import pandas as pd
from tqdm import tqdm
from woc.remote import WocMapsRemote

woc = WocMapsRemote(base_url='https://worldofcode.org/api/', **({'api_key': WOC_KEY} if WOC_KEY else {}))

assign = pd.read_csv('net2prj.csv')
assign.columns = [c.strip() for c in assign.columns]
mine = assign[assign['netID'].str.strip() == NETID].reset_index(drop=True)
mine['GH'] = mine['GH'].str.strip()
mine

,netID,WoC,GH
0,gelkhoda,gsi-cs-co_chart-fx,https://github.com/GSI-CS-CO/chart-fx
1,gelkhoda,bsaul_inferference,https://github.com/bsaul/inferference
2,gelkhoda,daohu527_dig-into-apollo,https://github.com/daohu527/Dig-into-Apollo
3,gelkhoda,martin2250_opencncpilot,https://github.com/martin2250/OpenCNCPilot
4,gelkhoda,usgs-astrogeology_isis3,https://github.com/USGS-Astrogeology/ISIS3
5,gelkhoda,sakov_enkf-c,https://github.com/sakov/enkf-c
6,gelkhoda,sfc-aqua_quisp,https://github.com/sfc-aqua/quisp
7,gelkhoda,stan-dev_rstanarm,https://github.com/stan-dev/rstanarm
8,gelkhoda,copasi_copasi-dependencies,https://github.com/copasi/copasi-dependencies
9,gelkhoda,almost-matching-exactly_dame-python-package,https://github.com/almost-matching-exactly/dam...

In [3]:
os.makedirs('cache', exist_ok=True)
CHUNK = 10   # WoC max batch size (README: keep chunks < 50 and wait between requests)

def fetch_batch(shas, tries=6):
    for a in range(tries):
        try:
            res, err = woc.get_values_many('commit.tch', shas)
            return {k: v[0] for k, v in res.items()}, err
        except Exception as e:
            wait = 5 * (a + 1)
            print(f'  batch error ({e}); retry in {wait}s'); time.sleep(wait)
    raise RuntimeError('batch failed repeatedly')

def get_project(wocid):
    cache = f'cache/{wocid}.csv'
    if os.path.exists(cache):
        return pd.read_csv(cache, sep=';', keep_default_na=False, dtype={'commit_sha1': str, 'author': str, 'commit message': str})
    shas = list(dict.fromkeys(woc.get_values('p2c', wocid)))
    print(wocid, '->', len(shas), 'commit sha1s')
    if not shas: raise ValueError(f'WoC returned no commits for {wocid} - check the project id')
    got = {}
    for i in tqdm(range(0, len(shas), CHUNK), desc=wocid):
        res, err = fetch_batch(shas[i:i+CHUNK])
        if err: print('  errors:', err)
        got.update(res); time.sleep(1)
    missing = [s for s in shas if s not in got]
    for i in range(0, len(missing), CHUNK):          # one retry pass for anything missed
        res, _ = fetch_batch(missing[i:i+CHUNK]); got.update(res); time.sleep(1)
    missing = [s for s in shas if s not in got]
    if missing: print(f'  WARNING: {len(missing)} commits could not be retrieved')
    rows = [{'project_wocid': wocid, 'commit_sha1': s, 'author': c[2][0],
             'time': int(c[2][1]), 'commit message': c[4]} for s, c in got.items()]
    d = pd.DataFrame(rows).sort_values('time').reset_index(drop=True)
    d.to_csv(cache, sep=';', index=False)
    return d

frames = [get_project(w) for w in mine['WoC']]
summary = pd.concat(frames, ignore_index=True)
summary.to_csv(f'{NETID}_project_summary.csv', sep=';', index=False)
print(len(summary), 'commits saved to', f'{NETID}_project_summary.csv')

gsi-cs-co_chart-fx -> 3641 commit sha1s

gsi-cs-co_chart-fx:   0%|                              | 0/365 [00:00<?, ?it/s]

gsi-cs-co_chart-fx:   0%|                      | 1/365 [00:01<06:14,  1.03s/it]

gsi-cs-co_chart-fx:   1%|                      | 2/365 [00:02<06:14,  1.03s/it]

gsi-cs-co_chart-fx:   1%|▏                     | 3/365 [00:03<06:14,  1.03s/it]

gsi-cs-co_chart-fx:   1%|▏                     | 4/365 [00:04<06:12,  1.03s/it]

gsi-cs-co_chart-fx:   1%|▎                     | 5/365 [00:05<06:11,  1.03s/it]

gsi-cs-co_chart-fx:   2%|▎                     | 6/365 [00:06<06:10,  1.03s/it]

gsi-cs-co_chart-fx:   2%|▍                     | 7/365 [00:07<06:09,  1.03s/it]

gsi-cs-co_chart-fx:   2%|▍                     | 8/365 [00:08<06:08,  1.03s/it]

  errors: {'05bef60a24ca40bdcee2dff902e5c5bef8685b6e': 'Key 05bef60a24ca40bdcee2dff902e5c5bef8685b6e not found in /da5_fast/All.sha1c/commit_5.tch'}

gsi-cs-co_chart-fx:   2%|▌                     | 9/365 [00:09<06:07,  1.03s/it]

gsi-cs-co_chart-fx:   3%|▌                    | 10/365 [00:10<06:06,  1.03s/it]

gsi-cs-co_chart-fx:   3%|▋                    | 11/365 [00:11<06:05,  1.03s/it]

gsi-cs-co_chart-fx:   3%|▋                    | 12/365 [00:12<06:04,  1.03s/it]

gsi-cs-co_chart-fx:   4%|▋                    | 13/365 [00:13<06:03,  1.03s/it]

gsi-cs-co_chart-fx:   4%|▊                    | 14/365 [00:14<06:02,  1.03s/it]

gsi-cs-co_chart-fx:   4%|▊                    | 15/365 [00:15<06:01,  1.03s/it]

gsi-cs-co_chart-fx:   4%|▉                    | 16/365 [00:16<06:00,  1.03s/it]

gsi-cs-co_chart-fx:   5%|▉                    | 17/365 [00:17<05:59,  1.03s/it]

gsi-cs-co_chart-fx:   5%|█                    | 18/365 [00:18<05:57,  1.03s/it]

gsi-cs-co_chart-fx:   5%|█                    | 19/365 [00:19<05:57,  1.03s/it]

gsi-cs-co_chart-fx:   5%|█▏                   | 20/365 [00:20<05:55,  1.03s/it]

gsi-cs-co_chart-fx:   6%|█▏                   | 21/365 [00:21<05:55,  1.03s/it]

gsi-cs-co_chart-fx:   6%|█▎                   | 22/365 [00:22<05:54,  1.03s/it]

gsi-cs-co_chart-fx:   6%|█▎                   | 23/365 [00:23<05:53,  1.03s/it]

gsi-cs-co_chart-fx:   7%|█▍                   | 24/365 [00:24<05:52,  1.03s/it]

gsi-cs-co_chart-fx:   7%|█▍                   | 25/365 [00:25<05:50,  1.03s/it]

gsi-cs-co_chart-fx:   7%|█▍                   | 26/365 [00:26<05:49,  1.03s/it]

gsi-cs-co_chart-fx:   7%|█▌                   | 27/365 [00:27<05:48,  1.03s/it]

gsi-cs-co_chart-fx:   8%|█▌                   | 28/365 [00:28<05:47,  1.03s/it]

gsi-cs-co_chart-fx:   8%|█▋                   | 29/365 [00:29<05:46,  1.03s/it]

gsi-cs-co_chart-fx:   8%|█▋                   | 30/365 [00:30<05:46,  1.03s/it]

gsi-cs-co_chart-fx:   8%|█▊                   | 31/365 [00:32<05:45,  1.03s/it]

gsi-cs-co_chart-fx:   9%|█▊                   | 32/365 [00:33<05:43,  1.03s/it]

gsi-cs-co_chart-fx:   9%|█▉                   | 33/365 [00:34<05:42,  1.03s/it]

gsi-cs-co_chart-fx:   9%|█▉                   | 34/365 [00:35<05:41,  1.03s/it]

gsi-cs-co_chart-fx:  10%|██                   | 35/365 [00:36<05:41,  1.03s/it]

gsi-cs-co_chart-fx:  10%|██                   | 36/365 [00:37<05:40,  1.03s/it]

gsi-cs-co_chart-fx:  10%|██▏                  | 37/365 [00:38<05:39,  1.04s/it]

gsi-cs-co_chart-fx:  10%|██▏                  | 38/365 [00:39<05:38,  1.04s/it]

gsi-cs-co_chart-fx:  11%|██▏                  | 39/365 [00:40<05:37,  1.04s/it]

gsi-cs-co_chart-fx:  11%|██▎                  | 40/365 [00:41<05:36,  1.04s/it]

gsi-cs-co_chart-fx:  11%|██▎                  | 41/365 [00:42<05:34,  1.03s/it]

gsi-cs-co_chart-fx:  12%|██▍                  | 42/365 [00:43<05:34,  1.03s/it]

gsi-cs-co_chart-fx:  12%|██▍                  | 43/365 [00:44<05:33,  1.04s/it]

gsi-cs-co_chart-fx:  12%|██▌                  | 44/365 [00:45<05:31,  1.03s/it]

gsi-cs-co_chart-fx:  12%|██▌                  | 45/365 [00:46<05:30,  1.03s/it]

gsi-cs-co_chart-fx:  13%|██▋                  | 46/365 [00:47<05:29,  1.03s/it]

gsi-cs-co_chart-fx:  13%|██▋                  | 47/365 [00:48<05:32,  1.05s/it]

gsi-cs-co_chart-fx:  13%|██▊                  | 48/365 [00:49<05:30,  1.04s/it]

gsi-cs-co_chart-fx:  13%|██▊                  | 49/365 [00:50<05:28,  1.04s/it]

gsi-cs-co_chart-fx:  14%|██▉                  | 50/365 [00:51<05:26,  1.04s/it]

gsi-cs-co_chart-fx:  14%|██▉                  | 51/365 [00:52<05:25,  1.04s/it]

gsi-cs-co_chart-fx:  14%|██▉                  | 52/365 [00:53<05:23,  1.03s/it]

gsi-cs-co_chart-fx:  15%|███                  | 53/365 [00:54<05:22,  1.03s/it]

gsi-cs-co_chart-fx:  15%|███                  | 54/365 [00:55<05:21,  1.03s/it]

gsi-cs-co_chart-fx:  15%|███▏                 | 55/365 [00:56<05:20,  1.03s/it]

gsi-cs-co_chart-fx:  15%|███▏                 | 56/365 [00:57<05:18,  1.03s/it]

gsi-cs-co_chart-fx:  16%|███▎                 | 57/365 [00:58<05:17,  1.03s/it]

gsi-cs-co_chart-fx:  16%|███▎                 | 58/365 [00:59<05:16,  1.03s/it]

gsi-cs-co_chart-fx:  16%|███▍                 | 59/365 [01:00<05:15,  1.03s/it]

gsi-cs-co_chart-fx:  16%|███▍                 | 60/365 [01:02<05:14,  1.03s/it]

gsi-cs-co_chart-fx:  17%|███▌                 | 61/365 [01:03<05:14,  1.03s/it]

gsi-cs-co_chart-fx:  17%|███▌                 | 62/365 [01:04<05:12,  1.03s/it]

gsi-cs-co_chart-fx:  17%|███▌                 | 63/365 [01:05<05:11,  1.03s/it]

gsi-cs-co_chart-fx:  18%|███▋                 | 64/365 [01:06<05:10,  1.03s/it]

gsi-cs-co_chart-fx:  18%|███▋                 | 65/365 [01:07<05:09,  1.03s/it]

gsi-cs-co_chart-fx:  18%|███▊                 | 66/365 [01:08<05:08,  1.03s/it]

gsi-cs-co_chart-fx:  18%|███▊                 | 67/365 [01:09<05:06,  1.03s/it]

gsi-cs-co_chart-fx:  19%|███▉                 | 68/365 [01:10<05:05,  1.03s/it]

gsi-cs-co_chart-fx:  19%|███▉                 | 69/365 [01:11<05:05,  1.03s/it]

gsi-cs-co_chart-fx:  19%|████                 | 70/365 [01:12<05:04,  1.03s/it]

gsi-cs-co_chart-fx:  19%|████                 | 71/365 [01:13<05:03,  1.03s/it]

gsi-cs-co_chart-fx:  20%|████▏                | 72/365 [01:14<05:02,  1.03s/it]

gsi-cs-co_chart-fx:  20%|████▏                | 73/365 [01:15<05:01,  1.03s/it]

gsi-cs-co_chart-fx:  20%|████▎                | 74/365 [01:16<05:00,  1.03s/it]

gsi-cs-co_chart-fx:  21%|████▎                | 75/365 [01:17<04:59,  1.03s/it]

gsi-cs-co_chart-fx:  21%|████▎                | 76/365 [01:18<04:58,  1.03s/it]

gsi-cs-co_chart-fx:  21%|████▍                | 77/365 [01:19<04:57,  1.03s/it]

gsi-cs-co_chart-fx:  21%|████▍                | 78/365 [01:20<04:56,  1.03s/it]

gsi-cs-co_chart-fx:  22%|████▌                | 79/365 [01:21<04:55,  1.03s/it]

gsi-cs-co_chart-fx:  22%|████▌                | 80/365 [01:22<04:54,  1.03s/it]

gsi-cs-co_chart-fx:  22%|████▋                | 81/365 [01:23<04:53,  1.03s/it]

gsi-cs-co_chart-fx:  22%|████▋                | 82/365 [01:24<04:52,  1.03s/it]

gsi-cs-co_chart-fx:  23%|████▊                | 83/365 [01:25<04:50,  1.03s/it]

gsi-cs-co_chart-fx:  23%|████▊                | 84/365 [01:26<04:49,  1.03s/it]

gsi-cs-co_chart-fx:  23%|████▉                | 85/365 [01:27<04:48,  1.03s/it]

gsi-cs-co_chart-fx:  24%|████▉                | 86/365 [01:28<04:48,  1.03s/it]

gsi-cs-co_chart-fx:  24%|█████                | 87/365 [01:29<04:46,  1.03s/it]

gsi-cs-co_chart-fx:  24%|█████                | 88/365 [01:30<04:45,  1.03s/it]

gsi-cs-co_chart-fx:  24%|█████                | 89/365 [01:31<04:44,  1.03s/it]

gsi-cs-co_chart-fx:  25%|█████▏               | 90/365 [01:32<04:43,  1.03s/it]

gsi-cs-co_chart-fx:  25%|█████▏               | 91/365 [01:34<04:42,  1.03s/it]

gsi-cs-co_chart-fx:  25%|█████▎               | 92/365 [01:35<04:41,  1.03s/it]

gsi-cs-co_chart-fx:  25%|█████▎               | 93/365 [01:36<04:40,  1.03s/it]

gsi-cs-co_chart-fx:  26%|█████▍               | 94/365 [01:37<04:39,  1.03s/it]

gsi-cs-co_chart-fx:  26%|█████▍               | 95/365 [01:38<04:38,  1.03s/it]

gsi-cs-co_chart-fx:  26%|█████▌               | 96/365 [01:39<04:37,  1.03s/it]

gsi-cs-co_chart-fx:  27%|█████▌               | 97/365 [01:40<04:36,  1.03s/it]

gsi-cs-co_chart-fx:  27%|█████▋               | 98/365 [01:41<04:36,  1.03s/it]

gsi-cs-co_chart-fx:  27%|█████▋               | 99/365 [01:42<04:34,  1.03s/it]

gsi-cs-co_chart-fx:  27%|█████▍              | 100/365 [01:43<04:33,  1.03s/it]

gsi-cs-co_chart-fx:  28%|█████▌              | 101/365 [01:44<04:32,  1.03s/it]

gsi-cs-co_chart-fx:  28%|█████▌              | 102/365 [01:45<04:31,  1.03s/it]

gsi-cs-co_chart-fx:  28%|█████▋              | 103/365 [01:46<04:30,  1.03s/it]

gsi-cs-co_chart-fx:  28%|█████▋              | 104/365 [01:47<04:29,  1.03s/it]

gsi-cs-co_chart-fx:  29%|█████▊              | 105/365 [01:48<04:28,  1.03s/it]

gsi-cs-co_chart-fx:  29%|█████▊              | 106/365 [01:49<04:26,  1.03s/it]

gsi-cs-co_chart-fx:  29%|█████▊              | 107/365 [01:50<04:26,  1.03s/it]

gsi-cs-co_chart-fx:  30%|█████▉              | 108/365 [01:51<04:26,  1.04s/it]

gsi-cs-co_chart-fx:  30%|█████▉              | 109/365 [01:52<04:24,  1.03s/it]

gsi-cs-co_chart-fx:  30%|██████              | 110/365 [01:53<04:23,  1.03s/it]

gsi-cs-co_chart-fx:  30%|██████              | 111/365 [01:54<04:22,  1.03s/it]

gsi-cs-co_chart-fx:  31%|██████▏             | 112/365 [01:55<04:21,  1.03s/it]

gsi-cs-co_chart-fx:  31%|██████▏             | 113/365 [01:56<04:20,  1.03s/it]

gsi-cs-co_chart-fx:  31%|██████▏             | 114/365 [01:57<04:19,  1.03s/it]

gsi-cs-co_chart-fx:  32%|██████▎             | 115/365 [01:58<04:17,  1.03s/it]

gsi-cs-co_chart-fx:  32%|██████▎             | 116/365 [01:59<04:16,  1.03s/it]

gsi-cs-co_chart-fx:  32%|██████▍             | 117/365 [02:00<04:15,  1.03s/it]

gsi-cs-co_chart-fx:  32%|██████▍             | 118/365 [02:01<04:14,  1.03s/it]

gsi-cs-co_chart-fx:  33%|██████▌             | 119/365 [02:02<04:13,  1.03s/it]

gsi-cs-co_chart-fx:  33%|██████▌             | 120/365 [02:03<04:12,  1.03s/it]

gsi-cs-co_chart-fx:  33%|██████▋             | 121/365 [02:04<04:11,  1.03s/it]

gsi-cs-co_chart-fx:  33%|██████▋             | 122/365 [02:06<04:10,  1.03s/it]

gsi-cs-co_chart-fx:  34%|██████▋             | 123/365 [02:07<04:09,  1.03s/it]

gsi-cs-co_chart-fx:  34%|██████▊             | 124/365 [02:08<04:08,  1.03s/it]

gsi-cs-co_chart-fx:  34%|██████▊             | 125/365 [02:09<04:08,  1.03s/it]

gsi-cs-co_chart-fx:  35%|██████▉             | 126/365 [02:10<04:06,  1.03s/it]

gsi-cs-co_chart-fx:  35%|██████▉             | 127/365 [02:11<04:05,  1.03s/it]

gsi-cs-co_chart-fx:  35%|███████             | 128/365 [02:12<04:10,  1.06s/it]

gsi-cs-co_chart-fx:  35%|███████             | 129/365 [02:13<04:07,  1.05s/it]

gsi-cs-co_chart-fx:  36%|███████             | 130/365 [02:14<04:05,  1.04s/it]

gsi-cs-co_chart-fx:  36%|███████▏            | 131/365 [02:15<04:03,  1.04s/it]

gsi-cs-co_chart-fx:  36%|███████▏            | 132/365 [02:16<04:02,  1.04s/it]

gsi-cs-co_chart-fx:  36%|███████▎            | 133/365 [02:17<04:00,  1.04s/it]

gsi-cs-co_chart-fx:  37%|███████▎            | 134/365 [02:18<03:59,  1.04s/it]

gsi-cs-co_chart-fx:  37%|███████▍            | 135/365 [02:19<03:58,  1.04s/it]

gsi-cs-co_chart-fx:  37%|███████▍            | 136/365 [02:20<03:56,  1.03s/it]

gsi-cs-co_chart-fx:  38%|███████▌            | 137/365 [02:21<03:55,  1.03s/it]

gsi-cs-co_chart-fx:  38%|███████▌            | 138/365 [02:22<03:54,  1.03s/it]

gsi-cs-co_chart-fx:  38%|███████▌            | 139/365 [02:23<03:53,  1.03s/it]

gsi-cs-co_chart-fx:  38%|███████▋            | 140/365 [02:24<03:52,  1.03s/it]

gsi-cs-co_chart-fx:  39%|███████▋            | 141/365 [02:25<03:51,  1.03s/it]

gsi-cs-co_chart-fx:  39%|███████▊            | 142/365 [02:26<03:50,  1.03s/it]

gsi-cs-co_chart-fx:  39%|███████▊            | 143/365 [02:27<03:49,  1.03s/it]

gsi-cs-co_chart-fx:  39%|███████▉            | 144/365 [02:28<03:48,  1.03s/it]

gsi-cs-co_chart-fx:  40%|███████▉            | 145/365 [02:29<03:47,  1.03s/it]

gsi-cs-co_chart-fx:  40%|████████            | 146/365 [02:30<03:46,  1.04s/it]

gsi-cs-co_chart-fx:  40%|████████            | 147/365 [02:31<03:45,  1.03s/it]

gsi-cs-co_chart-fx:  41%|████████            | 148/365 [02:32<03:44,  1.03s/it]

gsi-cs-co_chart-fx:  41%|████████▏           | 149/365 [02:33<03:43,  1.03s/it]

gsi-cs-co_chart-fx:  41%|████████▏           | 150/365 [02:35<03:42,  1.03s/it]

gsi-cs-co_chart-fx:  41%|████████▎           | 151/365 [02:36<03:40,  1.03s/it]

  errors: {'6b694ae775838a5756c630c965b343f243b23f3a': 'Key 6b694ae775838a5756c630c965b343f243b23f3a not found in /da5_fast/All.sha1c/commit_107.tch'}

gsi-cs-co_chart-fx:  42%|████████▎           | 152/365 [02:37<03:39,  1.03s/it]

gsi-cs-co_chart-fx:  42%|████████▍           | 153/365 [02:38<03:38,  1.03s/it]

gsi-cs-co_chart-fx:  42%|████████▍           | 154/365 [02:39<03:37,  1.03s/it]

gsi-cs-co_chart-fx:  42%|████████▍           | 155/365 [02:40<03:36,  1.03s/it]

gsi-cs-co_chart-fx:  43%|████████▌           | 156/365 [02:41<03:36,  1.03s/it]

gsi-cs-co_chart-fx:  43%|████████▌           | 157/365 [02:42<03:35,  1.03s/it]

gsi-cs-co_chart-fx:  43%|████████▋           | 158/365 [02:43<03:33,  1.03s/it]

gsi-cs-co_chart-fx:  44%|████████▋           | 159/365 [02:44<03:32,  1.03s/it]

gsi-cs-co_chart-fx:  44%|████████▊           | 160/365 [02:45<03:32,  1.03s/it]

gsi-cs-co_chart-fx:  44%|████████▊           | 161/365 [02:46<03:31,  1.04s/it]

gsi-cs-co_chart-fx:  44%|████████▉           | 162/365 [02:47<03:29,  1.03s/it]

gsi-cs-co_chart-fx:  45%|████████▉           | 163/365 [02:48<03:28,  1.03s/it]

gsi-cs-co_chart-fx:  45%|████████▉           | 164/365 [02:49<03:27,  1.03s/it]

  errors: {'7516999be182585304b8b53eba8d8b39c29266fc': 'Key 7516999be182585304b8b53eba8d8b39c29266fc not found in /da5_fast/All.sha1c/commit_117.tch'}

gsi-cs-co_chart-fx:  45%|█████████           | 165/365 [02:50<03:27,  1.04s/it]

gsi-cs-co_chart-fx:  45%|█████████           | 166/365 [02:51<03:25,  1.03s/it]

gsi-cs-co_chart-fx:  46%|█████████▏          | 167/365 [02:52<03:24,  1.03s/it]

gsi-cs-co_chart-fx:  46%|█████████▏          | 168/365 [02:53<03:23,  1.03s/it]

gsi-cs-co_chart-fx:  46%|█████████▎          | 169/365 [02:54<03:22,  1.03s/it]

gsi-cs-co_chart-fx:  47%|█████████▎          | 170/365 [02:55<03:21,  1.03s/it]

  errors: {'78b2048d6816447a7911b92fb3df2bb6db9b2b06': 'Key 78b2048d6816447a7911b92fb3df2bb6db9b2b06 not found in /da5_fast/All.sha1c/commit_120.tch'}

gsi-cs-co_chart-fx:  47%|█████████▎          | 171/365 [02:56<03:20,  1.03s/it]

gsi-cs-co_chart-fx:  47%|█████████▍          | 172/365 [02:57<03:19,  1.03s/it]

gsi-cs-co_chart-fx:  47%|█████████▍          | 173/365 [02:58<03:18,  1.03s/it]

gsi-cs-co_chart-fx:  48%|█████████▌          | 174/365 [02:59<03:17,  1.03s/it]

gsi-cs-co_chart-fx:  48%|█████████▌          | 175/365 [03:00<03:16,  1.03s/it]

  errors: {'7bcf7d25e816e9d1c22a2d9ea9854743595b19b2': 'Key 7bcf7d25e816e9d1c22a2d9ea9854743595b19b2 not found in /da5_fast/All.sha1c/commit_123.tch'}

gsi-cs-co_chart-fx:  48%|█████████▋          | 176/365 [03:01<03:15,  1.03s/it]

gsi-cs-co_chart-fx:  48%|█████████▋          | 177/365 [03:02<03:13,  1.03s/it]

gsi-cs-co_chart-fx:  49%|█████████▊          | 178/365 [03:03<03:12,  1.03s/it]

gsi-cs-co_chart-fx:  49%|█████████▊          | 179/365 [03:04<03:12,  1.03s/it]

gsi-cs-co_chart-fx:  49%|█████████▊          | 180/365 [03:06<03:11,  1.03s/it]

gsi-cs-co_chart-fx:  50%|█████████▉          | 181/365 [03:07<03:09,  1.03s/it]

gsi-cs-co_chart-fx:  50%|█████████▉          | 182/365 [03:08<03:08,  1.03s/it]

  errors: {'813f4d22194fa0dbe9ef445788f468a993e5a552': 'Key 813f4d22194fa0dbe9ef445788f468a993e5a552 not found in /da5_fast/All.sha1c/commit_1.tch'}

gsi-cs-co_chart-fx:  50%|██████████          | 183/365 [03:09<03:07,  1.03s/it]

gsi-cs-co_chart-fx:  50%|██████████          | 184/365 [03:10<03:05,  1.03s/it]

gsi-cs-co_chart-fx:  51%|██████████▏         | 185/365 [03:11<03:04,  1.02s/it]

gsi-cs-co_chart-fx:  51%|██████████▏         | 186/365 [03:12<03:03,  1.03s/it]

gsi-cs-co_chart-fx:  51%|██████████▏         | 187/365 [03:13<03:02,  1.03s/it]

gsi-cs-co_chart-fx:  52%|██████████▎         | 188/365 [03:14<03:01,  1.03s/it]

gsi-cs-co_chart-fx:  52%|██████████▎         | 189/365 [03:15<03:01,  1.03s/it]

gsi-cs-co_chart-fx:  52%|██████████▍         | 190/365 [03:16<03:00,  1.03s/it]

gsi-cs-co_chart-fx:  52%|██████████▍         | 191/365 [03:17<02:58,  1.03s/it]

gsi-cs-co_chart-fx:  53%|██████████▌         | 192/365 [03:18<02:58,  1.03s/it]

gsi-cs-co_chart-fx:  53%|██████████▌         | 193/365 [03:19<02:57,  1.03s/it]

gsi-cs-co_chart-fx:  53%|██████████▋         | 194/365 [03:20<02:56,  1.03s/it]

gsi-cs-co_chart-fx:  53%|██████████▋         | 195/365 [03:21<02:55,  1.03s/it]

gsi-cs-co_chart-fx:  54%|██████████▋         | 196/365 [03:22<02:54,  1.03s/it]

gsi-cs-co_chart-fx:  54%|██████████▊         | 197/365 [03:23<02:53,  1.03s/it]

gsi-cs-co_chart-fx:  54%|██████████▊         | 198/365 [03:24<02:52,  1.03s/it]

gsi-cs-co_chart-fx:  55%|██████████▉         | 199/365 [03:25<02:51,  1.03s/it]

gsi-cs-co_chart-fx:  55%|██████████▉         | 200/365 [03:26<02:50,  1.03s/it]

gsi-cs-co_chart-fx:  55%|███████████         | 201/365 [03:27<02:49,  1.03s/it]

gsi-cs-co_chart-fx:  55%|███████████         | 202/365 [03:28<02:48,  1.03s/it]

gsi-cs-co_chart-fx:  56%|███████████         | 203/365 [03:29<02:47,  1.03s/it]

gsi-cs-co_chart-fx:  56%|███████████▏        | 204/365 [03:30<02:46,  1.03s/it]

gsi-cs-co_chart-fx:  56%|███████████▏        | 205/365 [03:31<02:44,  1.03s/it]

gsi-cs-co_chart-fx:  56%|███████████▎        | 206/365 [03:32<02:44,  1.03s/it]

gsi-cs-co_chart-fx:  57%|███████████▎        | 207/365 [03:33<02:42,  1.03s/it]

gsi-cs-co_chart-fx:  57%|███████████▍        | 208/365 [03:34<02:41,  1.03s/it]

gsi-cs-co_chart-fx:  57%|███████████▍        | 209/365 [03:35<02:40,  1.03s/it]

gsi-cs-co_chart-fx:  58%|███████████▌        | 210/365 [03:36<02:39,  1.03s/it]

gsi-cs-co_chart-fx:  58%|███████████▌        | 211/365 [03:37<02:38,  1.03s/it]

gsi-cs-co_chart-fx:  58%|███████████▌        | 212/365 [03:38<02:37,  1.03s/it]

gsi-cs-co_chart-fx:  58%|███████████▋        | 213/365 [03:40<02:36,  1.03s/it]

gsi-cs-co_chart-fx:  59%|███████████▋        | 214/365 [03:41<02:35,  1.03s/it]

gsi-cs-co_chart-fx:  59%|███████████▊        | 215/365 [03:42<02:34,  1.03s/it]

gsi-cs-co_chart-fx:  59%|███████████▊        | 216/365 [03:43<02:33,  1.03s/it]

gsi-cs-co_chart-fx:  59%|███████████▉        | 217/365 [03:44<02:32,  1.03s/it]

gsi-cs-co_chart-fx:  60%|███████████▉        | 218/365 [03:45<02:31,  1.03s/it]

gsi-cs-co_chart-fx:  60%|████████████        | 219/365 [03:46<02:30,  1.03s/it]

gsi-cs-co_chart-fx:  60%|████████████        | 220/365 [03:47<02:29,  1.03s/it]

gsi-cs-co_chart-fx:  61%|████████████        | 221/365 [03:48<02:27,  1.03s/it]

gsi-cs-co_chart-fx:  61%|████████████▏       | 222/365 [03:49<02:26,  1.03s/it]

gsi-cs-co_chart-fx:  61%|████████████▏       | 223/365 [03:50<02:26,  1.03s/it]

gsi-cs-co_chart-fx:  61%|████████████▎       | 224/365 [03:51<02:25,  1.03s/it]

gsi-cs-co_chart-fx:  62%|████████████▎       | 225/365 [03:52<02:24,  1.03s/it]

gsi-cs-co_chart-fx:  62%|████████████▍       | 226/365 [03:53<02:23,  1.03s/it]

gsi-cs-co_chart-fx:  62%|████████████▍       | 227/365 [03:54<02:21,  1.03s/it]

gsi-cs-co_chart-fx:  62%|████████████▍       | 228/365 [03:55<02:20,  1.03s/it]

gsi-cs-co_chart-fx:  63%|████████████▌       | 229/365 [03:56<02:19,  1.03s/it]

gsi-cs-co_chart-fx:  63%|████████████▌       | 230/365 [03:57<02:18,  1.03s/it]

gsi-cs-co_chart-fx:  63%|████████████▋       | 231/365 [03:58<02:17,  1.03s/it]

gsi-cs-co_chart-fx:  64%|████████████▋       | 232/365 [03:59<02:16,  1.03s/it]

gsi-cs-co_chart-fx:  64%|████████████▊       | 233/365 [04:00<02:26,  1.11s/it]

gsi-cs-co_chart-fx:  64%|████████████▊       | 234/365 [04:01<02:22,  1.08s/it]

gsi-cs-co_chart-fx:  64%|████████████▉       | 235/365 [04:02<02:18,  1.07s/it]

gsi-cs-co_chart-fx:  65%|████████████▉       | 236/365 [04:03<02:16,  1.06s/it]

gsi-cs-co_chart-fx:  65%|████████████▉       | 237/365 [04:04<02:14,  1.05s/it]

gsi-cs-co_chart-fx:  65%|█████████████       | 238/365 [04:05<02:12,  1.04s/it]

gsi-cs-co_chart-fx:  65%|█████████████       | 239/365 [04:07<02:10,  1.04s/it]

gsi-cs-co_chart-fx:  66%|█████████████▏      | 240/365 [04:08<02:09,  1.04s/it]

gsi-cs-co_chart-fx:  66%|█████████████▏      | 241/365 [04:09<02:08,  1.03s/it]

gsi-cs-co_chart-fx:  66%|█████████████▎      | 242/365 [04:10<02:10,  1.06s/it]

gsi-cs-co_chart-fx:  67%|█████████████▎      | 243/365 [04:11<02:08,  1.05s/it]

gsi-cs-co_chart-fx:  67%|█████████████▎      | 244/365 [04:12<02:06,  1.05s/it]

gsi-cs-co_chart-fx:  67%|█████████████▍      | 245/365 [04:13<02:04,  1.04s/it]

gsi-cs-co_chart-fx:  67%|█████████████▍      | 246/365 [04:14<02:03,  1.04s/it]

gsi-cs-co_chart-fx:  68%|█████████████▌      | 247/365 [04:15<02:02,  1.03s/it]

gsi-cs-co_chart-fx:  68%|█████████████▌      | 248/365 [04:16<02:00,  1.03s/it]

gsi-cs-co_chart-fx:  68%|█████████████▋      | 249/365 [04:17<01:59,  1.03s/it]

gsi-cs-co_chart-fx:  68%|█████████████▋      | 250/365 [04:18<01:58,  1.03s/it]

gsi-cs-co_chart-fx:  69%|█████████████▊      | 251/365 [04:19<01:57,  1.03s/it]

gsi-cs-co_chart-fx:  69%|█████████████▊      | 252/365 [04:20<01:56,  1.03s/it]

gsi-cs-co_chart-fx:  69%|█████████████▊      | 253/365 [04:21<01:55,  1.03s/it]

gsi-cs-co_chart-fx:  70%|█████████████▉      | 254/365 [04:22<01:55,  1.04s/it]

gsi-cs-co_chart-fx:  70%|█████████████▉      | 255/365 [04:23<01:53,  1.03s/it]

gsi-cs-co_chart-fx:  70%|██████████████      | 256/365 [04:24<01:52,  1.03s/it]

gsi-cs-co_chart-fx:  70%|██████████████      | 257/365 [04:25<01:51,  1.03s/it]

gsi-cs-co_chart-fx:  71%|██████████████▏     | 258/365 [04:26<01:49,  1.03s/it]

gsi-cs-co_chart-fx:  71%|██████████████▏     | 259/365 [04:27<01:48,  1.03s/it]

gsi-cs-co_chart-fx:  71%|██████████████▏     | 260/365 [04:28<01:47,  1.03s/it]

gsi-cs-co_chart-fx:  72%|██████████████▎     | 261/365 [04:29<01:46,  1.03s/it]

gsi-cs-co_chart-fx:  72%|██████████████▎     | 262/365 [04:30<01:45,  1.03s/it]

gsi-cs-co_chart-fx:  72%|██████████████▍     | 263/365 [04:31<01:44,  1.03s/it]

gsi-cs-co_chart-fx:  72%|██████████████▍     | 264/365 [04:32<01:44,  1.03s/it]

  errors: {'b8f32cbf6db699f1299f78ba2a01706305287385': 'Key b8f32cbf6db699f1299f78ba2a01706305287385 not found in /da5_fast/All.sha1c/commit_56.tch'}

gsi-cs-co_chart-fx:  73%|██████████████▌     | 265/365 [04:33<01:43,  1.03s/it]

gsi-cs-co_chart-fx:  73%|██████████████▌     | 266/365 [04:34<01:42,  1.03s/it]

gsi-cs-co_chart-fx:  73%|██████████████▋     | 267/365 [04:35<01:40,  1.03s/it]

gsi-cs-co_chart-fx:  73%|██████████████▋     | 268/365 [04:36<01:39,  1.03s/it]

gsi-cs-co_chart-fx:  74%|██████████████▋     | 269/365 [04:38<01:38,  1.03s/it]

gsi-cs-co_chart-fx:  74%|██████████████▊     | 270/365 [04:39<01:37,  1.03s/it]

gsi-cs-co_chart-fx:  74%|██████████████▊     | 271/365 [04:40<01:36,  1.03s/it]

gsi-cs-co_chart-fx:  75%|██████████████▉     | 272/365 [04:41<01:35,  1.03s/it]

gsi-cs-co_chart-fx:  75%|██████████████▉     | 273/365 [04:42<01:34,  1.03s/it]

gsi-cs-co_chart-fx:  75%|███████████████     | 274/365 [04:43<01:33,  1.03s/it]

gsi-cs-co_chart-fx:  75%|███████████████     | 275/365 [04:44<01:32,  1.03s/it]

gsi-cs-co_chart-fx:  76%|███████████████     | 276/365 [04:45<01:31,  1.03s/it]

gsi-cs-co_chart-fx:  76%|███████████████▏    | 277/365 [04:46<01:30,  1.03s/it]

gsi-cs-co_chart-fx:  76%|███████████████▏    | 278/365 [04:47<01:29,  1.03s/it]

gsi-cs-co_chart-fx:  76%|███████████████▎    | 279/365 [04:48<01:28,  1.03s/it]

gsi-cs-co_chart-fx:  77%|███████████████▎    | 280/365 [04:49<01:27,  1.03s/it]

gsi-cs-co_chart-fx:  77%|███████████████▍    | 281/365 [04:50<01:26,  1.03s/it]

gsi-cs-co_chart-fx:  77%|███████████████▍    | 282/365 [04:51<01:25,  1.03s/it]

gsi-cs-co_chart-fx:  78%|███████████████▌    | 283/365 [04:52<01:24,  1.03s/it]

gsi-cs-co_chart-fx:  78%|███████████████▌    | 284/365 [04:53<01:23,  1.03s/it]

gsi-cs-co_chart-fx:  78%|███████████████▌    | 285/365 [04:54<01:22,  1.03s/it]

gsi-cs-co_chart-fx:  78%|███████████████▋    | 286/365 [04:55<01:21,  1.03s/it]

gsi-cs-co_chart-fx:  79%|███████████████▋    | 287/365 [04:56<01:20,  1.03s/it]

gsi-cs-co_chart-fx:  79%|███████████████▊    | 288/365 [04:57<01:19,  1.03s/it]

gsi-cs-co_chart-fx:  79%|███████████████▊    | 289/365 [04:58<01:18,  1.03s/it]

gsi-cs-co_chart-fx:  79%|███████████████▉    | 290/365 [04:59<01:17,  1.03s/it]

gsi-cs-co_chart-fx:  80%|███████████████▉    | 291/365 [05:00<01:16,  1.03s/it]

gsi-cs-co_chart-fx:  80%|████████████████    | 292/365 [05:01<01:15,  1.03s/it]

gsi-cs-co_chart-fx:  80%|████████████████    | 293/365 [05:02<01:14,  1.03s/it]

gsi-cs-co_chart-fx:  81%|████████████████    | 294/365 [05:03<01:13,  1.03s/it]

gsi-cs-co_chart-fx:  81%|████████████████▏   | 295/365 [05:04<01:12,  1.03s/it]

gsi-cs-co_chart-fx:  81%|████████████████▏   | 296/365 [05:05<01:11,  1.03s/it]

gsi-cs-co_chart-fx:  81%|████████████████▎   | 297/365 [05:06<01:10,  1.03s/it]

gsi-cs-co_chart-fx:  82%|████████████████▎   | 298/365 [05:07<01:09,  1.03s/it]

gsi-cs-co_chart-fx:  82%|████████████████▍   | 299/365 [05:08<01:08,  1.03s/it]

gsi-cs-co_chart-fx:  82%|████████████████▍   | 300/365 [05:09<01:07,  1.03s/it]

gsi-cs-co_chart-fx:  82%|████████████████▍   | 301/365 [05:10<01:06,  1.03s/it]

gsi-cs-co_chart-fx:  83%|████████████████▌   | 302/365 [05:12<01:04,  1.03s/it]

gsi-cs-co_chart-fx:  83%|████████████████▌   | 303/365 [05:13<01:03,  1.03s/it]

gsi-cs-co_chart-fx:  83%|████████████████▋   | 304/365 [05:14<01:02,  1.03s/it]

gsi-cs-co_chart-fx:  84%|████████████████▋   | 305/365 [05:15<01:01,  1.03s/it]

gsi-cs-co_chart-fx:  84%|████████████████▊   | 306/365 [05:16<01:00,  1.03s/it]

gsi-cs-co_chart-fx:  84%|████████████████▊   | 307/365 [05:17<00:59,  1.03s/it]

gsi-cs-co_chart-fx:  84%|████████████████▉   | 308/365 [05:18<00:58,  1.03s/it]

gsi-cs-co_chart-fx:  85%|████████████████▉   | 309/365 [05:19<00:57,  1.03s/it]

gsi-cs-co_chart-fx:  85%|████████████████▉   | 310/365 [05:20<00:56,  1.03s/it]

gsi-cs-co_chart-fx:  85%|█████████████████   | 311/365 [05:21<00:55,  1.03s/it]

gsi-cs-co_chart-fx:  85%|█████████████████   | 312/365 [05:22<00:54,  1.03s/it]

gsi-cs-co_chart-fx:  86%|█████████████████▏  | 313/365 [05:23<00:53,  1.03s/it]

gsi-cs-co_chart-fx:  86%|█████████████████▏  | 314/365 [05:24<00:52,  1.03s/it]

gsi-cs-co_chart-fx:  86%|█████████████████▎  | 315/365 [05:25<00:51,  1.03s/it]

gsi-cs-co_chart-fx:  87%|█████████████████▎  | 316/365 [05:26<00:50,  1.03s/it]

gsi-cs-co_chart-fx:  87%|█████████████████▎  | 317/365 [05:27<00:49,  1.03s/it]

gsi-cs-co_chart-fx:  87%|█████████████████▍  | 318/365 [05:28<00:48,  1.03s/it]

gsi-cs-co_chart-fx:  87%|█████████████████▍  | 319/365 [05:29<00:47,  1.03s/it]

gsi-cs-co_chart-fx:  88%|█████████████████▌  | 320/365 [05:30<00:46,  1.03s/it]

gsi-cs-co_chart-fx:  88%|█████████████████▌  | 321/365 [05:31<00:45,  1.03s/it]

gsi-cs-co_chart-fx:  88%|█████████████████▋  | 322/365 [05:32<00:44,  1.03s/it]

gsi-cs-co_chart-fx:  88%|█████████████████▋  | 323/365 [05:33<00:43,  1.03s/it]

gsi-cs-co_chart-fx:  89%|█████████████████▊  | 324/365 [05:34<00:42,  1.03s/it]

gsi-cs-co_chart-fx:  89%|█████████████████▊  | 325/365 [05:35<00:41,  1.03s/it]

gsi-cs-co_chart-fx:  89%|█████████████████▊  | 326/365 [05:36<00:40,  1.03s/it]

gsi-cs-co_chart-fx:  90%|█████████████████▉  | 327/365 [05:37<00:39,  1.03s/it]

gsi-cs-co_chart-fx:  90%|█████████████████▉  | 328/365 [05:38<00:38,  1.03s/it]

gsi-cs-co_chart-fx:  90%|██████████████████  | 329/365 [05:39<00:37,  1.03s/it]

gsi-cs-co_chart-fx:  90%|██████████████████  | 330/365 [05:40<00:36,  1.03s/it]

gsi-cs-co_chart-fx:  91%|██████████████████▏ | 331/365 [05:41<00:35,  1.03s/it]

gsi-cs-co_chart-fx:  91%|██████████████████▏ | 332/365 [05:42<00:34,  1.03s/it]

gsi-cs-co_chart-fx:  91%|██████████████████▏ | 333/365 [05:43<00:32,  1.03s/it]

gsi-cs-co_chart-fx:  92%|██████████████████▎ | 334/365 [05:45<00:31,  1.03s/it]

gsi-cs-co_chart-fx:  92%|██████████████████▎ | 335/365 [05:46<00:30,  1.03s/it]

gsi-cs-co_chart-fx:  92%|██████████████████▍ | 336/365 [05:47<00:29,  1.03s/it]

gsi-cs-co_chart-fx:  92%|██████████████████▍ | 337/365 [05:48<00:28,  1.03s/it]

gsi-cs-co_chart-fx:  93%|██████████████████▌ | 338/365 [05:49<00:27,  1.03s/it]

gsi-cs-co_chart-fx:  93%|██████████████████▌ | 339/365 [05:50<00:26,  1.03s/it]

gsi-cs-co_chart-fx:  93%|██████████████████▋ | 340/365 [05:51<00:25,  1.03s/it]

gsi-cs-co_chart-fx:  93%|██████████████████▋ | 341/365 [05:52<00:24,  1.03s/it]

gsi-cs-co_chart-fx:  94%|██████████████████▋ | 342/365 [05:53<00:23,  1.03s/it]

gsi-cs-co_chart-fx:  94%|██████████████████▊ | 343/365 [05:54<00:22,  1.03s/it]

gsi-cs-co_chart-fx:  94%|██████████████████▊ | 344/365 [05:55<00:21,  1.03s/it]

gsi-cs-co_chart-fx:  95%|██████████████████▉ | 345/365 [05:56<00:20,  1.03s/it]

gsi-cs-co_chart-fx:  95%|██████████████████▉ | 346/365 [05:57<00:19,  1.03s/it]

gsi-cs-co_chart-fx:  95%|███████████████████ | 347/365 [05:58<00:18,  1.03s/it]

gsi-cs-co_chart-fx:  95%|███████████████████ | 348/365 [05:59<00:17,  1.03s/it]

gsi-cs-co_chart-fx:  96%|███████████████████ | 349/365 [06:00<00:16,  1.03s/it]

gsi-cs-co_chart-fx:  96%|███████████████████▏| 350/365 [06:01<00:15,  1.03s/it]

gsi-cs-co_chart-fx:  96%|███████████████████▏| 351/365 [06:02<00:14,  1.03s/it]

  errors: {'f5c6d7f017f560d951da23e4df03508ed2eaecf4': 'Key f5c6d7f017f560d951da23e4df03508ed2eaecf4 not found in /da5_fast/All.sha1c/commit_117.tch'}

gsi-cs-co_chart-fx:  96%|███████████████████▎| 352/365 [06:03<00:13,  1.03s/it]

gsi-cs-co_chart-fx:  97%|███████████████████▎| 353/365 [06:04<00:12,  1.03s/it]

gsi-cs-co_chart-fx:  97%|███████████████████▍| 354/365 [06:05<00:11,  1.03s/it]

gsi-cs-co_chart-fx:  97%|███████████████████▍| 355/365 [06:06<00:10,  1.03s/it]

gsi-cs-co_chart-fx:  98%|███████████████████▌| 356/365 [06:07<00:09,  1.03s/it]

gsi-cs-co_chart-fx:  98%|███████████████████▌| 357/365 [06:08<00:08,  1.03s/it]

gsi-cs-co_chart-fx:  98%|███████████████████▌| 358/365 [06:09<00:07,  1.03s/it]

gsi-cs-co_chart-fx:  98%|███████████████████▋| 359/365 [06:10<00:06,  1.03s/it]

gsi-cs-co_chart-fx:  99%|███████████████████▋| 360/365 [06:11<00:05,  1.03s/it]

gsi-cs-co_chart-fx:  99%|███████████████████▊| 361/365 [06:12<00:04,  1.03s/it]

gsi-cs-co_chart-fx:  99%|███████████████████▊| 362/365 [06:13<00:03,  1.03s/it]

gsi-cs-co_chart-fx:  99%|███████████████████▉| 363/365 [06:14<00:02,  1.03s/it]

gsi-cs-co_chart-fx: 100%|███████████████████▉| 364/365 [06:15<00:01,  1.03s/it]

gsi-cs-co_chart-fx: 100%|████████████████████| 365/365 [06:16<00:00,  1.02s/it]

gsi-cs-co_chart-fx: 100%|████████████████████| 365/365 [06:16<00:00,  1.03s/it]

  WARNING: 8 commits could not be retrieved
bsaul_inferference -> 329 commit sha1s

bsaul_inferference:   0%|                               | 0/33 [00:00<?, ?it/s]

bsaul_inferference:   3%|▋                      | 1/33 [00:01<00:32,  1.03s/it]

bsaul_inferference:   6%|█▍                     | 2/33 [00:02<00:31,  1.03s/it]

bsaul_inferference:   9%|██                     | 3/33 [00:03<00:30,  1.03s/it]

bsaul_inferference:  12%|██▊                    | 4/33 [00:04<00:29,  1.03s/it]

bsaul_inferference:  15%|███▍                   | 5/33 [00:05<00:28,  1.03s/it]

bsaul_inferference:  18%|████▏                  | 6/33 [00:06<00:27,  1.03s/it]

bsaul_inferference:  21%|████▉                  | 7/33 [00:07<00:26,  1.03s/it]

bsaul_inferference:  24%|█████▌                 | 8/33 [00:08<00:25,  1.03s/it]

bsaul_inferference:  27%|██████▎                | 9/33 [00:09<00:24,  1.03s/it]

bsaul_inferference:  30%|██████▋               | 10/33 [00:10<00:23,  1.03s/it]

bsaul_inferference:  33%|███████▎              | 11/33 [00:11<00:22,  1.03s/it]

bsaul_inferference:  36%|████████              | 12/33 [00:12<00:21,  1.03s/it]

bsaul_inferference:  39%|████████▋             | 13/33 [00:13<00:20,  1.03s/it]

bsaul_inferference:  42%|█████████▎            | 14/33 [00:14<00:19,  1.03s/it]

bsaul_inferference:  45%|██████████            | 15/33 [00:15<00:18,  1.03s/it]

bsaul_inferference:  48%|██████████▋           | 16/33 [00:16<00:17,  1.03s/it]

bsaul_inferference:  52%|███████████▎          | 17/33 [00:17<00:16,  1.03s/it]

bsaul_inferference:  55%|████████████          | 18/33 [00:18<00:15,  1.03s/it]

bsaul_inferference:  58%|████████████▋         | 19/33 [00:19<00:14,  1.03s/it]

bsaul_inferference:  61%|█████████████▎        | 20/33 [00:20<00:13,  1.03s/it]

bsaul_inferference:  64%|██████████████        | 21/33 [00:21<00:12,  1.02s/it]

bsaul_inferference:  67%|██████████████▋       | 22/33 [00:22<00:11,  1.02s/it]

bsaul_inferference:  70%|███████████████▎      | 23/33 [00:23<00:10,  1.03s/it]

bsaul_inferference:  73%|████████████████      | 24/33 [00:24<00:09,  1.03s/it]

bsaul_inferference:  76%|████████████████▋     | 25/33 [00:25<00:08,  1.03s/it]

  errors: {'c863b1cf7a7bc5e376bc6c197e0179fc6a759803': 'Key c863b1cf7a7bc5e376bc6c197e0179fc6a759803 not found in /da5_fast/All.sha1c/commit_72.tch'}

bsaul_inferference:  79%|█████████████████▎    | 26/33 [00:26<00:07,  1.03s/it]

bsaul_inferference:  82%|██████████████████    | 27/33 [00:27<00:06,  1.03s/it]

bsaul_inferference:  85%|██████████████████▋   | 28/33 [00:28<00:05,  1.03s/it]

bsaul_inferference:  88%|███████████████████▎  | 29/33 [00:29<00:04,  1.03s/it]

bsaul_inferference:  91%|████████████████████  | 30/33 [00:30<00:03,  1.03s/it]

bsaul_inferference:  94%|████████████████████▋ | 31/33 [00:31<00:02,  1.03s/it]

bsaul_inferference:  97%|█████████████████████▎| 32/33 [00:32<00:01,  1.03s/it]

bsaul_inferference: 100%|██████████████████████| 33/33 [00:33<00:00,  1.03s/it]

bsaul_inferference: 100%|██████████████████████| 33/33 [00:33<00:00,  1.03s/it]

  WARNING: 1 commits could not be retrieved
daohu527_dig-into-apollo -> 425 commit sha1s

daohu527_dig-into-apollo:   0%|                         | 0/43 [00:00<?, ?it/s]

daohu527_dig-into-apollo:   2%|▍                | 1/43 [00:01<00:43,  1.03s/it]

daohu527_dig-into-apollo:   5%|▊                | 2/43 [00:02<00:42,  1.03s/it]

daohu527_dig-into-apollo:   7%|█▏               | 3/43 [00:03<00:41,  1.04s/it]

daohu527_dig-into-apollo:   9%|█▌               | 4/43 [00:04<00:40,  1.04s/it]

daohu527_dig-into-apollo:  12%|█▉               | 5/43 [00:05<00:39,  1.03s/it]

daohu527_dig-into-apollo:  14%|██▎              | 6/43 [00:06<00:38,  1.04s/it]

daohu527_dig-into-apollo:  16%|██▊              | 7/43 [00:07<00:37,  1.03s/it]

daohu527_dig-into-apollo:  19%|███▏             | 8/43 [00:08<00:36,  1.04s/it]

daohu527_dig-into-apollo:  21%|███▌             | 9/43 [00:09<00:35,  1.04s/it]

daohu527_dig-into-apollo:  23%|███▋            | 10/43 [00:10<00:34,  1.04s/it]

daohu527_dig-into-apollo:  26%|████            | 11/43 [00:11<00:33,  1.04s/it]

daohu527_dig-into-apollo:  28%|████▍           | 12/43 [00:12<00:32,  1.04s/it]

daohu527_dig-into-apollo:  30%|████▊           | 13/43 [00:13<00:31,  1.03s/it]

daohu527_dig-into-apollo:  33%|█████▏          | 14/43 [00:14<00:30,  1.03s/it]

daohu527_dig-into-apollo:  35%|█████▌          | 15/43 [00:15<00:28,  1.03s/it]

daohu527_dig-into-apollo:  37%|█████▉          | 16/43 [00:16<00:27,  1.03s/it]

daohu527_dig-into-apollo:  40%|██████▎         | 17/43 [00:17<00:26,  1.03s/it]

daohu527_dig-into-apollo:  42%|██████▋         | 18/43 [00:18<00:25,  1.03s/it]

daohu527_dig-into-apollo:  44%|███████         | 19/43 [00:19<00:24,  1.03s/it]

daohu527_dig-into-apollo:  47%|███████▍        | 20/43 [00:20<00:23,  1.03s/it]

daohu527_dig-into-apollo:  49%|███████▊        | 21/43 [00:21<00:22,  1.03s/it]

daohu527_dig-into-apollo:  51%|████████▏       | 22/43 [00:22<00:21,  1.03s/it]

daohu527_dig-into-apollo:  53%|████████▌       | 23/43 [00:23<00:20,  1.03s/it]

daohu527_dig-into-apollo:  56%|████████▉       | 24/43 [00:24<00:19,  1.03s/it]

daohu527_dig-into-apollo:  58%|█████████▎      | 25/43 [00:25<00:18,  1.03s/it]

daohu527_dig-into-apollo:  60%|█████████▋      | 26/43 [00:26<00:17,  1.03s/it]

daohu527_dig-into-apollo:  63%|██████████      | 27/43 [00:27<00:16,  1.03s/it]

daohu527_dig-into-apollo:  65%|██████████▍     | 28/43 [00:28<00:15,  1.03s/it]

daohu527_dig-into-apollo:  67%|██████████▊     | 29/43 [00:29<00:14,  1.03s/it]

daohu527_dig-into-apollo:  70%|███████████▏    | 30/43 [00:31<00:13,  1.03s/it]

daohu527_dig-into-apollo:  72%|███████████▌    | 31/43 [00:32<00:12,  1.03s/it]

daohu527_dig-into-apollo:  74%|███████████▉    | 32/43 [00:33<00:11,  1.03s/it]

daohu527_dig-into-apollo:  77%|████████████▎   | 33/43 [00:34<00:10,  1.03s/it]

daohu527_dig-into-apollo:  79%|████████████▋   | 34/43 [00:35<00:09,  1.03s/it]

daohu527_dig-into-apollo:  81%|█████████████   | 35/43 [00:36<00:08,  1.03s/it]

daohu527_dig-into-apollo:  84%|█████████████▍  | 36/43 [00:37<00:07,  1.03s/it]

daohu527_dig-into-apollo:  86%|█████████████▊  | 37/43 [00:38<00:06,  1.03s/it]

daohu527_dig-into-apollo:  88%|██████████████▏ | 38/43 [00:39<00:05,  1.03s/it]

daohu527_dig-into-apollo:  91%|██████████████▌ | 39/43 [00:40<00:04,  1.03s/it]

daohu527_dig-into-apollo:  93%|██████████████▉ | 40/43 [00:41<00:03,  1.04s/it]

daohu527_dig-into-apollo:  95%|███████████████▎| 41/43 [00:42<00:02,  1.03s/it]

daohu527_dig-into-apollo:  98%|███████████████▋| 42/43 [00:43<00:01,  1.03s/it]

daohu527_dig-into-apollo: 100%|████████████████| 43/43 [00:44<00:00,  1.03s/it]

daohu527_dig-into-apollo: 100%|████████████████| 43/43 [00:44<00:00,  1.03s/it]

martin2250_opencncpilot -> 254 commit sha1s

martin2250_opencncpilot:   0%|                          | 0/26 [00:00<?, ?it/s]

martin2250_opencncpilot:   4%|▋                 | 1/26 [00:01<00:25,  1.03s/it]

martin2250_opencncpilot:   8%|█▍                | 2/26 [00:02<00:24,  1.03s/it]

martin2250_opencncpilot:  12%|██                | 3/26 [00:03<00:23,  1.03s/it]

martin2250_opencncpilot:  15%|██▊               | 4/26 [00:04<00:22,  1.04s/it]

martin2250_opencncpilot:  19%|███▍              | 5/26 [00:05<00:21,  1.04s/it]

martin2250_opencncpilot:  23%|████▏             | 6/26 [00:06<00:20,  1.04s/it]

martin2250_opencncpilot:  27%|████▊             | 7/26 [00:07<00:19,  1.04s/it]

martin2250_opencncpilot:  31%|█████▌            | 8/26 [00:08<00:18,  1.03s/it]

martin2250_opencncpilot:  35%|██████▏           | 9/26 [00:09<00:17,  1.03s/it]

martin2250_opencncpilot:  38%|██████▌          | 10/26 [00:10<00:16,  1.03s/it]

martin2250_opencncpilot:  42%|███████▏         | 11/26 [00:11<00:15,  1.03s/it]

martin2250_opencncpilot:  46%|███████▊         | 12/26 [00:12<00:14,  1.03s/it]

  errors: {'880bca358a13bf617f06f4fdda6fd81eda2a336a': 'Key 880bca358a13bf617f06f4fdda6fd81eda2a336a not found in /da5_fast/All.sha1c/commit_8.tch'}

martin2250_opencncpilot:  50%|████████▌        | 13/26 [00:13<00:13,  1.03s/it]

martin2250_opencncpilot:  54%|█████████▏       | 14/26 [00:14<00:12,  1.03s/it]

martin2250_opencncpilot:  58%|█████████▊       | 15/26 [00:15<00:11,  1.03s/it]

martin2250_opencncpilot:  62%|██████████▍      | 16/26 [00:16<00:10,  1.03s/it]

martin2250_opencncpilot:  65%|███████████      | 17/26 [00:17<00:09,  1.03s/it]

martin2250_opencncpilot:  69%|███████████▊     | 18/26 [00:18<00:08,  1.04s/it]

martin2250_opencncpilot:  73%|████████████▍    | 19/26 [00:19<00:07,  1.04s/it]

martin2250_opencncpilot:  77%|█████████████    | 20/26 [00:20<00:06,  1.04s/it]

martin2250_opencncpilot:  81%|█████████████▋   | 21/26 [00:21<00:05,  1.03s/it]

martin2250_opencncpilot:  85%|██████████████▍  | 22/26 [00:22<00:04,  1.03s/it]

martin2250_opencncpilot:  88%|███████████████  | 23/26 [00:23<00:03,  1.04s/it]

martin2250_opencncpilot:  92%|███████████████▋ | 24/26 [00:24<00:02,  1.03s/it]

martin2250_opencncpilot:  96%|████████████████▎| 25/26 [00:25<00:01,  1.03s/it]

martin2250_opencncpilot: 100%|█████████████████| 26/26 [00:26<00:00,  1.03s/it]

martin2250_opencncpilot: 100%|█████████████████| 26/26 [00:26<00:00,  1.03s/it]

  WARNING: 1 commits could not be retrieved
usgs-astrogeology_isis3 -> 18328 commit sha1s

usgs-astrogeology_isis3:   0%|                        | 0/1833 [00:00<?, ?it/s]

usgs-astrogeology_isis3:   0%|                | 1/1833 [00:01<31:31,  1.03s/it]

usgs-astrogeology_isis3:   0%|                | 2/1833 [00:02<31:22,  1.03s/it]

usgs-astrogeology_isis3:   0%|                | 3/1833 [00:03<31:25,  1.03s/it]

usgs-astrogeology_isis3:   0%|                | 4/1833 [00:04<31:23,  1.03s/it]

usgs-astrogeology_isis3:   0%|                | 5/1833 [00:05<31:22,  1.03s/it]

usgs-astrogeology_isis3:   0%|                | 6/1833 [00:06<31:19,  1.03s/it]

usgs-astrogeology_isis3:   0%|                | 7/1833 [00:07<31:19,  1.03s/it]

usgs-astrogeology_isis3:   0%|                | 8/1833 [00:08<31:18,  1.03s/it]

usgs-astrogeology_isis3:   0%|                | 9/1833 [00:09<31:15,  1.03s/it]

usgs-astrogeology_isis3:   1%|               | 10/1833 [00:10<31:15,  1.03s/it]

usgs-astrogeology_isis3:   1%|               | 11/1833 [00:11<31:12,  1.03s/it]

usgs-astrogeology_isis3:   1%|               | 12/1833 [00:12<31:10,  1.03s/it]

usgs-astrogeology_isis3:   1%|               | 13/1833 [00:13<31:10,  1.03s/it]

usgs-astrogeology_isis3:   1%|               | 14/1833 [00:14<31:08,  1.03s/it]

usgs-astrogeology_isis3:   1%|               | 15/1833 [00:15<31:05,  1.03s/it]

usgs-astrogeology_isis3:   1%|▏              | 16/1833 [00:16<31:11,  1.03s/it]

usgs-astrogeology_isis3:   1%|▏              | 17/1833 [00:17<31:08,  1.03s/it]

usgs-astrogeology_isis3:   1%|▏              | 18/1833 [00:18<31:07,  1.03s/it]

usgs-astrogeology_isis3:   1%|▏              | 19/1833 [00:19<31:05,  1.03s/it]

usgs-astrogeology_isis3:   1%|▏              | 20/1833 [00:20<31:04,  1.03s/it]

usgs-astrogeology_isis3:   1%|▏              | 21/1833 [00:21<31:03,  1.03s/it]

usgs-astrogeology_isis3:   1%|▏              | 22/1833 [00:22<31:04,  1.03s/it]

usgs-astrogeology_isis3:   1%|▏              | 23/1833 [00:23<31:04,  1.03s/it]

usgs-astrogeology_isis3:   1%|▏              | 24/1833 [00:24<31:03,  1.03s/it]

usgs-astrogeology_isis3:   1%|▏              | 25/1833 [00:25<31:04,  1.03s/it]

usgs-astrogeology_isis3:   1%|▏              | 26/1833 [00:26<31:04,  1.03s/it]

usgs-astrogeology_isis3:   1%|▏              | 27/1833 [00:27<31:06,  1.03s/it]

usgs-astrogeology_isis3:   2%|▏              | 28/1833 [00:28<31:02,  1.03s/it]

usgs-astrogeology_isis3:   2%|▏              | 29/1833 [00:29<31:05,  1.03s/it]

usgs-astrogeology_isis3:   2%|▏              | 30/1833 [00:30<31:01,  1.03s/it]

usgs-astrogeology_isis3:   2%|▎              | 31/1833 [00:31<30:57,  1.03s/it]

usgs-astrogeology_isis3:   2%|▎              | 32/1833 [00:32<30:58,  1.03s/it]

usgs-astrogeology_isis3:   2%|▎              | 33/1833 [00:33<30:57,  1.03s/it]

usgs-astrogeology_isis3:   2%|▎              | 34/1833 [00:35<30:55,  1.03s/it]

usgs-astrogeology_isis3:   2%|▎              | 35/1833 [00:36<30:53,  1.03s/it]

usgs-astrogeology_isis3:   2%|▎              | 36/1833 [00:37<30:53,  1.03s/it]

usgs-astrogeology_isis3:   2%|▎              | 37/1833 [00:38<30:51,  1.03s/it]

usgs-astrogeology_isis3:   2%|▎              | 38/1833 [00:39<30:50,  1.03s/it]

usgs-astrogeology_isis3:   2%|▎              | 39/1833 [00:40<30:48,  1.03s/it]

usgs-astrogeology_isis3:   2%|▎              | 40/1833 [00:41<30:49,  1.03s/it]

usgs-astrogeology_isis3:   2%|▎              | 41/1833 [00:42<30:47,  1.03s/it]

usgs-astrogeology_isis3:   2%|▎              | 42/1833 [00:43<30:44,  1.03s/it]

usgs-astrogeology_isis3:   2%|▎              | 43/1833 [00:44<30:45,  1.03s/it]

  errors: {'062e5625b064b1fdfed0ffa5b42e6a6f53c34c41': 'Key 062e5625b064b1fdfed0ffa5b42e6a6f53c34c41 not found in /da5_fast/All.sha1c/commit_6.tch'}

usgs-astrogeology_isis3:   2%|▎              | 44/1833 [00:45<30:41,  1.03s/it]

usgs-astrogeology_isis3:   2%|▎              | 45/1833 [00:46<30:43,  1.03s/it]

usgs-astrogeology_isis3:   3%|▍              | 46/1833 [00:47<30:40,  1.03s/it]

usgs-astrogeology_isis3:   3%|▍              | 47/1833 [00:48<30:40,  1.03s/it]

usgs-astrogeology_isis3:   3%|▍              | 48/1833 [00:49<30:39,  1.03s/it]

usgs-astrogeology_isis3:   3%|▍              | 49/1833 [00:50<30:40,  1.03s/it]

usgs-astrogeology_isis3:   3%|▍              | 50/1833 [00:51<30:39,  1.03s/it]

usgs-astrogeology_isis3:   3%|▍              | 51/1833 [00:52<30:35,  1.03s/it]

usgs-astrogeology_isis3:   3%|▍              | 52/1833 [00:53<30:38,  1.03s/it]

usgs-astrogeology_isis3:   3%|▍              | 53/1833 [00:54<30:37,  1.03s/it]

usgs-astrogeology_isis3:   3%|▍              | 54/1833 [00:55<30:33,  1.03s/it]

usgs-astrogeology_isis3:   3%|▍              | 55/1833 [00:56<30:33,  1.03s/it]

usgs-astrogeology_isis3:   3%|▍              | 56/1833 [00:57<30:27,  1.03s/it]

usgs-astrogeology_isis3:   3%|▍              | 57/1833 [00:58<30:26,  1.03s/it]

usgs-astrogeology_isis3:   3%|▍              | 58/1833 [00:59<30:26,  1.03s/it]

usgs-astrogeology_isis3:   3%|▍              | 59/1833 [01:00<30:27,  1.03s/it]

usgs-astrogeology_isis3:   3%|▍              | 60/1833 [01:01<30:27,  1.03s/it]

usgs-astrogeology_isis3:   3%|▍              | 61/1833 [01:02<30:25,  1.03s/it]

usgs-astrogeology_isis3:   3%|▌              | 62/1833 [01:03<30:24,  1.03s/it]

usgs-astrogeology_isis3:   3%|▌              | 63/1833 [01:04<30:22,  1.03s/it]

usgs-astrogeology_isis3:   3%|▌              | 64/1833 [01:05<30:21,  1.03s/it]

usgs-astrogeology_isis3:   4%|▌              | 65/1833 [01:06<30:22,  1.03s/it]

usgs-astrogeology_isis3:   4%|▌              | 66/1833 [01:08<30:26,  1.03s/it]

usgs-astrogeology_isis3:   4%|▌              | 67/1833 [01:09<30:37,  1.04s/it]

usgs-astrogeology_isis3:   4%|▌              | 68/1833 [01:10<30:30,  1.04s/it]

usgs-astrogeology_isis3:   4%|▌              | 69/1833 [01:11<30:25,  1.03s/it]

usgs-astrogeology_isis3:   4%|▌              | 70/1833 [01:12<30:22,  1.03s/it]

usgs-astrogeology_isis3:   4%|▌              | 71/1833 [01:13<30:18,  1.03s/it]

usgs-astrogeology_isis3:   4%|▌              | 72/1833 [01:14<30:16,  1.03s/it]

usgs-astrogeology_isis3:   4%|▌              | 73/1833 [01:15<30:18,  1.03s/it]

usgs-astrogeology_isis3:   4%|▌              | 74/1833 [01:16<30:16,  1.03s/it]

usgs-astrogeology_isis3:   4%|▌              | 75/1833 [01:17<30:15,  1.03s/it]

usgs-astrogeology_isis3:   4%|▌              | 76/1833 [01:18<30:13,  1.03s/it]

usgs-astrogeology_isis3:   4%|▋              | 77/1833 [01:19<30:10,  1.03s/it]

usgs-astrogeology_isis3:   4%|▋              | 78/1833 [01:20<30:18,  1.04s/it]

usgs-astrogeology_isis3:   4%|▋              | 79/1833 [01:21<30:11,  1.03s/it]

usgs-astrogeology_isis3:   4%|▋              | 80/1833 [01:22<30:08,  1.03s/it]

usgs-astrogeology_isis3:   4%|▋              | 81/1833 [01:23<30:07,  1.03s/it]

usgs-astrogeology_isis3:   4%|▋              | 82/1833 [01:24<30:07,  1.03s/it]

usgs-astrogeology_isis3:   5%|▋              | 83/1833 [01:25<30:05,  1.03s/it]

usgs-astrogeology_isis3:   5%|▋              | 84/1833 [01:26<30:02,  1.03s/it]

usgs-astrogeology_isis3:   5%|▋              | 85/1833 [01:27<30:00,  1.03s/it]

usgs-astrogeology_isis3:   5%|▋              | 86/1833 [01:28<29:59,  1.03s/it]

usgs-astrogeology_isis3:   5%|▋              | 87/1833 [01:29<30:01,  1.03s/it]

usgs-astrogeology_isis3:   5%|▋              | 88/1833 [01:30<30:01,  1.03s/it]

usgs-astrogeology_isis3:   5%|▋              | 89/1833 [01:31<29:58,  1.03s/it]

usgs-astrogeology_isis3:   5%|▋              | 90/1833 [01:32<29:55,  1.03s/it]

usgs-astrogeology_isis3:   5%|▋              | 91/1833 [01:33<29:50,  1.03s/it]

usgs-astrogeology_isis3:   5%|▊              | 92/1833 [01:34<29:46,  1.03s/it]

usgs-astrogeology_isis3:   5%|▊              | 93/1833 [01:35<29:47,  1.03s/it]

usgs-astrogeology_isis3:   5%|▊              | 94/1833 [01:36<29:53,  1.03s/it]

usgs-astrogeology_isis3:   5%|▊              | 95/1833 [01:37<29:48,  1.03s/it]

usgs-astrogeology_isis3:   5%|▊              | 96/1833 [01:38<29:49,  1.03s/it]

usgs-astrogeology_isis3:   5%|▊              | 97/1833 [01:39<29:46,  1.03s/it]

usgs-astrogeology_isis3:   5%|▊              | 98/1833 [01:41<29:47,  1.03s/it]

usgs-astrogeology_isis3:   5%|▊              | 99/1833 [01:42<29:48,  1.03s/it]

usgs-astrogeology_isis3:   5%|▊             | 100/1833 [01:43<29:47,  1.03s/it]

usgs-astrogeology_isis3:   6%|▊             | 101/1833 [01:44<29:49,  1.03s/it]

usgs-astrogeology_isis3:   6%|▊             | 102/1833 [01:45<29:45,  1.03s/it]

usgs-astrogeology_isis3:   6%|▊             | 103/1833 [01:46<29:42,  1.03s/it]

usgs-astrogeology_isis3:   6%|▊             | 104/1833 [01:47<29:41,  1.03s/it]

usgs-astrogeology_isis3:   6%|▊             | 105/1833 [01:48<29:37,  1.03s/it]

usgs-astrogeology_isis3:   6%|▊             | 106/1833 [01:49<29:40,  1.03s/it]

usgs-astrogeology_isis3:   6%|▊             | 107/1833 [01:50<29:39,  1.03s/it]

usgs-astrogeology_isis3:   6%|▊             | 108/1833 [01:51<29:35,  1.03s/it]

usgs-astrogeology_isis3:   6%|▊             | 109/1833 [01:52<29:36,  1.03s/it]

usgs-astrogeology_isis3:   6%|▊             | 110/1833 [01:53<29:34,  1.03s/it]

usgs-astrogeology_isis3:   6%|▊             | 111/1833 [01:54<29:33,  1.03s/it]

usgs-astrogeology_isis3:   6%|▊             | 112/1833 [01:55<29:35,  1.03s/it]

usgs-astrogeology_isis3:   6%|▊             | 113/1833 [01:56<29:35,  1.03s/it]

usgs-astrogeology_isis3:   6%|▊             | 114/1833 [01:57<29:33,  1.03s/it]

usgs-astrogeology_isis3:   6%|▉             | 115/1833 [01:58<29:31,  1.03s/it]

usgs-astrogeology_isis3:   6%|▉             | 116/1833 [01:59<29:32,  1.03s/it]

usgs-astrogeology_isis3:   6%|▉             | 117/1833 [02:00<29:28,  1.03s/it]

usgs-astrogeology_isis3:   6%|▉             | 118/1833 [02:01<29:26,  1.03s/it]

usgs-astrogeology_isis3:   6%|▉             | 119/1833 [02:02<29:26,  1.03s/it]

usgs-astrogeology_isis3:   7%|▉             | 120/1833 [02:03<29:28,  1.03s/it]

usgs-astrogeology_isis3:   7%|▉             | 121/1833 [02:04<29:25,  1.03s/it]

usgs-astrogeology_isis3:   7%|▉             | 122/1833 [02:05<29:24,  1.03s/it]

usgs-astrogeology_isis3:   7%|▉             | 123/1833 [02:06<29:22,  1.03s/it]

usgs-astrogeology_isis3:   7%|▉             | 124/1833 [02:07<29:18,  1.03s/it]

usgs-astrogeology_isis3:   7%|▉             | 125/1833 [02:08<29:18,  1.03s/it]

usgs-astrogeology_isis3:   7%|▉             | 126/1833 [02:09<29:18,  1.03s/it]

usgs-astrogeology_isis3:   7%|▉             | 127/1833 [02:10<29:17,  1.03s/it]

usgs-astrogeology_isis3:   7%|▉             | 128/1833 [02:11<29:15,  1.03s/it]

usgs-astrogeology_isis3:   7%|▉             | 129/1833 [02:12<29:12,  1.03s/it]

usgs-astrogeology_isis3:   7%|▉             | 130/1833 [02:13<29:10,  1.03s/it]

usgs-astrogeology_isis3:   7%|█             | 131/1833 [02:15<29:09,  1.03s/it]

usgs-astrogeology_isis3:   7%|█             | 132/1833 [02:16<29:12,  1.03s/it]

usgs-astrogeology_isis3:   7%|█             | 133/1833 [02:17<29:12,  1.03s/it]

usgs-astrogeology_isis3:   7%|█             | 134/1833 [02:18<29:13,  1.03s/it]

usgs-astrogeology_isis3:   7%|█             | 135/1833 [02:19<29:13,  1.03s/it]

usgs-astrogeology_isis3:   7%|█             | 136/1833 [02:20<29:10,  1.03s/it]

usgs-astrogeology_isis3:   7%|█             | 137/1833 [02:21<29:04,  1.03s/it]

usgs-astrogeology_isis3:   8%|█             | 138/1833 [02:22<29:03,  1.03s/it]

usgs-astrogeology_isis3:   8%|█             | 139/1833 [02:23<29:03,  1.03s/it]

usgs-astrogeology_isis3:   8%|█             | 140/1833 [02:24<29:05,  1.03s/it]

usgs-astrogeology_isis3:   8%|█             | 141/1833 [02:25<29:03,  1.03s/it]

usgs-astrogeology_isis3:   8%|█             | 142/1833 [02:26<29:01,  1.03s/it]

usgs-astrogeology_isis3:   8%|█             | 143/1833 [02:27<29:01,  1.03s/it]

usgs-astrogeology_isis3:   8%|█             | 144/1833 [02:28<29:03,  1.03s/it]

usgs-astrogeology_isis3:   8%|█             | 145/1833 [02:29<29:01,  1.03s/it]

usgs-astrogeology_isis3:   8%|█             | 146/1833 [02:30<29:01,  1.03s/it]

usgs-astrogeology_isis3:   8%|█             | 147/1833 [02:31<29:02,  1.03s/it]

usgs-astrogeology_isis3:   8%|█▏            | 148/1833 [02:32<28:56,  1.03s/it]

usgs-astrogeology_isis3:   8%|█▏            | 149/1833 [02:33<28:54,  1.03s/it]

usgs-astrogeology_isis3:   8%|█▏            | 150/1833 [02:34<28:52,  1.03s/it]

usgs-astrogeology_isis3:   8%|█▏            | 151/1833 [02:35<28:50,  1.03s/it]

usgs-astrogeology_isis3:   8%|█▏            | 152/1833 [02:36<28:50,  1.03s/it]

usgs-astrogeology_isis3:   8%|█▏            | 153/1833 [02:37<28:53,  1.03s/it]

usgs-astrogeology_isis3:   8%|█▏            | 154/1833 [02:38<28:54,  1.03s/it]

usgs-astrogeology_isis3:   8%|█▏            | 155/1833 [02:39<28:47,  1.03s/it]

usgs-astrogeology_isis3:   9%|█▏            | 156/1833 [02:40<28:46,  1.03s/it]

usgs-astrogeology_isis3:   9%|█▏            | 157/1833 [02:41<28:41,  1.03s/it]

usgs-astrogeology_isis3:   9%|█▏            | 158/1833 [02:42<28:41,  1.03s/it]

usgs-astrogeology_isis3:   9%|█▏            | 159/1833 [02:43<28:39,  1.03s/it]

usgs-astrogeology_isis3:   9%|█▏            | 160/1833 [02:44<28:42,  1.03s/it]

usgs-astrogeology_isis3:   9%|█▏            | 161/1833 [02:45<28:47,  1.03s/it]

usgs-astrogeology_isis3:   9%|█▏            | 162/1833 [02:46<28:45,  1.03s/it]

usgs-astrogeology_isis3:   9%|█▏            | 163/1833 [02:47<28:43,  1.03s/it]

usgs-astrogeology_isis3:   9%|█▎            | 164/1833 [02:49<28:40,  1.03s/it]

usgs-astrogeology_isis3:   9%|█▎            | 165/1833 [02:50<28:38,  1.03s/it]

usgs-astrogeology_isis3:   9%|█▎            | 166/1833 [02:51<29:02,  1.05s/it]

usgs-astrogeology_isis3:   9%|█▎            | 167/1833 [02:52<28:55,  1.04s/it]

usgs-astrogeology_isis3:   9%|█▎            | 168/1833 [02:53<28:46,  1.04s/it]

usgs-astrogeology_isis3:   9%|█▎            | 169/1833 [02:54<28:42,  1.04s/it]

usgs-astrogeology_isis3:   9%|█▎            | 170/1833 [02:55<28:39,  1.03s/it]

usgs-astrogeology_isis3:   9%|█▎            | 171/1833 [02:56<28:38,  1.03s/it]

usgs-astrogeology_isis3:   9%|█▎            | 172/1833 [02:57<28:34,  1.03s/it]

usgs-astrogeology_isis3:   9%|█▎            | 173/1833 [02:58<28:32,  1.03s/it]

usgs-astrogeology_isis3:   9%|█▎            | 174/1833 [02:59<28:30,  1.03s/it]

usgs-astrogeology_isis3:  10%|█▎            | 175/1833 [03:00<28:30,  1.03s/it]

usgs-astrogeology_isis3:  10%|█▎            | 176/1833 [03:01<28:27,  1.03s/it]

usgs-astrogeology_isis3:  10%|█▎            | 177/1833 [03:02<28:28,  1.03s/it]

usgs-astrogeology_isis3:  10%|█▎            | 178/1833 [03:03<28:26,  1.03s/it]

usgs-astrogeology_isis3:  10%|█▎            | 179/1833 [03:04<28:22,  1.03s/it]

usgs-astrogeology_isis3:  10%|█▎            | 180/1833 [03:05<28:19,  1.03s/it]

usgs-astrogeology_isis3:  10%|█▍            | 181/1833 [03:06<28:17,  1.03s/it]

usgs-astrogeology_isis3:  10%|█▍            | 182/1833 [03:07<28:16,  1.03s/it]

usgs-astrogeology_isis3:  10%|█▍            | 183/1833 [03:08<28:16,  1.03s/it]

usgs-astrogeology_isis3:  10%|█▍            | 184/1833 [03:09<28:19,  1.03s/it]

usgs-astrogeology_isis3:  10%|█▍            | 185/1833 [03:10<28:15,  1.03s/it]

usgs-astrogeology_isis3:  10%|█▍            | 186/1833 [03:11<28:17,  1.03s/it]

usgs-astrogeology_isis3:  10%|█▍            | 187/1833 [03:12<28:16,  1.03s/it]

usgs-astrogeology_isis3:  10%|█▍            | 188/1833 [03:13<28:14,  1.03s/it]

usgs-astrogeology_isis3:  10%|█▍            | 189/1833 [03:14<28:10,  1.03s/it]

usgs-astrogeology_isis3:  10%|█▍            | 190/1833 [03:15<28:11,  1.03s/it]

usgs-astrogeology_isis3:  10%|█▍            | 191/1833 [03:16<28:07,  1.03s/it]

usgs-astrogeology_isis3:  10%|█▍            | 192/1833 [03:17<28:08,  1.03s/it]

usgs-astrogeology_isis3:  11%|█▍            | 193/1833 [03:18<28:13,  1.03s/it]

usgs-astrogeology_isis3:  11%|█▍            | 194/1833 [03:19<28:13,  1.03s/it]

usgs-astrogeology_isis3:  11%|█▍            | 195/1833 [03:21<28:13,  1.03s/it]

usgs-astrogeology_isis3:  11%|█▍            | 196/1833 [03:22<28:11,  1.03s/it]

usgs-astrogeology_isis3:  11%|█▌            | 197/1833 [03:23<28:07,  1.03s/it]

usgs-astrogeology_isis3:  11%|█▌            | 198/1833 [03:24<28:06,  1.03s/it]

usgs-astrogeology_isis3:  11%|█▌            | 199/1833 [03:25<28:04,  1.03s/it]

usgs-astrogeology_isis3:  11%|█▌            | 200/1833 [03:26<28:05,  1.03s/it]

usgs-astrogeology_isis3:  11%|█▌            | 201/1833 [03:27<28:02,  1.03s/it]

usgs-astrogeology_isis3:  11%|█▌            | 202/1833 [03:28<28:02,  1.03s/it]

usgs-astrogeology_isis3:  11%|█▌            | 203/1833 [03:29<28:01,  1.03s/it]

usgs-astrogeology_isis3:  11%|█▌            | 204/1833 [03:30<28:00,  1.03s/it]

usgs-astrogeology_isis3:  11%|█▌            | 205/1833 [03:31<27:59,  1.03s/it]

usgs-astrogeology_isis3:  11%|█▌            | 206/1833 [03:32<27:57,  1.03s/it]

usgs-astrogeology_isis3:  11%|█▌            | 207/1833 [03:33<27:54,  1.03s/it]

usgs-astrogeology_isis3:  11%|█▌            | 208/1833 [03:34<27:51,  1.03s/it]

usgs-astrogeology_isis3:  11%|█▌            | 209/1833 [03:35<27:51,  1.03s/it]

usgs-astrogeology_isis3:  11%|█▌            | 210/1833 [03:36<27:54,  1.03s/it]

usgs-astrogeology_isis3:  12%|█▌            | 211/1833 [03:37<27:53,  1.03s/it]

usgs-astrogeology_isis3:  12%|█▌            | 212/1833 [03:38<27:52,  1.03s/it]

usgs-astrogeology_isis3:  12%|█▋            | 213/1833 [03:39<27:49,  1.03s/it]

usgs-astrogeology_isis3:  12%|█▋            | 214/1833 [03:40<27:48,  1.03s/it]

usgs-astrogeology_isis3:  12%|█▋            | 215/1833 [03:41<27:45,  1.03s/it]

usgs-astrogeology_isis3:  12%|█▋            | 216/1833 [03:42<27:42,  1.03s/it]

usgs-astrogeology_isis3:  12%|█▋            | 217/1833 [03:43<27:43,  1.03s/it]

usgs-astrogeology_isis3:  12%|█▋            | 218/1833 [03:44<27:43,  1.03s/it]

usgs-astrogeology_isis3:  12%|█▋            | 219/1833 [03:45<27:44,  1.03s/it]

usgs-astrogeology_isis3:  12%|█▋            | 220/1833 [03:46<27:42,  1.03s/it]

usgs-astrogeology_isis3:  12%|█▋            | 221/1833 [03:47<27:39,  1.03s/it]

usgs-astrogeology_isis3:  12%|█▋            | 222/1833 [03:48<27:40,  1.03s/it]

usgs-astrogeology_isis3:  12%|█▋            | 223/1833 [03:49<27:37,  1.03s/it]

usgs-astrogeology_isis3:  12%|█▋            | 224/1833 [03:50<27:35,  1.03s/it]

usgs-astrogeology_isis3:  12%|█▋            | 225/1833 [03:51<27:37,  1.03s/it]

usgs-astrogeology_isis3:  12%|█▋            | 226/1833 [03:52<27:38,  1.03s/it]

usgs-astrogeology_isis3:  12%|█▋            | 227/1833 [03:53<27:36,  1.03s/it]

usgs-astrogeology_isis3:  12%|█▋            | 228/1833 [03:55<27:34,  1.03s/it]

usgs-astrogeology_isis3:  12%|█▋            | 229/1833 [03:56<27:31,  1.03s/it]

usgs-astrogeology_isis3:  13%|█▊            | 230/1833 [03:57<27:33,  1.03s/it]

usgs-astrogeology_isis3:  13%|█▊            | 231/1833 [03:58<27:30,  1.03s/it]

usgs-astrogeology_isis3:  13%|█▊            | 232/1833 [03:59<27:41,  1.04s/it]

usgs-astrogeology_isis3:  13%|█▊            | 233/1833 [04:00<27:41,  1.04s/it]

usgs-astrogeology_isis3:  13%|█▊            | 234/1833 [04:01<27:39,  1.04s/it]

usgs-astrogeology_isis3:  13%|█▊            | 235/1833 [04:02<27:35,  1.04s/it]

usgs-astrogeology_isis3:  13%|█▊            | 236/1833 [04:03<27:31,  1.03s/it]

usgs-astrogeology_isis3:  13%|█▊            | 237/1833 [04:04<27:24,  1.03s/it]

usgs-astrogeology_isis3:  13%|█▊            | 238/1833 [04:05<27:21,  1.03s/it]

usgs-astrogeology_isis3:  13%|█▊            | 239/1833 [04:06<27:20,  1.03s/it]

usgs-astrogeology_isis3:  13%|█▊            | 240/1833 [04:07<27:20,  1.03s/it]

usgs-astrogeology_isis3:  13%|█▊            | 241/1833 [04:08<27:22,  1.03s/it]

usgs-astrogeology_isis3:  13%|█▊            | 242/1833 [04:09<27:20,  1.03s/it]

usgs-astrogeology_isis3:  13%|█▊            | 243/1833 [04:10<27:18,  1.03s/it]

usgs-astrogeology_isis3:  13%|█▊            | 244/1833 [04:11<27:17,  1.03s/it]

usgs-astrogeology_isis3:  13%|█▊            | 245/1833 [04:12<27:18,  1.03s/it]

usgs-astrogeology_isis3:  13%|█▉            | 246/1833 [04:13<27:18,  1.03s/it]

usgs-astrogeology_isis3:  13%|█▉            | 247/1833 [04:14<27:15,  1.03s/it]

usgs-astrogeology_isis3:  14%|█▉            | 248/1833 [04:15<27:15,  1.03s/it]

usgs-astrogeology_isis3:  14%|█▉            | 249/1833 [04:16<27:12,  1.03s/it]

usgs-astrogeology_isis3:  14%|█▉            | 250/1833 [04:17<27:11,  1.03s/it]

usgs-astrogeology_isis3:  14%|█▉            | 251/1833 [04:18<27:13,  1.03s/it]

usgs-astrogeology_isis3:  14%|█▉            | 252/1833 [04:19<27:08,  1.03s/it]

usgs-astrogeology_isis3:  14%|█▉            | 253/1833 [04:20<27:07,  1.03s/it]

usgs-astrogeology_isis3:  14%|█▉            | 254/1833 [04:21<27:07,  1.03s/it]

usgs-astrogeology_isis3:  14%|█▉            | 255/1833 [04:22<27:07,  1.03s/it]

usgs-astrogeology_isis3:  14%|█▉            | 256/1833 [04:23<27:08,  1.03s/it]

usgs-astrogeology_isis3:  14%|█▉            | 257/1833 [04:24<27:06,  1.03s/it]

usgs-astrogeology_isis3:  14%|█▉            | 258/1833 [04:25<27:04,  1.03s/it]

usgs-astrogeology_isis3:  14%|█▉            | 259/1833 [04:27<27:02,  1.03s/it]

usgs-astrogeology_isis3:  14%|█▉            | 260/1833 [04:28<26:59,  1.03s/it]

usgs-astrogeology_isis3:  14%|█▉            | 261/1833 [04:29<27:01,  1.03s/it]

usgs-astrogeology_isis3:  14%|██            | 262/1833 [04:30<27:01,  1.03s/it]

usgs-astrogeology_isis3:  14%|██            | 263/1833 [04:31<27:01,  1.03s/it]

usgs-astrogeology_isis3:  14%|██            | 264/1833 [04:32<26:58,  1.03s/it]

usgs-astrogeology_isis3:  14%|██            | 265/1833 [04:33<26:57,  1.03s/it]

usgs-astrogeology_isis3:  15%|██            | 266/1833 [04:34<26:54,  1.03s/it]

usgs-astrogeology_isis3:  15%|██            | 267/1833 [04:35<26:53,  1.03s/it]

usgs-astrogeology_isis3:  15%|██            | 268/1833 [04:36<26:53,  1.03s/it]

usgs-astrogeology_isis3:  15%|██            | 269/1833 [04:37<26:54,  1.03s/it]

  errors: {'26215a34519f96bcfa9355f9218662168e6edd9c': 'Key 26215a34519f96bcfa9355f9218662168e6edd9c not found in /da5_fast/All.sha1c/commit_38.tch'}

usgs-astrogeology_isis3:  15%|██            | 270/1833 [04:38<26:50,  1.03s/it]

usgs-astrogeology_isis3:  15%|██            | 271/1833 [04:39<26:46,  1.03s/it]

usgs-astrogeology_isis3:  15%|██            | 272/1833 [04:40<26:46,  1.03s/it]

usgs-astrogeology_isis3:  15%|██            | 273/1833 [04:41<26:45,  1.03s/it]

usgs-astrogeology_isis3:  15%|██            | 274/1833 [04:42<26:44,  1.03s/it]

usgs-astrogeology_isis3:  15%|██            | 275/1833 [04:43<26:42,  1.03s/it]

usgs-astrogeology_isis3:  15%|██            | 276/1833 [04:44<26:44,  1.03s/it]

usgs-astrogeology_isis3:  15%|██            | 277/1833 [04:45<26:42,  1.03s/it]

usgs-astrogeology_isis3:  15%|██            | 278/1833 [04:46<26:41,  1.03s/it]

usgs-astrogeology_isis3:  15%|██▏           | 279/1833 [04:47<26:40,  1.03s/it]

usgs-astrogeology_isis3:  15%|██▏           | 280/1833 [04:48<26:42,  1.03s/it]

usgs-astrogeology_isis3:  15%|██▏           | 281/1833 [04:49<26:41,  1.03s/it]

usgs-astrogeology_isis3:  15%|██▏           | 282/1833 [04:50<26:38,  1.03s/it]

usgs-astrogeology_isis3:  15%|██▏           | 283/1833 [04:51<26:36,  1.03s/it]

usgs-astrogeology_isis3:  15%|██▏           | 284/1833 [04:52<26:38,  1.03s/it]

usgs-astrogeology_isis3:  16%|██▏           | 285/1833 [04:53<26:37,  1.03s/it]

usgs-astrogeology_isis3:  16%|██▏           | 286/1833 [04:54<26:38,  1.03s/it]

usgs-astrogeology_isis3:  16%|██▏           | 287/1833 [04:55<26:34,  1.03s/it]

usgs-astrogeology_isis3:  16%|██▏           | 288/1833 [04:56<26:31,  1.03s/it]

usgs-astrogeology_isis3:  16%|██▏           | 289/1833 [04:57<26:29,  1.03s/it]

usgs-astrogeology_isis3:  16%|██▏           | 290/1833 [04:58<26:31,  1.03s/it]

usgs-astrogeology_isis3:  16%|██▏           | 291/1833 [05:00<26:34,  1.03s/it]

usgs-astrogeology_isis3:  16%|██▏           | 292/1833 [05:01<26:31,  1.03s/it]

usgs-astrogeology_isis3:  16%|██▏           | 293/1833 [05:02<26:29,  1.03s/it]

usgs-astrogeology_isis3:  16%|██▏           | 294/1833 [05:03<26:27,  1.03s/it]

usgs-astrogeology_isis3:  16%|██▎           | 295/1833 [05:04<26:25,  1.03s/it]

usgs-astrogeology_isis3:  16%|██▎           | 296/1833 [05:05<26:22,  1.03s/it]

usgs-astrogeology_isis3:  16%|██▎           | 297/1833 [05:06<26:20,  1.03s/it]

usgs-astrogeology_isis3:  16%|██▎           | 298/1833 [05:07<26:19,  1.03s/it]

usgs-astrogeology_isis3:  16%|██▎           | 299/1833 [05:08<26:18,  1.03s/it]

usgs-astrogeology_isis3:  16%|██▎           | 300/1833 [05:09<26:18,  1.03s/it]

usgs-astrogeology_isis3:  16%|██▎           | 301/1833 [05:10<26:16,  1.03s/it]

usgs-astrogeology_isis3:  16%|██▎           | 302/1833 [05:11<26:11,  1.03s/it]

usgs-astrogeology_isis3:  17%|██▎           | 303/1833 [05:12<26:11,  1.03s/it]

usgs-astrogeology_isis3:  17%|██▎           | 304/1833 [05:13<26:12,  1.03s/it]

usgs-astrogeology_isis3:  17%|██▎           | 305/1833 [05:14<26:14,  1.03s/it]

usgs-astrogeology_isis3:  17%|██▎           | 306/1833 [05:15<26:18,  1.03s/it]

usgs-astrogeology_isis3:  17%|██▎           | 307/1833 [05:16<26:18,  1.03s/it]

usgs-astrogeology_isis3:  17%|██▎           | 308/1833 [05:17<26:15,  1.03s/it]

usgs-astrogeology_isis3:  17%|██▎           | 309/1833 [05:18<26:12,  1.03s/it]

usgs-astrogeology_isis3:  17%|██▎           | 310/1833 [05:19<26:10,  1.03s/it]

usgs-astrogeology_isis3:  17%|██▍           | 311/1833 [05:20<26:09,  1.03s/it]

usgs-astrogeology_isis3:  17%|██▍           | 312/1833 [05:21<26:09,  1.03s/it]

usgs-astrogeology_isis3:  17%|██▍           | 313/1833 [05:22<26:10,  1.03s/it]

usgs-astrogeology_isis3:  17%|██▍           | 314/1833 [05:23<26:08,  1.03s/it]

usgs-astrogeology_isis3:  17%|██▍           | 315/1833 [05:24<26:03,  1.03s/it]

usgs-astrogeology_isis3:  17%|██▍           | 316/1833 [05:25<26:02,  1.03s/it]

usgs-astrogeology_isis3:  17%|██▍           | 317/1833 [05:26<26:01,  1.03s/it]

usgs-astrogeology_isis3:  17%|██▍           | 318/1833 [05:27<25:59,  1.03s/it]

usgs-astrogeology_isis3:  17%|██▍           | 319/1833 [05:28<25:59,  1.03s/it]

usgs-astrogeology_isis3:  17%|██▍           | 320/1833 [05:29<25:59,  1.03s/it]

usgs-astrogeology_isis3:  18%|██▍           | 321/1833 [05:30<25:59,  1.03s/it]

usgs-astrogeology_isis3:  18%|██▍           | 322/1833 [05:31<25:59,  1.03s/it]

usgs-astrogeology_isis3:  18%|██▍           | 323/1833 [05:32<25:54,  1.03s/it]

usgs-astrogeology_isis3:  18%|██▍           | 324/1833 [05:34<25:57,  1.03s/it]

usgs-astrogeology_isis3:  18%|██▍           | 325/1833 [05:35<25:55,  1.03s/it]

usgs-astrogeology_isis3:  18%|██▍           | 326/1833 [05:36<25:53,  1.03s/it]

usgs-astrogeology_isis3:  18%|██▍           | 327/1833 [05:37<25:53,  1.03s/it]

usgs-astrogeology_isis3:  18%|██▌           | 328/1833 [05:38<25:51,  1.03s/it]

usgs-astrogeology_isis3:  18%|██▌           | 329/1833 [05:39<25:52,  1.03s/it]

usgs-astrogeology_isis3:  18%|██▌           | 330/1833 [05:40<25:49,  1.03s/it]

usgs-astrogeology_isis3:  18%|██▌           | 331/1833 [05:41<25:48,  1.03s/it]

usgs-astrogeology_isis3:  18%|██▌           | 332/1833 [05:42<25:46,  1.03s/it]

usgs-astrogeology_isis3:  18%|██▌           | 333/1833 [05:43<25:45,  1.03s/it]

usgs-astrogeology_isis3:  18%|██▌           | 334/1833 [05:44<25:44,  1.03s/it]

usgs-astrogeology_isis3:  18%|██▌           | 335/1833 [05:45<25:44,  1.03s/it]

usgs-astrogeology_isis3:  18%|██▌           | 336/1833 [05:46<25:45,  1.03s/it]

usgs-astrogeology_isis3:  18%|██▌           | 337/1833 [05:47<25:43,  1.03s/it]

usgs-astrogeology_isis3:  18%|██▌           | 338/1833 [05:48<25:44,  1.03s/it]

usgs-astrogeology_isis3:  18%|██▌           | 339/1833 [05:49<25:39,  1.03s/it]

usgs-astrogeology_isis3:  19%|██▌           | 340/1833 [05:50<25:42,  1.03s/it]

usgs-astrogeology_isis3:  19%|██▌           | 341/1833 [05:51<25:43,  1.03s/it]

usgs-astrogeology_isis3:  19%|██▌           | 342/1833 [05:52<25:41,  1.03s/it]

usgs-astrogeology_isis3:  19%|██▌           | 343/1833 [05:53<25:39,  1.03s/it]

usgs-astrogeology_isis3:  19%|██▋           | 344/1833 [05:54<25:37,  1.03s/it]

usgs-astrogeology_isis3:  19%|██▋           | 345/1833 [05:55<25:40,  1.04s/it]

usgs-astrogeology_isis3:  19%|██▋           | 346/1833 [05:56<25:39,  1.04s/it]

usgs-astrogeology_isis3:  19%|██▋           | 347/1833 [05:57<25:39,  1.04s/it]

usgs-astrogeology_isis3:  19%|██▋           | 348/1833 [05:58<25:37,  1.04s/it]

usgs-astrogeology_isis3:  19%|██▋           | 349/1833 [05:59<25:34,  1.03s/it]

usgs-astrogeology_isis3:  19%|██▋           | 350/1833 [06:00<25:34,  1.03s/it]

usgs-astrogeology_isis3:  19%|██▋           | 351/1833 [06:01<25:30,  1.03s/it]

usgs-astrogeology_isis3:  19%|██▋           | 352/1833 [06:02<25:28,  1.03s/it]

usgs-astrogeology_isis3:  19%|██▋           | 353/1833 [06:03<25:25,  1.03s/it]

usgs-astrogeology_isis3:  19%|██▋           | 354/1833 [06:04<25:26,  1.03s/it]

usgs-astrogeology_isis3:  19%|██▋           | 355/1833 [06:06<25:28,  1.03s/it]

usgs-astrogeology_isis3:  19%|██▋           | 356/1833 [06:07<25:29,  1.04s/it]

usgs-astrogeology_isis3:  19%|██▋           | 357/1833 [06:08<25:28,  1.04s/it]

usgs-astrogeology_isis3:  20%|██▋           | 358/1833 [06:09<25:21,  1.03s/it]

usgs-astrogeology_isis3:  20%|██▋           | 359/1833 [06:10<25:30,  1.04s/it]

usgs-astrogeology_isis3:  20%|██▋           | 360/1833 [06:11<26:47,  1.09s/it]

usgs-astrogeology_isis3:  20%|██▊           | 361/1833 [06:12<26:51,  1.09s/it]

usgs-astrogeology_isis3:  20%|██▊           | 362/1833 [06:13<26:20,  1.07s/it]

usgs-astrogeology_isis3:  20%|██▊           | 363/1833 [06:14<26:01,  1.06s/it]

usgs-astrogeology_isis3:  20%|██▊           | 364/1833 [06:15<25:46,  1.05s/it]

usgs-astrogeology_isis3:  20%|██▊           | 365/1833 [06:16<25:37,  1.05s/it]

usgs-astrogeology_isis3:  20%|██▊           | 366/1833 [06:17<25:29,  1.04s/it]

usgs-astrogeology_isis3:  20%|██▊           | 367/1833 [06:18<25:22,  1.04s/it]

usgs-astrogeology_isis3:  20%|██▊           | 368/1833 [06:19<25:17,  1.04s/it]

usgs-astrogeology_isis3:  20%|██▊           | 369/1833 [06:20<25:12,  1.03s/it]

usgs-astrogeology_isis3:  20%|██▊           | 370/1833 [06:21<25:10,  1.03s/it]

usgs-astrogeology_isis3:  20%|██▊           | 371/1833 [06:22<25:07,  1.03s/it]

usgs-astrogeology_isis3:  20%|██▊           | 372/1833 [06:23<25:04,  1.03s/it]

usgs-astrogeology_isis3:  20%|██▊           | 373/1833 [06:24<25:05,  1.03s/it]

usgs-astrogeology_isis3:  20%|██▊           | 374/1833 [06:25<25:06,  1.03s/it]

usgs-astrogeology_isis3:  20%|██▊           | 375/1833 [06:26<25:06,  1.03s/it]

usgs-astrogeology_isis3:  21%|██▊           | 376/1833 [06:27<25:04,  1.03s/it]

usgs-astrogeology_isis3:  21%|██▉           | 377/1833 [06:28<25:02,  1.03s/it]

usgs-astrogeology_isis3:  21%|██▉           | 378/1833 [06:30<25:05,  1.03s/it]

usgs-astrogeology_isis3:  21%|██▉           | 379/1833 [06:31<25:01,  1.03s/it]

usgs-astrogeology_isis3:  21%|██▉           | 380/1833 [06:32<24:59,  1.03s/it]

usgs-astrogeology_isis3:  21%|██▉           | 381/1833 [06:33<24:55,  1.03s/it]

usgs-astrogeology_isis3:  21%|██▉           | 382/1833 [06:34<24:54,  1.03s/it]

usgs-astrogeology_isis3:  21%|██▉           | 383/1833 [06:35<24:51,  1.03s/it]

usgs-astrogeology_isis3:  21%|██▉           | 384/1833 [06:36<24:48,  1.03s/it]

usgs-astrogeology_isis3:  21%|██▉           | 385/1833 [06:37<24:51,  1.03s/it]

usgs-astrogeology_isis3:  21%|██▉           | 386/1833 [06:38<24:53,  1.03s/it]

usgs-astrogeology_isis3:  21%|██▉           | 387/1833 [06:39<24:54,  1.03s/it]

usgs-astrogeology_isis3:  21%|██▉           | 388/1833 [06:40<24:48,  1.03s/it]

usgs-astrogeology_isis3:  21%|██▉           | 389/1833 [06:41<24:48,  1.03s/it]

usgs-astrogeology_isis3:  21%|██▉           | 390/1833 [06:42<25:15,  1.05s/it]

usgs-astrogeology_isis3:  21%|██▉           | 391/1833 [06:43<25:05,  1.04s/it]

usgs-astrogeology_isis3:  21%|██▉           | 392/1833 [06:44<24:57,  1.04s/it]

usgs-astrogeology_isis3:  21%|███           | 393/1833 [06:45<24:55,  1.04s/it]

usgs-astrogeology_isis3:  21%|███           | 394/1833 [06:46<24:50,  1.04s/it]

usgs-astrogeology_isis3:  22%|███           | 395/1833 [06:47<24:46,  1.03s/it]

usgs-astrogeology_isis3:  22%|███           | 396/1833 [06:48<24:43,  1.03s/it]

usgs-astrogeology_isis3:  22%|███           | 397/1833 [06:49<24:41,  1.03s/it]

usgs-astrogeology_isis3:  22%|███           | 398/1833 [06:50<24:40,  1.03s/it]

usgs-astrogeology_isis3:  22%|███           | 399/1833 [06:51<24:40,  1.03s/it]

usgs-astrogeology_isis3:  22%|███           | 400/1833 [06:52<24:41,  1.03s/it]

usgs-astrogeology_isis3:  22%|███           | 401/1833 [06:53<24:39,  1.03s/it]

usgs-astrogeology_isis3:  22%|███           | 402/1833 [06:54<24:35,  1.03s/it]

usgs-astrogeology_isis3:  22%|███           | 403/1833 [06:55<24:34,  1.03s/it]

usgs-astrogeology_isis3:  22%|███           | 404/1833 [06:56<24:32,  1.03s/it]

usgs-astrogeology_isis3:  22%|███           | 405/1833 [06:57<24:30,  1.03s/it]

usgs-astrogeology_isis3:  22%|███           | 406/1833 [06:58<24:32,  1.03s/it]

usgs-astrogeology_isis3:  22%|███           | 407/1833 [06:59<24:30,  1.03s/it]

usgs-astrogeology_isis3:  22%|███           | 408/1833 [07:01<24:29,  1.03s/it]

usgs-astrogeology_isis3:  22%|███           | 409/1833 [07:02<24:29,  1.03s/it]

usgs-astrogeology_isis3:  22%|███▏          | 410/1833 [07:03<24:26,  1.03s/it]

usgs-astrogeology_isis3:  22%|███▏          | 411/1833 [07:04<24:25,  1.03s/it]

usgs-astrogeology_isis3:  22%|███▏          | 412/1833 [07:05<24:23,  1.03s/it]

usgs-astrogeology_isis3:  23%|███▏          | 413/1833 [07:06<24:24,  1.03s/it]

usgs-astrogeology_isis3:  23%|███▏          | 414/1833 [07:07<24:22,  1.03s/it]

usgs-astrogeology_isis3:  23%|███▏          | 415/1833 [07:08<24:21,  1.03s/it]

usgs-astrogeology_isis3:  23%|███▏          | 416/1833 [07:09<24:20,  1.03s/it]

usgs-astrogeology_isis3:  23%|███▏          | 417/1833 [07:10<24:16,  1.03s/it]

usgs-astrogeology_isis3:  23%|███▏          | 418/1833 [07:11<24:16,  1.03s/it]

usgs-astrogeology_isis3:  23%|███▏          | 419/1833 [07:12<24:13,  1.03s/it]

usgs-astrogeology_isis3:  23%|███▏          | 420/1833 [07:13<24:14,  1.03s/it]

usgs-astrogeology_isis3:  23%|███▏          | 421/1833 [07:14<24:14,  1.03s/it]

usgs-astrogeology_isis3:  23%|███▏          | 422/1833 [07:15<24:16,  1.03s/it]

usgs-astrogeology_isis3:  23%|███▏          | 423/1833 [07:16<24:16,  1.03s/it]

usgs-astrogeology_isis3:  23%|███▏          | 424/1833 [07:17<24:13,  1.03s/it]

usgs-astrogeology_isis3:  23%|███▏          | 425/1833 [07:18<24:10,  1.03s/it]

usgs-astrogeology_isis3:  23%|███▎          | 426/1833 [07:19<24:09,  1.03s/it]

usgs-astrogeology_isis3:  23%|███▎          | 427/1833 [07:20<24:08,  1.03s/it]

usgs-astrogeology_isis3:  23%|███▎          | 428/1833 [07:21<24:10,  1.03s/it]

usgs-astrogeology_isis3:  23%|███▎          | 429/1833 [07:22<24:09,  1.03s/it]

usgs-astrogeology_isis3:  23%|███▎          | 430/1833 [07:23<24:05,  1.03s/it]

usgs-astrogeology_isis3:  24%|███▎          | 431/1833 [07:24<24:02,  1.03s/it]

usgs-astrogeology_isis3:  24%|███▎          | 432/1833 [07:25<24:08,  1.03s/it]

usgs-astrogeology_isis3:  24%|███▎          | 433/1833 [07:26<24:05,  1.03s/it]

usgs-astrogeology_isis3:  24%|███▎          | 434/1833 [07:27<24:05,  1.03s/it]

usgs-astrogeology_isis3:  24%|███▎          | 435/1833 [07:28<24:05,  1.03s/it]

usgs-astrogeology_isis3:  24%|███▎          | 436/1833 [07:29<24:02,  1.03s/it]

usgs-astrogeology_isis3:  24%|███▎          | 437/1833 [07:30<24:02,  1.03s/it]

usgs-astrogeology_isis3:  24%|███▎          | 438/1833 [07:31<23:58,  1.03s/it]

usgs-astrogeology_isis3:  24%|███▎          | 439/1833 [07:32<23:55,  1.03s/it]

usgs-astrogeology_isis3:  24%|███▎          | 440/1833 [07:34<23:53,  1.03s/it]

usgs-astrogeology_isis3:  24%|███▎          | 441/1833 [07:35<23:52,  1.03s/it]

usgs-astrogeology_isis3:  24%|███▍          | 442/1833 [07:36<23:56,  1.03s/it]

usgs-astrogeology_isis3:  24%|███▍          | 443/1833 [07:37<23:55,  1.03s/it]

usgs-astrogeology_isis3:  24%|███▍          | 444/1833 [07:38<23:52,  1.03s/it]

usgs-astrogeology_isis3:  24%|███▍          | 445/1833 [07:39<23:51,  1.03s/it]

usgs-astrogeology_isis3:  24%|███▍          | 446/1833 [07:40<23:48,  1.03s/it]

usgs-astrogeology_isis3:  24%|███▍          | 447/1833 [07:41<23:47,  1.03s/it]

usgs-astrogeology_isis3:  24%|███▍          | 448/1833 [07:42<23:48,  1.03s/it]

usgs-astrogeology_isis3:  24%|███▍          | 449/1833 [07:43<23:46,  1.03s/it]

usgs-astrogeology_isis3:  25%|███▍          | 450/1833 [07:44<23:53,  1.04s/it]

usgs-astrogeology_isis3:  25%|███▍          | 451/1833 [07:45<23:49,  1.03s/it]

usgs-astrogeology_isis3:  25%|███▍          | 452/1833 [07:46<23:46,  1.03s/it]

usgs-astrogeology_isis3:  25%|███▍          | 453/1833 [07:47<23:44,  1.03s/it]

usgs-astrogeology_isis3:  25%|███▍          | 454/1833 [07:48<23:44,  1.03s/it]

usgs-astrogeology_isis3:  25%|███▍          | 455/1833 [07:49<23:44,  1.03s/it]

usgs-astrogeology_isis3:  25%|███▍          | 456/1833 [07:50<23:43,  1.03s/it]

usgs-astrogeology_isis3:  25%|███▍          | 457/1833 [07:51<23:42,  1.03s/it]

usgs-astrogeology_isis3:  25%|███▍          | 458/1833 [07:52<23:40,  1.03s/it]

usgs-astrogeology_isis3:  25%|███▌          | 459/1833 [07:53<23:40,  1.03s/it]

usgs-astrogeology_isis3:  25%|███▌          | 460/1833 [07:54<23:36,  1.03s/it]

usgs-astrogeology_isis3:  25%|███▌          | 461/1833 [07:55<23:35,  1.03s/it]

usgs-astrogeology_isis3:  25%|███▌          | 462/1833 [07:56<23:33,  1.03s/it]

usgs-astrogeology_isis3:  25%|███▌          | 463/1833 [07:57<23:34,  1.03s/it]

usgs-astrogeology_isis3:  25%|███▌          | 464/1833 [07:58<23:33,  1.03s/it]

usgs-astrogeology_isis3:  25%|███▌          | 465/1833 [07:59<23:30,  1.03s/it]

usgs-astrogeology_isis3:  25%|███▌          | 466/1833 [08:00<23:29,  1.03s/it]

usgs-astrogeology_isis3:  25%|███▌          | 467/1833 [08:01<23:27,  1.03s/it]

usgs-astrogeology_isis3:  26%|███▌          | 468/1833 [08:02<23:26,  1.03s/it]

usgs-astrogeology_isis3:  26%|███▌          | 469/1833 [08:03<23:26,  1.03s/it]

usgs-astrogeology_isis3:  26%|███▌          | 470/1833 [08:04<23:27,  1.03s/it]

usgs-astrogeology_isis3:  26%|███▌          | 471/1833 [08:06<23:27,  1.03s/it]

usgs-astrogeology_isis3:  26%|███▌          | 472/1833 [08:07<23:26,  1.03s/it]

usgs-astrogeology_isis3:  26%|███▌          | 473/1833 [08:08<23:23,  1.03s/it]

usgs-astrogeology_isis3:  26%|███▌          | 474/1833 [08:09<23:20,  1.03s/it]

usgs-astrogeology_isis3:  26%|███▋          | 475/1833 [08:10<23:18,  1.03s/it]

usgs-astrogeology_isis3:  26%|███▋          | 476/1833 [08:11<23:17,  1.03s/it]

usgs-astrogeology_isis3:  26%|███▋          | 477/1833 [08:12<23:18,  1.03s/it]

usgs-astrogeology_isis3:  26%|███▋          | 478/1833 [08:13<23:18,  1.03s/it]

usgs-astrogeology_isis3:  26%|███▋          | 479/1833 [08:14<23:17,  1.03s/it]

usgs-astrogeology_isis3:  26%|███▋          | 480/1833 [08:15<23:15,  1.03s/it]

usgs-astrogeology_isis3:  26%|███▋          | 481/1833 [08:16<23:12,  1.03s/it]

usgs-astrogeology_isis3:  26%|███▋          | 482/1833 [08:17<23:09,  1.03s/it]

usgs-astrogeology_isis3:  26%|███▋          | 483/1833 [08:18<23:07,  1.03s/it]

usgs-astrogeology_isis3:  26%|███▋          | 484/1833 [08:19<23:08,  1.03s/it]

usgs-astrogeology_isis3:  26%|███▋          | 485/1833 [08:20<23:09,  1.03s/it]

usgs-astrogeology_isis3:  27%|███▋          | 486/1833 [08:21<23:10,  1.03s/it]

usgs-astrogeology_isis3:  27%|███▋          | 487/1833 [08:22<23:11,  1.03s/it]

usgs-astrogeology_isis3:  27%|███▋          | 488/1833 [08:23<23:09,  1.03s/it]

usgs-astrogeology_isis3:  27%|███▋          | 489/1833 [08:24<23:08,  1.03s/it]

usgs-astrogeology_isis3:  27%|███▋          | 490/1833 [08:25<23:06,  1.03s/it]

usgs-astrogeology_isis3:  27%|███▊          | 491/1833 [08:26<23:06,  1.03s/it]

usgs-astrogeology_isis3:  27%|███▊          | 492/1833 [08:27<23:05,  1.03s/it]

usgs-astrogeology_isis3:  27%|███▊          | 493/1833 [08:28<23:03,  1.03s/it]

usgs-astrogeology_isis3:  27%|███▊          | 494/1833 [08:29<23:02,  1.03s/it]

usgs-astrogeology_isis3:  27%|███▊          | 495/1833 [08:30<23:17,  1.04s/it]

usgs-astrogeology_isis3:  27%|███▊          | 496/1833 [08:31<23:10,  1.04s/it]

usgs-astrogeology_isis3:  27%|███▊          | 497/1833 [08:32<23:07,  1.04s/it]

usgs-astrogeology_isis3:  27%|███▊          | 498/1833 [08:33<23:04,  1.04s/it]

usgs-astrogeology_isis3:  27%|███▊          | 499/1833 [08:34<23:03,  1.04s/it]

usgs-astrogeology_isis3:  27%|███▊          | 500/1833 [08:35<23:01,  1.04s/it]

usgs-astrogeology_isis3:  27%|███▊          | 501/1833 [08:37<22:56,  1.03s/it]

usgs-astrogeology_isis3:  27%|███▊          | 502/1833 [08:38<22:52,  1.03s/it]

usgs-astrogeology_isis3:  27%|███▊          | 503/1833 [08:39<22:50,  1.03s/it]

usgs-astrogeology_isis3:  27%|███▊          | 504/1833 [08:40<22:50,  1.03s/it]

usgs-astrogeology_isis3:  28%|███▊          | 505/1833 [08:41<22:52,  1.03s/it]

usgs-astrogeology_isis3:  28%|███▊          | 506/1833 [08:42<22:50,  1.03s/it]

usgs-astrogeology_isis3:  28%|███▊          | 507/1833 [08:43<22:48,  1.03s/it]

usgs-astrogeology_isis3:  28%|███▉          | 508/1833 [08:44<22:45,  1.03s/it]

usgs-astrogeology_isis3:  28%|███▉          | 509/1833 [08:45<22:43,  1.03s/it]

usgs-astrogeology_isis3:  28%|███▉          | 510/1833 [08:46<22:41,  1.03s/it]

usgs-astrogeology_isis3:  28%|███▉          | 511/1833 [08:47<22:42,  1.03s/it]

usgs-astrogeology_isis3:  28%|███▉          | 512/1833 [08:48<22:42,  1.03s/it]

usgs-astrogeology_isis3:  28%|███▉          | 513/1833 [08:49<22:43,  1.03s/it]

usgs-astrogeology_isis3:  28%|███▉          | 514/1833 [08:50<22:42,  1.03s/it]

usgs-astrogeology_isis3:  28%|███▉          | 515/1833 [08:51<22:42,  1.03s/it]

usgs-astrogeology_isis3:  28%|███▉          | 516/1833 [08:52<22:42,  1.03s/it]

usgs-astrogeology_isis3:  28%|███▉          | 517/1833 [08:53<22:39,  1.03s/it]

usgs-astrogeology_isis3:  28%|███▉          | 518/1833 [08:54<22:37,  1.03s/it]

usgs-astrogeology_isis3:  28%|███▉          | 519/1833 [08:55<22:39,  1.03s/it]

usgs-astrogeology_isis3:  28%|███▉          | 520/1833 [08:56<22:37,  1.03s/it]

usgs-astrogeology_isis3:  28%|███▉          | 521/1833 [08:57<22:37,  1.03s/it]

usgs-astrogeology_isis3:  28%|███▉          | 522/1833 [08:58<22:36,  1.03s/it]

usgs-astrogeology_isis3:  29%|███▉          | 523/1833 [08:59<22:34,  1.03s/it]

usgs-astrogeology_isis3:  29%|████          | 524/1833 [09:00<22:32,  1.03s/it]

usgs-astrogeology_isis3:  29%|████          | 525/1833 [09:01<22:31,  1.03s/it]

usgs-astrogeology_isis3:  29%|████          | 526/1833 [09:02<22:35,  1.04s/it]

usgs-astrogeology_isis3:  29%|████          | 527/1833 [09:03<22:35,  1.04s/it]

usgs-astrogeology_isis3:  29%|████          | 528/1833 [09:04<22:30,  1.03s/it]

usgs-astrogeology_isis3:  29%|████          | 529/1833 [09:05<22:26,  1.03s/it]

usgs-astrogeology_isis3:  29%|████          | 530/1833 [09:06<22:24,  1.03s/it]

usgs-astrogeology_isis3:  29%|████          | 531/1833 [09:07<22:22,  1.03s/it]

usgs-astrogeology_isis3:  29%|████          | 532/1833 [09:09<22:21,  1.03s/it]

usgs-astrogeology_isis3:  29%|████          | 533/1833 [09:10<22:17,  1.03s/it]

usgs-astrogeology_isis3:  29%|████          | 534/1833 [09:11<22:17,  1.03s/it]

usgs-astrogeology_isis3:  29%|████          | 535/1833 [09:12<22:17,  1.03s/it]

usgs-astrogeology_isis3:  29%|████          | 536/1833 [09:13<22:19,  1.03s/it]

usgs-astrogeology_isis3:  29%|████          | 537/1833 [09:14<22:17,  1.03s/it]

usgs-astrogeology_isis3:  29%|████          | 538/1833 [09:15<22:15,  1.03s/it]

  errors: {'4bbc486d965e9d50b474065215370a8bf3e5e40e': 'Key 4bbc486d965e9d50b474065215370a8bf3e5e40e not found in /da5_fast/All.sha1c/commit_75.tch'}

usgs-astrogeology_isis3:  29%|████          | 539/1833 [09:16<22:14,  1.03s/it]

usgs-astrogeology_isis3:  29%|████          | 540/1833 [09:17<22:10,  1.03s/it]

usgs-astrogeology_isis3:  30%|████▏         | 541/1833 [09:18<22:11,  1.03s/it]

usgs-astrogeology_isis3:  30%|████▏         | 542/1833 [09:19<22:12,  1.03s/it]

usgs-astrogeology_isis3:  30%|████▏         | 543/1833 [09:20<22:12,  1.03s/it]

usgs-astrogeology_isis3:  30%|████▏         | 544/1833 [09:21<22:12,  1.03s/it]

usgs-astrogeology_isis3:  30%|████▏         | 545/1833 [09:22<22:10,  1.03s/it]

usgs-astrogeology_isis3:  30%|████▏         | 546/1833 [09:23<22:06,  1.03s/it]

usgs-astrogeology_isis3:  30%|████▏         | 547/1833 [09:24<22:06,  1.03s/it]

usgs-astrogeology_isis3:  30%|████▏         | 548/1833 [09:25<22:04,  1.03s/it]

usgs-astrogeology_isis3:  30%|████▏         | 549/1833 [09:26<22:04,  1.03s/it]

usgs-astrogeology_isis3:  30%|████▏         | 550/1833 [09:27<22:04,  1.03s/it]

usgs-astrogeology_isis3:  30%|████▏         | 551/1833 [09:28<22:04,  1.03s/it]

usgs-astrogeology_isis3:  30%|████▏         | 552/1833 [09:29<22:02,  1.03s/it]

  errors: {'4d6c7cf826c23b611eb01d5f9ba6e70461e334d0': 'Key 4d6c7cf826c23b611eb01d5f9ba6e70461e334d0 not found in /da5_fast/All.sha1c/commit_77.tch'}

usgs-astrogeology_isis3:  30%|████▏         | 553/1833 [09:30<22:01,  1.03s/it]

usgs-astrogeology_isis3:  30%|████▏         | 554/1833 [09:31<21:59,  1.03s/it]

usgs-astrogeology_isis3:  30%|████▏         | 555/1833 [09:32<21:56,  1.03s/it]

usgs-astrogeology_isis3:  30%|████▏         | 556/1833 [09:33<21:55,  1.03s/it]

usgs-astrogeology_isis3:  30%|████▎         | 557/1833 [09:34<21:54,  1.03s/it]

usgs-astrogeology_isis3:  30%|████▎         | 558/1833 [09:35<21:54,  1.03s/it]

usgs-astrogeology_isis3:  30%|████▎         | 559/1833 [09:36<21:54,  1.03s/it]

usgs-astrogeology_isis3:  31%|████▎         | 560/1833 [09:37<21:56,  1.03s/it]

usgs-astrogeology_isis3:  31%|████▎         | 561/1833 [09:38<21:52,  1.03s/it]

usgs-astrogeology_isis3:  31%|████▎         | 562/1833 [09:39<21:49,  1.03s/it]

usgs-astrogeology_isis3:  31%|████▎         | 563/1833 [09:40<21:50,  1.03s/it]

usgs-astrogeology_isis3:  31%|████▎         | 564/1833 [09:42<21:51,  1.03s/it]

usgs-astrogeology_isis3:  31%|████▎         | 565/1833 [09:43<21:52,  1.03s/it]

usgs-astrogeology_isis3:  31%|████▎         | 566/1833 [09:44<21:49,  1.03s/it]

usgs-astrogeology_isis3:  31%|████▎         | 567/1833 [09:45<21:46,  1.03s/it]

usgs-astrogeology_isis3:  31%|████▎         | 568/1833 [09:46<21:43,  1.03s/it]

usgs-astrogeology_isis3:  31%|████▎         | 569/1833 [09:47<21:41,  1.03s/it]

usgs-astrogeology_isis3:  31%|████▎         | 570/1833 [09:48<21:41,  1.03s/it]

usgs-astrogeology_isis3:  31%|████▎         | 571/1833 [09:49<21:40,  1.03s/it]

usgs-astrogeology_isis3:  31%|████▎         | 572/1833 [09:50<21:40,  1.03s/it]

usgs-astrogeology_isis3:  31%|████▍         | 573/1833 [09:51<21:40,  1.03s/it]

usgs-astrogeology_isis3:  31%|████▍         | 574/1833 [09:52<21:38,  1.03s/it]

usgs-astrogeology_isis3:  31%|████▍         | 575/1833 [09:53<21:38,  1.03s/it]

usgs-astrogeology_isis3:  31%|████▍         | 576/1833 [09:54<21:37,  1.03s/it]

usgs-astrogeology_isis3:  31%|████▍         | 577/1833 [09:55<21:34,  1.03s/it]

usgs-astrogeology_isis3:  32%|████▍         | 578/1833 [09:56<21:32,  1.03s/it]

usgs-astrogeology_isis3:  32%|████▍         | 579/1833 [09:57<21:32,  1.03s/it]

usgs-astrogeology_isis3:  32%|████▍         | 580/1833 [09:58<21:30,  1.03s/it]

usgs-astrogeology_isis3:  32%|████▍         | 581/1833 [09:59<21:28,  1.03s/it]

usgs-astrogeology_isis3:  32%|████▍         | 582/1833 [10:00<21:29,  1.03s/it]

usgs-astrogeology_isis3:  32%|████▍         | 583/1833 [10:01<21:27,  1.03s/it]

usgs-astrogeology_isis3:  32%|████▍         | 584/1833 [10:02<21:28,  1.03s/it]

usgs-astrogeology_isis3:  32%|████▍         | 585/1833 [10:03<21:27,  1.03s/it]

usgs-astrogeology_isis3:  32%|████▍         | 586/1833 [10:04<21:25,  1.03s/it]

usgs-astrogeology_isis3:  32%|████▍         | 587/1833 [10:05<21:25,  1.03s/it]

usgs-astrogeology_isis3:  32%|████▍         | 588/1833 [10:06<21:22,  1.03s/it]

usgs-astrogeology_isis3:  32%|████▍         | 589/1833 [10:07<21:20,  1.03s/it]

usgs-astrogeology_isis3:  32%|████▌         | 590/1833 [10:08<21:18,  1.03s/it]

usgs-astrogeology_isis3:  32%|████▌         | 591/1833 [10:09<21:19,  1.03s/it]

usgs-astrogeology_isis3:  32%|████▌         | 592/1833 [10:10<21:17,  1.03s/it]

usgs-astrogeology_isis3:  32%|████▌         | 593/1833 [10:11<21:18,  1.03s/it]

usgs-astrogeology_isis3:  32%|████▌         | 594/1833 [10:12<21:16,  1.03s/it]

usgs-astrogeology_isis3:  32%|████▌         | 595/1833 [10:13<21:17,  1.03s/it]

usgs-astrogeology_isis3:  33%|████▌         | 596/1833 [10:15<21:16,  1.03s/it]

usgs-astrogeology_isis3:  33%|████▌         | 597/1833 [10:16<21:16,  1.03s/it]

usgs-astrogeology_isis3:  33%|████▌         | 598/1833 [10:17<21:13,  1.03s/it]

usgs-astrogeology_isis3:  33%|████▌         | 599/1833 [10:18<21:12,  1.03s/it]

usgs-astrogeology_isis3:  33%|████▌         | 600/1833 [10:19<21:13,  1.03s/it]

usgs-astrogeology_isis3:  33%|████▌         | 601/1833 [10:20<21:11,  1.03s/it]

usgs-astrogeology_isis3:  33%|████▌         | 602/1833 [10:21<21:12,  1.03s/it]

usgs-astrogeology_isis3:  33%|████▌         | 603/1833 [10:22<21:09,  1.03s/it]

usgs-astrogeology_isis3:  33%|████▌         | 604/1833 [10:23<21:06,  1.03s/it]

  errors: {'54e0db34908ac13906efe84008a87d9d7a3afbba': 'Key 54e0db34908ac13906efe84008a87d9d7a3afbba not found in /da5_fast/All.sha1c/commit_84.tch'}

usgs-astrogeology_isis3:  33%|████▌         | 605/1833 [10:24<21:06,  1.03s/it]

usgs-astrogeology_isis3:  33%|████▋         | 606/1833 [10:25<21:04,  1.03s/it]

usgs-astrogeology_isis3:  33%|████▋         | 607/1833 [10:26<21:04,  1.03s/it]

usgs-astrogeology_isis3:  33%|████▋         | 608/1833 [10:27<21:04,  1.03s/it]

usgs-astrogeology_isis3:  33%|████▋         | 609/1833 [10:28<21:04,  1.03s/it]

usgs-astrogeology_isis3:  33%|████▋         | 610/1833 [10:29<21:04,  1.03s/it]

usgs-astrogeology_isis3:  33%|████▋         | 611/1833 [10:30<21:02,  1.03s/it]

usgs-astrogeology_isis3:  33%|████▋         | 612/1833 [10:31<21:00,  1.03s/it]

usgs-astrogeology_isis3:  33%|████▋         | 613/1833 [10:32<20:59,  1.03s/it]

usgs-astrogeology_isis3:  33%|████▋         | 614/1833 [10:33<20:58,  1.03s/it]

usgs-astrogeology_isis3:  34%|████▋         | 615/1833 [10:34<20:56,  1.03s/it]

usgs-astrogeology_isis3:  34%|████▋         | 616/1833 [10:35<20:55,  1.03s/it]

usgs-astrogeology_isis3:  34%|████▋         | 617/1833 [10:36<20:53,  1.03s/it]

usgs-astrogeology_isis3:  34%|████▋         | 618/1833 [10:37<20:51,  1.03s/it]

usgs-astrogeology_isis3:  34%|████▋         | 619/1833 [10:38<20:49,  1.03s/it]

usgs-astrogeology_isis3:  34%|████▋         | 620/1833 [10:39<20:47,  1.03s/it]

usgs-astrogeology_isis3:  34%|████▋         | 621/1833 [10:40<20:47,  1.03s/it]

usgs-astrogeology_isis3:  34%|████▊         | 622/1833 [10:41<20:46,  1.03s/it]

usgs-astrogeology_isis3:  34%|████▊         | 623/1833 [10:42<20:44,  1.03s/it]

usgs-astrogeology_isis3:  34%|████▊         | 624/1833 [10:43<20:43,  1.03s/it]

usgs-astrogeology_isis3:  34%|████▊         | 625/1833 [10:44<20:41,  1.03s/it]

usgs-astrogeology_isis3:  34%|████▊         | 626/1833 [10:45<20:41,  1.03s/it]

usgs-astrogeology_isis3:  34%|████▊         | 627/1833 [10:46<20:42,  1.03s/it]

usgs-astrogeology_isis3:  34%|████▊         | 628/1833 [10:48<20:43,  1.03s/it]

usgs-astrogeology_isis3:  34%|████▊         | 629/1833 [10:49<20:43,  1.03s/it]

usgs-astrogeology_isis3:  34%|████▊         | 630/1833 [10:50<20:41,  1.03s/it]

usgs-astrogeology_isis3:  34%|████▊         | 631/1833 [10:51<20:39,  1.03s/it]

usgs-astrogeology_isis3:  34%|████▊         | 632/1833 [10:52<20:38,  1.03s/it]

usgs-astrogeology_isis3:  35%|████▊         | 633/1833 [10:53<20:37,  1.03s/it]

usgs-astrogeology_isis3:  35%|████▊         | 634/1833 [10:54<20:37,  1.03s/it]

usgs-astrogeology_isis3:  35%|████▊         | 635/1833 [10:55<20:36,  1.03s/it]

usgs-astrogeology_isis3:  35%|████▊         | 636/1833 [10:56<20:35,  1.03s/it]

usgs-astrogeology_isis3:  35%|████▊         | 637/1833 [10:57<20:35,  1.03s/it]

usgs-astrogeology_isis3:  35%|████▊         | 638/1833 [10:58<20:32,  1.03s/it]

usgs-astrogeology_isis3:  35%|████▉         | 639/1833 [10:59<20:31,  1.03s/it]

usgs-astrogeology_isis3:  35%|████▉         | 640/1833 [11:00<20:29,  1.03s/it]

usgs-astrogeology_isis3:  35%|████▉         | 641/1833 [11:01<20:28,  1.03s/it]

usgs-astrogeology_isis3:  35%|████▉         | 642/1833 [11:02<20:29,  1.03s/it]

usgs-astrogeology_isis3:  35%|████▉         | 643/1833 [11:03<20:29,  1.03s/it]

usgs-astrogeology_isis3:  35%|████▉         | 644/1833 [11:04<20:28,  1.03s/it]

usgs-astrogeology_isis3:  35%|████▉         | 645/1833 [11:05<20:27,  1.03s/it]

usgs-astrogeology_isis3:  35%|████▉         | 646/1833 [11:06<20:24,  1.03s/it]

usgs-astrogeology_isis3:  35%|████▉         | 647/1833 [11:07<20:23,  1.03s/it]

usgs-astrogeology_isis3:  35%|████▉         | 648/1833 [11:08<20:20,  1.03s/it]

usgs-astrogeology_isis3:  35%|████▉         | 649/1833 [11:09<20:20,  1.03s/it]

  errors: {'5b1f102355b0ecbc597843db72f96249fc4e7fc8': 'Key 5b1f102355b0ecbc597843db72f96249fc4e7fc8 not found in /da5_fast/All.sha1c/commit_91.tch'}

usgs-astrogeology_isis3:  35%|████▉         | 650/1833 [11:10<21:41,  1.10s/it]

usgs-astrogeology_isis3:  36%|████▉         | 651/1833 [11:11<21:14,  1.08s/it]

usgs-astrogeology_isis3:  36%|████▉         | 652/1833 [11:13<20:56,  1.06s/it]

usgs-astrogeology_isis3:  36%|████▉         | 653/1833 [11:14<21:05,  1.07s/it]

usgs-astrogeology_isis3:  36%|████▉         | 654/1833 [11:15<21:09,  1.08s/it]

usgs-astrogeology_isis3:  36%|█████         | 655/1833 [11:16<20:52,  1.06s/it]

usgs-astrogeology_isis3:  36%|█████         | 656/1833 [11:17<20:38,  1.05s/it]

usgs-astrogeology_isis3:  36%|█████         | 657/1833 [11:18<20:29,  1.05s/it]

usgs-astrogeology_isis3:  36%|█████         | 658/1833 [11:19<20:24,  1.04s/it]

usgs-astrogeology_isis3:  36%|█████         | 659/1833 [11:20<20:17,  1.04s/it]

usgs-astrogeology_isis3:  36%|█████         | 660/1833 [11:21<20:17,  1.04s/it]

usgs-astrogeology_isis3:  36%|█████         | 661/1833 [11:22<20:15,  1.04s/it]

usgs-astrogeology_isis3:  36%|█████         | 662/1833 [11:23<20:12,  1.04s/it]

usgs-astrogeology_isis3:  36%|█████         | 663/1833 [11:24<20:09,  1.03s/it]

usgs-astrogeology_isis3:  36%|█████         | 664/1833 [11:25<20:07,  1.03s/it]

usgs-astrogeology_isis3:  36%|█████         | 665/1833 [11:26<20:05,  1.03s/it]

usgs-astrogeology_isis3:  36%|█████         | 666/1833 [11:27<20:04,  1.03s/it]

usgs-astrogeology_isis3:  36%|█████         | 667/1833 [11:28<20:04,  1.03s/it]

usgs-astrogeology_isis3:  36%|█████         | 668/1833 [11:29<20:03,  1.03s/it]

usgs-astrogeology_isis3:  36%|█████         | 669/1833 [11:30<20:01,  1.03s/it]

usgs-astrogeology_isis3:  37%|█████         | 670/1833 [11:31<19:58,  1.03s/it]

usgs-astrogeology_isis3:  37%|█████         | 671/1833 [11:32<19:57,  1.03s/it]

usgs-astrogeology_isis3:  37%|█████▏        | 672/1833 [11:33<19:56,  1.03s/it]

usgs-astrogeology_isis3:  37%|█████▏        | 673/1833 [11:34<19:54,  1.03s/it]

usgs-astrogeology_isis3:  37%|█████▏        | 674/1833 [11:35<19:51,  1.03s/it]

usgs-astrogeology_isis3:  37%|█████▏        | 675/1833 [11:36<19:51,  1.03s/it]

usgs-astrogeology_isis3:  37%|█████▏        | 676/1833 [11:37<19:51,  1.03s/it]

usgs-astrogeology_isis3:  37%|█████▏        | 677/1833 [11:38<19:51,  1.03s/it]

usgs-astrogeology_isis3:  37%|█████▏        | 678/1833 [11:39<19:50,  1.03s/it]

usgs-astrogeology_isis3:  37%|█████▏        | 679/1833 [11:40<19:49,  1.03s/it]

usgs-astrogeology_isis3:  37%|█████▏        | 680/1833 [11:41<19:49,  1.03s/it]

usgs-astrogeology_isis3:  37%|█████▏        | 681/1833 [11:43<19:47,  1.03s/it]

usgs-astrogeology_isis3:  37%|█████▏        | 682/1833 [11:44<19:45,  1.03s/it]

usgs-astrogeology_isis3:  37%|█████▏        | 683/1833 [11:45<19:43,  1.03s/it]

usgs-astrogeology_isis3:  37%|█████▏        | 684/1833 [11:46<19:40,  1.03s/it]

usgs-astrogeology_isis3:  37%|█████▏        | 685/1833 [11:47<19:39,  1.03s/it]

usgs-astrogeology_isis3:  37%|█████▏        | 686/1833 [11:48<19:40,  1.03s/it]

usgs-astrogeology_isis3:  37%|█████▏        | 687/1833 [11:49<19:40,  1.03s/it]

usgs-astrogeology_isis3:  38%|█████▎        | 688/1833 [11:50<19:40,  1.03s/it]

usgs-astrogeology_isis3:  38%|█████▎        | 689/1833 [11:51<19:40,  1.03s/it]

usgs-astrogeology_isis3:  38%|█████▎        | 690/1833 [11:52<19:38,  1.03s/it]

usgs-astrogeology_isis3:  38%|█████▎        | 691/1833 [11:53<19:37,  1.03s/it]

usgs-astrogeology_isis3:  38%|█████▎        | 692/1833 [11:54<19:34,  1.03s/it]

usgs-astrogeology_isis3:  38%|█████▎        | 693/1833 [11:55<19:34,  1.03s/it]

usgs-astrogeology_isis3:  38%|█████▎        | 694/1833 [11:56<19:35,  1.03s/it]

usgs-astrogeology_isis3:  38%|█████▎        | 695/1833 [11:57<19:36,  1.03s/it]

usgs-astrogeology_isis3:  38%|█████▎        | 696/1833 [11:58<19:35,  1.03s/it]

usgs-astrogeology_isis3:  38%|█████▎        | 697/1833 [11:59<19:39,  1.04s/it]

usgs-astrogeology_isis3:  38%|█████▎        | 698/1833 [12:00<19:36,  1.04s/it]

usgs-astrogeology_isis3:  38%|█████▎        | 699/1833 [12:01<19:34,  1.04s/it]

usgs-astrogeology_isis3:  38%|█████▎        | 700/1833 [12:02<19:30,  1.03s/it]

usgs-astrogeology_isis3:  38%|█████▎        | 701/1833 [12:03<19:30,  1.03s/it]

usgs-astrogeology_isis3:  38%|█████▎        | 702/1833 [12:04<19:28,  1.03s/it]

usgs-astrogeology_isis3:  38%|█████▎        | 703/1833 [12:05<19:26,  1.03s/it]

usgs-astrogeology_isis3:  38%|█████▍        | 704/1833 [12:06<19:26,  1.03s/it]

usgs-astrogeology_isis3:  38%|█████▍        | 705/1833 [12:07<19:21,  1.03s/it]

usgs-astrogeology_isis3:  39%|█████▍        | 706/1833 [12:08<19:22,  1.03s/it]

usgs-astrogeology_isis3:  39%|█████▍        | 707/1833 [12:09<19:20,  1.03s/it]

usgs-astrogeology_isis3:  39%|█████▍        | 708/1833 [12:10<19:19,  1.03s/it]

usgs-astrogeology_isis3:  39%|█████▍        | 709/1833 [12:11<19:19,  1.03s/it]

usgs-astrogeology_isis3:  39%|█████▍        | 710/1833 [12:12<19:14,  1.03s/it]

usgs-astrogeology_isis3:  39%|█████▍        | 711/1833 [12:13<19:16,  1.03s/it]

usgs-astrogeology_isis3:  39%|█████▍        | 712/1833 [12:14<19:15,  1.03s/it]

usgs-astrogeology_isis3:  39%|█████▍        | 713/1833 [12:16<19:23,  1.04s/it]

usgs-astrogeology_isis3:  39%|█████▍        | 714/1833 [12:17<19:20,  1.04s/it]

usgs-astrogeology_isis3:  39%|█████▍        | 715/1833 [12:18<19:16,  1.03s/it]

usgs-astrogeology_isis3:  39%|█████▍        | 716/1833 [12:19<19:16,  1.04s/it]

usgs-astrogeology_isis3:  39%|█████▍        | 717/1833 [12:20<19:14,  1.03s/it]

usgs-astrogeology_isis3:  39%|█████▍        | 718/1833 [12:21<19:12,  1.03s/it]

usgs-astrogeology_isis3:  39%|█████▍        | 719/1833 [12:22<19:10,  1.03s/it]

usgs-astrogeology_isis3:  39%|█████▍        | 720/1833 [12:23<19:08,  1.03s/it]

usgs-astrogeology_isis3:  39%|█████▌        | 721/1833 [12:24<19:03,  1.03s/it]

usgs-astrogeology_isis3:  39%|█████▌        | 722/1833 [12:25<19:02,  1.03s/it]

usgs-astrogeology_isis3:  39%|█████▌        | 723/1833 [12:26<19:01,  1.03s/it]

usgs-astrogeology_isis3:  39%|█████▌        | 724/1833 [12:27<19:01,  1.03s/it]

usgs-astrogeology_isis3:  40%|█████▌        | 725/1833 [12:28<19:01,  1.03s/it]

usgs-astrogeology_isis3:  40%|█████▌        | 726/1833 [12:29<18:59,  1.03s/it]

usgs-astrogeology_isis3:  40%|█████▌        | 727/1833 [12:30<19:00,  1.03s/it]

usgs-astrogeology_isis3:  40%|█████▌        | 728/1833 [12:31<18:58,  1.03s/it]

usgs-astrogeology_isis3:  40%|█████▌        | 729/1833 [12:32<18:57,  1.03s/it]

usgs-astrogeology_isis3:  40%|█████▌        | 730/1833 [12:33<18:55,  1.03s/it]

usgs-astrogeology_isis3:  40%|█████▌        | 731/1833 [12:34<18:54,  1.03s/it]

usgs-astrogeology_isis3:  40%|█████▌        | 732/1833 [12:35<18:55,  1.03s/it]

usgs-astrogeology_isis3:  40%|█████▌        | 733/1833 [12:36<18:53,  1.03s/it]

usgs-astrogeology_isis3:  40%|█████▌        | 734/1833 [12:37<18:52,  1.03s/it]

usgs-astrogeology_isis3:  40%|█████▌        | 735/1833 [12:38<18:51,  1.03s/it]

usgs-astrogeology_isis3:  40%|█████▌        | 736/1833 [12:39<18:49,  1.03s/it]

usgs-astrogeology_isis3:  40%|█████▋        | 737/1833 [12:40<18:49,  1.03s/it]

usgs-astrogeology_isis3:  40%|█████▋        | 738/1833 [12:41<18:49,  1.03s/it]

usgs-astrogeology_isis3:  40%|█████▋        | 739/1833 [12:42<18:49,  1.03s/it]

usgs-astrogeology_isis3:  40%|█████▋        | 740/1833 [12:43<18:49,  1.03s/it]

usgs-astrogeology_isis3:  40%|█████▋        | 741/1833 [12:44<18:48,  1.03s/it]

usgs-astrogeology_isis3:  40%|█████▋        | 742/1833 [12:45<18:46,  1.03s/it]

usgs-astrogeology_isis3:  41%|█████▋        | 743/1833 [12:46<18:42,  1.03s/it]

usgs-astrogeology_isis3:  41%|█████▋        | 744/1833 [12:47<18:40,  1.03s/it]

usgs-astrogeology_isis3:  41%|█████▋        | 745/1833 [12:49<18:44,  1.03s/it]

usgs-astrogeology_isis3:  41%|█████▋        | 746/1833 [12:50<18:44,  1.03s/it]

usgs-astrogeology_isis3:  41%|█████▋        | 747/1833 [12:51<18:41,  1.03s/it]

usgs-astrogeology_isis3:  41%|█████▋        | 748/1833 [12:52<18:39,  1.03s/it]

usgs-astrogeology_isis3:  41%|█████▋        | 749/1833 [12:53<18:37,  1.03s/it]

usgs-astrogeology_isis3:  41%|█████▋        | 750/1833 [12:54<18:35,  1.03s/it]

usgs-astrogeology_isis3:  41%|█████▋        | 751/1833 [12:55<18:36,  1.03s/it]

usgs-astrogeology_isis3:  41%|█████▋        | 752/1833 [12:56<18:36,  1.03s/it]

usgs-astrogeology_isis3:  41%|█████▊        | 753/1833 [12:57<18:36,  1.03s/it]

usgs-astrogeology_isis3:  41%|█████▊        | 754/1833 [12:58<18:36,  1.04s/it]

usgs-astrogeology_isis3:  41%|█████▊        | 755/1833 [12:59<18:35,  1.04s/it]

usgs-astrogeology_isis3:  41%|█████▊        | 756/1833 [13:00<18:32,  1.03s/it]

usgs-astrogeology_isis3:  41%|█████▊        | 757/1833 [13:01<18:29,  1.03s/it]

usgs-astrogeology_isis3:  41%|█████▊        | 758/1833 [13:02<18:29,  1.03s/it]

usgs-astrogeology_isis3:  41%|█████▊        | 759/1833 [13:03<18:26,  1.03s/it]

usgs-astrogeology_isis3:  41%|█████▊        | 760/1833 [13:04<18:25,  1.03s/it]

usgs-astrogeology_isis3:  42%|█████▊        | 761/1833 [13:05<18:24,  1.03s/it]

usgs-astrogeology_isis3:  42%|█████▊        | 762/1833 [13:06<18:25,  1.03s/it]

usgs-astrogeology_isis3:  42%|█████▊        | 763/1833 [13:07<18:24,  1.03s/it]

usgs-astrogeology_isis3:  42%|█████▊        | 764/1833 [13:08<18:21,  1.03s/it]

usgs-astrogeology_isis3:  42%|█████▊        | 765/1833 [13:09<18:18,  1.03s/it]

usgs-astrogeology_isis3:  42%|█████▊        | 766/1833 [13:10<18:17,  1.03s/it]

usgs-astrogeology_isis3:  42%|█████▊        | 767/1833 [13:11<18:19,  1.03s/it]

usgs-astrogeology_isis3:  42%|█████▊        | 768/1833 [13:12<18:18,  1.03s/it]

usgs-astrogeology_isis3:  42%|█████▊        | 769/1833 [13:13<18:18,  1.03s/it]

usgs-astrogeology_isis3:  42%|█████▉        | 770/1833 [13:14<18:15,  1.03s/it]

usgs-astrogeology_isis3:  42%|█████▉        | 771/1833 [13:15<18:12,  1.03s/it]

usgs-astrogeology_isis3:  42%|█████▉        | 772/1833 [13:16<18:12,  1.03s/it]

usgs-astrogeology_isis3:  42%|█████▉        | 773/1833 [13:17<18:11,  1.03s/it]

usgs-astrogeology_isis3:  42%|█████▉        | 774/1833 [13:18<18:10,  1.03s/it]

usgs-astrogeology_isis3:  42%|█████▉        | 775/1833 [13:19<18:11,  1.03s/it]

usgs-astrogeology_isis3:  42%|█████▉        | 776/1833 [13:21<18:09,  1.03s/it]

usgs-astrogeology_isis3:  42%|█████▉        | 777/1833 [13:22<18:08,  1.03s/it]

usgs-astrogeology_isis3:  42%|█████▉        | 778/1833 [13:23<18:07,  1.03s/it]

usgs-astrogeology_isis3:  42%|█████▉        | 779/1833 [13:24<18:06,  1.03s/it]

usgs-astrogeology_isis3:  43%|█████▉        | 780/1833 [13:25<18:04,  1.03s/it]

usgs-astrogeology_isis3:  43%|█████▉        | 781/1833 [13:26<18:03,  1.03s/it]

usgs-astrogeology_isis3:  43%|█████▉        | 782/1833 [13:27<18:04,  1.03s/it]

usgs-astrogeology_isis3:  43%|█████▉        | 783/1833 [13:28<18:02,  1.03s/it]

usgs-astrogeology_isis3:  43%|█████▉        | 784/1833 [13:29<18:02,  1.03s/it]

usgs-astrogeology_isis3:  43%|█████▉        | 785/1833 [13:30<18:01,  1.03s/it]

usgs-astrogeology_isis3:  43%|██████        | 786/1833 [13:31<17:59,  1.03s/it]

usgs-astrogeology_isis3:  43%|██████        | 787/1833 [13:32<18:18,  1.05s/it]

usgs-astrogeology_isis3:  43%|██████        | 788/1833 [13:33<18:09,  1.04s/it]

usgs-astrogeology_isis3:  43%|██████        | 789/1833 [13:34<18:05,  1.04s/it]

usgs-astrogeology_isis3:  43%|██████        | 790/1833 [13:35<18:02,  1.04s/it]

usgs-astrogeology_isis3:  43%|██████        | 791/1833 [13:36<17:59,  1.04s/it]

usgs-astrogeology_isis3:  43%|██████        | 792/1833 [13:37<17:56,  1.03s/it]

usgs-astrogeology_isis3:  43%|██████        | 793/1833 [13:38<17:55,  1.03s/it]

usgs-astrogeology_isis3:  43%|██████        | 794/1833 [13:39<17:52,  1.03s/it]

usgs-astrogeology_isis3:  43%|██████        | 795/1833 [13:40<17:48,  1.03s/it]

usgs-astrogeology_isis3:  43%|██████        | 796/1833 [13:41<17:46,  1.03s/it]

usgs-astrogeology_isis3:  43%|██████        | 797/1833 [13:42<17:46,  1.03s/it]

usgs-astrogeology_isis3:  44%|██████        | 798/1833 [13:43<17:48,  1.03s/it]

usgs-astrogeology_isis3:  44%|██████        | 799/1833 [13:44<17:47,  1.03s/it]

usgs-astrogeology_isis3:  44%|██████        | 800/1833 [13:45<17:46,  1.03s/it]

usgs-astrogeology_isis3:  44%|██████        | 801/1833 [13:46<17:45,  1.03s/it]

usgs-astrogeology_isis3:  44%|██████▏       | 802/1833 [13:47<17:48,  1.04s/it]

usgs-astrogeology_isis3:  44%|██████▏       | 803/1833 [13:48<17:46,  1.04s/it]

usgs-astrogeology_isis3:  44%|██████▏       | 804/1833 [13:49<17:45,  1.04s/it]

usgs-astrogeology_isis3:  44%|██████▏       | 805/1833 [13:50<17:43,  1.03s/it]

usgs-astrogeology_isis3:  44%|██████▏       | 806/1833 [13:52<17:41,  1.03s/it]

usgs-astrogeology_isis3:  44%|██████▏       | 807/1833 [13:53<17:39,  1.03s/it]

usgs-astrogeology_isis3:  44%|██████▏       | 808/1833 [13:54<17:36,  1.03s/it]

usgs-astrogeology_isis3:  44%|██████▏       | 809/1833 [13:55<17:35,  1.03s/it]

usgs-astrogeology_isis3:  44%|██████▏       | 810/1833 [13:56<17:35,  1.03s/it]

usgs-astrogeology_isis3:  44%|██████▏       | 811/1833 [13:57<17:35,  1.03s/it]

usgs-astrogeology_isis3:  44%|██████▏       | 812/1833 [13:58<17:32,  1.03s/it]

usgs-astrogeology_isis3:  44%|██████▏       | 813/1833 [13:59<17:30,  1.03s/it]

usgs-astrogeology_isis3:  44%|██████▏       | 814/1833 [14:00<17:30,  1.03s/it]

usgs-astrogeology_isis3:  44%|██████▏       | 815/1833 [14:01<17:29,  1.03s/it]

usgs-astrogeology_isis3:  45%|██████▏       | 816/1833 [14:02<17:28,  1.03s/it]

usgs-astrogeology_isis3:  45%|██████▏       | 817/1833 [14:03<17:28,  1.03s/it]

usgs-astrogeology_isis3:  45%|██████▏       | 818/1833 [14:04<17:28,  1.03s/it]

usgs-astrogeology_isis3:  45%|██████▎       | 819/1833 [14:05<17:26,  1.03s/it]

usgs-astrogeology_isis3:  45%|██████▎       | 820/1833 [14:06<17:26,  1.03s/it]

usgs-astrogeology_isis3:  45%|██████▎       | 821/1833 [14:07<17:23,  1.03s/it]

usgs-astrogeology_isis3:  45%|██████▎       | 822/1833 [14:08<17:23,  1.03s/it]

usgs-astrogeology_isis3:  45%|██████▎       | 823/1833 [14:09<17:22,  1.03s/it]

usgs-astrogeology_isis3:  45%|██████▎       | 824/1833 [14:10<17:20,  1.03s/it]

usgs-astrogeology_isis3:  45%|██████▎       | 825/1833 [14:11<17:20,  1.03s/it]

usgs-astrogeology_isis3:  45%|██████▎       | 826/1833 [14:12<17:17,  1.03s/it]

usgs-astrogeology_isis3:  45%|██████▎       | 827/1833 [14:13<17:15,  1.03s/it]

usgs-astrogeology_isis3:  45%|██████▎       | 828/1833 [14:14<17:15,  1.03s/it]

usgs-astrogeology_isis3:  45%|██████▎       | 829/1833 [14:15<17:15,  1.03s/it]

usgs-astrogeology_isis3:  45%|██████▎       | 830/1833 [14:16<17:15,  1.03s/it]

usgs-astrogeology_isis3:  45%|██████▎       | 831/1833 [14:17<17:14,  1.03s/it]

usgs-astrogeology_isis3:  45%|██████▎       | 832/1833 [14:18<17:14,  1.03s/it]

usgs-astrogeology_isis3:  45%|██████▎       | 833/1833 [14:19<17:13,  1.03s/it]

usgs-astrogeology_isis3:  45%|██████▎       | 834/1833 [14:20<17:09,  1.03s/it]

usgs-astrogeology_isis3:  46%|██████▍       | 835/1833 [14:21<17:07,  1.03s/it]

usgs-astrogeology_isis3:  46%|██████▍       | 836/1833 [14:22<17:08,  1.03s/it]

usgs-astrogeology_isis3:  46%|██████▍       | 837/1833 [14:24<17:08,  1.03s/it]

usgs-astrogeology_isis3:  46%|██████▍       | 838/1833 [14:25<17:08,  1.03s/it]

usgs-astrogeology_isis3:  46%|██████▍       | 839/1833 [14:26<17:07,  1.03s/it]

usgs-astrogeology_isis3:  46%|██████▍       | 840/1833 [14:27<17:05,  1.03s/it]

usgs-astrogeology_isis3:  46%|██████▍       | 841/1833 [14:28<17:02,  1.03s/it]

usgs-astrogeology_isis3:  46%|██████▍       | 842/1833 [14:29<17:02,  1.03s/it]

usgs-astrogeology_isis3:  46%|██████▍       | 843/1833 [14:30<16:59,  1.03s/it]

usgs-astrogeology_isis3:  46%|██████▍       | 844/1833 [14:31<16:57,  1.03s/it]

usgs-astrogeology_isis3:  46%|██████▍       | 845/1833 [14:32<16:55,  1.03s/it]

usgs-astrogeology_isis3:  46%|██████▍       | 846/1833 [14:33<16:55,  1.03s/it]

usgs-astrogeology_isis3:  46%|██████▍       | 847/1833 [14:34<16:54,  1.03s/it]

usgs-astrogeology_isis3:  46%|██████▍       | 848/1833 [14:35<16:58,  1.03s/it]

usgs-astrogeology_isis3:  46%|██████▍       | 849/1833 [14:36<16:54,  1.03s/it]

usgs-astrogeology_isis3:  46%|██████▍       | 850/1833 [14:37<16:52,  1.03s/it]

usgs-astrogeology_isis3:  46%|██████▍       | 851/1833 [14:38<16:53,  1.03s/it]

usgs-astrogeology_isis3:  46%|██████▌       | 852/1833 [14:39<16:51,  1.03s/it]

usgs-astrogeology_isis3:  47%|██████▌       | 853/1833 [14:40<16:51,  1.03s/it]

usgs-astrogeology_isis3:  47%|██████▌       | 854/1833 [14:41<16:51,  1.03s/it]

usgs-astrogeology_isis3:  47%|██████▌       | 855/1833 [14:42<16:50,  1.03s/it]

usgs-astrogeology_isis3:  47%|██████▌       | 856/1833 [14:43<16:50,  1.03s/it]

usgs-astrogeology_isis3:  47%|██████▌       | 857/1833 [14:44<16:46,  1.03s/it]

usgs-astrogeology_isis3:  47%|██████▌       | 858/1833 [14:45<16:44,  1.03s/it]

usgs-astrogeology_isis3:  47%|██████▌       | 859/1833 [14:46<16:44,  1.03s/it]

usgs-astrogeology_isis3:  47%|██████▌       | 860/1833 [14:47<16:45,  1.03s/it]

usgs-astrogeology_isis3:  47%|██████▌       | 861/1833 [14:48<16:45,  1.03s/it]

usgs-astrogeology_isis3:  47%|██████▌       | 862/1833 [14:49<16:42,  1.03s/it]

usgs-astrogeology_isis3:  47%|██████▌       | 863/1833 [14:50<16:40,  1.03s/it]

usgs-astrogeology_isis3:  47%|██████▌       | 864/1833 [14:51<16:41,  1.03s/it]

usgs-astrogeology_isis3:  47%|██████▌       | 865/1833 [14:52<16:38,  1.03s/it]

usgs-astrogeology_isis3:  47%|██████▌       | 866/1833 [14:53<16:37,  1.03s/it]

usgs-astrogeology_isis3:  47%|██████▌       | 867/1833 [14:54<16:36,  1.03s/it]

usgs-astrogeology_isis3:  47%|██████▋       | 868/1833 [14:55<16:35,  1.03s/it]

usgs-astrogeology_isis3:  47%|██████▋       | 869/1833 [14:57<16:33,  1.03s/it]

usgs-astrogeology_isis3:  47%|██████▋       | 870/1833 [14:58<16:31,  1.03s/it]

usgs-astrogeology_isis3:  48%|██████▋       | 871/1833 [14:59<16:30,  1.03s/it]

usgs-astrogeology_isis3:  48%|██████▋       | 872/1833 [15:00<16:27,  1.03s/it]

usgs-astrogeology_isis3:  48%|██████▋       | 873/1833 [15:01<16:28,  1.03s/it]

usgs-astrogeology_isis3:  48%|██████▋       | 874/1833 [15:02<16:32,  1.03s/it]

usgs-astrogeology_isis3:  48%|██████▋       | 875/1833 [15:03<16:29,  1.03s/it]

usgs-astrogeology_isis3:  48%|██████▋       | 876/1833 [15:04<16:26,  1.03s/it]

usgs-astrogeology_isis3:  48%|██████▋       | 877/1833 [15:05<16:24,  1.03s/it]

usgs-astrogeology_isis3:  48%|██████▋       | 878/1833 [15:06<16:22,  1.03s/it]

usgs-astrogeology_isis3:  48%|██████▋       | 879/1833 [15:07<16:22,  1.03s/it]

usgs-astrogeology_isis3:  48%|██████▋       | 880/1833 [15:08<16:22,  1.03s/it]

usgs-astrogeology_isis3:  48%|██████▋       | 881/1833 [15:09<16:20,  1.03s/it]

usgs-astrogeology_isis3:  48%|██████▋       | 882/1833 [15:10<16:18,  1.03s/it]

usgs-astrogeology_isis3:  48%|██████▋       | 883/1833 [15:11<16:15,  1.03s/it]

usgs-astrogeology_isis3:  48%|██████▊       | 884/1833 [15:12<16:14,  1.03s/it]

usgs-astrogeology_isis3:  48%|██████▊       | 885/1833 [15:13<16:13,  1.03s/it]

usgs-astrogeology_isis3:  48%|██████▊       | 886/1833 [15:14<16:13,  1.03s/it]

usgs-astrogeology_isis3:  48%|██████▊       | 887/1833 [15:15<16:14,  1.03s/it]

usgs-astrogeology_isis3:  48%|██████▊       | 888/1833 [15:16<16:12,  1.03s/it]

usgs-astrogeology_isis3:  48%|██████▊       | 889/1833 [15:17<16:11,  1.03s/it]

usgs-astrogeology_isis3:  49%|██████▊       | 890/1833 [15:18<16:08,  1.03s/it]

usgs-astrogeology_isis3:  49%|██████▊       | 891/1833 [15:19<16:09,  1.03s/it]

usgs-astrogeology_isis3:  49%|██████▊       | 892/1833 [15:20<16:07,  1.03s/it]

usgs-astrogeology_isis3:  49%|██████▊       | 893/1833 [15:21<16:06,  1.03s/it]

usgs-astrogeology_isis3:  49%|██████▊       | 894/1833 [15:22<16:07,  1.03s/it]

usgs-astrogeology_isis3:  49%|██████▊       | 895/1833 [15:23<16:07,  1.03s/it]

usgs-astrogeology_isis3:  49%|██████▊       | 896/1833 [15:24<16:05,  1.03s/it]

usgs-astrogeology_isis3:  49%|██████▊       | 897/1833 [15:25<16:02,  1.03s/it]

usgs-astrogeology_isis3:  49%|██████▊       | 898/1833 [15:26<16:00,  1.03s/it]

usgs-astrogeology_isis3:  49%|██████▊       | 899/1833 [15:27<16:01,  1.03s/it]

usgs-astrogeology_isis3:  49%|██████▊       | 900/1833 [15:28<16:01,  1.03s/it]

usgs-astrogeology_isis3:  49%|██████▉       | 901/1833 [15:29<16:00,  1.03s/it]

usgs-astrogeology_isis3:  49%|██████▉       | 902/1833 [15:30<15:59,  1.03s/it]

usgs-astrogeology_isis3:  49%|██████▉       | 903/1833 [15:32<15:56,  1.03s/it]

usgs-astrogeology_isis3:  49%|██████▉       | 904/1833 [15:33<15:56,  1.03s/it]

usgs-astrogeology_isis3:  49%|██████▉       | 905/1833 [15:34<15:53,  1.03s/it]

usgs-astrogeology_isis3:  49%|██████▉       | 906/1833 [15:35<15:53,  1.03s/it]

  errors: {'7f2017024600f7765f9b787387f9b450892575fe': 'Key 7f2017024600f7765f9b787387f9b450892575fe not found in /da5_fast/All.sha1c/commit_127.tch'}

usgs-astrogeology_isis3:  49%|██████▉       | 907/1833 [15:36<15:52,  1.03s/it]

usgs-astrogeology_isis3:  50%|██████▉       | 908/1833 [15:37<15:52,  1.03s/it]

usgs-astrogeology_isis3:  50%|██████▉       | 909/1833 [15:38<15:52,  1.03s/it]

usgs-astrogeology_isis3:  50%|██████▉       | 910/1833 [15:39<15:51,  1.03s/it]

usgs-astrogeology_isis3:  50%|██████▉       | 911/1833 [15:40<15:47,  1.03s/it]

usgs-astrogeology_isis3:  50%|██████▉       | 912/1833 [15:41<15:47,  1.03s/it]

usgs-astrogeology_isis3:  50%|██████▉       | 913/1833 [15:42<15:46,  1.03s/it]

usgs-astrogeology_isis3:  50%|██████▉       | 914/1833 [15:43<15:45,  1.03s/it]

usgs-astrogeology_isis3:  50%|██████▉       | 915/1833 [15:44<15:43,  1.03s/it]

usgs-astrogeology_isis3:  50%|██████▉       | 916/1833 [15:45<15:42,  1.03s/it]

usgs-astrogeology_isis3:  50%|███████       | 917/1833 [15:46<15:41,  1.03s/it]

usgs-astrogeology_isis3:  50%|███████       | 918/1833 [15:47<15:39,  1.03s/it]

usgs-astrogeology_isis3:  50%|███████       | 919/1833 [15:48<15:37,  1.03s/it]

usgs-astrogeology_isis3:  50%|███████       | 920/1833 [15:49<15:36,  1.03s/it]

usgs-astrogeology_isis3:  50%|███████       | 921/1833 [15:50<15:36,  1.03s/it]

usgs-astrogeology_isis3:  50%|███████       | 922/1833 [15:51<15:35,  1.03s/it]

usgs-astrogeology_isis3:  50%|███████       | 923/1833 [15:52<15:35,  1.03s/it]

usgs-astrogeology_isis3:  50%|███████       | 924/1833 [15:53<15:34,  1.03s/it]

usgs-astrogeology_isis3:  50%|███████       | 925/1833 [15:54<15:34,  1.03s/it]

usgs-astrogeology_isis3:  51%|███████       | 926/1833 [15:55<15:32,  1.03s/it]

usgs-astrogeology_isis3:  51%|███████       | 927/1833 [15:56<15:32,  1.03s/it]

usgs-astrogeology_isis3:  51%|███████       | 928/1833 [15:57<15:32,  1.03s/it]

usgs-astrogeology_isis3:  51%|███████       | 929/1833 [15:58<15:30,  1.03s/it]

usgs-astrogeology_isis3:  51%|███████       | 930/1833 [15:59<15:29,  1.03s/it]

usgs-astrogeology_isis3:  51%|███████       | 931/1833 [16:00<15:27,  1.03s/it]

usgs-astrogeology_isis3:  51%|███████       | 932/1833 [16:01<15:26,  1.03s/it]

usgs-astrogeology_isis3:  51%|███████▏      | 933/1833 [16:02<15:24,  1.03s/it]

usgs-astrogeology_isis3:  51%|███████▏      | 934/1833 [16:03<15:26,  1.03s/it]

usgs-astrogeology_isis3:  51%|███████▏      | 935/1833 [16:04<15:24,  1.03s/it]

usgs-astrogeology_isis3:  51%|███████▏      | 936/1833 [16:05<15:24,  1.03s/it]

usgs-astrogeology_isis3:  51%|███████▏      | 937/1833 [16:06<15:22,  1.03s/it]

usgs-astrogeology_isis3:  51%|███████▏      | 938/1833 [16:08<15:20,  1.03s/it]

usgs-astrogeology_isis3:  51%|███████▏      | 939/1833 [16:09<15:19,  1.03s/it]

usgs-astrogeology_isis3:  51%|███████▏      | 940/1833 [16:10<15:18,  1.03s/it]

usgs-astrogeology_isis3:  51%|███████▏      | 941/1833 [16:11<15:18,  1.03s/it]

usgs-astrogeology_isis3:  51%|███████▏      | 942/1833 [16:12<15:17,  1.03s/it]

usgs-astrogeology_isis3:  51%|███████▏      | 943/1833 [16:13<15:16,  1.03s/it]

usgs-astrogeology_isis3:  52%|███████▏      | 944/1833 [16:14<15:14,  1.03s/it]

usgs-astrogeology_isis3:  52%|███████▏      | 945/1833 [16:15<15:11,  1.03s/it]

usgs-astrogeology_isis3:  52%|███████▏      | 946/1833 [16:16<15:11,  1.03s/it]

usgs-astrogeology_isis3:  52%|███████▏      | 947/1833 [16:17<15:11,  1.03s/it]

usgs-astrogeology_isis3:  52%|███████▏      | 948/1833 [16:18<15:11,  1.03s/it]

usgs-astrogeology_isis3:  52%|███████▏      | 949/1833 [16:19<15:28,  1.05s/it]

usgs-astrogeology_isis3:  52%|███████▎      | 950/1833 [16:20<15:29,  1.05s/it]

usgs-astrogeology_isis3:  52%|███████▎      | 951/1833 [16:21<15:22,  1.05s/it]

usgs-astrogeology_isis3:  52%|███████▎      | 952/1833 [16:22<15:17,  1.04s/it]

usgs-astrogeology_isis3:  52%|███████▎      | 953/1833 [16:23<15:12,  1.04s/it]

usgs-astrogeology_isis3:  52%|███████▎      | 954/1833 [16:24<15:07,  1.03s/it]

usgs-astrogeology_isis3:  52%|███████▎      | 955/1833 [16:25<15:04,  1.03s/it]

usgs-astrogeology_isis3:  52%|███████▎      | 956/1833 [16:26<15:03,  1.03s/it]

usgs-astrogeology_isis3:  52%|███████▎      | 957/1833 [16:27<15:02,  1.03s/it]

usgs-astrogeology_isis3:  52%|███████▎      | 958/1833 [16:28<15:01,  1.03s/it]

usgs-astrogeology_isis3:  52%|███████▎      | 959/1833 [16:29<15:00,  1.03s/it]

usgs-astrogeology_isis3:  52%|███████▎      | 960/1833 [16:30<14:58,  1.03s/it]

usgs-astrogeology_isis3:  52%|███████▎      | 961/1833 [16:31<14:59,  1.03s/it]

usgs-astrogeology_isis3:  52%|███████▎      | 962/1833 [16:32<14:58,  1.03s/it]

usgs-astrogeology_isis3:  53%|███████▎      | 963/1833 [16:33<14:55,  1.03s/it]

usgs-astrogeology_isis3:  53%|███████▎      | 964/1833 [16:34<14:53,  1.03s/it]

usgs-astrogeology_isis3:  53%|███████▎      | 965/1833 [16:35<14:52,  1.03s/it]

usgs-astrogeology_isis3:  53%|███████▍      | 966/1833 [16:36<14:53,  1.03s/it]

usgs-astrogeology_isis3:  53%|███████▍      | 967/1833 [16:37<14:50,  1.03s/it]

usgs-astrogeology_isis3:  53%|███████▍      | 968/1833 [16:38<14:49,  1.03s/it]

usgs-astrogeology_isis3:  53%|███████▍      | 969/1833 [16:39<14:49,  1.03s/it]

usgs-astrogeology_isis3:  53%|███████▍      | 970/1833 [16:41<14:48,  1.03s/it]

usgs-astrogeology_isis3:  53%|███████▍      | 971/1833 [16:42<14:47,  1.03s/it]

usgs-astrogeology_isis3:  53%|███████▍      | 972/1833 [16:43<14:47,  1.03s/it]

usgs-astrogeology_isis3:  53%|███████▍      | 973/1833 [16:44<14:46,  1.03s/it]

usgs-astrogeology_isis3:  53%|███████▍      | 974/1833 [16:45<15:01,  1.05s/it]

usgs-astrogeology_isis3:  53%|███████▍      | 975/1833 [16:46<14:56,  1.04s/it]

usgs-astrogeology_isis3:  53%|███████▍      | 976/1833 [16:47<14:51,  1.04s/it]

usgs-astrogeology_isis3:  53%|███████▍      | 977/1833 [16:48<14:47,  1.04s/it]

usgs-astrogeology_isis3:  53%|███████▍      | 978/1833 [16:49<14:44,  1.03s/it]

usgs-astrogeology_isis3:  53%|███████▍      | 979/1833 [16:50<14:41,  1.03s/it]

usgs-astrogeology_isis3:  53%|███████▍      | 980/1833 [16:51<14:59,  1.05s/it]

usgs-astrogeology_isis3:  54%|███████▍      | 981/1833 [16:52<14:51,  1.05s/it]

usgs-astrogeology_isis3:  54%|███████▌      | 982/1833 [16:53<14:45,  1.04s/it]

usgs-astrogeology_isis3:  54%|███████▌      | 983/1833 [16:54<14:41,  1.04s/it]

usgs-astrogeology_isis3:  54%|███████▌      | 984/1833 [16:55<14:37,  1.03s/it]

usgs-astrogeology_isis3:  54%|███████▌      | 985/1833 [16:56<14:33,  1.03s/it]

usgs-astrogeology_isis3:  54%|███████▌      | 986/1833 [16:57<14:31,  1.03s/it]

usgs-astrogeology_isis3:  54%|███████▌      | 987/1833 [16:58<14:30,  1.03s/it]

usgs-astrogeology_isis3:  54%|███████▌      | 988/1833 [16:59<14:30,  1.03s/it]

usgs-astrogeology_isis3:  54%|███████▌      | 989/1833 [17:00<14:28,  1.03s/it]

usgs-astrogeology_isis3:  54%|███████▌      | 990/1833 [17:01<14:27,  1.03s/it]

usgs-astrogeology_isis3:  54%|███████▌      | 991/1833 [17:02<14:26,  1.03s/it]

usgs-astrogeology_isis3:  54%|███████▌      | 992/1833 [17:03<14:27,  1.03s/it]

usgs-astrogeology_isis3:  54%|███████▌      | 993/1833 [17:04<14:25,  1.03s/it]

usgs-astrogeology_isis3:  54%|███████▌      | 994/1833 [17:05<14:24,  1.03s/it]

usgs-astrogeology_isis3:  54%|███████▌      | 995/1833 [17:06<14:22,  1.03s/it]

usgs-astrogeology_isis3:  54%|███████▌      | 996/1833 [17:07<14:21,  1.03s/it]

usgs-astrogeology_isis3:  54%|███████▌      | 997/1833 [17:08<14:21,  1.03s/it]

usgs-astrogeology_isis3:  54%|███████▌      | 998/1833 [17:09<14:19,  1.03s/it]

usgs-astrogeology_isis3:  55%|███████▋      | 999/1833 [17:11<14:18,  1.03s/it]

usgs-astrogeology_isis3:  55%|███████      | 1000/1833 [17:12<14:18,  1.03s/it]

usgs-astrogeology_isis3:  55%|███████      | 1001/1833 [17:13<14:16,  1.03s/it]

usgs-astrogeology_isis3:  55%|███████      | 1002/1833 [17:14<14:16,  1.03s/it]

usgs-astrogeology_isis3:  55%|███████      | 1003/1833 [17:15<14:14,  1.03s/it]

usgs-astrogeology_isis3:  55%|███████      | 1004/1833 [17:16<14:12,  1.03s/it]

usgs-astrogeology_isis3:  55%|███████▏     | 1005/1833 [17:17<14:11,  1.03s/it]

usgs-astrogeology_isis3:  55%|███████▏     | 1006/1833 [17:18<14:11,  1.03s/it]

usgs-astrogeology_isis3:  55%|███████▏     | 1007/1833 [17:19<14:10,  1.03s/it]

usgs-astrogeology_isis3:  55%|███████▏     | 1008/1833 [17:20<14:09,  1.03s/it]

usgs-astrogeology_isis3:  55%|███████▏     | 1009/1833 [17:21<14:08,  1.03s/it]

usgs-astrogeology_isis3:  55%|███████▏     | 1010/1833 [17:22<14:06,  1.03s/it]

usgs-astrogeology_isis3:  55%|███████▏     | 1011/1833 [17:23<14:05,  1.03s/it]

usgs-astrogeology_isis3:  55%|███████▏     | 1012/1833 [17:24<14:05,  1.03s/it]

usgs-astrogeology_isis3:  55%|███████▏     | 1013/1833 [17:25<14:02,  1.03s/it]

usgs-astrogeology_isis3:  55%|███████▏     | 1014/1833 [17:26<14:01,  1.03s/it]

usgs-astrogeology_isis3:  55%|███████▏     | 1015/1833 [17:27<14:00,  1.03s/it]

usgs-astrogeology_isis3:  55%|███████▏     | 1016/1833 [17:28<14:00,  1.03s/it]

usgs-astrogeology_isis3:  55%|███████▏     | 1017/1833 [17:29<13:58,  1.03s/it]

usgs-astrogeology_isis3:  56%|███████▏     | 1018/1833 [17:30<13:59,  1.03s/it]

usgs-astrogeology_isis3:  56%|███████▏     | 1019/1833 [17:31<13:56,  1.03s/it]

usgs-astrogeology_isis3:  56%|███████▏     | 1020/1833 [17:32<13:55,  1.03s/it]

usgs-astrogeology_isis3:  56%|███████▏     | 1021/1833 [17:33<13:56,  1.03s/it]

usgs-astrogeology_isis3:  56%|███████▏     | 1022/1833 [17:34<13:55,  1.03s/it]

usgs-astrogeology_isis3:  56%|███████▎     | 1023/1833 [17:35<13:53,  1.03s/it]

usgs-astrogeology_isis3:  56%|███████▎     | 1024/1833 [17:36<13:52,  1.03s/it]

usgs-astrogeology_isis3:  56%|███████▎     | 1025/1833 [17:37<13:52,  1.03s/it]

usgs-astrogeology_isis3:  56%|███████▎     | 1026/1833 [17:38<13:51,  1.03s/it]

usgs-astrogeology_isis3:  56%|███████▎     | 1027/1833 [17:39<13:50,  1.03s/it]

usgs-astrogeology_isis3:  56%|███████▎     | 1028/1833 [17:40<13:48,  1.03s/it]

usgs-astrogeology_isis3:  56%|███████▎     | 1029/1833 [17:41<13:46,  1.03s/it]

usgs-astrogeology_isis3:  56%|███████▎     | 1030/1833 [17:42<13:44,  1.03s/it]

usgs-astrogeology_isis3:  56%|███████▎     | 1031/1833 [17:43<13:42,  1.03s/it]

usgs-astrogeology_isis3:  56%|███████▎     | 1032/1833 [17:44<13:41,  1.03s/it]

usgs-astrogeology_isis3:  56%|███████▎     | 1033/1833 [17:45<13:41,  1.03s/it]

usgs-astrogeology_isis3:  56%|███████▎     | 1034/1833 [17:47<13:39,  1.03s/it]

usgs-astrogeology_isis3:  56%|███████▎     | 1035/1833 [17:48<13:38,  1.03s/it]

usgs-astrogeology_isis3:  57%|███████▎     | 1036/1833 [17:49<13:37,  1.03s/it]

usgs-astrogeology_isis3:  57%|███████▎     | 1037/1833 [17:50<13:36,  1.03s/it]

usgs-astrogeology_isis3:  57%|███████▎     | 1038/1833 [17:51<13:37,  1.03s/it]

usgs-astrogeology_isis3:  57%|███████▎     | 1039/1833 [17:52<13:36,  1.03s/it]

usgs-astrogeology_isis3:  57%|███████▍     | 1040/1833 [17:53<13:35,  1.03s/it]

usgs-astrogeology_isis3:  57%|███████▍     | 1041/1833 [17:54<13:34,  1.03s/it]

usgs-astrogeology_isis3:  57%|███████▍     | 1042/1833 [17:55<13:33,  1.03s/it]

usgs-astrogeology_isis3:  57%|███████▍     | 1043/1833 [17:56<13:32,  1.03s/it]

usgs-astrogeology_isis3:  57%|███████▍     | 1044/1833 [17:57<13:32,  1.03s/it]

usgs-astrogeology_isis3:  57%|███████▍     | 1045/1833 [17:58<13:31,  1.03s/it]

usgs-astrogeology_isis3:  57%|███████▍     | 1046/1833 [17:59<13:30,  1.03s/it]

usgs-astrogeology_isis3:  57%|███████▍     | 1047/1833 [18:00<13:28,  1.03s/it]

usgs-astrogeology_isis3:  57%|███████▍     | 1048/1833 [18:01<13:27,  1.03s/it]

usgs-astrogeology_isis3:  57%|███████▍     | 1049/1833 [18:02<13:26,  1.03s/it]

usgs-astrogeology_isis3:  57%|███████▍     | 1050/1833 [18:03<13:26,  1.03s/it]

usgs-astrogeology_isis3:  57%|███████▍     | 1051/1833 [18:04<13:25,  1.03s/it]

usgs-astrogeology_isis3:  57%|███████▍     | 1052/1833 [18:05<13:24,  1.03s/it]

usgs-astrogeology_isis3:  57%|███████▍     | 1053/1833 [18:06<13:23,  1.03s/it]

usgs-astrogeology_isis3:  58%|███████▍     | 1054/1833 [18:07<13:22,  1.03s/it]

usgs-astrogeology_isis3:  58%|███████▍     | 1055/1833 [18:08<13:21,  1.03s/it]

usgs-astrogeology_isis3:  58%|███████▍     | 1056/1833 [18:09<13:20,  1.03s/it]

usgs-astrogeology_isis3:  58%|███████▍     | 1057/1833 [18:10<13:18,  1.03s/it]

usgs-astrogeology_isis3:  58%|███████▌     | 1058/1833 [18:11<13:17,  1.03s/it]

usgs-astrogeology_isis3:  58%|███████▌     | 1059/1833 [18:12<13:16,  1.03s/it]

usgs-astrogeology_isis3:  58%|███████▌     | 1060/1833 [18:13<13:15,  1.03s/it]

usgs-astrogeology_isis3:  58%|███████▌     | 1061/1833 [18:14<13:14,  1.03s/it]

usgs-astrogeology_isis3:  58%|███████▌     | 1062/1833 [18:15<13:12,  1.03s/it]

usgs-astrogeology_isis3:  58%|███████▌     | 1063/1833 [18:16<13:10,  1.03s/it]

usgs-astrogeology_isis3:  58%|███████▌     | 1064/1833 [18:17<13:10,  1.03s/it]

usgs-astrogeology_isis3:  58%|███████▌     | 1065/1833 [18:18<13:10,  1.03s/it]

usgs-astrogeology_isis3:  58%|███████▌     | 1066/1833 [18:19<13:10,  1.03s/it]

usgs-astrogeology_isis3:  58%|███████▌     | 1067/1833 [18:20<13:08,  1.03s/it]

usgs-astrogeology_isis3:  58%|███████▌     | 1068/1833 [18:21<13:07,  1.03s/it]

usgs-astrogeology_isis3:  58%|███████▌     | 1069/1833 [18:23<13:05,  1.03s/it]

usgs-astrogeology_isis3:  58%|███████▌     | 1070/1833 [18:24<13:03,  1.03s/it]

usgs-astrogeology_isis3:  58%|███████▌     | 1071/1833 [18:25<13:03,  1.03s/it]

usgs-astrogeology_isis3:  58%|███████▌     | 1072/1833 [18:26<13:02,  1.03s/it]

usgs-astrogeology_isis3:  59%|███████▌     | 1073/1833 [18:27<13:01,  1.03s/it]

usgs-astrogeology_isis3:  59%|███████▌     | 1074/1833 [18:28<13:00,  1.03s/it]

usgs-astrogeology_isis3:  59%|███████▌     | 1075/1833 [18:29<12:59,  1.03s/it]

usgs-astrogeology_isis3:  59%|███████▋     | 1076/1833 [18:30<12:59,  1.03s/it]

usgs-astrogeology_isis3:  59%|███████▋     | 1077/1833 [18:31<12:58,  1.03s/it]

usgs-astrogeology_isis3:  59%|███████▋     | 1078/1833 [18:32<12:57,  1.03s/it]

usgs-astrogeology_isis3:  59%|███████▋     | 1079/1833 [18:33<12:55,  1.03s/it]

usgs-astrogeology_isis3:  59%|███████▋     | 1080/1833 [18:34<12:53,  1.03s/it]

usgs-astrogeology_isis3:  59%|███████▋     | 1081/1833 [18:35<12:52,  1.03s/it]

usgs-astrogeology_isis3:  59%|███████▋     | 1082/1833 [18:36<12:51,  1.03s/it]

usgs-astrogeology_isis3:  59%|███████▋     | 1083/1833 [18:37<12:51,  1.03s/it]

usgs-astrogeology_isis3:  59%|███████▋     | 1084/1833 [18:38<12:50,  1.03s/it]

usgs-astrogeology_isis3:  59%|███████▋     | 1085/1833 [18:39<12:49,  1.03s/it]

usgs-astrogeology_isis3:  59%|███████▋     | 1086/1833 [18:40<13:05,  1.05s/it]

usgs-astrogeology_isis3:  59%|███████▋     | 1087/1833 [18:41<13:00,  1.05s/it]

usgs-astrogeology_isis3:  59%|███████▋     | 1088/1833 [18:42<12:54,  1.04s/it]

usgs-astrogeology_isis3:  59%|███████▋     | 1089/1833 [18:43<12:53,  1.04s/it]

usgs-astrogeology_isis3:  59%|███████▋     | 1090/1833 [18:44<12:50,  1.04s/it]

usgs-astrogeology_isis3:  60%|███████▋     | 1091/1833 [18:45<12:46,  1.03s/it]

usgs-astrogeology_isis3:  60%|███████▋     | 1092/1833 [18:46<12:44,  1.03s/it]

usgs-astrogeology_isis3:  60%|███████▊     | 1093/1833 [18:47<12:42,  1.03s/it]

usgs-astrogeology_isis3:  60%|███████▊     | 1094/1833 [18:48<12:41,  1.03s/it]

usgs-astrogeology_isis3:  60%|███████▊     | 1095/1833 [18:49<12:37,  1.03s/it]

usgs-astrogeology_isis3:  60%|███████▊     | 1096/1833 [18:50<12:36,  1.03s/it]

usgs-astrogeology_isis3:  60%|███████▊     | 1097/1833 [18:51<12:34,  1.03s/it]

usgs-astrogeology_isis3:  60%|███████▊     | 1098/1833 [18:52<12:33,  1.03s/it]

usgs-astrogeology_isis3:  60%|███████▊     | 1099/1833 [18:53<12:33,  1.03s/it]

usgs-astrogeology_isis3:  60%|███████▊     | 1100/1833 [18:54<12:32,  1.03s/it]

usgs-astrogeology_isis3:  60%|███████▊     | 1101/1833 [18:56<12:32,  1.03s/it]

usgs-astrogeology_isis3:  60%|███████▊     | 1102/1833 [18:57<12:31,  1.03s/it]

usgs-astrogeology_isis3:  60%|███████▊     | 1103/1833 [18:58<12:30,  1.03s/it]

usgs-astrogeology_isis3:  60%|███████▊     | 1104/1833 [18:59<12:28,  1.03s/it]

usgs-astrogeology_isis3:  60%|███████▊     | 1105/1833 [19:00<12:27,  1.03s/it]

usgs-astrogeology_isis3:  60%|███████▊     | 1106/1833 [19:01<12:37,  1.04s/it]

usgs-astrogeology_isis3:  60%|███████▊     | 1107/1833 [19:02<12:33,  1.04s/it]

usgs-astrogeology_isis3:  60%|███████▊     | 1108/1833 [19:03<12:32,  1.04s/it]

usgs-astrogeology_isis3:  61%|███████▊     | 1109/1833 [19:04<12:29,  1.04s/it]

usgs-astrogeology_isis3:  61%|███████▊     | 1110/1833 [19:05<12:27,  1.03s/it]

usgs-astrogeology_isis3:  61%|███████▉     | 1111/1833 [19:06<12:25,  1.03s/it]

usgs-astrogeology_isis3:  61%|███████▉     | 1112/1833 [19:07<12:22,  1.03s/it]

usgs-astrogeology_isis3:  61%|███████▉     | 1113/1833 [19:08<12:20,  1.03s/it]

usgs-astrogeology_isis3:  61%|███████▉     | 1114/1833 [19:09<12:18,  1.03s/it]

usgs-astrogeology_isis3:  61%|███████▉     | 1115/1833 [19:10<12:18,  1.03s/it]

usgs-astrogeology_isis3:  61%|███████▉     | 1116/1833 [19:11<12:18,  1.03s/it]

usgs-astrogeology_isis3:  61%|███████▉     | 1117/1833 [19:12<12:16,  1.03s/it]

usgs-astrogeology_isis3:  61%|███████▉     | 1118/1833 [19:13<12:27,  1.05s/it]

usgs-astrogeology_isis3:  61%|███████▉     | 1119/1833 [19:14<12:23,  1.04s/it]

usgs-astrogeology_isis3:  61%|███████▉     | 1120/1833 [19:15<12:19,  1.04s/it]

usgs-astrogeology_isis3:  61%|███████▉     | 1121/1833 [19:16<12:16,  1.03s/it]

usgs-astrogeology_isis3:  61%|███████▉     | 1122/1833 [19:17<12:14,  1.03s/it]

usgs-astrogeology_isis3:  61%|███████▉     | 1123/1833 [19:18<12:13,  1.03s/it]

usgs-astrogeology_isis3:  61%|███████▉     | 1124/1833 [19:19<12:11,  1.03s/it]

usgs-astrogeology_isis3:  61%|███████▉     | 1125/1833 [19:20<12:10,  1.03s/it]

usgs-astrogeology_isis3:  61%|███████▉     | 1126/1833 [19:21<12:07,  1.03s/it]

usgs-astrogeology_isis3:  61%|███████▉     | 1127/1833 [19:22<12:06,  1.03s/it]

usgs-astrogeology_isis3:  62%|████████     | 1128/1833 [19:23<12:06,  1.03s/it]

usgs-astrogeology_isis3:  62%|████████     | 1129/1833 [19:24<12:06,  1.03s/it]

usgs-astrogeology_isis3:  62%|████████     | 1130/1833 [19:25<12:04,  1.03s/it]

usgs-astrogeology_isis3:  62%|████████     | 1131/1833 [19:26<12:03,  1.03s/it]

usgs-astrogeology_isis3:  62%|████████     | 1132/1833 [19:28<12:02,  1.03s/it]

usgs-astrogeology_isis3:  62%|████████     | 1133/1833 [19:29<12:00,  1.03s/it]

usgs-astrogeology_isis3:  62%|████████     | 1134/1833 [19:30<11:59,  1.03s/it]

usgs-astrogeology_isis3:  62%|████████     | 1135/1833 [19:31<11:57,  1.03s/it]

usgs-astrogeology_isis3:  62%|████████     | 1136/1833 [19:32<11:56,  1.03s/it]

usgs-astrogeology_isis3:  62%|████████     | 1137/1833 [19:33<11:54,  1.03s/it]

usgs-astrogeology_isis3:  62%|████████     | 1138/1833 [19:34<11:54,  1.03s/it]

usgs-astrogeology_isis3:  62%|████████     | 1139/1833 [19:35<11:52,  1.03s/it]

usgs-astrogeology_isis3:  62%|████████     | 1140/1833 [19:36<11:51,  1.03s/it]

usgs-astrogeology_isis3:  62%|████████     | 1141/1833 [19:37<11:50,  1.03s/it]

usgs-astrogeology_isis3:  62%|████████     | 1142/1833 [19:38<11:50,  1.03s/it]

usgs-astrogeology_isis3:  62%|████████     | 1143/1833 [19:39<11:50,  1.03s/it]

usgs-astrogeology_isis3:  62%|████████     | 1144/1833 [19:40<11:53,  1.03s/it]

usgs-astrogeology_isis3:  62%|████████     | 1145/1833 [19:41<11:50,  1.03s/it]

usgs-astrogeology_isis3:  63%|████████▏    | 1146/1833 [19:42<11:48,  1.03s/it]

usgs-astrogeology_isis3:  63%|████████▏    | 1147/1833 [19:43<11:47,  1.03s/it]

usgs-astrogeology_isis3:  63%|████████▏    | 1148/1833 [19:44<11:45,  1.03s/it]

usgs-astrogeology_isis3:  63%|████████▏    | 1149/1833 [19:45<11:43,  1.03s/it]

usgs-astrogeology_isis3:  63%|████████▏    | 1150/1833 [19:46<11:43,  1.03s/it]

usgs-astrogeology_isis3:  63%|████████▏    | 1151/1833 [19:47<11:41,  1.03s/it]

usgs-astrogeology_isis3:  63%|████████▏    | 1152/1833 [19:48<11:39,  1.03s/it]

usgs-astrogeology_isis3:  63%|████████▏    | 1153/1833 [19:49<11:38,  1.03s/it]

usgs-astrogeology_isis3:  63%|████████▏    | 1154/1833 [19:50<11:37,  1.03s/it]

usgs-astrogeology_isis3:  63%|████████▏    | 1155/1833 [19:51<11:36,  1.03s/it]

usgs-astrogeology_isis3:  63%|████████▏    | 1156/1833 [19:52<11:34,  1.03s/it]

usgs-astrogeology_isis3:  63%|████████▏    | 1157/1833 [19:53<11:35,  1.03s/it]

usgs-astrogeology_isis3:  63%|████████▏    | 1158/1833 [19:54<11:34,  1.03s/it]

usgs-astrogeology_isis3:  63%|████████▏    | 1159/1833 [19:55<11:33,  1.03s/it]

usgs-astrogeology_isis3:  63%|████████▏    | 1160/1833 [19:56<11:33,  1.03s/it]

usgs-astrogeology_isis3:  63%|████████▏    | 1161/1833 [19:57<11:34,  1.03s/it]

usgs-astrogeology_isis3:  63%|████████▏    | 1162/1833 [19:58<11:31,  1.03s/it]

usgs-astrogeology_isis3:  63%|████████▏    | 1163/1833 [19:59<11:29,  1.03s/it]

usgs-astrogeology_isis3:  64%|████████▎    | 1164/1833 [20:00<11:27,  1.03s/it]

usgs-astrogeology_isis3:  64%|████████▎    | 1165/1833 [20:01<11:26,  1.03s/it]

usgs-astrogeology_isis3:  64%|████████▎    | 1166/1833 [20:02<11:24,  1.03s/it]

usgs-astrogeology_isis3:  64%|████████▎    | 1167/1833 [20:04<11:24,  1.03s/it]

usgs-astrogeology_isis3:  64%|████████▎    | 1168/1833 [20:05<11:23,  1.03s/it]

usgs-astrogeology_isis3:  64%|████████▎    | 1169/1833 [20:06<11:22,  1.03s/it]

usgs-astrogeology_isis3:  64%|████████▎    | 1170/1833 [20:07<11:22,  1.03s/it]

usgs-astrogeology_isis3:  64%|████████▎    | 1171/1833 [20:08<11:21,  1.03s/it]

usgs-astrogeology_isis3:  64%|████████▎    | 1172/1833 [20:09<11:19,  1.03s/it]

usgs-astrogeology_isis3:  64%|████████▎    | 1173/1833 [20:10<11:18,  1.03s/it]

usgs-astrogeology_isis3:  64%|████████▎    | 1174/1833 [20:11<11:17,  1.03s/it]

usgs-astrogeology_isis3:  64%|████████▎    | 1175/1833 [20:12<11:14,  1.03s/it]

usgs-astrogeology_isis3:  64%|████████▎    | 1176/1833 [20:13<11:14,  1.03s/it]

usgs-astrogeology_isis3:  64%|████████▎    | 1177/1833 [20:14<11:13,  1.03s/it]

usgs-astrogeology_isis3:  64%|████████▎    | 1178/1833 [20:15<11:13,  1.03s/it]

usgs-astrogeology_isis3:  64%|████████▎    | 1179/1833 [20:16<11:13,  1.03s/it]

usgs-astrogeology_isis3:  64%|████████▎    | 1180/1833 [20:17<11:12,  1.03s/it]

usgs-astrogeology_isis3:  64%|████████▍    | 1181/1833 [20:18<11:10,  1.03s/it]

usgs-astrogeology_isis3:  64%|████████▍    | 1182/1833 [20:19<11:10,  1.03s/it]

usgs-astrogeology_isis3:  65%|████████▍    | 1183/1833 [20:20<11:08,  1.03s/it]

usgs-astrogeology_isis3:  65%|████████▍    | 1184/1833 [20:21<11:08,  1.03s/it]

usgs-astrogeology_isis3:  65%|████████▍    | 1185/1833 [20:22<11:16,  1.04s/it]

usgs-astrogeology_isis3:  65%|████████▍    | 1186/1833 [20:23<11:13,  1.04s/it]

usgs-astrogeology_isis3:  65%|████████▍    | 1187/1833 [20:24<11:09,  1.04s/it]

usgs-astrogeology_isis3:  65%|████████▍    | 1188/1833 [20:25<11:05,  1.03s/it]

usgs-astrogeology_isis3:  65%|████████▍    | 1189/1833 [20:26<11:04,  1.03s/it]

usgs-astrogeology_isis3:  65%|████████▍    | 1190/1833 [20:27<11:03,  1.03s/it]

usgs-astrogeology_isis3:  65%|████████▍    | 1191/1833 [20:28<11:02,  1.03s/it]

usgs-astrogeology_isis3:  65%|████████▍    | 1192/1833 [20:29<11:01,  1.03s/it]

usgs-astrogeology_isis3:  65%|████████▍    | 1193/1833 [20:30<11:00,  1.03s/it]

usgs-astrogeology_isis3:  65%|████████▍    | 1194/1833 [20:31<10:58,  1.03s/it]

usgs-astrogeology_isis3:  65%|████████▍    | 1195/1833 [20:32<10:57,  1.03s/it]

usgs-astrogeology_isis3:  65%|████████▍    | 1196/1833 [20:33<10:56,  1.03s/it]

usgs-astrogeology_isis3:  65%|████████▍    | 1197/1833 [20:34<10:57,  1.03s/it]

usgs-astrogeology_isis3:  65%|████████▍    | 1198/1833 [20:35<10:55,  1.03s/it]

usgs-astrogeology_isis3:  65%|████████▌    | 1199/1833 [20:37<10:53,  1.03s/it]

usgs-astrogeology_isis3:  65%|████████▌    | 1200/1833 [20:38<10:52,  1.03s/it]

usgs-astrogeology_isis3:  66%|████████▌    | 1201/1833 [20:39<10:50,  1.03s/it]

usgs-astrogeology_isis3:  66%|████████▌    | 1202/1833 [20:40<10:49,  1.03s/it]

usgs-astrogeology_isis3:  66%|████████▌    | 1203/1833 [20:41<10:48,  1.03s/it]

usgs-astrogeology_isis3:  66%|████████▌    | 1204/1833 [20:42<10:47,  1.03s/it]

usgs-astrogeology_isis3:  66%|████████▌    | 1205/1833 [20:43<10:59,  1.05s/it]

usgs-astrogeology_isis3:  66%|████████▌    | 1206/1833 [20:44<11:01,  1.05s/it]

usgs-astrogeology_isis3:  66%|████████▌    | 1207/1833 [20:45<10:55,  1.05s/it]

usgs-astrogeology_isis3:  66%|████████▌    | 1208/1833 [20:46<10:50,  1.04s/it]

usgs-astrogeology_isis3:  66%|████████▌    | 1209/1833 [20:47<10:47,  1.04s/it]

usgs-astrogeology_isis3:  66%|████████▌    | 1210/1833 [20:48<10:45,  1.04s/it]

usgs-astrogeology_isis3:  66%|████████▌    | 1211/1833 [20:49<10:42,  1.03s/it]

usgs-astrogeology_isis3:  66%|████████▌    | 1212/1833 [20:50<10:40,  1.03s/it]

usgs-astrogeology_isis3:  66%|████████▌    | 1213/1833 [20:51<10:39,  1.03s/it]

usgs-astrogeology_isis3:  66%|████████▌    | 1214/1833 [20:52<10:39,  1.03s/it]

usgs-astrogeology_isis3:  66%|████████▌    | 1215/1833 [20:53<10:37,  1.03s/it]

usgs-astrogeology_isis3:  66%|████████▌    | 1216/1833 [20:54<10:36,  1.03s/it]

usgs-astrogeology_isis3:  66%|████████▋    | 1217/1833 [20:55<10:34,  1.03s/it]

usgs-astrogeology_isis3:  66%|████████▋    | 1218/1833 [20:56<10:34,  1.03s/it]

usgs-astrogeology_isis3:  67%|████████▋    | 1219/1833 [20:57<10:33,  1.03s/it]

usgs-astrogeology_isis3:  67%|████████▋    | 1220/1833 [20:58<10:31,  1.03s/it]

usgs-astrogeology_isis3:  67%|████████▋    | 1221/1833 [20:59<10:30,  1.03s/it]

usgs-astrogeology_isis3:  67%|████████▋    | 1222/1833 [21:00<10:28,  1.03s/it]

usgs-astrogeology_isis3:  67%|████████▋    | 1223/1833 [21:01<10:26,  1.03s/it]

usgs-astrogeology_isis3:  67%|████████▋    | 1224/1833 [21:02<10:26,  1.03s/it]

usgs-astrogeology_isis3:  67%|████████▋    | 1225/1833 [21:03<10:24,  1.03s/it]

usgs-astrogeology_isis3:  67%|████████▋    | 1226/1833 [21:04<10:23,  1.03s/it]

usgs-astrogeology_isis3:  67%|████████▋    | 1227/1833 [21:05<10:22,  1.03s/it]

usgs-astrogeology_isis3:  67%|████████▋    | 1228/1833 [21:06<10:23,  1.03s/it]

usgs-astrogeology_isis3:  67%|████████▋    | 1229/1833 [21:07<10:22,  1.03s/it]

usgs-astrogeology_isis3:  67%|████████▋    | 1230/1833 [21:09<10:21,  1.03s/it]

usgs-astrogeology_isis3:  67%|████████▋    | 1231/1833 [21:10<10:19,  1.03s/it]

usgs-astrogeology_isis3:  67%|████████▋    | 1232/1833 [21:11<10:18,  1.03s/it]

usgs-astrogeology_isis3:  67%|████████▋    | 1233/1833 [21:12<10:17,  1.03s/it]

usgs-astrogeology_isis3:  67%|████████▊    | 1234/1833 [21:13<10:16,  1.03s/it]

usgs-astrogeology_isis3:  67%|████████▊    | 1235/1833 [21:14<10:16,  1.03s/it]

usgs-astrogeology_isis3:  67%|████████▊    | 1236/1833 [21:15<10:14,  1.03s/it]

usgs-astrogeology_isis3:  67%|████████▊    | 1237/1833 [21:16<10:12,  1.03s/it]

usgs-astrogeology_isis3:  68%|████████▊    | 1238/1833 [21:17<10:12,  1.03s/it]

usgs-astrogeology_isis3:  68%|████████▊    | 1239/1833 [21:18<10:11,  1.03s/it]

usgs-astrogeology_isis3:  68%|████████▊    | 1240/1833 [21:19<10:10,  1.03s/it]

usgs-astrogeology_isis3:  68%|████████▊    | 1241/1833 [21:20<10:08,  1.03s/it]

usgs-astrogeology_isis3:  68%|████████▊    | 1242/1833 [21:21<10:12,  1.04s/it]

usgs-astrogeology_isis3:  68%|████████▊    | 1243/1833 [21:22<10:15,  1.04s/it]

usgs-astrogeology_isis3:  68%|████████▊    | 1244/1833 [21:23<10:12,  1.04s/it]

usgs-astrogeology_isis3:  68%|████████▊    | 1245/1833 [21:24<10:10,  1.04s/it]

usgs-astrogeology_isis3:  68%|████████▊    | 1246/1833 [21:25<10:08,  1.04s/it]

usgs-astrogeology_isis3:  68%|████████▊    | 1247/1833 [21:26<10:05,  1.03s/it]

usgs-astrogeology_isis3:  68%|████████▊    | 1248/1833 [21:27<10:04,  1.03s/it]

usgs-astrogeology_isis3:  68%|████████▊    | 1249/1833 [21:28<10:02,  1.03s/it]

usgs-astrogeology_isis3:  68%|████████▊    | 1250/1833 [21:29<10:00,  1.03s/it]

usgs-astrogeology_isis3:  68%|████████▊    | 1251/1833 [21:30<10:01,  1.03s/it]

usgs-astrogeology_isis3:  68%|████████▉    | 1252/1833 [21:31<09:59,  1.03s/it]

usgs-astrogeology_isis3:  68%|████████▉    | 1253/1833 [21:32<09:58,  1.03s/it]

usgs-astrogeology_isis3:  68%|████████▉    | 1254/1833 [21:33<09:57,  1.03s/it]

usgs-astrogeology_isis3:  68%|████████▉    | 1255/1833 [21:34<09:55,  1.03s/it]

usgs-astrogeology_isis3:  69%|████████▉    | 1256/1833 [21:35<09:53,  1.03s/it]

usgs-astrogeology_isis3:  69%|████████▉    | 1257/1833 [21:36<09:52,  1.03s/it]

usgs-astrogeology_isis3:  69%|████████▉    | 1258/1833 [21:37<09:51,  1.03s/it]

usgs-astrogeology_isis3:  69%|████████▉    | 1259/1833 [21:38<09:50,  1.03s/it]

usgs-astrogeology_isis3:  69%|████████▉    | 1260/1833 [21:39<09:49,  1.03s/it]

usgs-astrogeology_isis3:  69%|████████▉    | 1261/1833 [21:40<09:48,  1.03s/it]

usgs-astrogeology_isis3:  69%|████████▉    | 1262/1833 [21:42<09:46,  1.03s/it]

usgs-astrogeology_isis3:  69%|████████▉    | 1263/1833 [21:43<09:45,  1.03s/it]

usgs-astrogeology_isis3:  69%|████████▉    | 1264/1833 [21:44<09:45,  1.03s/it]

usgs-astrogeology_isis3:  69%|████████▉    | 1265/1833 [21:45<09:44,  1.03s/it]

usgs-astrogeology_isis3:  69%|████████▉    | 1266/1833 [21:46<09:44,  1.03s/it]

usgs-astrogeology_isis3:  69%|████████▉    | 1267/1833 [21:47<09:43,  1.03s/it]

usgs-astrogeology_isis3:  69%|████████▉    | 1268/1833 [21:48<09:41,  1.03s/it]

usgs-astrogeology_isis3:  69%|█████████    | 1269/1833 [21:49<09:40,  1.03s/it]

usgs-astrogeology_isis3:  69%|█████████    | 1270/1833 [21:50<09:39,  1.03s/it]

usgs-astrogeology_isis3:  69%|█████████    | 1271/1833 [21:51<09:41,  1.03s/it]

usgs-astrogeology_isis3:  69%|█████████    | 1272/1833 [21:52<09:39,  1.03s/it]

usgs-astrogeology_isis3:  69%|█████████    | 1273/1833 [21:53<09:37,  1.03s/it]

usgs-astrogeology_isis3:  70%|█████████    | 1274/1833 [21:54<09:36,  1.03s/it]

usgs-astrogeology_isis3:  70%|█████████    | 1275/1833 [21:55<09:34,  1.03s/it]

usgs-astrogeology_isis3:  70%|█████████    | 1276/1833 [21:56<09:33,  1.03s/it]

usgs-astrogeology_isis3:  70%|█████████    | 1277/1833 [21:57<09:32,  1.03s/it]

usgs-astrogeology_isis3:  70%|█████████    | 1278/1833 [21:58<09:31,  1.03s/it]

usgs-astrogeology_isis3:  70%|█████████    | 1279/1833 [21:59<09:31,  1.03s/it]

usgs-astrogeology_isis3:  70%|█████████    | 1280/1833 [22:00<09:29,  1.03s/it]

usgs-astrogeology_isis3:  70%|█████████    | 1281/1833 [22:01<09:29,  1.03s/it]

usgs-astrogeology_isis3:  70%|█████████    | 1282/1833 [22:02<09:28,  1.03s/it]

usgs-astrogeology_isis3:  70%|█████████    | 1283/1833 [22:03<09:27,  1.03s/it]

usgs-astrogeology_isis3:  70%|█████████    | 1284/1833 [22:04<09:25,  1.03s/it]

usgs-astrogeology_isis3:  70%|█████████    | 1285/1833 [22:05<09:24,  1.03s/it]

usgs-astrogeology_isis3:  70%|█████████    | 1286/1833 [22:06<09:23,  1.03s/it]

usgs-astrogeology_isis3:  70%|█████████▏   | 1287/1833 [22:07<09:22,  1.03s/it]

usgs-astrogeology_isis3:  70%|█████████▏   | 1288/1833 [22:08<09:20,  1.03s/it]

usgs-astrogeology_isis3:  70%|█████████▏   | 1289/1833 [22:09<09:23,  1.04s/it]

usgs-astrogeology_isis3:  70%|█████████▏   | 1290/1833 [22:10<09:21,  1.03s/it]

usgs-astrogeology_isis3:  70%|█████████▏   | 1291/1833 [22:11<09:19,  1.03s/it]

usgs-astrogeology_isis3:  70%|█████████▏   | 1292/1833 [22:12<09:18,  1.03s/it]

usgs-astrogeology_isis3:  71%|█████████▏   | 1293/1833 [22:13<09:17,  1.03s/it]

usgs-astrogeology_isis3:  71%|█████████▏   | 1294/1833 [22:15<09:16,  1.03s/it]

usgs-astrogeology_isis3:  71%|█████████▏   | 1295/1833 [22:16<09:15,  1.03s/it]

usgs-astrogeology_isis3:  71%|█████████▏   | 1296/1833 [22:17<09:14,  1.03s/it]

usgs-astrogeology_isis3:  71%|█████████▏   | 1297/1833 [22:18<09:12,  1.03s/it]

usgs-astrogeology_isis3:  71%|█████████▏   | 1298/1833 [22:19<09:11,  1.03s/it]

usgs-astrogeology_isis3:  71%|█████████▏   | 1299/1833 [22:20<09:10,  1.03s/it]

usgs-astrogeology_isis3:  71%|█████████▏   | 1300/1833 [22:21<09:09,  1.03s/it]

usgs-astrogeology_isis3:  71%|█████████▏   | 1301/1833 [22:22<09:07,  1.03s/it]

usgs-astrogeology_isis3:  71%|█████████▏   | 1302/1833 [22:23<09:07,  1.03s/it]

usgs-astrogeology_isis3:  71%|█████████▏   | 1303/1833 [22:24<09:06,  1.03s/it]

usgs-astrogeology_isis3:  71%|█████████▏   | 1304/1833 [22:25<09:04,  1.03s/it]

usgs-astrogeology_isis3:  71%|█████████▎   | 1305/1833 [22:26<09:03,  1.03s/it]

usgs-astrogeology_isis3:  71%|█████████▎   | 1306/1833 [22:27<09:01,  1.03s/it]

usgs-astrogeology_isis3:  71%|█████████▎   | 1307/1833 [22:28<09:00,  1.03s/it]

usgs-astrogeology_isis3:  71%|█████████▎   | 1308/1833 [22:29<09:04,  1.04s/it]

usgs-astrogeology_isis3:  71%|█████████▎   | 1309/1833 [22:30<09:02,  1.04s/it]

usgs-astrogeology_isis3:  71%|█████████▎   | 1310/1833 [22:31<08:59,  1.03s/it]

usgs-astrogeology_isis3:  72%|█████████▎   | 1311/1833 [22:32<08:57,  1.03s/it]

usgs-astrogeology_isis3:  72%|█████████▎   | 1312/1833 [22:33<08:56,  1.03s/it]

usgs-astrogeology_isis3:  72%|█████████▎   | 1313/1833 [22:34<08:54,  1.03s/it]

usgs-astrogeology_isis3:  72%|█████████▎   | 1314/1833 [22:35<08:53,  1.03s/it]

usgs-astrogeology_isis3:  72%|█████████▎   | 1315/1833 [22:36<08:52,  1.03s/it]

usgs-astrogeology_isis3:  72%|█████████▎   | 1316/1833 [22:37<08:51,  1.03s/it]

usgs-astrogeology_isis3:  72%|█████████▎   | 1317/1833 [22:38<08:50,  1.03s/it]

usgs-astrogeology_isis3:  72%|█████████▎   | 1318/1833 [22:39<08:49,  1.03s/it]

usgs-astrogeology_isis3:  72%|█████████▎   | 1319/1833 [22:40<08:48,  1.03s/it]

usgs-astrogeology_isis3:  72%|█████████▎   | 1320/1833 [22:41<08:47,  1.03s/it]

usgs-astrogeology_isis3:  72%|█████████▎   | 1321/1833 [22:42<08:46,  1.03s/it]

usgs-astrogeology_isis3:  72%|█████████▍   | 1322/1833 [22:43<08:45,  1.03s/it]

usgs-astrogeology_isis3:  72%|█████████▍   | 1323/1833 [22:44<08:45,  1.03s/it]

usgs-astrogeology_isis3:  72%|█████████▍   | 1324/1833 [22:45<08:44,  1.03s/it]

usgs-astrogeology_isis3:  72%|█████████▍   | 1325/1833 [22:46<08:42,  1.03s/it]

usgs-astrogeology_isis3:  72%|█████████▍   | 1326/1833 [22:47<08:41,  1.03s/it]

usgs-astrogeology_isis3:  72%|█████████▍   | 1327/1833 [22:48<08:40,  1.03s/it]

usgs-astrogeology_isis3:  72%|█████████▍   | 1328/1833 [22:50<08:38,  1.03s/it]

usgs-astrogeology_isis3:  73%|█████████▍   | 1329/1833 [22:51<08:37,  1.03s/it]

usgs-astrogeology_isis3:  73%|█████████▍   | 1330/1833 [22:52<08:36,  1.03s/it]

usgs-astrogeology_isis3:  73%|█████████▍   | 1331/1833 [22:53<08:35,  1.03s/it]

usgs-astrogeology_isis3:  73%|█████████▍   | 1332/1833 [22:54<08:34,  1.03s/it]

usgs-astrogeology_isis3:  73%|█████████▍   | 1333/1833 [22:55<08:33,  1.03s/it]

usgs-astrogeology_isis3:  73%|█████████▍   | 1334/1833 [22:56<08:32,  1.03s/it]

usgs-astrogeology_isis3:  73%|█████████▍   | 1335/1833 [22:57<08:31,  1.03s/it]

usgs-astrogeology_isis3:  73%|█████████▍   | 1336/1833 [22:58<08:30,  1.03s/it]

usgs-astrogeology_isis3:  73%|█████████▍   | 1337/1833 [22:59<08:30,  1.03s/it]

usgs-astrogeology_isis3:  73%|█████████▍   | 1338/1833 [23:00<08:29,  1.03s/it]

usgs-astrogeology_isis3:  73%|█████████▍   | 1339/1833 [23:01<08:28,  1.03s/it]

usgs-astrogeology_isis3:  73%|█████████▌   | 1340/1833 [23:02<08:28,  1.03s/it]

usgs-astrogeology_isis3:  73%|█████████▌   | 1341/1833 [23:03<08:26,  1.03s/it]

usgs-astrogeology_isis3:  73%|█████████▌   | 1342/1833 [23:04<08:25,  1.03s/it]

usgs-astrogeology_isis3:  73%|█████████▌   | 1343/1833 [23:05<08:25,  1.03s/it]

usgs-astrogeology_isis3:  73%|█████████▌   | 1344/1833 [23:06<08:23,  1.03s/it]

usgs-astrogeology_isis3:  73%|█████████▌   | 1345/1833 [23:07<08:22,  1.03s/it]

usgs-astrogeology_isis3:  73%|█████████▌   | 1346/1833 [23:08<08:21,  1.03s/it]

usgs-astrogeology_isis3:  73%|█████████▌   | 1347/1833 [23:09<08:20,  1.03s/it]

usgs-astrogeology_isis3:  74%|█████████▌   | 1348/1833 [23:10<08:18,  1.03s/it]

usgs-astrogeology_isis3:  74%|█████████▌   | 1349/1833 [23:11<08:17,  1.03s/it]

usgs-astrogeology_isis3:  74%|█████████▌   | 1350/1833 [23:12<08:16,  1.03s/it]

usgs-astrogeology_isis3:  74%|█████████▌   | 1351/1833 [23:13<08:15,  1.03s/it]

usgs-astrogeology_isis3:  74%|█████████▌   | 1352/1833 [23:14<08:15,  1.03s/it]

usgs-astrogeology_isis3:  74%|█████████▌   | 1353/1833 [23:15<08:13,  1.03s/it]

usgs-astrogeology_isis3:  74%|█████████▌   | 1354/1833 [23:16<08:11,  1.03s/it]

usgs-astrogeology_isis3:  74%|█████████▌   | 1355/1833 [23:17<08:11,  1.03s/it]

usgs-astrogeology_isis3:  74%|█████████▌   | 1356/1833 [23:18<08:11,  1.03s/it]

usgs-astrogeology_isis3:  74%|█████████▌   | 1357/1833 [23:19<08:10,  1.03s/it]

usgs-astrogeology_isis3:  74%|█████████▋   | 1358/1833 [23:20<08:08,  1.03s/it]

usgs-astrogeology_isis3:  74%|█████████▋   | 1359/1833 [23:21<08:06,  1.03s/it]

usgs-astrogeology_isis3:  74%|█████████▋   | 1360/1833 [23:22<08:06,  1.03s/it]

usgs-astrogeology_isis3:  74%|█████████▋   | 1361/1833 [23:23<08:05,  1.03s/it]

usgs-astrogeology_isis3:  74%|█████████▋   | 1362/1833 [23:24<08:05,  1.03s/it]

usgs-astrogeology_isis3:  74%|█████████▋   | 1363/1833 [23:26<08:03,  1.03s/it]

usgs-astrogeology_isis3:  74%|█████████▋   | 1364/1833 [23:27<08:01,  1.03s/it]

usgs-astrogeology_isis3:  74%|█████████▋   | 1365/1833 [23:28<08:00,  1.03s/it]

usgs-astrogeology_isis3:  75%|█████████▋   | 1366/1833 [23:29<07:59,  1.03s/it]

usgs-astrogeology_isis3:  75%|█████████▋   | 1367/1833 [23:30<07:59,  1.03s/it]

usgs-astrogeology_isis3:  75%|█████████▋   | 1368/1833 [23:31<07:59,  1.03s/it]

usgs-astrogeology_isis3:  75%|█████████▋   | 1369/1833 [23:32<07:57,  1.03s/it]

usgs-astrogeology_isis3:  75%|█████████▋   | 1370/1833 [23:33<07:56,  1.03s/it]

usgs-astrogeology_isis3:  75%|█████████▋   | 1371/1833 [23:34<07:56,  1.03s/it]

usgs-astrogeology_isis3:  75%|█████████▋   | 1372/1833 [23:35<07:55,  1.03s/it]

  errors: {'c09f17f7b7b5e7859d6ab12e9e761d10886da045': 'Key c09f17f7b7b5e7859d6ab12e9e761d10886da045 not found in /da5_fast/All.sha1c/commit_64.tch'}

usgs-astrogeology_isis3:  75%|█████████▋   | 1373/1833 [23:36<07:54,  1.03s/it]

usgs-astrogeology_isis3:  75%|█████████▋   | 1374/1833 [23:37<07:53,  1.03s/it]

usgs-astrogeology_isis3:  75%|█████████▊   | 1375/1833 [23:38<07:51,  1.03s/it]

usgs-astrogeology_isis3:  75%|█████████▊   | 1376/1833 [23:39<07:50,  1.03s/it]

usgs-astrogeology_isis3:  75%|█████████▊   | 1377/1833 [23:40<07:49,  1.03s/it]

usgs-astrogeology_isis3:  75%|█████████▊   | 1378/1833 [23:41<07:48,  1.03s/it]

usgs-astrogeology_isis3:  75%|█████████▊   | 1379/1833 [23:42<07:47,  1.03s/it]

usgs-astrogeology_isis3:  75%|█████████▊   | 1380/1833 [23:43<07:46,  1.03s/it]

usgs-astrogeology_isis3:  75%|█████████▊   | 1381/1833 [23:44<07:45,  1.03s/it]

usgs-astrogeology_isis3:  75%|█████████▊   | 1382/1833 [23:45<07:44,  1.03s/it]

usgs-astrogeology_isis3:  75%|█████████▊   | 1383/1833 [23:46<07:43,  1.03s/it]

usgs-astrogeology_isis3:  76%|█████████▊   | 1384/1833 [23:47<07:41,  1.03s/it]

usgs-astrogeology_isis3:  76%|█████████▊   | 1385/1833 [23:48<07:40,  1.03s/it]

usgs-astrogeology_isis3:  76%|█████████▊   | 1386/1833 [23:49<07:39,  1.03s/it]

usgs-astrogeology_isis3:  76%|█████████▊   | 1387/1833 [23:50<07:38,  1.03s/it]

usgs-astrogeology_isis3:  76%|█████████▊   | 1388/1833 [23:51<07:38,  1.03s/it]

usgs-astrogeology_isis3:  76%|█████████▊   | 1389/1833 [23:52<07:36,  1.03s/it]

usgs-astrogeology_isis3:  76%|█████████▊   | 1390/1833 [23:53<07:35,  1.03s/it]

usgs-astrogeology_isis3:  76%|█████████▊   | 1391/1833 [23:54<07:33,  1.03s/it]

usgs-astrogeology_isis3:  76%|█████████▊   | 1392/1833 [23:55<07:35,  1.03s/it]

usgs-astrogeology_isis3:  76%|█████████▉   | 1393/1833 [23:56<07:34,  1.03s/it]

usgs-astrogeology_isis3:  76%|█████████▉   | 1394/1833 [23:57<07:33,  1.03s/it]

usgs-astrogeology_isis3:  76%|█████████▉   | 1395/1833 [23:58<07:32,  1.03s/it]

usgs-astrogeology_isis3:  76%|█████████▉   | 1396/1833 [23:59<07:30,  1.03s/it]

usgs-astrogeology_isis3:  76%|█████████▉   | 1397/1833 [24:01<07:28,  1.03s/it]

usgs-astrogeology_isis3:  76%|█████████▉   | 1398/1833 [24:02<07:27,  1.03s/it]

usgs-astrogeology_isis3:  76%|█████████▉   | 1399/1833 [24:03<07:26,  1.03s/it]

usgs-astrogeology_isis3:  76%|█████████▉   | 1400/1833 [24:04<07:25,  1.03s/it]

usgs-astrogeology_isis3:  76%|█████████▉   | 1401/1833 [24:05<07:24,  1.03s/it]

usgs-astrogeology_isis3:  76%|█████████▉   | 1402/1833 [24:06<07:23,  1.03s/it]

usgs-astrogeology_isis3:  77%|█████████▉   | 1403/1833 [24:07<07:22,  1.03s/it]

usgs-astrogeology_isis3:  77%|█████████▉   | 1404/1833 [24:08<07:21,  1.03s/it]

usgs-astrogeology_isis3:  77%|█████████▉   | 1405/1833 [24:09<07:20,  1.03s/it]

usgs-astrogeology_isis3:  77%|█████████▉   | 1406/1833 [24:10<07:20,  1.03s/it]

usgs-astrogeology_isis3:  77%|█████████▉   | 1407/1833 [24:11<07:18,  1.03s/it]

usgs-astrogeology_isis3:  77%|█████████▉   | 1408/1833 [24:12<07:18,  1.03s/it]

usgs-astrogeology_isis3:  77%|█████████▉   | 1409/1833 [24:13<07:17,  1.03s/it]

usgs-astrogeology_isis3:  77%|██████████   | 1410/1833 [24:14<07:15,  1.03s/it]

usgs-astrogeology_isis3:  77%|██████████   | 1411/1833 [24:15<07:13,  1.03s/it]

usgs-astrogeology_isis3:  77%|██████████   | 1412/1833 [24:16<07:13,  1.03s/it]

usgs-astrogeology_isis3:  77%|██████████   | 1413/1833 [24:17<07:12,  1.03s/it]

usgs-astrogeology_isis3:  77%|██████████   | 1414/1833 [24:18<07:11,  1.03s/it]

usgs-astrogeology_isis3:  77%|██████████   | 1415/1833 [24:19<07:10,  1.03s/it]

usgs-astrogeology_isis3:  77%|██████████   | 1416/1833 [24:20<07:09,  1.03s/it]

usgs-astrogeology_isis3:  77%|██████████   | 1417/1833 [24:21<07:08,  1.03s/it]

usgs-astrogeology_isis3:  77%|██████████   | 1418/1833 [24:22<07:16,  1.05s/it]

usgs-astrogeology_isis3:  77%|██████████   | 1419/1833 [24:23<07:12,  1.05s/it]

usgs-astrogeology_isis3:  77%|██████████   | 1420/1833 [24:24<07:09,  1.04s/it]

usgs-astrogeology_isis3:  78%|██████████   | 1421/1833 [24:25<07:07,  1.04s/it]

usgs-astrogeology_isis3:  78%|██████████   | 1422/1833 [24:26<07:05,  1.04s/it]

usgs-astrogeology_isis3:  78%|██████████   | 1423/1833 [24:27<07:03,  1.03s/it]

usgs-astrogeology_isis3:  78%|██████████   | 1424/1833 [24:28<07:02,  1.03s/it]

usgs-astrogeology_isis3:  78%|██████████   | 1425/1833 [24:29<07:00,  1.03s/it]

usgs-astrogeology_isis3:  78%|██████████   | 1426/1833 [24:30<06:59,  1.03s/it]

usgs-astrogeology_isis3:  78%|██████████   | 1427/1833 [24:31<06:58,  1.03s/it]

usgs-astrogeology_isis3:  78%|██████████▏  | 1428/1833 [24:33<06:57,  1.03s/it]

usgs-astrogeology_isis3:  78%|██████████▏  | 1429/1833 [24:34<06:56,  1.03s/it]

usgs-astrogeology_isis3:  78%|██████████▏  | 1430/1833 [24:35<06:55,  1.03s/it]

usgs-astrogeology_isis3:  78%|██████████▏  | 1431/1833 [24:36<06:54,  1.03s/it]

usgs-astrogeology_isis3:  78%|██████████▏  | 1432/1833 [24:37<06:53,  1.03s/it]

usgs-astrogeology_isis3:  78%|██████████▏  | 1433/1833 [24:38<06:51,  1.03s/it]

usgs-astrogeology_isis3:  78%|██████████▏  | 1434/1833 [24:39<06:51,  1.03s/it]

usgs-astrogeology_isis3:  78%|██████████▏  | 1435/1833 [24:40<06:49,  1.03s/it]

usgs-astrogeology_isis3:  78%|██████████▏  | 1436/1833 [24:41<06:48,  1.03s/it]

usgs-astrogeology_isis3:  78%|██████████▏  | 1437/1833 [24:42<06:47,  1.03s/it]

usgs-astrogeology_isis3:  78%|██████████▏  | 1438/1833 [24:43<06:47,  1.03s/it]

usgs-astrogeology_isis3:  79%|██████████▏  | 1439/1833 [24:44<06:45,  1.03s/it]

usgs-astrogeology_isis3:  79%|██████████▏  | 1440/1833 [24:45<06:45,  1.03s/it]

usgs-astrogeology_isis3:  79%|██████████▏  | 1441/1833 [24:46<06:43,  1.03s/it]

usgs-astrogeology_isis3:  79%|██████████▏  | 1442/1833 [24:47<06:42,  1.03s/it]

usgs-astrogeology_isis3:  79%|██████████▏  | 1443/1833 [24:48<06:41,  1.03s/it]

usgs-astrogeology_isis3:  79%|██████████▏  | 1444/1833 [24:49<06:39,  1.03s/it]

usgs-astrogeology_isis3:  79%|██████████▏  | 1445/1833 [24:50<06:38,  1.03s/it]

usgs-astrogeology_isis3:  79%|██████████▎  | 1446/1833 [24:51<06:37,  1.03s/it]

usgs-astrogeology_isis3:  79%|██████████▎  | 1447/1833 [24:52<06:35,  1.03s/it]

usgs-astrogeology_isis3:  79%|██████████▎  | 1448/1833 [24:53<06:35,  1.03s/it]

usgs-astrogeology_isis3:  79%|██████████▎  | 1449/1833 [24:54<06:34,  1.03s/it]

usgs-astrogeology_isis3:  79%|██████████▎  | 1450/1833 [24:55<06:33,  1.03s/it]

usgs-astrogeology_isis3:  79%|██████████▎  | 1451/1833 [24:56<06:32,  1.03s/it]

usgs-astrogeology_isis3:  79%|██████████▎  | 1452/1833 [24:57<06:31,  1.03s/it]

usgs-astrogeology_isis3:  79%|██████████▎  | 1453/1833 [24:58<06:30,  1.03s/it]

usgs-astrogeology_isis3:  79%|██████████▎  | 1454/1833 [24:59<06:29,  1.03s/it]

usgs-astrogeology_isis3:  79%|██████████▎  | 1455/1833 [25:00<06:28,  1.03s/it]

usgs-astrogeology_isis3:  79%|██████████▎  | 1456/1833 [25:01<06:27,  1.03s/it]

usgs-astrogeology_isis3:  79%|██████████▎  | 1457/1833 [25:02<06:26,  1.03s/it]

usgs-astrogeology_isis3:  80%|██████████▎  | 1458/1833 [25:03<06:24,  1.03s/it]

usgs-astrogeology_isis3:  80%|██████████▎  | 1459/1833 [25:04<06:24,  1.03s/it]

usgs-astrogeology_isis3:  80%|██████████▎  | 1460/1833 [25:05<06:23,  1.03s/it]

usgs-astrogeology_isis3:  80%|██████████▎  | 1461/1833 [25:06<06:22,  1.03s/it]

usgs-astrogeology_isis3:  80%|██████████▎  | 1462/1833 [25:07<06:21,  1.03s/it]

usgs-astrogeology_isis3:  80%|██████████▍  | 1463/1833 [25:09<06:20,  1.03s/it]

usgs-astrogeology_isis3:  80%|██████████▍  | 1464/1833 [25:10<06:22,  1.04s/it]

usgs-astrogeology_isis3:  80%|██████████▍  | 1465/1833 [25:11<06:20,  1.03s/it]

usgs-astrogeology_isis3:  80%|██████████▍  | 1466/1833 [25:12<06:19,  1.03s/it]

usgs-astrogeology_isis3:  80%|██████████▍  | 1467/1833 [25:13<06:17,  1.03s/it]

usgs-astrogeology_isis3:  80%|██████████▍  | 1468/1833 [25:14<06:15,  1.03s/it]

usgs-astrogeology_isis3:  80%|██████████▍  | 1469/1833 [25:15<06:14,  1.03s/it]

usgs-astrogeology_isis3:  80%|██████████▍  | 1470/1833 [25:16<06:14,  1.03s/it]

usgs-astrogeology_isis3:  80%|██████████▍  | 1471/1833 [25:17<06:13,  1.03s/it]

usgs-astrogeology_isis3:  80%|██████████▍  | 1472/1833 [25:18<06:12,  1.03s/it]

usgs-astrogeology_isis3:  80%|██████████▍  | 1473/1833 [25:19<06:11,  1.03s/it]

usgs-astrogeology_isis3:  80%|██████████▍  | 1474/1833 [25:20<06:10,  1.03s/it]

usgs-astrogeology_isis3:  80%|██████████▍  | 1475/1833 [25:21<06:08,  1.03s/it]

usgs-astrogeology_isis3:  81%|██████████▍  | 1476/1833 [25:22<06:08,  1.03s/it]

usgs-astrogeology_isis3:  81%|██████████▍  | 1477/1833 [25:23<06:07,  1.03s/it]

usgs-astrogeology_isis3:  81%|██████████▍  | 1478/1833 [25:24<06:06,  1.03s/it]

usgs-astrogeology_isis3:  81%|██████████▍  | 1479/1833 [25:25<06:05,  1.03s/it]

usgs-astrogeology_isis3:  81%|██████████▍  | 1480/1833 [25:26<06:05,  1.04s/it]

usgs-astrogeology_isis3:  81%|██████████▌  | 1481/1833 [25:27<06:04,  1.03s/it]

usgs-astrogeology_isis3:  81%|██████████▌  | 1482/1833 [25:28<06:03,  1.04s/it]

usgs-astrogeology_isis3:  81%|██████████▌  | 1483/1833 [25:29<06:16,  1.08s/it]

usgs-astrogeology_isis3:  81%|██████████▌  | 1484/1833 [25:30<06:10,  1.06s/it]

usgs-astrogeology_isis3:  81%|██████████▌  | 1485/1833 [25:31<06:05,  1.05s/it]

usgs-astrogeology_isis3:  81%|██████████▌  | 1486/1833 [25:32<06:02,  1.04s/it]

usgs-astrogeology_isis3:  81%|██████████▌  | 1487/1833 [25:33<06:00,  1.04s/it]

usgs-astrogeology_isis3:  81%|██████████▌  | 1488/1833 [25:34<05:58,  1.04s/it]

usgs-astrogeology_isis3:  81%|██████████▌  | 1489/1833 [25:35<05:56,  1.04s/it]

usgs-astrogeology_isis3:  81%|██████████▌  | 1490/1833 [25:37<05:54,  1.03s/it]

usgs-astrogeology_isis3:  81%|██████████▌  | 1491/1833 [25:38<05:53,  1.03s/it]

usgs-astrogeology_isis3:  81%|██████████▌  | 1492/1833 [25:39<05:52,  1.03s/it]

usgs-astrogeology_isis3:  81%|██████████▌  | 1493/1833 [25:40<05:51,  1.03s/it]

usgs-astrogeology_isis3:  82%|██████████▌  | 1494/1833 [25:41<05:50,  1.03s/it]

usgs-astrogeology_isis3:  82%|██████████▌  | 1495/1833 [25:42<05:48,  1.03s/it]

usgs-astrogeology_isis3:  82%|██████████▌  | 1496/1833 [25:43<05:47,  1.03s/it]

usgs-astrogeology_isis3:  82%|██████████▌  | 1497/1833 [25:44<05:46,  1.03s/it]

usgs-astrogeology_isis3:  82%|██████████▌  | 1498/1833 [25:45<05:44,  1.03s/it]

usgs-astrogeology_isis3:  82%|██████████▋  | 1499/1833 [25:46<05:43,  1.03s/it]

usgs-astrogeology_isis3:  82%|██████████▋  | 1500/1833 [25:47<05:42,  1.03s/it]

usgs-astrogeology_isis3:  82%|██████████▋  | 1501/1833 [25:48<05:41,  1.03s/it]

usgs-astrogeology_isis3:  82%|██████████▋  | 1502/1833 [25:49<05:40,  1.03s/it]

usgs-astrogeology_isis3:  82%|██████████▋  | 1503/1833 [25:50<05:39,  1.03s/it]

usgs-astrogeology_isis3:  82%|██████████▋  | 1504/1833 [25:51<05:38,  1.03s/it]

usgs-astrogeology_isis3:  82%|██████████▋  | 1505/1833 [25:52<05:37,  1.03s/it]

usgs-astrogeology_isis3:  82%|██████████▋  | 1506/1833 [25:53<05:36,  1.03s/it]

usgs-astrogeology_isis3:  82%|██████████▋  | 1507/1833 [25:54<05:35,  1.03s/it]

usgs-astrogeology_isis3:  82%|██████████▋  | 1508/1833 [25:55<05:34,  1.03s/it]

usgs-astrogeology_isis3:  82%|██████████▋  | 1509/1833 [25:56<05:33,  1.03s/it]

usgs-astrogeology_isis3:  82%|██████████▋  | 1510/1833 [25:57<05:32,  1.03s/it]

usgs-astrogeology_isis3:  82%|██████████▋  | 1511/1833 [25:58<05:31,  1.03s/it]

usgs-astrogeology_isis3:  82%|██████████▋  | 1512/1833 [25:59<05:29,  1.03s/it]

usgs-astrogeology_isis3:  83%|██████████▋  | 1513/1833 [26:00<05:29,  1.03s/it]

usgs-astrogeology_isis3:  83%|██████████▋  | 1514/1833 [26:01<05:28,  1.03s/it]

usgs-astrogeology_isis3:  83%|██████████▋  | 1515/1833 [26:02<05:27,  1.03s/it]

usgs-astrogeology_isis3:  83%|██████████▊  | 1516/1833 [26:03<05:25,  1.03s/it]

usgs-astrogeology_isis3:  83%|██████████▊  | 1517/1833 [26:04<05:24,  1.03s/it]

usgs-astrogeology_isis3:  83%|██████████▊  | 1518/1833 [26:05<05:23,  1.03s/it]

usgs-astrogeology_isis3:  83%|██████████▊  | 1519/1833 [26:06<05:22,  1.03s/it]

usgs-astrogeology_isis3:  83%|██████████▊  | 1520/1833 [26:07<05:21,  1.03s/it]

usgs-astrogeology_isis3:  83%|██████████▊  | 1521/1833 [26:08<05:20,  1.03s/it]

usgs-astrogeology_isis3:  83%|██████████▊  | 1522/1833 [26:09<05:19,  1.03s/it]

usgs-astrogeology_isis3:  83%|██████████▊  | 1523/1833 [26:10<05:19,  1.03s/it]

usgs-astrogeology_isis3:  83%|██████████▊  | 1524/1833 [26:12<05:18,  1.03s/it]

usgs-astrogeology_isis3:  83%|██████████▊  | 1525/1833 [26:13<05:17,  1.03s/it]

usgs-astrogeology_isis3:  83%|██████████▊  | 1526/1833 [26:14<05:17,  1.03s/it]

usgs-astrogeology_isis3:  83%|██████████▊  | 1527/1833 [26:15<05:16,  1.03s/it]

  errors: {'d5e55a9d12cf2f014fa0dc4c9654781651a7e97c': 'Key d5e55a9d12cf2f014fa0dc4c9654781651a7e97c not found in /da5_fast/All.sha1c/commit_85.tch'}

usgs-astrogeology_isis3:  83%|██████████▊  | 1528/1833 [26:16<05:14,  1.03s/it]

usgs-astrogeology_isis3:  83%|██████████▊  | 1529/1833 [26:17<05:13,  1.03s/it]

usgs-astrogeology_isis3:  83%|██████████▊  | 1530/1833 [26:18<05:11,  1.03s/it]

usgs-astrogeology_isis3:  84%|██████████▊  | 1531/1833 [26:19<05:10,  1.03s/it]

usgs-astrogeology_isis3:  84%|██████████▊  | 1532/1833 [26:20<05:09,  1.03s/it]

usgs-astrogeology_isis3:  84%|██████████▊  | 1533/1833 [26:21<05:08,  1.03s/it]

  errors: {'d6db6c66ca6bd1f5f072f3955beff06b192663ee': 'Key d6db6c66ca6bd1f5f072f3955beff06b192663ee not found in /da5_fast/All.sha1c/commit_86.tch'}

usgs-astrogeology_isis3:  84%|██████████▉  | 1534/1833 [26:22<05:08,  1.03s/it]

usgs-astrogeology_isis3:  84%|██████████▉  | 1535/1833 [26:23<05:07,  1.03s/it]

usgs-astrogeology_isis3:  84%|██████████▉  | 1536/1833 [26:24<05:05,  1.03s/it]

usgs-astrogeology_isis3:  84%|██████████▉  | 1537/1833 [26:25<05:04,  1.03s/it]

usgs-astrogeology_isis3:  84%|██████████▉  | 1538/1833 [26:26<05:03,  1.03s/it]

usgs-astrogeology_isis3:  84%|██████████▉  | 1539/1833 [26:27<05:02,  1.03s/it]

usgs-astrogeology_isis3:  84%|██████████▉  | 1540/1833 [26:28<05:02,  1.03s/it]

usgs-astrogeology_isis3:  84%|██████████▉  | 1541/1833 [26:29<05:00,  1.03s/it]

usgs-astrogeology_isis3:  84%|██████████▉  | 1542/1833 [26:30<04:59,  1.03s/it]

usgs-astrogeology_isis3:  84%|██████████▉  | 1543/1833 [26:31<04:58,  1.03s/it]

usgs-astrogeology_isis3:  84%|██████████▉  | 1544/1833 [26:32<04:57,  1.03s/it]

usgs-astrogeology_isis3:  84%|██████████▉  | 1545/1833 [26:33<04:56,  1.03s/it]

usgs-astrogeology_isis3:  84%|██████████▉  | 1546/1833 [26:34<04:55,  1.03s/it]

usgs-astrogeology_isis3:  84%|██████████▉  | 1547/1833 [26:35<04:54,  1.03s/it]

usgs-astrogeology_isis3:  84%|██████████▉  | 1548/1833 [26:36<04:53,  1.03s/it]

usgs-astrogeology_isis3:  85%|██████████▉  | 1549/1833 [26:37<04:51,  1.03s/it]

usgs-astrogeology_isis3:  85%|██████████▉  | 1550/1833 [26:38<04:51,  1.03s/it]

usgs-astrogeology_isis3:  85%|███████████  | 1551/1833 [26:39<04:49,  1.03s/it]

usgs-astrogeology_isis3:  85%|███████████  | 1552/1833 [26:40<04:48,  1.03s/it]

usgs-astrogeology_isis3:  85%|███████████  | 1553/1833 [26:41<04:48,  1.03s/it]

usgs-astrogeology_isis3:  85%|███████████  | 1554/1833 [26:42<04:46,  1.03s/it]

usgs-astrogeology_isis3:  85%|███████████  | 1555/1833 [26:43<04:45,  1.03s/it]

usgs-astrogeology_isis3:  85%|███████████  | 1556/1833 [26:44<04:44,  1.03s/it]

usgs-astrogeology_isis3:  85%|███████████  | 1557/1833 [26:45<04:43,  1.03s/it]

usgs-astrogeology_isis3:  85%|███████████  | 1558/1833 [26:47<04:43,  1.03s/it]

usgs-astrogeology_isis3:  85%|███████████  | 1559/1833 [26:48<04:42,  1.03s/it]

usgs-astrogeology_isis3:  85%|███████████  | 1560/1833 [26:49<04:41,  1.03s/it]

usgs-astrogeology_isis3:  85%|███████████  | 1561/1833 [26:50<04:40,  1.03s/it]

usgs-astrogeology_isis3:  85%|███████████  | 1562/1833 [26:51<04:40,  1.03s/it]

usgs-astrogeology_isis3:  85%|███████████  | 1563/1833 [26:52<04:39,  1.03s/it]

usgs-astrogeology_isis3:  85%|███████████  | 1564/1833 [26:53<04:38,  1.03s/it]

usgs-astrogeology_isis3:  85%|███████████  | 1565/1833 [26:54<04:36,  1.03s/it]

usgs-astrogeology_isis3:  85%|███████████  | 1566/1833 [26:55<04:35,  1.03s/it]

usgs-astrogeology_isis3:  85%|███████████  | 1567/1833 [26:56<04:34,  1.03s/it]

usgs-astrogeology_isis3:  86%|███████████  | 1568/1833 [26:57<04:32,  1.03s/it]

usgs-astrogeology_isis3:  86%|███████████▏ | 1569/1833 [26:58<04:31,  1.03s/it]

usgs-astrogeology_isis3:  86%|███████████▏ | 1570/1833 [26:59<04:31,  1.03s/it]

usgs-astrogeology_isis3:  86%|███████████▏ | 1571/1833 [27:00<04:30,  1.03s/it]

usgs-astrogeology_isis3:  86%|███████████▏ | 1572/1833 [27:01<04:29,  1.03s/it]

usgs-astrogeology_isis3:  86%|███████████▏ | 1573/1833 [27:02<04:28,  1.03s/it]

usgs-astrogeology_isis3:  86%|███████████▏ | 1574/1833 [27:03<04:27,  1.03s/it]

usgs-astrogeology_isis3:  86%|███████████▏ | 1575/1833 [27:04<04:26,  1.03s/it]

usgs-astrogeology_isis3:  86%|███████████▏ | 1576/1833 [27:05<04:24,  1.03s/it]

usgs-astrogeology_isis3:  86%|███████████▏ | 1577/1833 [27:06<04:23,  1.03s/it]

usgs-astrogeology_isis3:  86%|███████████▏ | 1578/1833 [27:07<04:22,  1.03s/it]

usgs-astrogeology_isis3:  86%|███████████▏ | 1579/1833 [27:08<04:21,  1.03s/it]

usgs-astrogeology_isis3:  86%|███████████▏ | 1580/1833 [27:09<04:20,  1.03s/it]

usgs-astrogeology_isis3:  86%|███████████▏ | 1581/1833 [27:10<04:19,  1.03s/it]

usgs-astrogeology_isis3:  86%|███████████▏ | 1582/1833 [27:11<04:18,  1.03s/it]

usgs-astrogeology_isis3:  86%|███████████▏ | 1583/1833 [27:12<04:17,  1.03s/it]

usgs-astrogeology_isis3:  86%|███████████▏ | 1584/1833 [27:13<04:16,  1.03s/it]

usgs-astrogeology_isis3:  86%|███████████▏ | 1585/1833 [27:14<04:14,  1.03s/it]

usgs-astrogeology_isis3:  87%|███████████▏ | 1586/1833 [27:15<04:13,  1.03s/it]

usgs-astrogeology_isis3:  87%|███████████▎ | 1587/1833 [27:16<04:12,  1.03s/it]

usgs-astrogeology_isis3:  87%|███████████▎ | 1588/1833 [27:17<04:12,  1.03s/it]

usgs-astrogeology_isis3:  87%|███████████▎ | 1589/1833 [27:18<04:11,  1.03s/it]

usgs-astrogeology_isis3:  87%|███████████▎ | 1590/1833 [27:19<04:10,  1.03s/it]

usgs-astrogeology_isis3:  87%|███████████▎ | 1591/1833 [27:21<04:08,  1.03s/it]

usgs-astrogeology_isis3:  87%|███████████▎ | 1592/1833 [27:22<04:07,  1.03s/it]

usgs-astrogeology_isis3:  87%|███████████▎ | 1593/1833 [27:23<04:06,  1.03s/it]

usgs-astrogeology_isis3:  87%|███████████▎ | 1594/1833 [27:24<04:05,  1.03s/it]

usgs-astrogeology_isis3:  87%|███████████▎ | 1595/1833 [27:25<04:04,  1.03s/it]

usgs-astrogeology_isis3:  87%|███████████▎ | 1596/1833 [27:26<04:04,  1.03s/it]

usgs-astrogeology_isis3:  87%|███████████▎ | 1597/1833 [27:27<04:02,  1.03s/it]

usgs-astrogeology_isis3:  87%|███████████▎ | 1598/1833 [27:28<04:01,  1.03s/it]

usgs-astrogeology_isis3:  87%|███████████▎ | 1599/1833 [27:29<04:00,  1.03s/it]

usgs-astrogeology_isis3:  87%|███████████▎ | 1600/1833 [27:30<03:59,  1.03s/it]

usgs-astrogeology_isis3:  87%|███████████▎ | 1601/1833 [27:31<03:58,  1.03s/it]

usgs-astrogeology_isis3:  87%|███████████▎ | 1602/1833 [27:32<03:57,  1.03s/it]

usgs-astrogeology_isis3:  87%|███████████▎ | 1603/1833 [27:33<03:56,  1.03s/it]

usgs-astrogeology_isis3:  88%|███████████▍ | 1604/1833 [27:34<03:55,  1.03s/it]

usgs-astrogeology_isis3:  88%|███████████▍ | 1605/1833 [27:35<03:54,  1.03s/it]

usgs-astrogeology_isis3:  88%|███████████▍ | 1606/1833 [27:36<03:53,  1.03s/it]

usgs-astrogeology_isis3:  88%|███████████▍ | 1607/1833 [27:37<03:52,  1.03s/it]

usgs-astrogeology_isis3:  88%|███████████▍ | 1608/1833 [27:38<03:51,  1.03s/it]

usgs-astrogeology_isis3:  88%|███████████▍ | 1609/1833 [27:39<03:50,  1.03s/it]

usgs-astrogeology_isis3:  88%|███████████▍ | 1610/1833 [27:40<03:49,  1.03s/it]

usgs-astrogeology_isis3:  88%|███████████▍ | 1611/1833 [27:41<03:52,  1.05s/it]

usgs-astrogeology_isis3:  88%|███████████▍ | 1612/1833 [27:42<03:49,  1.04s/it]

usgs-astrogeology_isis3:  88%|███████████▍ | 1613/1833 [27:43<03:48,  1.04s/it]

usgs-astrogeology_isis3:  88%|███████████▍ | 1614/1833 [27:44<03:46,  1.03s/it]

usgs-astrogeology_isis3:  88%|███████████▍ | 1615/1833 [27:45<03:45,  1.03s/it]

usgs-astrogeology_isis3:  88%|███████████▍ | 1616/1833 [27:46<03:43,  1.03s/it]

usgs-astrogeology_isis3:  88%|███████████▍ | 1617/1833 [27:47<03:43,  1.04s/it]

usgs-astrogeology_isis3:  88%|███████████▍ | 1618/1833 [27:48<03:42,  1.03s/it]

usgs-astrogeology_isis3:  88%|███████████▍ | 1619/1833 [27:49<03:40,  1.03s/it]

usgs-astrogeology_isis3:  88%|███████████▍ | 1620/1833 [27:50<03:39,  1.03s/it]

usgs-astrogeology_isis3:  88%|███████████▍ | 1621/1833 [27:51<03:38,  1.03s/it]

usgs-astrogeology_isis3:  88%|███████████▌ | 1622/1833 [27:52<03:37,  1.03s/it]

usgs-astrogeology_isis3:  89%|███████████▌ | 1623/1833 [27:53<03:35,  1.03s/it]

usgs-astrogeology_isis3:  89%|███████████▌ | 1624/1833 [27:55<03:35,  1.03s/it]

usgs-astrogeology_isis3:  89%|███████████▌ | 1625/1833 [27:56<03:34,  1.03s/it]

usgs-astrogeology_isis3:  89%|███████████▌ | 1626/1833 [27:57<03:32,  1.03s/it]

usgs-astrogeology_isis3:  89%|███████████▌ | 1627/1833 [27:58<03:31,  1.03s/it]

usgs-astrogeology_isis3:  89%|███████████▌ | 1628/1833 [27:59<03:31,  1.03s/it]

usgs-astrogeology_isis3:  89%|███████████▌ | 1629/1833 [28:00<03:30,  1.03s/it]

usgs-astrogeology_isis3:  89%|███████████▌ | 1630/1833 [28:01<03:29,  1.03s/it]

usgs-astrogeology_isis3:  89%|███████████▌ | 1631/1833 [28:02<03:28,  1.03s/it]

usgs-astrogeology_isis3:  89%|███████████▌ | 1632/1833 [28:03<03:27,  1.03s/it]

usgs-astrogeology_isis3:  89%|███████████▌ | 1633/1833 [28:04<03:25,  1.03s/it]

usgs-astrogeology_isis3:  89%|███████████▌ | 1634/1833 [28:05<03:24,  1.03s/it]

usgs-astrogeology_isis3:  89%|███████████▌ | 1635/1833 [28:06<03:23,  1.03s/it]

usgs-astrogeology_isis3:  89%|███████████▌ | 1636/1833 [28:07<03:22,  1.03s/it]

usgs-astrogeology_isis3:  89%|███████████▌ | 1637/1833 [28:08<03:21,  1.03s/it]

usgs-astrogeology_isis3:  89%|███████████▌ | 1638/1833 [28:09<03:20,  1.03s/it]

usgs-astrogeology_isis3:  89%|███████████▌ | 1639/1833 [28:10<03:19,  1.03s/it]

usgs-astrogeology_isis3:  89%|███████████▋ | 1640/1833 [28:11<03:18,  1.03s/it]

usgs-astrogeology_isis3:  90%|███████████▋ | 1641/1833 [28:12<03:17,  1.03s/it]

usgs-astrogeology_isis3:  90%|███████████▋ | 1642/1833 [28:13<03:16,  1.03s/it]

usgs-astrogeology_isis3:  90%|███████████▋ | 1643/1833 [28:14<03:15,  1.03s/it]

usgs-astrogeology_isis3:  90%|███████████▋ | 1644/1833 [28:15<03:14,  1.03s/it]

usgs-astrogeology_isis3:  90%|███████████▋ | 1645/1833 [28:16<03:13,  1.03s/it]

usgs-astrogeology_isis3:  90%|███████████▋ | 1646/1833 [28:17<03:12,  1.03s/it]

usgs-astrogeology_isis3:  90%|███████████▋ | 1647/1833 [28:18<03:11,  1.03s/it]

usgs-astrogeology_isis3:  90%|███████████▋ | 1648/1833 [28:19<03:10,  1.03s/it]

usgs-astrogeology_isis3:  90%|███████████▋ | 1649/1833 [28:20<03:09,  1.03s/it]

usgs-astrogeology_isis3:  90%|███████████▋ | 1650/1833 [28:21<03:08,  1.03s/it]

usgs-astrogeology_isis3:  90%|███████████▋ | 1651/1833 [28:22<03:07,  1.03s/it]

usgs-astrogeology_isis3:  90%|███████████▋ | 1652/1833 [28:23<03:06,  1.03s/it]

usgs-astrogeology_isis3:  90%|███████████▋ | 1653/1833 [28:24<03:05,  1.03s/it]

usgs-astrogeology_isis3:  90%|███████████▋ | 1654/1833 [28:25<03:04,  1.03s/it]

usgs-astrogeology_isis3:  90%|███████████▋ | 1655/1833 [28:26<03:03,  1.03s/it]

usgs-astrogeology_isis3:  90%|███████████▋ | 1656/1833 [28:27<03:02,  1.03s/it]

usgs-astrogeology_isis3:  90%|███████████▊ | 1657/1833 [28:28<03:01,  1.03s/it]

usgs-astrogeology_isis3:  90%|███████████▊ | 1658/1833 [28:30<03:00,  1.03s/it]

usgs-astrogeology_isis3:  91%|███████████▊ | 1659/1833 [28:31<02:59,  1.03s/it]

usgs-astrogeology_isis3:  91%|███████████▊ | 1660/1833 [28:32<02:58,  1.03s/it]

usgs-astrogeology_isis3:  91%|███████████▊ | 1661/1833 [28:33<02:56,  1.03s/it]

usgs-astrogeology_isis3:  91%|███████████▊ | 1662/1833 [28:34<02:55,  1.03s/it]

usgs-astrogeology_isis3:  91%|███████████▊ | 1663/1833 [28:35<02:54,  1.03s/it]

usgs-astrogeology_isis3:  91%|███████████▊ | 1664/1833 [28:36<02:53,  1.03s/it]

usgs-astrogeology_isis3:  91%|███████████▊ | 1665/1833 [28:37<02:52,  1.03s/it]

usgs-astrogeology_isis3:  91%|███████████▊ | 1666/1833 [28:38<02:51,  1.03s/it]

usgs-astrogeology_isis3:  91%|███████████▊ | 1667/1833 [28:39<02:50,  1.03s/it]

usgs-astrogeology_isis3:  91%|███████████▊ | 1668/1833 [28:40<02:49,  1.03s/it]

usgs-astrogeology_isis3:  91%|███████████▊ | 1669/1833 [28:41<02:48,  1.03s/it]

usgs-astrogeology_isis3:  91%|███████████▊ | 1670/1833 [28:42<02:47,  1.03s/it]

usgs-astrogeology_isis3:  91%|███████████▊ | 1671/1833 [28:43<02:46,  1.03s/it]

usgs-astrogeology_isis3:  91%|███████████▊ | 1672/1833 [28:44<02:45,  1.03s/it]

usgs-astrogeology_isis3:  91%|███████████▊ | 1673/1833 [28:45<02:44,  1.03s/it]

usgs-astrogeology_isis3:  91%|███████████▊ | 1674/1833 [28:46<02:43,  1.03s/it]

usgs-astrogeology_isis3:  91%|███████████▉ | 1675/1833 [28:47<02:42,  1.03s/it]

usgs-astrogeology_isis3:  91%|███████████▉ | 1676/1833 [28:48<02:41,  1.03s/it]

usgs-astrogeology_isis3:  91%|███████████▉ | 1677/1833 [28:49<02:40,  1.03s/it]

usgs-astrogeology_isis3:  92%|███████████▉ | 1678/1833 [28:50<02:39,  1.03s/it]

usgs-astrogeology_isis3:  92%|███████████▉ | 1679/1833 [28:51<02:38,  1.03s/it]

usgs-astrogeology_isis3:  92%|███████████▉ | 1680/1833 [28:52<02:37,  1.03s/it]

usgs-astrogeology_isis3:  92%|███████████▉ | 1681/1833 [28:53<02:36,  1.03s/it]

usgs-astrogeology_isis3:  92%|███████████▉ | 1682/1833 [28:54<02:35,  1.03s/it]

usgs-astrogeology_isis3:  92%|███████████▉ | 1683/1833 [28:55<02:34,  1.03s/it]

usgs-astrogeology_isis3:  92%|███████████▉ | 1684/1833 [28:56<02:33,  1.03s/it]

usgs-astrogeology_isis3:  92%|███████████▉ | 1685/1833 [28:57<02:32,  1.03s/it]

usgs-astrogeology_isis3:  92%|███████████▉ | 1686/1833 [28:58<02:31,  1.03s/it]

usgs-astrogeology_isis3:  92%|███████████▉ | 1687/1833 [28:59<02:30,  1.03s/it]

usgs-astrogeology_isis3:  92%|███████████▉ | 1688/1833 [29:00<02:29,  1.03s/it]

usgs-astrogeology_isis3:  92%|███████████▉ | 1689/1833 [29:01<02:28,  1.03s/it]

usgs-astrogeology_isis3:  92%|███████████▉ | 1690/1833 [29:02<02:27,  1.03s/it]

usgs-astrogeology_isis3:  92%|███████████▉ | 1691/1833 [29:03<02:25,  1.03s/it]

usgs-astrogeology_isis3:  92%|████████████ | 1692/1833 [29:04<02:24,  1.03s/it]

usgs-astrogeology_isis3:  92%|████████████ | 1693/1833 [29:06<02:23,  1.03s/it]

usgs-astrogeology_isis3:  92%|████████████ | 1694/1833 [29:07<02:22,  1.03s/it]

usgs-astrogeology_isis3:  92%|████████████ | 1695/1833 [29:08<02:22,  1.03s/it]

usgs-astrogeology_isis3:  93%|████████████ | 1696/1833 [29:09<02:21,  1.03s/it]

usgs-astrogeology_isis3:  93%|████████████ | 1697/1833 [29:10<02:20,  1.03s/it]

usgs-astrogeology_isis3:  93%|████████████ | 1698/1833 [29:11<02:19,  1.03s/it]

usgs-astrogeology_isis3:  93%|████████████ | 1699/1833 [29:12<02:17,  1.03s/it]

usgs-astrogeology_isis3:  93%|████████████ | 1700/1833 [29:13<02:16,  1.03s/it]

usgs-astrogeology_isis3:  93%|████████████ | 1701/1833 [29:14<02:15,  1.03s/it]

usgs-astrogeology_isis3:  93%|████████████ | 1702/1833 [29:15<02:14,  1.03s/it]

usgs-astrogeology_isis3:  93%|████████████ | 1703/1833 [29:16<02:13,  1.03s/it]

usgs-astrogeology_isis3:  93%|████████████ | 1704/1833 [29:17<02:12,  1.03s/it]

usgs-astrogeology_isis3:  93%|████████████ | 1705/1833 [29:18<02:11,  1.03s/it]

usgs-astrogeology_isis3:  93%|████████████ | 1706/1833 [29:19<02:10,  1.03s/it]

usgs-astrogeology_isis3:  93%|████████████ | 1707/1833 [29:20<02:09,  1.03s/it]

usgs-astrogeology_isis3:  93%|████████████ | 1708/1833 [29:21<02:08,  1.03s/it]

usgs-astrogeology_isis3:  93%|████████████ | 1709/1833 [29:22<02:07,  1.03s/it]

usgs-astrogeology_isis3:  93%|████████████▏| 1710/1833 [29:23<02:06,  1.03s/it]

usgs-astrogeology_isis3:  93%|████████████▏| 1711/1833 [29:24<02:05,  1.03s/it]

usgs-astrogeology_isis3:  93%|████████████▏| 1712/1833 [29:25<02:04,  1.03s/it]

usgs-astrogeology_isis3:  93%|████████████▏| 1713/1833 [29:26<02:03,  1.03s/it]

usgs-astrogeology_isis3:  94%|████████████▏| 1714/1833 [29:27<02:02,  1.03s/it]

usgs-astrogeology_isis3:  94%|████████████▏| 1715/1833 [29:28<02:01,  1.03s/it]

usgs-astrogeology_isis3:  94%|████████████▏| 1716/1833 [29:29<02:00,  1.03s/it]

usgs-astrogeology_isis3:  94%|████████████▏| 1717/1833 [29:30<01:59,  1.03s/it]

usgs-astrogeology_isis3:  94%|████████████▏| 1718/1833 [29:31<01:58,  1.03s/it]

usgs-astrogeology_isis3:  94%|████████████▏| 1719/1833 [29:32<01:57,  1.03s/it]

usgs-astrogeology_isis3:  94%|████████████▏| 1720/1833 [29:33<01:56,  1.03s/it]

usgs-astrogeology_isis3:  94%|████████████▏| 1721/1833 [29:34<01:55,  1.03s/it]

usgs-astrogeology_isis3:  94%|████████████▏| 1722/1833 [29:35<01:54,  1.03s/it]

usgs-astrogeology_isis3:  94%|████████████▏| 1723/1833 [29:36<01:53,  1.03s/it]

usgs-astrogeology_isis3:  94%|████████████▏| 1724/1833 [29:37<01:52,  1.03s/it]

usgs-astrogeology_isis3:  94%|████████████▏| 1725/1833 [29:38<01:51,  1.03s/it]

usgs-astrogeology_isis3:  94%|████████████▏| 1726/1833 [29:39<01:50,  1.03s/it]

usgs-astrogeology_isis3:  94%|████████████▏| 1727/1833 [29:40<01:49,  1.03s/it]

usgs-astrogeology_isis3:  94%|████████████▎| 1728/1833 [29:42<01:48,  1.03s/it]

usgs-astrogeology_isis3:  94%|████████████▎| 1729/1833 [29:43<01:47,  1.03s/it]

usgs-astrogeology_isis3:  94%|████████████▎| 1730/1833 [29:44<01:46,  1.03s/it]

usgs-astrogeology_isis3:  94%|████████████▎| 1731/1833 [29:45<01:45,  1.03s/it]

usgs-astrogeology_isis3:  94%|████████████▎| 1732/1833 [29:46<01:44,  1.03s/it]

usgs-astrogeology_isis3:  95%|████████████▎| 1733/1833 [29:47<01:42,  1.03s/it]

usgs-astrogeology_isis3:  95%|████████████▎| 1734/1833 [29:48<01:41,  1.03s/it]

usgs-astrogeology_isis3:  95%|████████████▎| 1735/1833 [29:49<01:40,  1.03s/it]

usgs-astrogeology_isis3:  95%|████████████▎| 1736/1833 [29:50<01:39,  1.03s/it]

usgs-astrogeology_isis3:  95%|████████████▎| 1737/1833 [29:51<01:38,  1.03s/it]

usgs-astrogeology_isis3:  95%|████████████▎| 1738/1833 [29:52<01:37,  1.03s/it]

usgs-astrogeology_isis3:  95%|████████████▎| 1739/1833 [29:53<01:36,  1.03s/it]

usgs-astrogeology_isis3:  95%|████████████▎| 1740/1833 [29:54<01:35,  1.03s/it]

usgs-astrogeology_isis3:  95%|████████████▎| 1741/1833 [29:55<01:34,  1.03s/it]

usgs-astrogeology_isis3:  95%|████████████▎| 1742/1833 [29:56<01:33,  1.03s/it]

usgs-astrogeology_isis3:  95%|████████████▎| 1743/1833 [29:57<01:32,  1.03s/it]

usgs-astrogeology_isis3:  95%|████████████▎| 1744/1833 [29:58<01:31,  1.03s/it]

usgs-astrogeology_isis3:  95%|████████████▍| 1745/1833 [29:59<01:30,  1.03s/it]

usgs-astrogeology_isis3:  95%|████████████▍| 1746/1833 [30:00<01:29,  1.03s/it]

usgs-astrogeology_isis3:  95%|████████████▍| 1747/1833 [30:01<01:28,  1.03s/it]

usgs-astrogeology_isis3:  95%|████████████▍| 1748/1833 [30:02<01:27,  1.03s/it]

usgs-astrogeology_isis3:  95%|████████████▍| 1749/1833 [30:03<01:26,  1.03s/it]

usgs-astrogeology_isis3:  95%|████████████▍| 1750/1833 [30:04<01:25,  1.03s/it]

usgs-astrogeology_isis3:  96%|████████████▍| 1751/1833 [30:05<01:24,  1.03s/it]

usgs-astrogeology_isis3:  96%|████████████▍| 1752/1833 [30:06<01:23,  1.03s/it]

usgs-astrogeology_isis3:  96%|████████████▍| 1753/1833 [30:07<01:22,  1.03s/it]

usgs-astrogeology_isis3:  96%|████████████▍| 1754/1833 [30:08<01:21,  1.03s/it]

usgs-astrogeology_isis3:  96%|████████████▍| 1755/1833 [30:09<01:20,  1.03s/it]

usgs-astrogeology_isis3:  96%|████████████▍| 1756/1833 [30:10<01:19,  1.03s/it]

usgs-astrogeology_isis3:  96%|████████████▍| 1757/1833 [30:11<01:18,  1.03s/it]

usgs-astrogeology_isis3:  96%|████████████▍| 1758/1833 [30:12<01:17,  1.03s/it]

usgs-astrogeology_isis3:  96%|████████████▍| 1759/1833 [30:13<01:16,  1.03s/it]

usgs-astrogeology_isis3:  96%|████████████▍| 1760/1833 [30:14<01:15,  1.03s/it]

usgs-astrogeology_isis3:  96%|████████████▍| 1761/1833 [30:15<01:14,  1.03s/it]

usgs-astrogeology_isis3:  96%|████████████▍| 1762/1833 [30:16<01:13,  1.03s/it]

usgs-astrogeology_isis3:  96%|████████████▌| 1763/1833 [30:18<01:12,  1.03s/it]

usgs-astrogeology_isis3:  96%|████████████▌| 1764/1833 [30:19<01:11,  1.03s/it]

usgs-astrogeology_isis3:  96%|████████████▌| 1765/1833 [30:20<01:09,  1.03s/it]

usgs-astrogeology_isis3:  96%|████████████▌| 1766/1833 [30:21<01:08,  1.03s/it]

usgs-astrogeology_isis3:  96%|████████████▌| 1767/1833 [30:22<01:07,  1.03s/it]

usgs-astrogeology_isis3:  96%|████████████▌| 1768/1833 [30:23<01:06,  1.03s/it]

usgs-astrogeology_isis3:  97%|████████████▌| 1769/1833 [30:24<01:05,  1.03s/it]

usgs-astrogeology_isis3:  97%|████████████▌| 1770/1833 [30:25<01:04,  1.03s/it]

usgs-astrogeology_isis3:  97%|████████████▌| 1771/1833 [30:26<01:03,  1.03s/it]

usgs-astrogeology_isis3:  97%|████████████▌| 1772/1833 [30:27<01:02,  1.03s/it]

usgs-astrogeology_isis3:  97%|████████████▌| 1773/1833 [30:28<01:01,  1.03s/it]

usgs-astrogeology_isis3:  97%|████████████▌| 1774/1833 [30:29<01:00,  1.03s/it]

usgs-astrogeology_isis3:  97%|████████████▌| 1775/1833 [30:30<00:59,  1.03s/it]

usgs-astrogeology_isis3:  97%|████████████▌| 1776/1833 [30:31<00:58,  1.03s/it]

usgs-astrogeology_isis3:  97%|████████████▌| 1777/1833 [30:32<00:57,  1.03s/it]

usgs-astrogeology_isis3:  97%|████████████▌| 1778/1833 [30:33<00:56,  1.03s/it]

usgs-astrogeology_isis3:  97%|████████████▌| 1779/1833 [30:34<00:55,  1.03s/it]

usgs-astrogeology_isis3:  97%|████████████▌| 1780/1833 [30:35<00:54,  1.03s/it]

usgs-astrogeology_isis3:  97%|████████████▋| 1781/1833 [30:36<00:53,  1.03s/it]

usgs-astrogeology_isis3:  97%|████████████▋| 1782/1833 [30:37<00:52,  1.03s/it]

usgs-astrogeology_isis3:  97%|████████████▋| 1783/1833 [30:38<00:51,  1.03s/it]

usgs-astrogeology_isis3:  97%|████████████▋| 1784/1833 [30:39<00:50,  1.03s/it]

usgs-astrogeology_isis3:  97%|████████████▋| 1785/1833 [30:40<00:49,  1.03s/it]

usgs-astrogeology_isis3:  97%|████████████▋| 1786/1833 [30:41<00:48,  1.03s/it]

usgs-astrogeology_isis3:  97%|████████████▋| 1787/1833 [30:42<00:47,  1.03s/it]

usgs-astrogeology_isis3:  98%|████████████▋| 1788/1833 [30:43<00:46,  1.03s/it]

usgs-astrogeology_isis3:  98%|████████████▋| 1789/1833 [30:44<00:45,  1.03s/it]

usgs-astrogeology_isis3:  98%|████████████▋| 1790/1833 [30:45<00:44,  1.03s/it]

usgs-astrogeology_isis3:  98%|████████████▋| 1791/1833 [30:46<00:43,  1.03s/it]

usgs-astrogeology_isis3:  98%|████████████▋| 1792/1833 [30:47<00:42,  1.03s/it]

usgs-astrogeology_isis3:  98%|████████████▋| 1793/1833 [30:48<00:41,  1.03s/it]

usgs-astrogeology_isis3:  98%|████████████▋| 1794/1833 [30:49<00:40,  1.03s/it]

usgs-astrogeology_isis3:  98%|████████████▋| 1795/1833 [30:50<00:39,  1.03s/it]

usgs-astrogeology_isis3:  98%|████████████▋| 1796/1833 [30:51<00:38,  1.03s/it]

usgs-astrogeology_isis3:  98%|████████████▋| 1797/1833 [30:52<00:37,  1.03s/it]

usgs-astrogeology_isis3:  98%|████████████▊| 1798/1833 [30:54<00:36,  1.03s/it]

usgs-astrogeology_isis3:  98%|████████████▊| 1799/1833 [30:55<00:34,  1.03s/it]

usgs-astrogeology_isis3:  98%|████████████▊| 1800/1833 [30:56<00:33,  1.03s/it]

usgs-astrogeology_isis3:  98%|████████████▊| 1801/1833 [30:57<00:32,  1.03s/it]

usgs-astrogeology_isis3:  98%|████████████▊| 1802/1833 [30:58<00:31,  1.03s/it]

usgs-astrogeology_isis3:  98%|████████████▊| 1803/1833 [30:59<00:30,  1.03s/it]

usgs-astrogeology_isis3:  98%|████████████▊| 1804/1833 [31:00<00:29,  1.03s/it]

usgs-astrogeology_isis3:  98%|████████████▊| 1805/1833 [31:01<00:28,  1.03s/it]

usgs-astrogeology_isis3:  99%|████████████▊| 1806/1833 [31:02<00:27,  1.03s/it]

usgs-astrogeology_isis3:  99%|████████████▊| 1807/1833 [31:03<00:26,  1.03s/it]

usgs-astrogeology_isis3:  99%|████████████▊| 1808/1833 [31:04<00:25,  1.03s/it]

usgs-astrogeology_isis3:  99%|████████████▊| 1809/1833 [31:05<00:24,  1.03s/it]

usgs-astrogeology_isis3:  99%|████████████▊| 1810/1833 [31:06<00:23,  1.03s/it]

usgs-astrogeology_isis3:  99%|████████████▊| 1811/1833 [31:07<00:22,  1.03s/it]

usgs-astrogeology_isis3:  99%|████████████▊| 1812/1833 [31:08<00:21,  1.03s/it]

usgs-astrogeology_isis3:  99%|████████████▊| 1813/1833 [31:09<00:20,  1.03s/it]

usgs-astrogeology_isis3:  99%|████████████▊| 1814/1833 [31:10<00:19,  1.03s/it]

usgs-astrogeology_isis3:  99%|████████████▊| 1815/1833 [31:11<00:18,  1.03s/it]

usgs-astrogeology_isis3:  99%|████████████▉| 1816/1833 [31:12<00:17,  1.03s/it]

usgs-astrogeology_isis3:  99%|████████████▉| 1817/1833 [31:13<00:16,  1.03s/it]

usgs-astrogeology_isis3:  99%|████████████▉| 1818/1833 [31:14<00:15,  1.03s/it]

usgs-astrogeology_isis3:  99%|████████████▉| 1819/1833 [31:15<00:14,  1.03s/it]

usgs-astrogeology_isis3:  99%|████████████▉| 1820/1833 [31:16<00:13,  1.03s/it]

usgs-astrogeology_isis3:  99%|████████████▉| 1821/1833 [31:17<00:12,  1.03s/it]

usgs-astrogeology_isis3:  99%|████████████▉| 1822/1833 [31:18<00:11,  1.03s/it]

usgs-astrogeology_isis3:  99%|████████████▉| 1823/1833 [31:19<00:10,  1.03s/it]

usgs-astrogeology_isis3: 100%|████████████▉| 1824/1833 [31:20<00:09,  1.03s/it]

usgs-astrogeology_isis3: 100%|████████████▉| 1825/1833 [31:21<00:08,  1.03s/it]

usgs-astrogeology_isis3: 100%|████████████▉| 1826/1833 [31:22<00:07,  1.03s/it]

usgs-astrogeology_isis3: 100%|████████████▉| 1827/1833 [31:23<00:06,  1.03s/it]

usgs-astrogeology_isis3: 100%|████████████▉| 1828/1833 [31:24<00:05,  1.03s/it]

usgs-astrogeology_isis3: 100%|████████████▉| 1829/1833 [31:25<00:04,  1.03s/it]

usgs-astrogeology_isis3: 100%|████████████▉| 1830/1833 [31:26<00:03,  1.03s/it]

usgs-astrogeology_isis3: 100%|████████████▉| 1831/1833 [31:27<00:02,  1.03s/it]

usgs-astrogeology_isis3: 100%|████████████▉| 1832/1833 [31:29<00:01,  1.04s/it]

usgs-astrogeology_isis3: 100%|█████████████| 1833/1833 [31:30<00:00,  1.04s/it]

usgs-astrogeology_isis3: 100%|█████████████| 1833/1833 [31:30<00:00,  1.03s/it]

  WARNING: 10 commits could not be retrieved
sakov_enkf-c -> 1772 commit sha1s

sakov_enkf-c:   0%|                                    | 0/178 [00:00<?, ?it/s]

sakov_enkf-c:   1%|▏                           | 1/178 [00:01<03:01,  1.03s/it]

sakov_enkf-c:   1%|▎                           | 2/178 [00:02<03:00,  1.03s/it]

sakov_enkf-c:   2%|▍                           | 3/178 [00:03<02:59,  1.03s/it]

sakov_enkf-c:   2%|▋                           | 4/178 [00:04<02:58,  1.03s/it]

sakov_enkf-c:   3%|▊                           | 5/178 [00:05<02:57,  1.03s/it]

sakov_enkf-c:   3%|▉                           | 6/178 [00:06<02:57,  1.03s/it]

sakov_enkf-c:   4%|█                           | 7/178 [00:07<02:56,  1.03s/it]

sakov_enkf-c:   4%|█▎                          | 8/178 [00:08<02:55,  1.03s/it]

sakov_enkf-c:   5%|█▍                          | 9/178 [00:09<02:54,  1.03s/it]

sakov_enkf-c:   6%|█▌                         | 10/178 [00:10<02:53,  1.03s/it]

sakov_enkf-c:   6%|█▋                         | 11/178 [00:11<02:52,  1.03s/it]

sakov_enkf-c:   7%|█▊                         | 12/178 [00:12<02:51,  1.03s/it]

sakov_enkf-c:   7%|█▉                         | 13/178 [00:13<02:50,  1.03s/it]

sakov_enkf-c:   8%|██                         | 14/178 [00:14<02:49,  1.03s/it]

sakov_enkf-c:   8%|██▎                        | 15/178 [00:15<02:47,  1.03s/it]

sakov_enkf-c:   9%|██▍                        | 16/178 [00:16<02:47,  1.03s/it]

sakov_enkf-c:  10%|██▌                        | 17/178 [00:17<02:46,  1.03s/it]

sakov_enkf-c:  10%|██▋                        | 18/178 [00:18<02:45,  1.03s/it]

sakov_enkf-c:  11%|██▉                        | 19/178 [00:19<02:43,  1.03s/it]

sakov_enkf-c:  11%|███                        | 20/178 [00:20<02:43,  1.03s/it]

sakov_enkf-c:  12%|███▏                       | 21/178 [00:21<02:51,  1.10s/it]

sakov_enkf-c:  12%|███▎                       | 22/178 [00:22<02:47,  1.08s/it]

sakov_enkf-c:  13%|███▍                       | 23/178 [00:23<02:44,  1.06s/it]

sakov_enkf-c:  13%|███▋                       | 24/178 [00:24<02:42,  1.06s/it]

sakov_enkf-c:  14%|███▊                       | 25/178 [00:25<02:40,  1.05s/it]

sakov_enkf-c:  15%|███▉                       | 26/178 [00:27<02:38,  1.04s/it]

sakov_enkf-c:  15%|████                       | 27/178 [00:28<02:36,  1.04s/it]

sakov_enkf-c:  16%|████▏                      | 28/178 [00:29<02:35,  1.04s/it]

sakov_enkf-c:  16%|████▍                      | 29/178 [00:30<02:34,  1.04s/it]

sakov_enkf-c:  17%|████▌                      | 30/178 [00:31<02:33,  1.04s/it]

sakov_enkf-c:  17%|████▋                      | 31/178 [00:32<02:32,  1.04s/it]

sakov_enkf-c:  18%|████▊                      | 32/178 [00:33<02:30,  1.03s/it]

sakov_enkf-c:  19%|█████                      | 33/178 [00:34<02:29,  1.03s/it]

sakov_enkf-c:  19%|█████▏                     | 34/178 [00:35<02:28,  1.03s/it]

sakov_enkf-c:  20%|█████▎                     | 35/178 [00:36<02:27,  1.03s/it]

sakov_enkf-c:  20%|█████▍                     | 36/178 [00:37<02:26,  1.03s/it]

sakov_enkf-c:  21%|█████▌                     | 37/178 [00:38<02:25,  1.03s/it]

sakov_enkf-c:  21%|█████▊                     | 38/178 [00:39<02:24,  1.03s/it]

sakov_enkf-c:  22%|█████▉                     | 39/178 [00:40<02:23,  1.03s/it]

sakov_enkf-c:  22%|██████                     | 40/178 [00:41<02:22,  1.03s/it]

sakov_enkf-c:  23%|██████▏                    | 41/178 [00:42<02:21,  1.03s/it]

sakov_enkf-c:  24%|██████▎                    | 42/178 [00:43<02:20,  1.03s/it]

sakov_enkf-c:  24%|██████▌                    | 43/178 [00:44<02:19,  1.03s/it]

sakov_enkf-c:  25%|██████▋                    | 44/178 [00:45<02:18,  1.03s/it]

sakov_enkf-c:  25%|██████▊                    | 45/178 [00:46<02:20,  1.05s/it]

sakov_enkf-c:  26%|██████▉                    | 46/178 [00:47<02:18,  1.05s/it]

sakov_enkf-c:  26%|███████▏                   | 47/178 [00:48<02:16,  1.04s/it]

sakov_enkf-c:  27%|███████▎                   | 48/178 [00:49<02:15,  1.04s/it]

sakov_enkf-c:  28%|███████▍                   | 49/178 [00:50<02:14,  1.04s/it]

sakov_enkf-c:  28%|███████▌                   | 50/178 [00:51<02:12,  1.04s/it]

sakov_enkf-c:  29%|███████▋                   | 51/178 [00:52<02:11,  1.04s/it]

sakov_enkf-c:  29%|███████▉                   | 52/178 [00:53<02:10,  1.04s/it]

sakov_enkf-c:  30%|████████                   | 53/178 [00:55<02:09,  1.04s/it]

sakov_enkf-c:  30%|████████▏                  | 54/178 [00:56<02:08,  1.04s/it]

sakov_enkf-c:  31%|████████▎                  | 55/178 [00:57<02:07,  1.03s/it]

sakov_enkf-c:  31%|████████▍                  | 56/178 [00:58<02:06,  1.03s/it]

sakov_enkf-c:  32%|████████▋                  | 57/178 [00:59<02:05,  1.03s/it]

sakov_enkf-c:  33%|████████▊                  | 58/178 [01:00<02:04,  1.03s/it]

sakov_enkf-c:  33%|████████▉                  | 59/178 [01:01<02:02,  1.03s/it]

sakov_enkf-c:  34%|█████████                  | 60/178 [01:02<02:01,  1.03s/it]

sakov_enkf-c:  34%|█████████▎                 | 61/178 [01:03<02:00,  1.03s/it]

sakov_enkf-c:  35%|█████████▍                 | 62/178 [01:04<01:59,  1.03s/it]

sakov_enkf-c:  35%|█████████▌                 | 63/178 [01:05<01:58,  1.03s/it]

sakov_enkf-c:  36%|█████████▋                 | 64/178 [01:06<01:57,  1.03s/it]

sakov_enkf-c:  37%|█████████▊                 | 65/178 [01:07<01:57,  1.04s/it]

sakov_enkf-c:  37%|██████████                 | 66/178 [01:08<01:55,  1.03s/it]

sakov_enkf-c:  38%|██████████▏                | 67/178 [01:09<01:54,  1.03s/it]

sakov_enkf-c:  38%|██████████▎                | 68/178 [01:10<01:53,  1.03s/it]

sakov_enkf-c:  39%|██████████▍                | 69/178 [01:11<01:52,  1.03s/it]

sakov_enkf-c:  39%|██████████▌                | 70/178 [01:12<01:51,  1.03s/it]

sakov_enkf-c:  40%|██████████▊                | 71/178 [01:13<01:50,  1.03s/it]

sakov_enkf-c:  40%|██████████▉                | 72/178 [01:14<01:49,  1.03s/it]

sakov_enkf-c:  41%|███████████                | 73/178 [01:15<01:48,  1.03s/it]

sakov_enkf-c:  42%|███████████▏               | 74/178 [01:16<01:47,  1.03s/it]

sakov_enkf-c:  42%|███████████▍               | 75/178 [01:17<01:46,  1.03s/it]

sakov_enkf-c:  43%|███████████▌               | 76/178 [01:18<01:45,  1.03s/it]

sakov_enkf-c:  43%|███████████▋               | 77/178 [01:19<01:44,  1.03s/it]

sakov_enkf-c:  44%|███████████▊               | 78/178 [01:20<01:43,  1.03s/it]

sakov_enkf-c:  44%|███████████▉               | 79/178 [01:21<01:42,  1.03s/it]

sakov_enkf-c:  45%|████████████▏              | 80/178 [01:22<01:40,  1.03s/it]

sakov_enkf-c:  46%|████████████▎              | 81/178 [01:23<01:39,  1.03s/it]

sakov_enkf-c:  46%|████████████▍              | 82/178 [01:24<01:38,  1.03s/it]

sakov_enkf-c:  47%|████████████▌              | 83/178 [01:25<01:37,  1.03s/it]

sakov_enkf-c:  47%|████████████▋              | 84/178 [01:27<01:36,  1.03s/it]

sakov_enkf-c:  48%|████████████▉              | 85/178 [01:28<01:35,  1.03s/it]

sakov_enkf-c:  48%|█████████████              | 86/178 [01:29<01:34,  1.03s/it]

sakov_enkf-c:  49%|█████████████▏             | 87/178 [01:30<01:33,  1.03s/it]

sakov_enkf-c:  49%|█████████████▎             | 88/178 [01:31<01:32,  1.03s/it]

sakov_enkf-c:  50%|█████████████▌             | 89/178 [01:32<01:31,  1.03s/it]

sakov_enkf-c:  51%|█████████████▋             | 90/178 [01:33<01:30,  1.03s/it]

sakov_enkf-c:  51%|█████████████▊             | 91/178 [01:34<01:29,  1.03s/it]

sakov_enkf-c:  52%|█████████████▉             | 92/178 [01:35<01:28,  1.03s/it]

sakov_enkf-c:  52%|██████████████             | 93/178 [01:36<01:27,  1.03s/it]

sakov_enkf-c:  53%|██████████████▎            | 94/178 [01:37<01:26,  1.03s/it]

sakov_enkf-c:  53%|██████████████▍            | 95/178 [01:38<01:27,  1.05s/it]

sakov_enkf-c:  54%|██████████████▌            | 96/178 [01:39<01:25,  1.05s/it]

sakov_enkf-c:  54%|██████████████▋            | 97/178 [01:40<01:24,  1.04s/it]

sakov_enkf-c:  55%|██████████████▊            | 98/178 [01:41<01:22,  1.04s/it]

sakov_enkf-c:  56%|███████████████            | 99/178 [01:42<01:21,  1.04s/it]

sakov_enkf-c:  56%|██████████████▌           | 100/178 [01:43<01:20,  1.03s/it]

sakov_enkf-c:  57%|██████████████▊           | 101/178 [01:44<01:19,  1.03s/it]

sakov_enkf-c:  57%|██████████████▉           | 102/178 [01:45<01:18,  1.03s/it]

sakov_enkf-c:  58%|███████████████           | 103/178 [01:46<01:17,  1.03s/it]

sakov_enkf-c:  58%|███████████████▏          | 104/178 [01:47<01:16,  1.03s/it]

sakov_enkf-c:  59%|███████████████▎          | 105/178 [01:48<01:15,  1.03s/it]

sakov_enkf-c:  60%|███████████████▍          | 106/178 [01:49<01:14,  1.03s/it]

sakov_enkf-c:  60%|███████████████▋          | 107/178 [01:50<01:13,  1.03s/it]

sakov_enkf-c:  61%|███████████████▊          | 108/178 [01:51<01:12,  1.03s/it]

sakov_enkf-c:  61%|███████████████▉          | 109/178 [01:52<01:11,  1.03s/it]

sakov_enkf-c:  62%|████████████████          | 110/178 [01:53<01:09,  1.03s/it]

sakov_enkf-c:  62%|████████████████▏         | 111/178 [01:54<01:08,  1.03s/it]

sakov_enkf-c:  63%|████████████████▎         | 112/178 [01:55<01:07,  1.03s/it]

sakov_enkf-c:  63%|████████████████▌         | 113/178 [01:56<01:06,  1.03s/it]

sakov_enkf-c:  64%|████████████████▋         | 114/178 [01:57<01:06,  1.03s/it]

sakov_enkf-c:  65%|████████████████▊         | 115/178 [01:59<01:05,  1.03s/it]

sakov_enkf-c:  65%|████████████████▉         | 116/178 [02:00<01:04,  1.03s/it]

sakov_enkf-c:  66%|█████████████████         | 117/178 [02:01<01:02,  1.03s/it]

sakov_enkf-c:  66%|█████████████████▏        | 118/178 [02:02<01:01,  1.03s/it]

sakov_enkf-c:  67%|█████████████████▍        | 119/178 [02:03<01:00,  1.03s/it]

sakov_enkf-c:  67%|█████████████████▌        | 120/178 [02:04<00:59,  1.03s/it]

sakov_enkf-c:  68%|█████████████████▋        | 121/178 [02:05<00:58,  1.03s/it]

sakov_enkf-c:  69%|█████████████████▊        | 122/178 [02:06<00:57,  1.03s/it]

sakov_enkf-c:  69%|█████████████████▉        | 123/178 [02:07<00:56,  1.03s/it]

sakov_enkf-c:  70%|██████████████████        | 124/178 [02:08<00:55,  1.03s/it]

sakov_enkf-c:  70%|██████████████████▎       | 125/178 [02:09<00:54,  1.03s/it]

sakov_enkf-c:  71%|██████████████████▍       | 126/178 [02:10<00:53,  1.03s/it]

sakov_enkf-c:  71%|██████████████████▌       | 127/178 [02:11<00:52,  1.03s/it]

sakov_enkf-c:  72%|██████████████████▋       | 128/178 [02:12<00:51,  1.03s/it]

sakov_enkf-c:  72%|██████████████████▊       | 129/178 [02:13<00:50,  1.03s/it]

sakov_enkf-c:  73%|██████████████████▉       | 130/178 [02:14<00:49,  1.03s/it]

sakov_enkf-c:  74%|███████████████████▏      | 131/178 [02:15<00:48,  1.03s/it]

sakov_enkf-c:  74%|███████████████████▎      | 132/178 [02:16<00:47,  1.03s/it]

sakov_enkf-c:  75%|███████████████████▍      | 133/178 [02:17<00:46,  1.03s/it]

sakov_enkf-c:  75%|███████████████████▌      | 134/178 [02:18<00:45,  1.03s/it]

sakov_enkf-c:  76%|███████████████████▋      | 135/178 [02:19<00:44,  1.03s/it]

sakov_enkf-c:  76%|███████████████████▊      | 136/178 [02:20<00:43,  1.03s/it]

sakov_enkf-c:  77%|████████████████████      | 137/178 [02:21<00:42,  1.03s/it]

sakov_enkf-c:  78%|████████████████████▏     | 138/178 [02:22<00:41,  1.03s/it]

sakov_enkf-c:  78%|████████████████████▎     | 139/178 [02:23<00:40,  1.03s/it]

sakov_enkf-c:  79%|████████████████████▍     | 140/178 [02:24<00:39,  1.03s/it]

sakov_enkf-c:  79%|████████████████████▌     | 141/178 [02:25<00:38,  1.03s/it]

sakov_enkf-c:  80%|████████████████████▋     | 142/178 [02:26<00:37,  1.03s/it]

sakov_enkf-c:  80%|████████████████████▉     | 143/178 [02:27<00:36,  1.03s/it]

sakov_enkf-c:  81%|█████████████████████     | 144/178 [02:28<00:35,  1.03s/it]

sakov_enkf-c:  81%|█████████████████████▏    | 145/178 [02:29<00:33,  1.03s/it]

sakov_enkf-c:  82%|█████████████████████▎    | 146/178 [02:30<00:32,  1.03s/it]

sakov_enkf-c:  83%|█████████████████████▍    | 147/178 [02:31<00:31,  1.03s/it]

sakov_enkf-c:  83%|█████████████████████▌    | 148/178 [02:33<00:30,  1.03s/it]

sakov_enkf-c:  84%|█████████████████████▊    | 149/178 [02:34<00:29,  1.03s/it]

sakov_enkf-c:  84%|█████████████████████▉    | 150/178 [02:35<00:28,  1.03s/it]

sakov_enkf-c:  85%|██████████████████████    | 151/178 [02:36<00:27,  1.03s/it]

sakov_enkf-c:  85%|██████████████████████▏   | 152/178 [02:37<00:26,  1.03s/it]

sakov_enkf-c:  86%|██████████████████████▎   | 153/178 [02:38<00:25,  1.03s/it]

sakov_enkf-c:  87%|██████████████████████▍   | 154/178 [02:39<00:24,  1.03s/it]

sakov_enkf-c:  87%|██████████████████████▋   | 155/178 [02:40<00:23,  1.03s/it]

sakov_enkf-c:  88%|██████████████████████▊   | 156/178 [02:41<00:22,  1.03s/it]

sakov_enkf-c:  88%|██████████████████████▉   | 157/178 [02:42<00:21,  1.03s/it]

sakov_enkf-c:  89%|███████████████████████   | 158/178 [02:43<00:20,  1.03s/it]

sakov_enkf-c:  89%|███████████████████████▏  | 159/178 [02:44<00:19,  1.03s/it]

sakov_enkf-c:  90%|███████████████████████▎  | 160/178 [02:45<00:18,  1.03s/it]

sakov_enkf-c:  90%|███████████████████████▌  | 161/178 [02:46<00:17,  1.03s/it]

sakov_enkf-c:  91%|███████████████████████▋  | 162/178 [02:47<00:16,  1.03s/it]

sakov_enkf-c:  92%|███████████████████████▊  | 163/178 [02:48<00:15,  1.03s/it]

sakov_enkf-c:  92%|███████████████████████▉  | 164/178 [02:49<00:14,  1.03s/it]

sakov_enkf-c:  93%|████████████████████████  | 165/178 [02:50<00:13,  1.03s/it]

sakov_enkf-c:  93%|████████████████████████▏ | 166/178 [02:51<00:12,  1.03s/it]

sakov_enkf-c:  94%|████████████████████████▍ | 167/178 [02:52<00:11,  1.03s/it]

sakov_enkf-c:  94%|████████████████████████▌ | 168/178 [02:53<00:10,  1.03s/it]

sakov_enkf-c:  95%|████████████████████████▋ | 169/178 [02:54<00:09,  1.03s/it]

sakov_enkf-c:  96%|████████████████████████▊ | 170/178 [02:55<00:08,  1.03s/it]

sakov_enkf-c:  96%|████████████████████████▉ | 171/178 [02:56<00:07,  1.03s/it]

sakov_enkf-c:  97%|█████████████████████████ | 172/178 [02:57<00:06,  1.03s/it]

sakov_enkf-c:  97%|█████████████████████████▎| 173/178 [02:58<00:05,  1.03s/it]

sakov_enkf-c:  98%|█████████████████████████▍| 174/178 [02:59<00:04,  1.03s/it]

sakov_enkf-c:  98%|█████████████████████████▌| 175/178 [03:00<00:03,  1.03s/it]

sakov_enkf-c:  99%|█████████████████████████▋| 176/178 [03:01<00:02,  1.03s/it]

sakov_enkf-c:  99%|█████████████████████████▊| 177/178 [03:02<00:01,  1.03s/it]

sakov_enkf-c: 100%|██████████████████████████| 178/178 [03:03<00:00,  1.03s/it]

sakov_enkf-c: 100%|██████████████████████████| 178/178 [03:03<00:00,  1.03s/it]

sfc-aqua_quisp -> 4409 commit sha1s

sfc-aqua_quisp:   0%|                                  | 0/441 [00:00<?, ?it/s]

sfc-aqua_quisp:   0%|                          | 1/441 [00:01<07:34,  1.03s/it]

sfc-aqua_quisp:   0%|                          | 2/441 [00:02<07:35,  1.04s/it]

sfc-aqua_quisp:   1%|▏                         | 3/441 [00:03<07:33,  1.04s/it]

sfc-aqua_quisp:   1%|▏                         | 4/441 [00:04<07:32,  1.04s/it]

sfc-aqua_quisp:   1%|▎                         | 5/441 [00:05<07:31,  1.04s/it]

sfc-aqua_quisp:   1%|▎                         | 6/441 [00:06<07:30,  1.04s/it]

sfc-aqua_quisp:   2%|▍                         | 7/441 [00:07<07:28,  1.03s/it]

sfc-aqua_quisp:   2%|▍                         | 8/441 [00:08<07:27,  1.03s/it]

sfc-aqua_quisp:   2%|▌                         | 9/441 [00:09<07:25,  1.03s/it]

sfc-aqua_quisp:   2%|▌                        | 10/441 [00:10<07:25,  1.03s/it]

sfc-aqua_quisp:   2%|▌                        | 11/441 [00:11<07:23,  1.03s/it]

sfc-aqua_quisp:   3%|▋                        | 12/441 [00:12<07:23,  1.03s/it]

sfc-aqua_quisp:   3%|▋                        | 13/441 [00:13<07:22,  1.03s/it]

sfc-aqua_quisp:   3%|▊                        | 14/441 [00:14<07:21,  1.03s/it]

sfc-aqua_quisp:   3%|▊                        | 15/441 [00:15<07:20,  1.03s/it]

sfc-aqua_quisp:   4%|▉                        | 16/441 [00:16<07:19,  1.03s/it]

sfc-aqua_quisp:   4%|▉                        | 17/441 [00:17<07:19,  1.04s/it]

sfc-aqua_quisp:   4%|█                        | 18/441 [00:18<07:16,  1.03s/it]

sfc-aqua_quisp:   4%|█                        | 19/441 [00:19<07:15,  1.03s/it]

sfc-aqua_quisp:   5%|█▏                       | 20/441 [00:20<07:14,  1.03s/it]

sfc-aqua_quisp:   5%|█▏                       | 21/441 [00:21<07:13,  1.03s/it]

sfc-aqua_quisp:   5%|█▏                       | 22/441 [00:22<07:13,  1.03s/it]

sfc-aqua_quisp:   5%|█▎                       | 23/441 [00:23<07:11,  1.03s/it]

sfc-aqua_quisp:   5%|█▎                       | 24/441 [00:24<07:11,  1.03s/it]

sfc-aqua_quisp:   6%|█▍                       | 25/441 [00:25<07:10,  1.04s/it]

sfc-aqua_quisp:   6%|█▍                       | 26/441 [00:26<07:09,  1.03s/it]

sfc-aqua_quisp:   6%|█▌                       | 27/441 [00:27<07:08,  1.03s/it]

sfc-aqua_quisp:   6%|█▌                       | 28/441 [00:28<07:07,  1.03s/it]

sfc-aqua_quisp:   7%|█▋                       | 29/441 [00:29<07:06,  1.04s/it]

sfc-aqua_quisp:   7%|█▋                       | 30/441 [00:31<07:05,  1.04s/it]

sfc-aqua_quisp:   7%|█▊                       | 31/441 [00:32<07:04,  1.03s/it]

sfc-aqua_quisp:   7%|█▊                       | 32/441 [00:33<07:02,  1.03s/it]

sfc-aqua_quisp:   7%|█▊                       | 33/441 [00:34<07:01,  1.03s/it]

sfc-aqua_quisp:   8%|█▉                       | 34/441 [00:35<06:59,  1.03s/it]

sfc-aqua_quisp:   8%|█▉                       | 35/441 [00:36<06:59,  1.03s/it]

sfc-aqua_quisp:   8%|██                       | 36/441 [00:37<06:58,  1.03s/it]

sfc-aqua_quisp:   8%|██                       | 37/441 [00:38<06:57,  1.03s/it]

sfc-aqua_quisp:   9%|██▏                      | 38/441 [00:39<06:56,  1.03s/it]

sfc-aqua_quisp:   9%|██▏                      | 39/441 [00:40<06:55,  1.03s/it]

sfc-aqua_quisp:   9%|██▎                      | 40/441 [00:41<06:54,  1.03s/it]

sfc-aqua_quisp:   9%|██▎                      | 41/441 [00:42<06:53,  1.03s/it]

sfc-aqua_quisp:  10%|██▍                      | 42/441 [00:43<06:53,  1.04s/it]

sfc-aqua_quisp:  10%|██▍                      | 43/441 [00:44<06:51,  1.03s/it]

sfc-aqua_quisp:  10%|██▍                      | 44/441 [00:45<06:51,  1.04s/it]

sfc-aqua_quisp:  10%|██▌                      | 45/441 [00:46<06:49,  1.03s/it]

sfc-aqua_quisp:  10%|██▌                      | 46/441 [00:47<06:48,  1.04s/it]

sfc-aqua_quisp:  11%|██▋                      | 47/441 [00:48<06:47,  1.03s/it]

sfc-aqua_quisp:  11%|██▋                      | 48/441 [00:49<06:46,  1.03s/it]

sfc-aqua_quisp:  11%|██▊                      | 49/441 [00:50<06:45,  1.04s/it]

sfc-aqua_quisp:  11%|██▊                      | 50/441 [00:51<06:44,  1.03s/it]

sfc-aqua_quisp:  12%|██▉                      | 51/441 [00:52<06:43,  1.03s/it]

sfc-aqua_quisp:  12%|██▉                      | 52/441 [00:53<06:43,  1.04s/it]

sfc-aqua_quisp:  12%|███                      | 53/441 [00:54<06:41,  1.04s/it]

sfc-aqua_quisp:  12%|███                      | 54/441 [00:55<06:40,  1.04s/it]

sfc-aqua_quisp:  12%|███                      | 55/441 [00:56<06:39,  1.04s/it]

sfc-aqua_quisp:  13%|███▏                     | 56/441 [00:57<06:39,  1.04s/it]

sfc-aqua_quisp:  13%|███▏                     | 57/441 [00:58<06:38,  1.04s/it]

sfc-aqua_quisp:  13%|███▎                     | 58/441 [01:00<06:37,  1.04s/it]

sfc-aqua_quisp:  13%|███▎                     | 59/441 [01:01<06:35,  1.04s/it]

sfc-aqua_quisp:  14%|███▍                     | 60/441 [01:02<06:35,  1.04s/it]

sfc-aqua_quisp:  14%|███▍                     | 61/441 [01:03<06:33,  1.04s/it]

sfc-aqua_quisp:  14%|███▌                     | 62/441 [01:04<06:32,  1.04s/it]

sfc-aqua_quisp:  14%|███▌                     | 63/441 [01:05<06:31,  1.04s/it]

sfc-aqua_quisp:  15%|███▋                     | 64/441 [01:06<06:30,  1.03s/it]

sfc-aqua_quisp:  15%|███▋                     | 65/441 [01:07<06:29,  1.04s/it]

sfc-aqua_quisp:  15%|███▋                     | 66/441 [01:08<06:28,  1.04s/it]

sfc-aqua_quisp:  15%|███▊                     | 67/441 [01:09<06:26,  1.03s/it]

sfc-aqua_quisp:  15%|███▊                     | 68/441 [01:10<06:24,  1.03s/it]

sfc-aqua_quisp:  16%|███▉                     | 69/441 [01:11<06:23,  1.03s/it]

sfc-aqua_quisp:  16%|███▉                     | 70/441 [01:12<06:23,  1.03s/it]

sfc-aqua_quisp:  16%|████                     | 71/441 [01:13<06:22,  1.03s/it]

sfc-aqua_quisp:  16%|████                     | 72/441 [01:14<06:21,  1.03s/it]

sfc-aqua_quisp:  17%|████▏                    | 73/441 [01:15<06:21,  1.04s/it]

sfc-aqua_quisp:  17%|████▏                    | 74/441 [01:16<06:20,  1.04s/it]

sfc-aqua_quisp:  17%|████▎                    | 75/441 [01:17<06:18,  1.04s/it]

sfc-aqua_quisp:  17%|████▎                    | 76/441 [01:18<06:17,  1.04s/it]

sfc-aqua_quisp:  17%|████▎                    | 77/441 [01:19<06:16,  1.04s/it]

sfc-aqua_quisp:  18%|████▍                    | 78/441 [01:20<06:15,  1.04s/it]

sfc-aqua_quisp:  18%|████▍                    | 79/441 [01:21<06:14,  1.03s/it]

sfc-aqua_quisp:  18%|████▌                    | 80/441 [01:22<06:13,  1.04s/it]

sfc-aqua_quisp:  18%|████▌                    | 81/441 [01:23<06:12,  1.04s/it]

sfc-aqua_quisp:  19%|████▋                    | 82/441 [01:24<06:11,  1.04s/it]

sfc-aqua_quisp:  19%|████▋                    | 83/441 [01:25<06:10,  1.03s/it]

sfc-aqua_quisp:  19%|████▊                    | 84/441 [01:26<06:09,  1.03s/it]

sfc-aqua_quisp:  19%|████▊                    | 85/441 [01:27<06:07,  1.03s/it]

sfc-aqua_quisp:  20%|████▉                    | 86/441 [01:28<06:06,  1.03s/it]

sfc-aqua_quisp:  20%|████▉                    | 87/441 [01:30<06:05,  1.03s/it]

sfc-aqua_quisp:  20%|████▉                    | 88/441 [01:31<06:04,  1.03s/it]

sfc-aqua_quisp:  20%|█████                    | 89/441 [01:32<06:04,  1.03s/it]

sfc-aqua_quisp:  20%|█████                    | 90/441 [01:33<06:03,  1.03s/it]

sfc-aqua_quisp:  21%|█████▏                   | 91/441 [01:34<06:02,  1.04s/it]

sfc-aqua_quisp:  21%|█████▏                   | 92/441 [01:35<06:01,  1.03s/it]

sfc-aqua_quisp:  21%|█████▎                   | 93/441 [01:36<05:59,  1.03s/it]

sfc-aqua_quisp:  21%|█████▎                   | 94/441 [01:37<05:59,  1.04s/it]

sfc-aqua_quisp:  22%|█████▍                   | 95/441 [01:38<05:58,  1.04s/it]

sfc-aqua_quisp:  22%|█████▍                   | 96/441 [01:39<05:57,  1.04s/it]

sfc-aqua_quisp:  22%|█████▍                   | 97/441 [01:40<05:55,  1.03s/it]

sfc-aqua_quisp:  22%|█████▌                   | 98/441 [01:41<05:55,  1.04s/it]

sfc-aqua_quisp:  22%|█████▌                   | 99/441 [01:42<05:55,  1.04s/it]

sfc-aqua_quisp:  23%|█████▍                  | 100/441 [01:43<05:54,  1.04s/it]

sfc-aqua_quisp:  23%|█████▍                  | 101/441 [01:44<05:52,  1.04s/it]

sfc-aqua_quisp:  23%|█████▌                  | 102/441 [01:45<05:51,  1.04s/it]

sfc-aqua_quisp:  23%|█████▌                  | 103/441 [01:46<05:50,  1.04s/it]

sfc-aqua_quisp:  24%|█████▋                  | 104/441 [01:47<05:49,  1.04s/it]

sfc-aqua_quisp:  24%|█████▋                  | 105/441 [01:48<05:47,  1.04s/it]

sfc-aqua_quisp:  24%|█████▊                  | 106/441 [01:49<05:46,  1.03s/it]

sfc-aqua_quisp:  24%|█████▊                  | 107/441 [01:50<05:45,  1.03s/it]

sfc-aqua_quisp:  24%|█████▉                  | 108/441 [01:51<05:44,  1.03s/it]

sfc-aqua_quisp:  25%|█████▉                  | 109/441 [01:52<05:43,  1.03s/it]

sfc-aqua_quisp:  25%|█████▉                  | 110/441 [01:53<05:41,  1.03s/it]

sfc-aqua_quisp:  25%|██████                  | 111/441 [01:54<05:46,  1.05s/it]

sfc-aqua_quisp:  25%|██████                  | 112/441 [01:56<06:15,  1.14s/it]

sfc-aqua_quisp:  26%|██████▏                 | 113/441 [01:57<06:05,  1.12s/it]

sfc-aqua_quisp:  26%|██████▏                 | 114/441 [01:58<05:59,  1.10s/it]

sfc-aqua_quisp:  26%|██████▎                 | 115/441 [01:59<05:51,  1.08s/it]

sfc-aqua_quisp:  26%|██████▎                 | 116/441 [02:00<05:46,  1.07s/it]

sfc-aqua_quisp:  27%|██████▎                 | 117/441 [02:01<05:42,  1.06s/it]

sfc-aqua_quisp:  27%|██████▍                 | 118/441 [02:02<05:39,  1.05s/it]

sfc-aqua_quisp:  27%|██████▍                 | 119/441 [02:03<05:37,  1.05s/it]

sfc-aqua_quisp:  27%|██████▌                 | 120/441 [02:04<05:35,  1.05s/it]

sfc-aqua_quisp:  27%|██████▌                 | 121/441 [02:05<05:32,  1.04s/it]

sfc-aqua_quisp:  28%|██████▋                 | 122/441 [02:06<05:31,  1.04s/it]

sfc-aqua_quisp:  28%|██████▋                 | 123/441 [02:07<05:30,  1.04s/it]

sfc-aqua_quisp:  28%|██████▋                 | 124/441 [02:08<05:28,  1.04s/it]

sfc-aqua_quisp:  28%|██████▊                 | 125/441 [02:09<05:27,  1.04s/it]

sfc-aqua_quisp:  29%|██████▊                 | 126/441 [02:10<05:26,  1.04s/it]

sfc-aqua_quisp:  29%|██████▉                 | 127/441 [02:11<05:24,  1.03s/it]

sfc-aqua_quisp:  29%|██████▉                 | 128/441 [02:12<05:23,  1.03s/it]

sfc-aqua_quisp:  29%|███████                 | 129/441 [02:13<05:23,  1.04s/it]

sfc-aqua_quisp:  29%|███████                 | 130/441 [02:14<05:22,  1.04s/it]

sfc-aqua_quisp:  30%|███████▏                | 131/441 [02:15<05:21,  1.04s/it]

sfc-aqua_quisp:  30%|███████▏                | 132/441 [02:17<05:19,  1.04s/it]

sfc-aqua_quisp:  30%|███████▏                | 133/441 [02:18<05:18,  1.04s/it]

sfc-aqua_quisp:  30%|███████▎                | 134/441 [02:19<05:17,  1.03s/it]

sfc-aqua_quisp:  31%|███████▎                | 135/441 [02:20<05:16,  1.03s/it]

sfc-aqua_quisp:  31%|███████▍                | 136/441 [02:21<05:15,  1.03s/it]

sfc-aqua_quisp:  31%|███████▍                | 137/441 [02:22<05:14,  1.03s/it]

sfc-aqua_quisp:  31%|███████▌                | 138/441 [02:23<05:13,  1.03s/it]

sfc-aqua_quisp:  32%|███████▌                | 139/441 [02:24<05:12,  1.04s/it]

sfc-aqua_quisp:  32%|███████▌                | 140/441 [02:25<05:11,  1.03s/it]

sfc-aqua_quisp:  32%|███████▋                | 141/441 [02:26<05:10,  1.03s/it]

sfc-aqua_quisp:  32%|███████▋                | 142/441 [02:27<05:09,  1.03s/it]

sfc-aqua_quisp:  32%|███████▊                | 143/441 [02:28<05:07,  1.03s/it]

sfc-aqua_quisp:  33%|███████▊                | 144/441 [02:29<05:06,  1.03s/it]

sfc-aqua_quisp:  33%|███████▉                | 145/441 [02:30<05:05,  1.03s/it]

sfc-aqua_quisp:  33%|███████▉                | 146/441 [02:31<05:05,  1.03s/it]

sfc-aqua_quisp:  33%|████████                | 147/441 [02:32<05:04,  1.03s/it]

sfc-aqua_quisp:  34%|████████                | 148/441 [02:33<05:03,  1.04s/it]

sfc-aqua_quisp:  34%|████████                | 149/441 [02:34<05:01,  1.03s/it]

sfc-aqua_quisp:  34%|████████▏               | 150/441 [02:35<05:01,  1.03s/it]

sfc-aqua_quisp:  34%|████████▏               | 151/441 [02:36<05:00,  1.04s/it]

sfc-aqua_quisp:  34%|████████▎               | 152/441 [02:37<04:59,  1.04s/it]

sfc-aqua_quisp:  35%|████████▎               | 153/441 [02:38<04:58,  1.04s/it]

sfc-aqua_quisp:  35%|████████▍               | 154/441 [02:39<04:57,  1.04s/it]

sfc-aqua_quisp:  35%|████████▍               | 155/441 [02:40<04:56,  1.04s/it]

sfc-aqua_quisp:  35%|████████▍               | 156/441 [02:41<04:55,  1.04s/it]

sfc-aqua_quisp:  36%|████████▌               | 157/441 [02:42<04:54,  1.04s/it]

sfc-aqua_quisp:  36%|████████▌               | 158/441 [02:43<04:53,  1.04s/it]

sfc-aqua_quisp:  36%|████████▋               | 159/441 [02:44<04:52,  1.04s/it]

sfc-aqua_quisp:  36%|████████▋               | 160/441 [02:45<04:50,  1.04s/it]

sfc-aqua_quisp:  37%|████████▊               | 161/441 [02:47<04:49,  1.03s/it]

sfc-aqua_quisp:  37%|████████▊               | 162/441 [02:48<04:48,  1.03s/it]

sfc-aqua_quisp:  37%|████████▊               | 163/441 [02:49<04:47,  1.03s/it]

sfc-aqua_quisp:  37%|████████▉               | 164/441 [02:50<04:46,  1.03s/it]

sfc-aqua_quisp:  37%|████████▉               | 165/441 [02:51<04:45,  1.04s/it]

sfc-aqua_quisp:  38%|█████████               | 166/441 [02:52<04:44,  1.03s/it]

sfc-aqua_quisp:  38%|█████████               | 167/441 [02:53<04:43,  1.03s/it]

sfc-aqua_quisp:  38%|█████████▏              | 168/441 [02:54<04:42,  1.03s/it]

sfc-aqua_quisp:  38%|█████████▏              | 169/441 [02:55<04:41,  1.03s/it]

sfc-aqua_quisp:  39%|█████████▎              | 170/441 [02:56<04:40,  1.04s/it]

sfc-aqua_quisp:  39%|█████████▎              | 171/441 [02:57<04:39,  1.03s/it]

sfc-aqua_quisp:  39%|█████████▎              | 172/441 [02:58<04:38,  1.03s/it]

sfc-aqua_quisp:  39%|█████████▍              | 173/441 [02:59<04:37,  1.03s/it]

sfc-aqua_quisp:  39%|█████████▍              | 174/441 [03:00<04:35,  1.03s/it]

sfc-aqua_quisp:  40%|█████████▌              | 175/441 [03:01<04:35,  1.03s/it]

sfc-aqua_quisp:  40%|█████████▌              | 176/441 [03:02<04:34,  1.04s/it]

sfc-aqua_quisp:  40%|█████████▋              | 177/441 [03:03<04:33,  1.04s/it]

sfc-aqua_quisp:  40%|█████████▋              | 178/441 [03:04<04:32,  1.03s/it]

sfc-aqua_quisp:  41%|█████████▋              | 179/441 [03:05<04:31,  1.04s/it]

sfc-aqua_quisp:  41%|█████████▊              | 180/441 [03:06<04:30,  1.04s/it]

sfc-aqua_quisp:  41%|█████████▊              | 181/441 [03:07<04:28,  1.03s/it]

sfc-aqua_quisp:  41%|█████████▉              | 182/441 [03:08<04:27,  1.03s/it]

sfc-aqua_quisp:  41%|█████████▉              | 183/441 [03:09<04:26,  1.03s/it]

sfc-aqua_quisp:  42%|██████████              | 184/441 [03:10<04:25,  1.03s/it]

sfc-aqua_quisp:  42%|██████████              | 185/441 [03:11<04:24,  1.03s/it]

sfc-aqua_quisp:  42%|██████████              | 186/441 [03:12<04:23,  1.03s/it]

sfc-aqua_quisp:  42%|██████████▏             | 187/441 [03:13<04:23,  1.04s/it]

sfc-aqua_quisp:  43%|██████████▏             | 188/441 [03:14<04:21,  1.04s/it]

sfc-aqua_quisp:  43%|██████████▎             | 189/441 [03:15<04:20,  1.04s/it]

sfc-aqua_quisp:  43%|██████████▎             | 190/441 [03:17<04:19,  1.03s/it]

sfc-aqua_quisp:  43%|██████████▍             | 191/441 [03:18<04:18,  1.03s/it]

sfc-aqua_quisp:  44%|██████████▍             | 192/441 [03:19<04:17,  1.03s/it]

sfc-aqua_quisp:  44%|██████████▌             | 193/441 [03:20<04:16,  1.03s/it]

sfc-aqua_quisp:  44%|██████████▌             | 194/441 [03:21<04:15,  1.04s/it]

sfc-aqua_quisp:  44%|██████████▌             | 195/441 [03:22<04:14,  1.04s/it]

sfc-aqua_quisp:  44%|██████████▋             | 196/441 [03:23<04:14,  1.04s/it]

sfc-aqua_quisp:  45%|██████████▋             | 197/441 [03:24<04:12,  1.04s/it]

sfc-aqua_quisp:  45%|██████████▊             | 198/441 [03:25<04:11,  1.04s/it]

sfc-aqua_quisp:  45%|██████████▊             | 199/441 [03:26<04:10,  1.04s/it]

sfc-aqua_quisp:  45%|██████████▉             | 200/441 [03:27<04:09,  1.03s/it]

sfc-aqua_quisp:  46%|██████████▉             | 201/441 [03:28<04:08,  1.04s/it]

sfc-aqua_quisp:  46%|██████████▉             | 202/441 [03:29<04:07,  1.04s/it]

sfc-aqua_quisp:  46%|███████████             | 203/441 [03:30<04:06,  1.04s/it]

sfc-aqua_quisp:  46%|███████████             | 204/441 [03:31<04:05,  1.04s/it]

sfc-aqua_quisp:  46%|███████████▏            | 205/441 [03:32<04:04,  1.04s/it]

sfc-aqua_quisp:  47%|███████████▏            | 206/441 [03:33<04:03,  1.04s/it]

sfc-aqua_quisp:  47%|███████████▎            | 207/441 [03:34<04:02,  1.04s/it]

sfc-aqua_quisp:  47%|███████████▎            | 208/441 [03:35<04:01,  1.04s/it]

sfc-aqua_quisp:  47%|███████████▎            | 209/441 [03:36<04:00,  1.04s/it]

sfc-aqua_quisp:  48%|███████████▍            | 210/441 [03:37<03:59,  1.04s/it]

sfc-aqua_quisp:  48%|███████████▍            | 211/441 [03:38<03:58,  1.04s/it]

sfc-aqua_quisp:  48%|███████████▌            | 212/441 [03:39<03:57,  1.04s/it]

sfc-aqua_quisp:  48%|███████████▌            | 213/441 [03:40<03:56,  1.04s/it]

sfc-aqua_quisp:  49%|███████████▋            | 214/441 [03:41<03:54,  1.04s/it]

sfc-aqua_quisp:  49%|███████████▋            | 215/441 [03:42<03:53,  1.04s/it]

sfc-aqua_quisp:  49%|███████████▊            | 216/441 [03:43<03:53,  1.04s/it]

sfc-aqua_quisp:  49%|███████████▊            | 217/441 [03:45<03:52,  1.04s/it]

sfc-aqua_quisp:  49%|███████████▊            | 218/441 [03:46<03:51,  1.04s/it]

sfc-aqua_quisp:  50%|███████████▉            | 219/441 [03:47<03:49,  1.04s/it]

sfc-aqua_quisp:  50%|███████████▉            | 220/441 [03:48<03:48,  1.03s/it]

sfc-aqua_quisp:  50%|████████████            | 221/441 [03:49<03:47,  1.03s/it]

sfc-aqua_quisp:  50%|████████████            | 222/441 [03:50<03:46,  1.03s/it]

sfc-aqua_quisp:  51%|████████████▏           | 223/441 [03:51<03:45,  1.03s/it]

sfc-aqua_quisp:  51%|████████████▏           | 224/441 [03:52<03:44,  1.03s/it]

sfc-aqua_quisp:  51%|████████████▏           | 225/441 [03:53<03:43,  1.03s/it]

sfc-aqua_quisp:  51%|████████████▎           | 226/441 [03:54<03:41,  1.03s/it]

sfc-aqua_quisp:  51%|████████████▎           | 227/441 [03:55<03:41,  1.03s/it]

sfc-aqua_quisp:  52%|████████████▍           | 228/441 [03:56<03:40,  1.03s/it]

sfc-aqua_quisp:  52%|████████████▍           | 229/441 [03:57<03:38,  1.03s/it]

sfc-aqua_quisp:  52%|████████████▌           | 230/441 [03:58<03:37,  1.03s/it]

sfc-aqua_quisp:  52%|████████████▌           | 231/441 [03:59<03:36,  1.03s/it]

sfc-aqua_quisp:  53%|████████████▋           | 232/441 [04:00<03:35,  1.03s/it]

sfc-aqua_quisp:  53%|████████████▋           | 233/441 [04:01<03:34,  1.03s/it]

sfc-aqua_quisp:  53%|████████████▋           | 234/441 [04:02<03:33,  1.03s/it]

sfc-aqua_quisp:  53%|████████████▊           | 235/441 [04:03<03:32,  1.03s/it]

sfc-aqua_quisp:  54%|████████████▊           | 236/441 [04:04<03:31,  1.03s/it]

sfc-aqua_quisp:  54%|████████████▉           | 237/441 [04:05<03:30,  1.03s/it]

sfc-aqua_quisp:  54%|████████████▉           | 238/441 [04:06<03:29,  1.03s/it]

sfc-aqua_quisp:  54%|█████████████           | 239/441 [04:07<03:28,  1.03s/it]

sfc-aqua_quisp:  54%|█████████████           | 240/441 [04:08<03:27,  1.03s/it]

sfc-aqua_quisp:  55%|█████████████           | 241/441 [04:09<03:26,  1.03s/it]

sfc-aqua_quisp:  55%|█████████████▏          | 242/441 [04:10<03:25,  1.03s/it]

sfc-aqua_quisp:  55%|█████████████▏          | 243/441 [04:11<03:24,  1.03s/it]

sfc-aqua_quisp:  55%|█████████████▎          | 244/441 [04:12<03:28,  1.06s/it]

sfc-aqua_quisp:  56%|█████████████▎          | 245/441 [04:13<03:25,  1.05s/it]

sfc-aqua_quisp:  56%|█████████████▍          | 246/441 [04:15<03:23,  1.04s/it]

sfc-aqua_quisp:  56%|█████████████▍          | 247/441 [04:16<03:21,  1.04s/it]

sfc-aqua_quisp:  56%|█████████████▍          | 248/441 [04:17<03:20,  1.04s/it]

sfc-aqua_quisp:  56%|█████████████▌          | 249/441 [04:18<03:18,  1.03s/it]

sfc-aqua_quisp:  57%|█████████████▌          | 250/441 [04:19<03:17,  1.03s/it]

sfc-aqua_quisp:  57%|█████████████▋          | 251/441 [04:20<03:16,  1.03s/it]

sfc-aqua_quisp:  57%|█████████████▋          | 252/441 [04:21<03:15,  1.03s/it]

sfc-aqua_quisp:  57%|█████████████▊          | 253/441 [04:22<03:14,  1.03s/it]

sfc-aqua_quisp:  58%|█████████████▊          | 254/441 [04:23<03:13,  1.03s/it]

sfc-aqua_quisp:  58%|█████████████▉          | 255/441 [04:24<03:12,  1.04s/it]

sfc-aqua_quisp:  58%|█████████████▉          | 256/441 [04:25<03:11,  1.04s/it]

sfc-aqua_quisp:  58%|█████████████▉          | 257/441 [04:26<03:10,  1.03s/it]

sfc-aqua_quisp:  59%|██████████████          | 258/441 [04:27<03:09,  1.03s/it]

sfc-aqua_quisp:  59%|██████████████          | 259/441 [04:28<03:07,  1.03s/it]

sfc-aqua_quisp:  59%|██████████████▏         | 260/441 [04:29<03:06,  1.03s/it]

sfc-aqua_quisp:  59%|██████████████▏         | 261/441 [04:30<03:05,  1.03s/it]

sfc-aqua_quisp:  59%|██████████████▎         | 262/441 [04:31<03:04,  1.03s/it]

sfc-aqua_quisp:  60%|██████████████▎         | 263/441 [04:32<03:03,  1.03s/it]

sfc-aqua_quisp:  60%|██████████████▎         | 264/441 [04:33<03:02,  1.03s/it]

sfc-aqua_quisp:  60%|██████████████▍         | 265/441 [04:34<03:01,  1.03s/it]

sfc-aqua_quisp:  60%|██████████████▍         | 266/441 [04:35<03:01,  1.04s/it]

sfc-aqua_quisp:  61%|██████████████▌         | 267/441 [04:36<03:00,  1.03s/it]

sfc-aqua_quisp:  61%|██████████████▌         | 268/441 [04:37<02:58,  1.03s/it]

sfc-aqua_quisp:  61%|██████████████▋         | 269/441 [04:38<02:57,  1.03s/it]

sfc-aqua_quisp:  61%|██████████████▋         | 270/441 [04:39<02:56,  1.03s/it]

sfc-aqua_quisp:  61%|██████████████▋         | 271/441 [04:40<02:55,  1.03s/it]

sfc-aqua_quisp:  62%|██████████████▊         | 272/441 [04:41<02:54,  1.03s/it]

sfc-aqua_quisp:  62%|██████████████▊         | 273/441 [04:42<02:53,  1.03s/it]

sfc-aqua_quisp:  62%|██████████████▉         | 274/441 [04:43<02:52,  1.03s/it]

sfc-aqua_quisp:  62%|██████████████▉         | 275/441 [04:44<02:51,  1.03s/it]

sfc-aqua_quisp:  63%|███████████████         | 276/441 [04:46<02:50,  1.03s/it]

sfc-aqua_quisp:  63%|███████████████         | 277/441 [04:47<02:49,  1.03s/it]

sfc-aqua_quisp:  63%|███████████████▏        | 278/441 [04:48<02:48,  1.03s/it]

sfc-aqua_quisp:  63%|███████████████▏        | 279/441 [04:49<02:47,  1.03s/it]

sfc-aqua_quisp:  63%|███████████████▏        | 280/441 [04:50<02:46,  1.03s/it]

sfc-aqua_quisp:  64%|███████████████▎        | 281/441 [04:51<02:45,  1.03s/it]

sfc-aqua_quisp:  64%|███████████████▎        | 282/441 [04:52<02:44,  1.03s/it]

sfc-aqua_quisp:  64%|███████████████▍        | 283/441 [04:53<02:43,  1.03s/it]

sfc-aqua_quisp:  64%|███████████████▍        | 284/441 [04:54<02:41,  1.03s/it]

sfc-aqua_quisp:  65%|███████████████▌        | 285/441 [04:55<02:40,  1.03s/it]

sfc-aqua_quisp:  65%|███████████████▌        | 286/441 [04:56<02:39,  1.03s/it]

sfc-aqua_quisp:  65%|███████████████▌        | 287/441 [04:57<02:38,  1.03s/it]

sfc-aqua_quisp:  65%|███████████████▋        | 288/441 [04:58<02:37,  1.03s/it]

sfc-aqua_quisp:  66%|███████████████▋        | 289/441 [04:59<02:36,  1.03s/it]

sfc-aqua_quisp:  66%|███████████████▊        | 290/441 [05:00<02:35,  1.03s/it]

sfc-aqua_quisp:  66%|███████████████▊        | 291/441 [05:01<02:34,  1.03s/it]

sfc-aqua_quisp:  66%|███████████████▉        | 292/441 [05:02<02:34,  1.03s/it]

sfc-aqua_quisp:  66%|███████████████▉        | 293/441 [05:03<02:32,  1.03s/it]

sfc-aqua_quisp:  67%|████████████████        | 294/441 [05:04<02:31,  1.03s/it]

sfc-aqua_quisp:  67%|████████████████        | 295/441 [05:05<02:30,  1.03s/it]

sfc-aqua_quisp:  67%|████████████████        | 296/441 [05:06<02:29,  1.03s/it]

sfc-aqua_quisp:  67%|████████████████▏       | 297/441 [05:07<02:28,  1.03s/it]

sfc-aqua_quisp:  68%|████████████████▏       | 298/441 [05:08<02:28,  1.04s/it]

sfc-aqua_quisp:  68%|████████████████▎       | 299/441 [05:09<02:27,  1.04s/it]

sfc-aqua_quisp:  68%|████████████████▎       | 300/441 [05:10<02:25,  1.03s/it]

sfc-aqua_quisp:  68%|████████████████▍       | 301/441 [05:11<02:24,  1.03s/it]

sfc-aqua_quisp:  68%|████████████████▍       | 302/441 [05:12<02:23,  1.03s/it]

sfc-aqua_quisp:  69%|████████████████▍       | 303/441 [05:13<02:22,  1.03s/it]

sfc-aqua_quisp:  69%|████████████████▌       | 304/441 [05:14<02:21,  1.04s/it]

sfc-aqua_quisp:  69%|████████████████▌       | 305/441 [05:15<02:20,  1.03s/it]

sfc-aqua_quisp:  69%|████████████████▋       | 306/441 [05:17<02:19,  1.03s/it]

sfc-aqua_quisp:  70%|████████████████▋       | 307/441 [05:18<02:18,  1.03s/it]

sfc-aqua_quisp:  70%|████████████████▊       | 308/441 [05:19<02:17,  1.03s/it]

sfc-aqua_quisp:  70%|████████████████▊       | 309/441 [05:20<02:16,  1.03s/it]

sfc-aqua_quisp:  70%|████████████████▊       | 310/441 [05:21<02:15,  1.03s/it]

sfc-aqua_quisp:  71%|████████████████▉       | 311/441 [05:22<02:14,  1.03s/it]

sfc-aqua_quisp:  71%|████████████████▉       | 312/441 [05:23<02:13,  1.03s/it]

sfc-aqua_quisp:  71%|█████████████████       | 313/441 [05:24<02:12,  1.03s/it]

sfc-aqua_quisp:  71%|█████████████████       | 314/441 [05:25<02:11,  1.03s/it]

sfc-aqua_quisp:  71%|█████████████████▏      | 315/441 [05:26<02:10,  1.03s/it]

sfc-aqua_quisp:  72%|█████████████████▏      | 316/441 [05:27<02:09,  1.03s/it]

sfc-aqua_quisp:  72%|█████████████████▎      | 317/441 [05:28<02:07,  1.03s/it]

sfc-aqua_quisp:  72%|█████████████████▎      | 318/441 [05:29<02:06,  1.03s/it]

sfc-aqua_quisp:  72%|█████████████████▎      | 319/441 [05:30<02:05,  1.03s/it]

sfc-aqua_quisp:  73%|█████████████████▍      | 320/441 [05:31<02:05,  1.04s/it]

sfc-aqua_quisp:  73%|█████████████████▍      | 321/441 [05:32<02:04,  1.03s/it]

sfc-aqua_quisp:  73%|█████████████████▌      | 322/441 [05:33<02:03,  1.03s/it]

sfc-aqua_quisp:  73%|█████████████████▌      | 323/441 [05:34<02:01,  1.03s/it]

sfc-aqua_quisp:  73%|█████████████████▋      | 324/441 [05:35<02:00,  1.03s/it]

sfc-aqua_quisp:  74%|█████████████████▋      | 325/441 [05:36<01:59,  1.03s/it]

sfc-aqua_quisp:  74%|█████████████████▋      | 326/441 [05:37<01:58,  1.03s/it]

sfc-aqua_quisp:  74%|█████████████████▊      | 327/441 [05:38<01:58,  1.04s/it]

sfc-aqua_quisp:  74%|█████████████████▊      | 328/441 [05:39<01:57,  1.04s/it]

sfc-aqua_quisp:  75%|█████████████████▉      | 329/441 [05:40<01:55,  1.03s/it]

sfc-aqua_quisp:  75%|█████████████████▉      | 330/441 [05:41<01:54,  1.03s/it]

sfc-aqua_quisp:  75%|██████████████████      | 331/441 [05:42<01:53,  1.03s/it]

sfc-aqua_quisp:  75%|██████████████████      | 332/441 [05:43<01:52,  1.04s/it]

sfc-aqua_quisp:  76%|██████████████████      | 333/441 [05:44<01:51,  1.03s/it]

sfc-aqua_quisp:  76%|██████████████████▏     | 334/441 [05:45<01:50,  1.03s/it]

sfc-aqua_quisp:  76%|██████████████████▏     | 335/441 [05:46<01:49,  1.03s/it]

sfc-aqua_quisp:  76%|██████████████████▎     | 336/441 [05:47<01:48,  1.03s/it]

sfc-aqua_quisp:  76%|██████████████████▎     | 337/441 [05:49<01:47,  1.03s/it]

sfc-aqua_quisp:  77%|██████████████████▍     | 338/441 [05:50<01:46,  1.03s/it]

sfc-aqua_quisp:  77%|██████████████████▍     | 339/441 [05:51<01:45,  1.03s/it]

sfc-aqua_quisp:  77%|██████████████████▌     | 340/441 [05:52<01:44,  1.03s/it]

sfc-aqua_quisp:  77%|██████████████████▌     | 341/441 [05:53<01:43,  1.03s/it]

sfc-aqua_quisp:  78%|██████████████████▌     | 342/441 [05:54<01:42,  1.03s/it]

sfc-aqua_quisp:  78%|██████████████████▋     | 343/441 [05:55<01:41,  1.03s/it]

sfc-aqua_quisp:  78%|██████████████████▋     | 344/441 [05:56<01:40,  1.03s/it]

sfc-aqua_quisp:  78%|██████████████████▊     | 345/441 [05:57<01:39,  1.03s/it]

sfc-aqua_quisp:  78%|██████████████████▊     | 346/441 [05:58<01:38,  1.04s/it]

sfc-aqua_quisp:  79%|██████████████████▉     | 347/441 [05:59<01:37,  1.04s/it]

sfc-aqua_quisp:  79%|██████████████████▉     | 348/441 [06:00<01:36,  1.03s/it]

sfc-aqua_quisp:  79%|██████████████████▉     | 349/441 [06:01<01:35,  1.03s/it]

sfc-aqua_quisp:  79%|███████████████████     | 350/441 [06:02<01:34,  1.03s/it]

sfc-aqua_quisp:  80%|███████████████████     | 351/441 [06:03<01:33,  1.04s/it]

sfc-aqua_quisp:  80%|███████████████████▏    | 352/441 [06:04<01:32,  1.04s/it]

sfc-aqua_quisp:  80%|███████████████████▏    | 353/441 [06:05<01:31,  1.04s/it]

sfc-aqua_quisp:  80%|███████████████████▎    | 354/441 [06:06<01:29,  1.03s/it]

sfc-aqua_quisp:  80%|███████████████████▎    | 355/441 [06:07<01:28,  1.03s/it]

sfc-aqua_quisp:  81%|███████████████████▎    | 356/441 [06:08<01:27,  1.03s/it]

sfc-aqua_quisp:  81%|███████████████████▍    | 357/441 [06:09<01:26,  1.03s/it]

sfc-aqua_quisp:  81%|███████████████████▍    | 358/441 [06:10<01:25,  1.03s/it]

sfc-aqua_quisp:  81%|███████████████████▌    | 359/441 [06:11<01:24,  1.03s/it]

sfc-aqua_quisp:  82%|███████████████████▌    | 360/441 [06:12<01:23,  1.03s/it]

sfc-aqua_quisp:  82%|███████████████████▋    | 361/441 [06:13<01:22,  1.03s/it]

sfc-aqua_quisp:  82%|███████████████████▋    | 362/441 [06:14<01:21,  1.03s/it]

sfc-aqua_quisp:  82%|███████████████████▊    | 363/441 [06:15<01:20,  1.03s/it]

sfc-aqua_quisp:  83%|███████████████████▊    | 364/441 [06:16<01:19,  1.03s/it]

sfc-aqua_quisp:  83%|███████████████████▊    | 365/441 [06:17<01:18,  1.03s/it]

sfc-aqua_quisp:  83%|███████████████████▉    | 366/441 [06:19<01:17,  1.03s/it]

sfc-aqua_quisp:  83%|███████████████████▉    | 367/441 [06:20<01:16,  1.03s/it]

sfc-aqua_quisp:  83%|████████████████████    | 368/441 [06:21<01:15,  1.03s/it]

sfc-aqua_quisp:  84%|████████████████████    | 369/441 [06:22<01:14,  1.03s/it]

sfc-aqua_quisp:  84%|████████████████████▏   | 370/441 [06:23<01:13,  1.03s/it]

sfc-aqua_quisp:  84%|████████████████████▏   | 371/441 [06:24<01:12,  1.03s/it]

sfc-aqua_quisp:  84%|████████████████████▏   | 372/441 [06:25<01:11,  1.03s/it]

sfc-aqua_quisp:  85%|████████████████████▎   | 373/441 [06:26<01:10,  1.03s/it]

sfc-aqua_quisp:  85%|████████████████████▎   | 374/441 [06:27<01:09,  1.03s/it]

sfc-aqua_quisp:  85%|████████████████████▍   | 375/441 [06:28<01:08,  1.03s/it]

sfc-aqua_quisp:  85%|████████████████████▍   | 376/441 [06:29<01:07,  1.03s/it]

sfc-aqua_quisp:  85%|████████████████████▌   | 377/441 [06:30<01:06,  1.03s/it]

sfc-aqua_quisp:  86%|████████████████████▌   | 378/441 [06:31<01:04,  1.03s/it]

sfc-aqua_quisp:  86%|████████████████████▋   | 379/441 [06:32<01:03,  1.03s/it]

sfc-aqua_quisp:  86%|████████████████████▋   | 380/441 [06:33<01:02,  1.03s/it]

sfc-aqua_quisp:  86%|████████████████████▋   | 381/441 [06:34<01:01,  1.03s/it]

sfc-aqua_quisp:  87%|████████████████████▊   | 382/441 [06:35<01:00,  1.03s/it]

sfc-aqua_quisp:  87%|████████████████████▊   | 383/441 [06:36<00:59,  1.03s/it]

sfc-aqua_quisp:  87%|████████████████████▉   | 384/441 [06:37<00:59,  1.04s/it]

sfc-aqua_quisp:  87%|████████████████████▉   | 385/441 [06:38<00:57,  1.03s/it]

sfc-aqua_quisp:  88%|█████████████████████   | 386/441 [06:39<00:56,  1.03s/it]

sfc-aqua_quisp:  88%|█████████████████████   | 387/441 [06:40<00:55,  1.03s/it]

sfc-aqua_quisp:  88%|█████████████████████   | 388/441 [06:41<00:54,  1.03s/it]

sfc-aqua_quisp:  88%|█████████████████████▏  | 389/441 [06:42<00:53,  1.03s/it]

sfc-aqua_quisp:  88%|█████████████████████▏  | 390/441 [06:43<00:52,  1.03s/it]

sfc-aqua_quisp:  89%|█████████████████████▎  | 391/441 [06:44<00:51,  1.03s/it]

sfc-aqua_quisp:  89%|█████████████████████▎  | 392/441 [06:45<00:50,  1.03s/it]

sfc-aqua_quisp:  89%|█████████████████████▍  | 393/441 [06:46<00:49,  1.03s/it]

sfc-aqua_quisp:  89%|█████████████████████▍  | 394/441 [06:47<00:48,  1.03s/it]

sfc-aqua_quisp:  90%|█████████████████████▍  | 395/441 [06:48<00:47,  1.03s/it]

sfc-aqua_quisp:  90%|█████████████████████▌  | 396/441 [06:49<00:46,  1.03s/it]

sfc-aqua_quisp:  90%|█████████████████████▌  | 397/441 [06:51<00:45,  1.03s/it]

sfc-aqua_quisp:  90%|█████████████████████▋  | 398/441 [06:52<00:44,  1.03s/it]

sfc-aqua_quisp:  90%|█████████████████████▋  | 399/441 [06:53<00:43,  1.03s/it]

sfc-aqua_quisp:  91%|█████████████████████▊  | 400/441 [06:54<00:42,  1.03s/it]

sfc-aqua_quisp:  91%|█████████████████████▊  | 401/441 [06:55<00:41,  1.03s/it]

sfc-aqua_quisp:  91%|█████████████████████▉  | 402/441 [06:56<00:40,  1.03s/it]

sfc-aqua_quisp:  91%|█████████████████████▉  | 403/441 [06:57<00:39,  1.03s/it]

sfc-aqua_quisp:  92%|█████████████████████▉  | 404/441 [06:58<00:38,  1.03s/it]

sfc-aqua_quisp:  92%|██████████████████████  | 405/441 [06:59<00:38,  1.07s/it]

sfc-aqua_quisp:  92%|██████████████████████  | 406/441 [07:00<00:37,  1.06s/it]

sfc-aqua_quisp:  92%|██████████████████████▏ | 407/441 [07:01<00:35,  1.06s/it]

sfc-aqua_quisp:  93%|██████████████████████▏ | 408/441 [07:02<00:34,  1.05s/it]

sfc-aqua_quisp:  93%|██████████████████████▎ | 409/441 [07:03<00:33,  1.04s/it]

sfc-aqua_quisp:  93%|██████████████████████▎ | 410/441 [07:04<00:32,  1.04s/it]

sfc-aqua_quisp:  93%|██████████████████████▎ | 411/441 [07:05<00:31,  1.04s/it]

sfc-aqua_quisp:  93%|██████████████████████▍ | 412/441 [07:06<00:29,  1.03s/it]

sfc-aqua_quisp:  94%|██████████████████████▍ | 413/441 [07:07<00:28,  1.03s/it]

sfc-aqua_quisp:  94%|██████████████████████▌ | 414/441 [07:08<00:27,  1.03s/it]

sfc-aqua_quisp:  94%|██████████████████████▌ | 415/441 [07:09<00:26,  1.03s/it]

sfc-aqua_quisp:  94%|██████████████████████▋ | 416/441 [07:10<00:25,  1.03s/it]

sfc-aqua_quisp:  95%|██████████████████████▋ | 417/441 [07:11<00:24,  1.03s/it]

sfc-aqua_quisp:  95%|██████████████████████▋ | 418/441 [07:12<00:23,  1.03s/it]

sfc-aqua_quisp:  95%|██████████████████████▊ | 419/441 [07:13<00:22,  1.03s/it]

sfc-aqua_quisp:  95%|██████████████████████▊ | 420/441 [07:14<00:21,  1.03s/it]

sfc-aqua_quisp:  95%|██████████████████████▉ | 421/441 [07:15<00:20,  1.03s/it]

sfc-aqua_quisp:  96%|██████████████████████▉ | 422/441 [07:16<00:19,  1.03s/it]

sfc-aqua_quisp:  96%|███████████████████████ | 423/441 [07:17<00:18,  1.03s/it]

sfc-aqua_quisp:  96%|███████████████████████ | 424/441 [07:19<00:17,  1.03s/it]

sfc-aqua_quisp:  96%|███████████████████████▏| 425/441 [07:20<00:16,  1.03s/it]

sfc-aqua_quisp:  97%|███████████████████████▏| 426/441 [07:21<00:15,  1.03s/it]

sfc-aqua_quisp:  97%|███████████████████████▏| 427/441 [07:22<00:14,  1.03s/it]

sfc-aqua_quisp:  97%|███████████████████████▎| 428/441 [07:23<00:13,  1.03s/it]

sfc-aqua_quisp:  97%|███████████████████████▎| 429/441 [07:24<00:12,  1.03s/it]

sfc-aqua_quisp:  98%|███████████████████████▍| 430/441 [07:25<00:11,  1.03s/it]

sfc-aqua_quisp:  98%|███████████████████████▍| 431/441 [07:26<00:10,  1.03s/it]

sfc-aqua_quisp:  98%|███████████████████████▌| 432/441 [07:27<00:09,  1.03s/it]

sfc-aqua_quisp:  98%|███████████████████████▌| 433/441 [07:28<00:08,  1.03s/it]

sfc-aqua_quisp:  98%|███████████████████████▌| 434/441 [07:29<00:07,  1.03s/it]

sfc-aqua_quisp:  99%|███████████████████████▋| 435/441 [07:30<00:06,  1.03s/it]

sfc-aqua_quisp:  99%|███████████████████████▋| 436/441 [07:31<00:05,  1.03s/it]

sfc-aqua_quisp:  99%|███████████████████████▊| 437/441 [07:32<00:04,  1.03s/it]

sfc-aqua_quisp:  99%|███████████████████████▊| 438/441 [07:33<00:03,  1.03s/it]

sfc-aqua_quisp: 100%|███████████████████████▉| 439/441 [07:34<00:02,  1.03s/it]

sfc-aqua_quisp: 100%|███████████████████████▉| 440/441 [07:35<00:01,  1.03s/it]

sfc-aqua_quisp: 100%|████████████████████████| 441/441 [07:36<00:00,  1.03s/it]

sfc-aqua_quisp: 100%|████████████████████████| 441/441 [07:36<00:00,  1.04s/it]

stan-dev_rstanarm -> 4159 commit sha1s

stan-dev_rstanarm:   0%|                               | 0/416 [00:00<?, ?it/s]

stan-dev_rstanarm:   0%|                       | 1/416 [00:01<07:05,  1.02s/it]

stan-dev_rstanarm:   0%|                       | 2/416 [00:02<07:03,  1.02s/it]

stan-dev_rstanarm:   1%|▏                      | 3/416 [00:03<07:04,  1.03s/it]

stan-dev_rstanarm:   1%|▏                      | 4/416 [00:04<07:03,  1.03s/it]

stan-dev_rstanarm:   1%|▎                      | 5/416 [00:05<07:02,  1.03s/it]

stan-dev_rstanarm:   1%|▎                      | 6/416 [00:06<07:01,  1.03s/it]

stan-dev_rstanarm:   2%|▍                      | 7/416 [00:07<07:00,  1.03s/it]

stan-dev_rstanarm:   2%|▍                      | 8/416 [00:08<06:59,  1.03s/it]

stan-dev_rstanarm:   2%|▍                      | 9/416 [00:09<06:57,  1.03s/it]

stan-dev_rstanarm:   2%|▌                     | 10/416 [00:10<06:56,  1.03s/it]

stan-dev_rstanarm:   3%|▌                     | 11/416 [00:11<06:55,  1.03s/it]

stan-dev_rstanarm:   3%|▋                     | 12/416 [00:12<06:55,  1.03s/it]

stan-dev_rstanarm:   3%|▋                     | 13/416 [00:13<06:54,  1.03s/it]

stan-dev_rstanarm:   3%|▋                     | 14/416 [00:14<06:53,  1.03s/it]

stan-dev_rstanarm:   4%|▊                     | 15/416 [00:15<06:52,  1.03s/it]

stan-dev_rstanarm:   4%|▊                     | 16/416 [00:16<06:51,  1.03s/it]

stan-dev_rstanarm:   4%|▉                     | 17/416 [00:17<06:50,  1.03s/it]

stan-dev_rstanarm:   4%|▉                     | 18/416 [00:18<06:49,  1.03s/it]

stan-dev_rstanarm:   5%|█                     | 19/416 [00:19<06:48,  1.03s/it]

stan-dev_rstanarm:   5%|█                     | 20/416 [00:20<06:47,  1.03s/it]

stan-dev_rstanarm:   5%|█                     | 21/416 [00:21<06:46,  1.03s/it]

stan-dev_rstanarm:   5%|█▏                    | 22/416 [00:22<06:44,  1.03s/it]

stan-dev_rstanarm:   6%|█▏                    | 23/416 [00:23<06:43,  1.03s/it]

stan-dev_rstanarm:   6%|█▎                    | 24/416 [00:24<06:42,  1.03s/it]

stan-dev_rstanarm:   6%|█▎                    | 25/416 [00:25<06:42,  1.03s/it]

stan-dev_rstanarm:   6%|█▍                    | 26/416 [00:26<06:41,  1.03s/it]

stan-dev_rstanarm:   6%|█▍                    | 27/416 [00:27<06:40,  1.03s/it]

stan-dev_rstanarm:   7%|█▍                    | 28/416 [00:28<06:39,  1.03s/it]

stan-dev_rstanarm:   7%|█▌                    | 29/416 [00:29<06:38,  1.03s/it]

stan-dev_rstanarm:   7%|█▌                    | 30/416 [00:30<06:37,  1.03s/it]

stan-dev_rstanarm:   7%|█▋                    | 31/416 [00:31<06:37,  1.03s/it]

stan-dev_rstanarm:   8%|█▋                    | 32/416 [00:32<06:35,  1.03s/it]

stan-dev_rstanarm:   8%|█▋                    | 33/416 [00:33<06:34,  1.03s/it]

stan-dev_rstanarm:   8%|█▊                    | 34/416 [00:34<06:33,  1.03s/it]

stan-dev_rstanarm:   8%|█▊                    | 35/416 [00:36<06:31,  1.03s/it]

stan-dev_rstanarm:   9%|█▉                    | 36/416 [00:37<06:31,  1.03s/it]

stan-dev_rstanarm:   9%|█▉                    | 37/416 [00:38<06:29,  1.03s/it]

stan-dev_rstanarm:   9%|██                    | 38/416 [00:39<06:28,  1.03s/it]

stan-dev_rstanarm:   9%|██                    | 39/416 [00:40<06:27,  1.03s/it]

stan-dev_rstanarm:  10%|██                    | 40/416 [00:41<06:26,  1.03s/it]

stan-dev_rstanarm:  10%|██▏                   | 41/416 [00:42<06:24,  1.03s/it]

stan-dev_rstanarm:  10%|██▏                   | 42/416 [00:43<06:24,  1.03s/it]

stan-dev_rstanarm:  10%|██▎                   | 43/416 [00:44<06:23,  1.03s/it]

stan-dev_rstanarm:  11%|██▎                   | 44/416 [00:45<06:22,  1.03s/it]

stan-dev_rstanarm:  11%|██▍                   | 45/416 [00:46<06:21,  1.03s/it]

stan-dev_rstanarm:  11%|██▍                   | 46/416 [00:47<06:20,  1.03s/it]

stan-dev_rstanarm:  11%|██▍                   | 47/416 [00:48<06:19,  1.03s/it]

stan-dev_rstanarm:  12%|██▌                   | 48/416 [00:49<06:18,  1.03s/it]

stan-dev_rstanarm:  12%|██▌                   | 49/416 [00:50<06:17,  1.03s/it]

stan-dev_rstanarm:  12%|██▋                   | 50/416 [00:51<06:16,  1.03s/it]

stan-dev_rstanarm:  12%|██▋                   | 51/416 [00:52<06:15,  1.03s/it]

stan-dev_rstanarm:  12%|██▊                   | 52/416 [00:53<06:14,  1.03s/it]

stan-dev_rstanarm:  13%|██▊                   | 53/416 [00:54<06:13,  1.03s/it]

stan-dev_rstanarm:  13%|██▊                   | 54/416 [00:55<06:12,  1.03s/it]

stan-dev_rstanarm:  13%|██▉                   | 55/416 [00:56<06:11,  1.03s/it]

stan-dev_rstanarm:  13%|██▉                   | 56/416 [00:57<06:11,  1.03s/it]

stan-dev_rstanarm:  14%|███                   | 57/416 [00:58<06:10,  1.03s/it]

stan-dev_rstanarm:  14%|███                   | 58/416 [00:59<06:09,  1.03s/it]

stan-dev_rstanarm:  14%|███                   | 59/416 [01:00<06:07,  1.03s/it]

  errors: {'243cccbaf2b10084de13ac380b35ccec26dd5e24': 'Key 243cccbaf2b10084de13ac380b35ccec26dd5e24 not found in /da5_fast/All.sha1c/commit_36.tch'}

stan-dev_rstanarm:  14%|███▏                  | 60/416 [01:01<06:06,  1.03s/it]

stan-dev_rstanarm:  15%|███▏                  | 61/416 [01:02<06:04,  1.03s/it]

  errors: {'254418e8bf050a78cec28acd0f245e42fa8fe479': 'Key 254418e8bf050a78cec28acd0f245e42fa8fe479 not found in /da5_fast/All.sha1c/commit_37.tch'}

stan-dev_rstanarm:  15%|███▎                  | 62/416 [01:03<06:04,  1.03s/it]

stan-dev_rstanarm:  15%|███▎                  | 63/416 [01:04<06:02,  1.03s/it]

stan-dev_rstanarm:  15%|███▍                  | 64/416 [01:05<06:01,  1.03s/it]

stan-dev_rstanarm:  16%|███▍                  | 65/416 [01:06<06:01,  1.03s/it]

stan-dev_rstanarm:  16%|███▍                  | 66/416 [01:07<06:00,  1.03s/it]

stan-dev_rstanarm:  16%|███▌                  | 67/416 [01:08<05:58,  1.03s/it]

stan-dev_rstanarm:  16%|███▌                  | 68/416 [01:09<05:57,  1.03s/it]

stan-dev_rstanarm:  17%|███▋                  | 69/416 [01:10<05:56,  1.03s/it]

stan-dev_rstanarm:  17%|███▋                  | 70/416 [01:12<05:56,  1.03s/it]

stan-dev_rstanarm:  17%|███▊                  | 71/416 [01:13<05:56,  1.03s/it]

stan-dev_rstanarm:  17%|███▊                  | 72/416 [01:14<05:55,  1.03s/it]

  errors: {'2bfb69f5349a3a3a4891f6f4dc509c3fe0889117': 'Key 2bfb69f5349a3a3a4891f6f4dc509c3fe0889117 not found in /da5_fast/All.sha1c/commit_43.tch'}

stan-dev_rstanarm:  18%|███▊                  | 73/416 [01:15<05:53,  1.03s/it]

stan-dev_rstanarm:  18%|███▉                  | 74/416 [01:16<05:52,  1.03s/it]

stan-dev_rstanarm:  18%|███▉                  | 75/416 [01:17<05:51,  1.03s/it]

stan-dev_rstanarm:  18%|████                  | 76/416 [01:18<05:50,  1.03s/it]

stan-dev_rstanarm:  19%|████                  | 77/416 [01:19<05:49,  1.03s/it]

stan-dev_rstanarm:  19%|████▏                 | 78/416 [01:20<05:48,  1.03s/it]

stan-dev_rstanarm:  19%|████▏                 | 79/416 [01:21<05:47,  1.03s/it]

stan-dev_rstanarm:  19%|████▏                 | 80/416 [01:22<05:46,  1.03s/it]

stan-dev_rstanarm:  19%|████▎                 | 81/416 [01:23<05:45,  1.03s/it]

stan-dev_rstanarm:  20%|████▎                 | 82/416 [01:24<05:43,  1.03s/it]

stan-dev_rstanarm:  20%|████▍                 | 83/416 [01:25<05:42,  1.03s/it]

stan-dev_rstanarm:  20%|████▍                 | 84/416 [01:26<05:41,  1.03s/it]

stan-dev_rstanarm:  20%|████▍                 | 85/416 [01:27<05:40,  1.03s/it]

stan-dev_rstanarm:  21%|████▌                 | 86/416 [01:28<05:39,  1.03s/it]

stan-dev_rstanarm:  21%|████▌                 | 87/416 [01:29<05:38,  1.03s/it]

stan-dev_rstanarm:  21%|████▋                 | 88/416 [01:30<05:37,  1.03s/it]

stan-dev_rstanarm:  21%|████▋                 | 89/416 [01:31<05:36,  1.03s/it]

stan-dev_rstanarm:  22%|████▊                 | 90/416 [01:32<05:36,  1.03s/it]

stan-dev_rstanarm:  22%|████▊                 | 91/416 [01:33<05:34,  1.03s/it]

stan-dev_rstanarm:  22%|████▊                 | 92/416 [01:34<05:33,  1.03s/it]

stan-dev_rstanarm:  22%|████▉                 | 93/416 [01:35<05:32,  1.03s/it]

stan-dev_rstanarm:  23%|████▉                 | 94/416 [01:36<05:31,  1.03s/it]

stan-dev_rstanarm:  23%|█████                 | 95/416 [01:37<05:31,  1.03s/it]

stan-dev_rstanarm:  23%|█████                 | 96/416 [01:38<05:29,  1.03s/it]

stan-dev_rstanarm:  23%|█████▏                | 97/416 [01:39<05:28,  1.03s/it]

stan-dev_rstanarm:  24%|█████▏                | 98/416 [01:40<05:27,  1.03s/it]

stan-dev_rstanarm:  24%|█████▏                | 99/416 [01:41<05:26,  1.03s/it]

stan-dev_rstanarm:  24%|█████                | 100/416 [01:42<05:25,  1.03s/it]

stan-dev_rstanarm:  24%|█████                | 101/416 [01:43<05:24,  1.03s/it]

stan-dev_rstanarm:  25%|█████▏               | 102/416 [01:44<05:23,  1.03s/it]

stan-dev_rstanarm:  25%|█████▏               | 103/416 [01:46<05:22,  1.03s/it]

stan-dev_rstanarm:  25%|█████▎               | 104/416 [01:47<05:20,  1.03s/it]

stan-dev_rstanarm:  25%|█████▎               | 105/416 [01:48<05:19,  1.03s/it]

stan-dev_rstanarm:  25%|█████▎               | 106/416 [01:49<05:18,  1.03s/it]

stan-dev_rstanarm:  26%|█████▍               | 107/416 [01:50<05:17,  1.03s/it]

stan-dev_rstanarm:  26%|█████▍               | 108/416 [01:51<05:17,  1.03s/it]

stan-dev_rstanarm:  26%|█████▌               | 109/416 [01:52<05:15,  1.03s/it]

stan-dev_rstanarm:  26%|█████▌               | 110/416 [01:53<05:14,  1.03s/it]

stan-dev_rstanarm:  27%|█████▌               | 111/416 [01:54<05:14,  1.03s/it]

stan-dev_rstanarm:  27%|█████▋               | 112/416 [01:55<05:13,  1.03s/it]

stan-dev_rstanarm:  27%|█████▋               | 113/416 [01:56<05:12,  1.03s/it]

stan-dev_rstanarm:  27%|█████▊               | 114/416 [01:57<05:11,  1.03s/it]

stan-dev_rstanarm:  28%|█████▊               | 115/416 [01:58<05:10,  1.03s/it]

stan-dev_rstanarm:  28%|█████▊               | 116/416 [01:59<05:08,  1.03s/it]

stan-dev_rstanarm:  28%|█████▉               | 117/416 [02:00<05:07,  1.03s/it]

stan-dev_rstanarm:  28%|█████▉               | 118/416 [02:01<05:06,  1.03s/it]

stan-dev_rstanarm:  29%|██████               | 119/416 [02:02<05:05,  1.03s/it]

stan-dev_rstanarm:  29%|██████               | 120/416 [02:03<05:05,  1.03s/it]

stan-dev_rstanarm:  29%|██████               | 121/416 [02:04<05:04,  1.03s/it]

stan-dev_rstanarm:  29%|██████▏              | 122/416 [02:05<05:03,  1.03s/it]

stan-dev_rstanarm:  30%|██████▏              | 123/416 [02:06<05:01,  1.03s/it]

stan-dev_rstanarm:  30%|██████▎              | 124/416 [02:07<05:00,  1.03s/it]

stan-dev_rstanarm:  30%|██████▎              | 125/416 [02:08<05:00,  1.03s/it]

stan-dev_rstanarm:  30%|██████▎              | 126/416 [02:09<04:58,  1.03s/it]

stan-dev_rstanarm:  31%|██████▍              | 127/416 [02:10<04:57,  1.03s/it]

stan-dev_rstanarm:  31%|██████▍              | 128/416 [02:11<04:56,  1.03s/it]

  errors: {'4eba5084fb4bd009626b86d025c884cdbacd72b8': 'Key 4eba5084fb4bd009626b86d025c884cdbacd72b8 not found in /da5_fast/All.sha1c/commit_78.tch'}

stan-dev_rstanarm:  31%|██████▌              | 129/416 [02:12<04:55,  1.03s/it]

stan-dev_rstanarm:  31%|██████▌              | 130/416 [02:13<04:54,  1.03s/it]

stan-dev_rstanarm:  31%|██████▌              | 131/416 [02:14<04:53,  1.03s/it]

stan-dev_rstanarm:  32%|██████▋              | 132/416 [02:15<04:52,  1.03s/it]

stan-dev_rstanarm:  32%|██████▋              | 133/416 [02:16<04:51,  1.03s/it]

stan-dev_rstanarm:  32%|██████▊              | 134/416 [02:17<04:49,  1.03s/it]

stan-dev_rstanarm:  32%|██████▊              | 135/416 [02:18<04:49,  1.03s/it]

stan-dev_rstanarm:  33%|██████▊              | 136/416 [02:19<04:48,  1.03s/it]

stan-dev_rstanarm:  33%|██████▉              | 137/416 [02:21<04:47,  1.03s/it]

stan-dev_rstanarm:  33%|██████▉              | 138/416 [02:22<04:46,  1.03s/it]

  errors: {'55ad8210a5b390d02ca93b4cb16393ac3f192ccc': 'Key 55ad8210a5b390d02ca93b4cb16393ac3f192ccc not found in /da5_fast/All.sha1c/commit_85.tch'}

stan-dev_rstanarm:  33%|███████              | 139/416 [02:23<04:45,  1.03s/it]

stan-dev_rstanarm:  34%|███████              | 140/416 [02:24<04:44,  1.03s/it]

stan-dev_rstanarm:  34%|███████              | 141/416 [02:25<04:43,  1.03s/it]

stan-dev_rstanarm:  34%|███████▏             | 142/416 [02:26<04:41,  1.03s/it]

stan-dev_rstanarm:  34%|███████▏             | 143/416 [02:27<04:40,  1.03s/it]

stan-dev_rstanarm:  35%|███████▎             | 144/416 [02:28<04:39,  1.03s/it]

stan-dev_rstanarm:  35%|███████▎             | 145/416 [02:29<04:38,  1.03s/it]

stan-dev_rstanarm:  35%|███████▎             | 146/416 [02:30<04:37,  1.03s/it]

stan-dev_rstanarm:  35%|███████▍             | 147/416 [02:31<04:36,  1.03s/it]

stan-dev_rstanarm:  36%|███████▍             | 148/416 [02:32<04:35,  1.03s/it]

stan-dev_rstanarm:  36%|███████▌             | 149/416 [02:33<04:34,  1.03s/it]

stan-dev_rstanarm:  36%|███████▌             | 150/416 [02:34<04:33,  1.03s/it]

stan-dev_rstanarm:  36%|███████▌             | 151/416 [02:35<04:32,  1.03s/it]

stan-dev_rstanarm:  37%|███████▋             | 152/416 [02:36<04:31,  1.03s/it]

stan-dev_rstanarm:  37%|███████▋             | 153/416 [02:37<04:31,  1.03s/it]

stan-dev_rstanarm:  37%|███████▊             | 154/416 [02:38<04:29,  1.03s/it]

  errors: {'5fc1e76459c6fa5ca6791e51cc5d234330859a51': 'Key 5fc1e76459c6fa5ca6791e51cc5d234330859a51 not found in /da5_fast/All.sha1c/commit_95.tch'}

stan-dev_rstanarm:  37%|███████▊             | 155/416 [02:39<04:28,  1.03s/it]

stan-dev_rstanarm:  38%|███████▉             | 156/416 [02:40<04:27,  1.03s/it]

stan-dev_rstanarm:  38%|███████▉             | 157/416 [02:41<04:26,  1.03s/it]

stan-dev_rstanarm:  38%|███████▉             | 158/416 [02:42<04:25,  1.03s/it]

stan-dev_rstanarm:  38%|████████             | 159/416 [02:43<04:24,  1.03s/it]

stan-dev_rstanarm:  38%|████████             | 160/416 [02:44<04:23,  1.03s/it]

stan-dev_rstanarm:  39%|████████▏            | 161/416 [02:45<04:22,  1.03s/it]

stan-dev_rstanarm:  39%|████████▏            | 162/416 [02:46<04:21,  1.03s/it]

stan-dev_rstanarm:  39%|████████▏            | 163/416 [02:47<04:20,  1.03s/it]

stan-dev_rstanarm:  39%|████████▎            | 164/416 [02:48<04:19,  1.03s/it]

stan-dev_rstanarm:  40%|████████▎            | 165/416 [02:49<04:18,  1.03s/it]

stan-dev_rstanarm:  40%|████████▍            | 166/416 [02:50<04:17,  1.03s/it]

stan-dev_rstanarm:  40%|████████▍            | 167/416 [02:51<04:16,  1.03s/it]

stan-dev_rstanarm:  40%|████████▍            | 168/416 [02:52<04:15,  1.03s/it]

stan-dev_rstanarm:  41%|████████▌            | 169/416 [02:53<04:14,  1.03s/it]

stan-dev_rstanarm:  41%|████████▌            | 170/416 [02:54<04:13,  1.03s/it]

stan-dev_rstanarm:  41%|████████▋            | 171/416 [02:56<04:11,  1.03s/it]

stan-dev_rstanarm:  41%|████████▋            | 172/416 [02:57<04:10,  1.03s/it]

stan-dev_rstanarm:  42%|████████▋            | 173/416 [02:58<04:10,  1.03s/it]

stan-dev_rstanarm:  42%|████████▊            | 174/416 [02:59<04:08,  1.03s/it]

stan-dev_rstanarm:  42%|████████▊            | 175/416 [03:00<04:08,  1.03s/it]

stan-dev_rstanarm:  42%|████████▉            | 176/416 [03:01<04:07,  1.03s/it]

stan-dev_rstanarm:  43%|████████▉            | 177/416 [03:02<04:09,  1.05s/it]

stan-dev_rstanarm:  43%|████████▉            | 178/416 [03:03<04:07,  1.04s/it]

stan-dev_rstanarm:  43%|█████████            | 179/416 [03:04<04:08,  1.05s/it]

stan-dev_rstanarm:  43%|█████████            | 180/416 [03:05<04:10,  1.06s/it]

stan-dev_rstanarm:  44%|█████████▏           | 181/416 [03:06<04:07,  1.05s/it]

stan-dev_rstanarm:  44%|█████████▏           | 182/416 [03:07<04:04,  1.05s/it]

stan-dev_rstanarm:  44%|█████████▏           | 183/416 [03:08<04:02,  1.04s/it]

stan-dev_rstanarm:  44%|█████████▎           | 184/416 [03:09<04:00,  1.04s/it]

stan-dev_rstanarm:  44%|█████████▎           | 185/416 [03:10<03:58,  1.03s/it]

stan-dev_rstanarm:  45%|█████████▍           | 186/416 [03:11<03:57,  1.03s/it]

stan-dev_rstanarm:  45%|█████████▍           | 187/416 [03:12<03:55,  1.03s/it]

stan-dev_rstanarm:  45%|█████████▍           | 188/416 [03:13<03:54,  1.03s/it]

stan-dev_rstanarm:  45%|█████████▌           | 189/416 [03:14<03:53,  1.03s/it]

stan-dev_rstanarm:  46%|█████████▌           | 190/416 [03:15<03:52,  1.03s/it]

stan-dev_rstanarm:  46%|█████████▋           | 191/416 [03:16<03:51,  1.03s/it]

stan-dev_rstanarm:  46%|█████████▋           | 192/416 [03:17<03:50,  1.03s/it]

stan-dev_rstanarm:  46%|█████████▋           | 193/416 [03:18<03:49,  1.03s/it]

stan-dev_rstanarm:  47%|█████████▊           | 194/416 [03:19<03:48,  1.03s/it]

stan-dev_rstanarm:  47%|█████████▊           | 195/416 [03:20<03:47,  1.03s/it]

stan-dev_rstanarm:  47%|█████████▉           | 196/416 [03:21<03:46,  1.03s/it]

stan-dev_rstanarm:  47%|█████████▉           | 197/416 [03:22<03:45,  1.03s/it]

stan-dev_rstanarm:  48%|█████████▉           | 198/416 [03:23<03:44,  1.03s/it]

stan-dev_rstanarm:  48%|██████████           | 199/416 [03:24<03:43,  1.03s/it]

stan-dev_rstanarm:  48%|██████████           | 200/416 [03:26<03:42,  1.03s/it]

stan-dev_rstanarm:  48%|██████████▏          | 201/416 [03:27<03:41,  1.03s/it]

stan-dev_rstanarm:  49%|██████████▏          | 202/416 [03:28<03:40,  1.03s/it]

stan-dev_rstanarm:  49%|██████████▏          | 203/416 [03:29<03:39,  1.03s/it]

stan-dev_rstanarm:  49%|██████████▎          | 204/416 [03:30<03:38,  1.03s/it]

stan-dev_rstanarm:  49%|██████████▎          | 205/416 [03:31<03:37,  1.03s/it]

stan-dev_rstanarm:  50%|██████████▍          | 206/416 [03:32<03:35,  1.03s/it]

stan-dev_rstanarm:  50%|██████████▍          | 207/416 [03:33<03:35,  1.03s/it]

stan-dev_rstanarm:  50%|██████████▌          | 208/416 [03:34<03:33,  1.03s/it]

stan-dev_rstanarm:  50%|██████████▌          | 209/416 [03:35<03:32,  1.03s/it]

stan-dev_rstanarm:  50%|██████████▌          | 210/416 [03:36<03:31,  1.03s/it]

stan-dev_rstanarm:  51%|██████████▋          | 211/416 [03:37<03:30,  1.03s/it]

stan-dev_rstanarm:  51%|██████████▋          | 212/416 [03:38<03:29,  1.03s/it]

stan-dev_rstanarm:  51%|██████████▊          | 213/416 [03:39<03:28,  1.03s/it]

stan-dev_rstanarm:  51%|██████████▊          | 214/416 [03:40<03:27,  1.03s/it]

stan-dev_rstanarm:  52%|██████████▊          | 215/416 [03:41<03:26,  1.03s/it]

stan-dev_rstanarm:  52%|██████████▉          | 216/416 [03:42<03:25,  1.03s/it]

stan-dev_rstanarm:  52%|██████████▉          | 217/416 [03:43<03:24,  1.03s/it]

stan-dev_rstanarm:  52%|███████████          | 218/416 [03:44<03:23,  1.03s/it]

stan-dev_rstanarm:  53%|███████████          | 219/416 [03:45<03:22,  1.03s/it]

stan-dev_rstanarm:  53%|███████████          | 220/416 [03:46<03:21,  1.03s/it]

stan-dev_rstanarm:  53%|███████████▏         | 221/416 [03:47<03:20,  1.03s/it]

stan-dev_rstanarm:  53%|███████████▏         | 222/416 [03:48<03:19,  1.03s/it]

stan-dev_rstanarm:  54%|███████████▎         | 223/416 [03:49<03:18,  1.03s/it]

stan-dev_rstanarm:  54%|███████████▎         | 224/416 [03:50<03:16,  1.02s/it]

stan-dev_rstanarm:  54%|███████████▎         | 225/416 [03:51<03:15,  1.02s/it]

stan-dev_rstanarm:  54%|███████████▍         | 226/416 [03:52<03:14,  1.03s/it]

stan-dev_rstanarm:  55%|███████████▍         | 227/416 [03:53<03:14,  1.03s/it]

stan-dev_rstanarm:  55%|███████████▌         | 228/416 [03:54<03:13,  1.03s/it]

stan-dev_rstanarm:  55%|███████████▌         | 229/416 [03:55<03:12,  1.03s/it]

stan-dev_rstanarm:  55%|███████████▌         | 230/416 [03:56<03:11,  1.03s/it]

stan-dev_rstanarm:  56%|███████████▋         | 231/416 [03:57<03:10,  1.03s/it]

stan-dev_rstanarm:  56%|███████████▋         | 232/416 [03:58<03:09,  1.03s/it]

stan-dev_rstanarm:  56%|███████████▊         | 233/416 [03:59<03:08,  1.03s/it]

stan-dev_rstanarm:  56%|███████████▊         | 234/416 [04:00<03:06,  1.03s/it]

stan-dev_rstanarm:  56%|███████████▊         | 235/416 [04:01<03:06,  1.03s/it]

stan-dev_rstanarm:  57%|███████████▉         | 236/416 [04:02<03:04,  1.03s/it]

stan-dev_rstanarm:  57%|███████████▉         | 237/416 [04:04<03:03,  1.03s/it]

stan-dev_rstanarm:  57%|████████████         | 238/416 [04:05<03:02,  1.03s/it]

stan-dev_rstanarm:  57%|████████████         | 239/416 [04:06<03:01,  1.03s/it]

stan-dev_rstanarm:  58%|████████████         | 240/416 [04:07<03:00,  1.03s/it]

stan-dev_rstanarm:  58%|████████████▏        | 241/416 [04:08<02:59,  1.03s/it]

stan-dev_rstanarm:  58%|████████████▏        | 242/416 [04:09<02:58,  1.03s/it]

stan-dev_rstanarm:  58%|████████████▎        | 243/416 [04:10<02:57,  1.03s/it]

stan-dev_rstanarm:  59%|████████████▎        | 244/416 [04:11<02:56,  1.03s/it]

stan-dev_rstanarm:  59%|████████████▎        | 245/416 [04:12<02:55,  1.03s/it]

stan-dev_rstanarm:  59%|████████████▍        | 246/416 [04:13<02:54,  1.03s/it]

stan-dev_rstanarm:  59%|████████████▍        | 247/416 [04:14<02:53,  1.03s/it]

stan-dev_rstanarm:  60%|████████████▌        | 248/416 [04:15<02:52,  1.03s/it]

stan-dev_rstanarm:  60%|████████████▌        | 249/416 [04:16<02:51,  1.03s/it]

stan-dev_rstanarm:  60%|████████████▌        | 250/416 [04:17<02:50,  1.03s/it]

stan-dev_rstanarm:  60%|████████████▋        | 251/416 [04:18<02:49,  1.03s/it]

stan-dev_rstanarm:  61%|████████████▋        | 252/416 [04:19<02:48,  1.03s/it]

stan-dev_rstanarm:  61%|████████████▊        | 253/416 [04:20<02:47,  1.03s/it]

stan-dev_rstanarm:  61%|████████████▊        | 254/416 [04:21<02:46,  1.03s/it]

stan-dev_rstanarm:  61%|████████████▊        | 255/416 [04:22<02:45,  1.03s/it]

stan-dev_rstanarm:  62%|████████████▉        | 256/416 [04:23<02:44,  1.03s/it]

stan-dev_rstanarm:  62%|████████████▉        | 257/416 [04:24<02:43,  1.03s/it]

stan-dev_rstanarm:  62%|█████████████        | 258/416 [04:25<02:45,  1.04s/it]

stan-dev_rstanarm:  62%|█████████████        | 259/416 [04:26<02:48,  1.07s/it]

stan-dev_rstanarm:  62%|█████████████▏       | 260/416 [04:27<02:45,  1.06s/it]

stan-dev_rstanarm:  63%|█████████████▏       | 261/416 [04:28<02:42,  1.05s/it]

stan-dev_rstanarm:  63%|█████████████▏       | 262/416 [04:29<02:40,  1.04s/it]

stan-dev_rstanarm:  63%|█████████████▎       | 263/416 [04:30<02:38,  1.04s/it]

stan-dev_rstanarm:  63%|█████████████▎       | 264/416 [04:31<02:37,  1.03s/it]

stan-dev_rstanarm:  64%|█████████████▍       | 265/416 [04:32<02:35,  1.03s/it]

  errors: {'a3a24d7f72acb0a32f747d31ebbd40a0141ae9ee': 'Key a3a24d7f72acb0a32f747d31ebbd40a0141ae9ee not found in /da5_fast/All.sha1c/commit_35.tch'}

stan-dev_rstanarm:  64%|█████████████▍       | 266/416 [04:33<02:34,  1.03s/it]

stan-dev_rstanarm:  64%|█████████████▍       | 267/416 [04:35<02:33,  1.03s/it]

stan-dev_rstanarm:  64%|█████████████▌       | 268/416 [04:36<02:32,  1.03s/it]

stan-dev_rstanarm:  65%|█████████████▌       | 269/416 [04:37<02:31,  1.03s/it]

  errors: {'a6092d0c200000bfae6f37da224e294991cd4a39': 'Key a6092d0c200000bfae6f37da224e294991cd4a39 not found in /da5_fast/All.sha1c/commit_38.tch'}

stan-dev_rstanarm:  65%|█████████████▋       | 270/416 [04:38<02:30,  1.03s/it]

stan-dev_rstanarm:  65%|█████████████▋       | 271/416 [04:39<02:28,  1.03s/it]

stan-dev_rstanarm:  65%|█████████████▋       | 272/416 [04:40<02:27,  1.03s/it]

stan-dev_rstanarm:  66%|█████████████▊       | 273/416 [04:41<02:26,  1.03s/it]

stan-dev_rstanarm:  66%|█████████████▊       | 274/416 [04:42<02:25,  1.03s/it]

stan-dev_rstanarm:  66%|█████████████▉       | 275/416 [04:43<02:24,  1.03s/it]

stan-dev_rstanarm:  66%|█████████████▉       | 276/416 [04:44<02:23,  1.03s/it]

stan-dev_rstanarm:  67%|█████████████▉       | 277/416 [04:45<02:22,  1.03s/it]

stan-dev_rstanarm:  67%|██████████████       | 278/416 [04:46<02:21,  1.03s/it]

stan-dev_rstanarm:  67%|██████████████       | 279/416 [04:47<02:20,  1.03s/it]

stan-dev_rstanarm:  67%|██████████████▏      | 280/416 [04:48<02:19,  1.03s/it]

stan-dev_rstanarm:  68%|██████████████▏      | 281/416 [04:49<02:18,  1.03s/it]

stan-dev_rstanarm:  68%|██████████████▏      | 282/416 [04:50<02:17,  1.03s/it]

stan-dev_rstanarm:  68%|██████████████▎      | 283/416 [04:51<02:16,  1.03s/it]

stan-dev_rstanarm:  68%|██████████████▎      | 284/416 [04:52<02:15,  1.03s/it]

stan-dev_rstanarm:  69%|██████████████▍      | 285/416 [04:53<02:14,  1.03s/it]

stan-dev_rstanarm:  69%|██████████████▍      | 286/416 [04:54<02:13,  1.03s/it]

stan-dev_rstanarm:  69%|██████████████▍      | 287/416 [04:55<02:12,  1.03s/it]

stan-dev_rstanarm:  69%|██████████████▌      | 288/416 [04:56<02:11,  1.03s/it]

stan-dev_rstanarm:  69%|██████████████▌      | 289/416 [04:57<02:10,  1.03s/it]

stan-dev_rstanarm:  70%|██████████████▋      | 290/416 [04:58<02:09,  1.03s/it]

  errors: {'b271cbfc848f53cb1b2592cddd167223a28cef14': 'Key b271cbfc848f53cb1b2592cddd167223a28cef14 not found in /da5_fast/All.sha1c/commit_50.tch'}

stan-dev_rstanarm:  70%|██████████████▋      | 291/416 [04:59<02:08,  1.03s/it]

stan-dev_rstanarm:  70%|██████████████▋      | 292/416 [05:00<02:07,  1.03s/it]

stan-dev_rstanarm:  70%|██████████████▊      | 293/416 [05:01<02:06,  1.03s/it]

stan-dev_rstanarm:  71%|██████████████▊      | 294/416 [05:02<02:05,  1.03s/it]

stan-dev_rstanarm:  71%|██████████████▉      | 295/416 [05:03<02:04,  1.03s/it]

stan-dev_rstanarm:  71%|██████████████▉      | 296/416 [05:04<02:03,  1.03s/it]

stan-dev_rstanarm:  71%|██████████████▉      | 297/416 [05:05<02:02,  1.03s/it]

stan-dev_rstanarm:  72%|███████████████      | 298/416 [05:06<02:01,  1.03s/it]

stan-dev_rstanarm:  72%|███████████████      | 299/416 [05:07<02:00,  1.03s/it]

stan-dev_rstanarm:  72%|███████████████▏     | 300/416 [05:08<01:59,  1.03s/it]

stan-dev_rstanarm:  72%|███████████████▏     | 301/416 [05:09<01:58,  1.03s/it]

stan-dev_rstanarm:  73%|███████████████▏     | 302/416 [05:10<01:57,  1.03s/it]

stan-dev_rstanarm:  73%|███████████████▎     | 303/416 [05:11<01:55,  1.03s/it]

stan-dev_rstanarm:  73%|███████████████▎     | 304/416 [05:13<01:54,  1.03s/it]

stan-dev_rstanarm:  73%|███████████████▍     | 305/416 [05:14<01:54,  1.03s/it]

stan-dev_rstanarm:  74%|███████████████▍     | 306/416 [05:15<01:52,  1.03s/it]

stan-dev_rstanarm:  74%|███████████████▍     | 307/416 [05:16<01:51,  1.03s/it]

stan-dev_rstanarm:  74%|███████████████▌     | 308/416 [05:17<01:50,  1.03s/it]

stan-dev_rstanarm:  74%|███████████████▌     | 309/416 [05:18<01:49,  1.03s/it]

stan-dev_rstanarm:  75%|███████████████▋     | 310/416 [05:19<01:48,  1.03s/it]

stan-dev_rstanarm:  75%|███████████████▋     | 311/416 [05:20<01:47,  1.02s/it]

stan-dev_rstanarm:  75%|███████████████▊     | 312/416 [05:21<01:46,  1.03s/it]

stan-dev_rstanarm:  75%|███████████████▊     | 313/416 [05:22<01:45,  1.03s/it]

stan-dev_rstanarm:  75%|███████████████▊     | 314/416 [05:23<01:44,  1.02s/it]

stan-dev_rstanarm:  76%|███████████████▉     | 315/416 [05:24<01:43,  1.02s/it]

stan-dev_rstanarm:  76%|███████████████▉     | 316/416 [05:25<01:42,  1.02s/it]

stan-dev_rstanarm:  76%|████████████████     | 317/416 [05:26<01:41,  1.03s/it]

stan-dev_rstanarm:  76%|████████████████     | 318/416 [05:27<01:40,  1.03s/it]

stan-dev_rstanarm:  77%|████████████████     | 319/416 [05:28<01:39,  1.03s/it]

stan-dev_rstanarm:  77%|████████████████▏    | 320/416 [05:29<01:38,  1.03s/it]

stan-dev_rstanarm:  77%|████████████████▏    | 321/416 [05:30<01:37,  1.03s/it]

stan-dev_rstanarm:  77%|████████████████▎    | 322/416 [05:31<01:36,  1.03s/it]

stan-dev_rstanarm:  78%|████████████████▎    | 323/416 [05:32<01:35,  1.03s/it]

stan-dev_rstanarm:  78%|████████████████▎    | 324/416 [05:33<01:34,  1.03s/it]

stan-dev_rstanarm:  78%|████████████████▍    | 325/416 [05:34<01:33,  1.03s/it]

stan-dev_rstanarm:  78%|████████████████▍    | 326/416 [05:35<01:32,  1.03s/it]

stan-dev_rstanarm:  79%|████████████████▌    | 327/416 [05:36<01:31,  1.03s/it]

stan-dev_rstanarm:  79%|████████████████▌    | 328/416 [05:37<01:30,  1.03s/it]

stan-dev_rstanarm:  79%|████████████████▌    | 329/416 [05:38<01:29,  1.03s/it]

stan-dev_rstanarm:  79%|████████████████▋    | 330/416 [05:39<01:28,  1.03s/it]

stan-dev_rstanarm:  80%|████████████████▋    | 331/416 [05:40<01:27,  1.03s/it]

stan-dev_rstanarm:  80%|████████████████▊    | 332/416 [05:41<01:26,  1.03s/it]

stan-dev_rstanarm:  80%|████████████████▊    | 333/416 [05:42<01:25,  1.03s/it]

stan-dev_rstanarm:  80%|████████████████▊    | 334/416 [05:43<01:24,  1.03s/it]

stan-dev_rstanarm:  81%|████████████████▉    | 335/416 [05:44<01:23,  1.03s/it]

stan-dev_rstanarm:  81%|████████████████▉    | 336/416 [05:45<01:22,  1.03s/it]

stan-dev_rstanarm:  81%|█████████████████    | 337/416 [05:46<01:21,  1.03s/it]

stan-dev_rstanarm:  81%|█████████████████    | 338/416 [05:47<01:20,  1.03s/it]

stan-dev_rstanarm:  81%|█████████████████    | 339/416 [05:48<01:19,  1.03s/it]

stan-dev_rstanarm:  82%|█████████████████▏   | 340/416 [05:49<01:17,  1.03s/it]

stan-dev_rstanarm:  82%|█████████████████▏   | 341/416 [05:50<01:16,  1.03s/it]

stan-dev_rstanarm:  82%|█████████████████▎   | 342/416 [05:52<01:16,  1.03s/it]

stan-dev_rstanarm:  82%|█████████████████▎   | 343/416 [05:53<01:14,  1.03s/it]

stan-dev_rstanarm:  83%|█████████████████▎   | 344/416 [05:54<01:13,  1.03s/it]

stan-dev_rstanarm:  83%|█████████████████▍   | 345/416 [05:55<01:12,  1.03s/it]

stan-dev_rstanarm:  83%|█████████████████▍   | 346/416 [05:56<01:11,  1.03s/it]

stan-dev_rstanarm:  83%|█████████████████▌   | 347/416 [05:57<01:10,  1.03s/it]

stan-dev_rstanarm:  84%|█████████████████▌   | 348/416 [05:58<01:09,  1.03s/it]

  errors: {'d5d19caf80180b56346260f7d93471dc79807d7b': 'Key d5d19caf80180b56346260f7d93471dc79807d7b not found in /da5_fast/All.sha1c/commit_85.tch'}

stan-dev_rstanarm:  84%|█████████████████▌   | 349/416 [05:59<01:08,  1.03s/it]

stan-dev_rstanarm:  84%|█████████████████▋   | 350/416 [06:00<01:07,  1.03s/it]

stan-dev_rstanarm:  84%|█████████████████▋   | 351/416 [06:01<01:06,  1.03s/it]

stan-dev_rstanarm:  85%|█████████████████▊   | 352/416 [06:02<01:05,  1.03s/it]

stan-dev_rstanarm:  85%|█████████████████▊   | 353/416 [06:03<01:04,  1.03s/it]

stan-dev_rstanarm:  85%|█████████████████▊   | 354/416 [06:04<01:03,  1.02s/it]

stan-dev_rstanarm:  85%|█████████████████▉   | 355/416 [06:05<01:02,  1.03s/it]

stan-dev_rstanarm:  86%|█████████████████▉   | 356/416 [06:06<01:01,  1.03s/it]

stan-dev_rstanarm:  86%|██████████████████   | 357/416 [06:07<01:01,  1.05s/it]

  errors: {'db53dc88adad9c4d0ab1723eebc125f8538cfa56': 'Key db53dc88adad9c4d0ab1723eebc125f8538cfa56 not found in /da5_fast/All.sha1c/commit_91.tch'}

stan-dev_rstanarm:  86%|██████████████████   | 358/416 [06:08<01:00,  1.04s/it]

stan-dev_rstanarm:  86%|██████████████████   | 359/416 [06:09<00:59,  1.04s/it]

stan-dev_rstanarm:  87%|██████████████████▏  | 360/416 [06:10<00:57,  1.03s/it]

stan-dev_rstanarm:  87%|██████████████████▏  | 361/416 [06:11<00:56,  1.03s/it]

stan-dev_rstanarm:  87%|██████████████████▎  | 362/416 [06:12<00:55,  1.03s/it]

stan-dev_rstanarm:  87%|██████████████████▎  | 363/416 [06:13<00:54,  1.03s/it]

stan-dev_rstanarm:  88%|██████████████████▍  | 364/416 [06:14<00:53,  1.03s/it]

stan-dev_rstanarm:  88%|██████████████████▍  | 365/416 [06:15<00:52,  1.03s/it]

stan-dev_rstanarm:  88%|██████████████████▍  | 366/416 [06:16<00:51,  1.03s/it]

stan-dev_rstanarm:  88%|██████████████████▌  | 367/416 [06:17<00:50,  1.03s/it]

stan-dev_rstanarm:  88%|██████████████████▌  | 368/416 [06:18<00:49,  1.03s/it]

stan-dev_rstanarm:  89%|██████████████████▋  | 369/416 [06:19<00:48,  1.03s/it]

stan-dev_rstanarm:  89%|██████████████████▋  | 370/416 [06:20<00:47,  1.03s/it]

stan-dev_rstanarm:  89%|██████████████████▋  | 371/416 [06:21<00:46,  1.03s/it]

stan-dev_rstanarm:  89%|██████████████████▊  | 372/416 [06:22<00:45,  1.03s/it]

stan-dev_rstanarm:  90%|██████████████████▊  | 373/416 [06:23<00:44,  1.03s/it]

stan-dev_rstanarm:  90%|██████████████████▉  | 374/416 [06:24<00:43,  1.03s/it]

stan-dev_rstanarm:  90%|██████████████████▉  | 375/416 [06:25<00:42,  1.03s/it]

stan-dev_rstanarm:  90%|██████████████████▉  | 376/416 [06:26<00:41,  1.03s/it]

stan-dev_rstanarm:  91%|███████████████████  | 377/416 [06:28<00:40,  1.03s/it]

stan-dev_rstanarm:  91%|███████████████████  | 378/416 [06:29<00:39,  1.03s/it]

stan-dev_rstanarm:  91%|███████████████████▏ | 379/416 [06:30<00:38,  1.03s/it]

stan-dev_rstanarm:  91%|███████████████████▏ | 380/416 [06:31<00:36,  1.03s/it]

stan-dev_rstanarm:  92%|███████████████████▏ | 381/416 [06:32<00:36,  1.03s/it]

stan-dev_rstanarm:  92%|███████████████████▎ | 382/416 [06:33<00:34,  1.03s/it]

stan-dev_rstanarm:  92%|███████████████████▎ | 383/416 [06:34<00:33,  1.03s/it]

stan-dev_rstanarm:  92%|███████████████████▍ | 384/416 [06:35<00:32,  1.03s/it]

stan-dev_rstanarm:  93%|███████████████████▍ | 385/416 [06:36<00:32,  1.05s/it]

stan-dev_rstanarm:  93%|███████████████████▍ | 386/416 [06:37<00:31,  1.04s/it]

stan-dev_rstanarm:  93%|███████████████████▌ | 387/416 [06:38<00:30,  1.04s/it]

stan-dev_rstanarm:  93%|███████████████████▌ | 388/416 [06:39<00:28,  1.03s/it]

stan-dev_rstanarm:  94%|███████████████████▋ | 389/416 [06:40<00:27,  1.03s/it]

stan-dev_rstanarm:  94%|███████████████████▋ | 390/416 [06:41<00:26,  1.03s/it]

stan-dev_rstanarm:  94%|███████████████████▋ | 391/416 [06:42<00:25,  1.03s/it]

stan-dev_rstanarm:  94%|███████████████████▊ | 392/416 [06:43<00:24,  1.03s/it]

stan-dev_rstanarm:  94%|███████████████████▊ | 393/416 [06:44<00:23,  1.03s/it]

stan-dev_rstanarm:  95%|███████████████████▉ | 394/416 [06:45<00:22,  1.03s/it]

stan-dev_rstanarm:  95%|███████████████████▉ | 395/416 [06:46<00:21,  1.03s/it]

stan-dev_rstanarm:  95%|███████████████████▉ | 396/416 [06:47<00:20,  1.03s/it]

stan-dev_rstanarm:  95%|████████████████████ | 397/416 [06:48<00:19,  1.03s/it]

stan-dev_rstanarm:  96%|████████████████████ | 398/416 [06:49<00:18,  1.03s/it]

stan-dev_rstanarm:  96%|████████████████████▏| 399/416 [06:50<00:17,  1.03s/it]

stan-dev_rstanarm:  96%|████████████████████▏| 400/416 [06:51<00:16,  1.03s/it]

stan-dev_rstanarm:  96%|████████████████████▏| 401/416 [06:52<00:15,  1.03s/it]

  errors: {'f6504f591b58c85f900fb59e26bdad4fec77f0b5': 'Key f6504f591b58c85f900fb59e26bdad4fec77f0b5 not found in /da5_fast/All.sha1c/commit_118.tch'}

stan-dev_rstanarm:  97%|████████████████████▎| 402/416 [06:53<00:14,  1.03s/it]

stan-dev_rstanarm:  97%|████████████████████▎| 403/416 [06:54<00:13,  1.03s/it]

stan-dev_rstanarm:  97%|████████████████████▍| 404/416 [06:55<00:12,  1.03s/it]

stan-dev_rstanarm:  97%|████████████████████▍| 405/416 [06:56<00:11,  1.03s/it]

stan-dev_rstanarm:  98%|████████████████████▍| 406/416 [06:57<00:10,  1.03s/it]

  errors: {'fa03d1ac0451964b746d6490ba721e1967369d65': 'Key fa03d1ac0451964b746d6490ba721e1967369d65 not found in /da5_fast/All.sha1c/commit_122.tch'}

stan-dev_rstanarm:  98%|████████████████████▌| 407/416 [06:58<00:09,  1.03s/it]

stan-dev_rstanarm:  98%|████████████████████▌| 408/416 [06:59<00:08,  1.03s/it]

stan-dev_rstanarm:  98%|████████████████████▋| 409/416 [07:00<00:07,  1.03s/it]

stan-dev_rstanarm:  99%|████████████████████▋| 410/416 [07:01<00:06,  1.03s/it]

stan-dev_rstanarm:  99%|████████████████████▋| 411/416 [07:03<00:05,  1.03s/it]

stan-dev_rstanarm:  99%|████████████████████▊| 412/416 [07:04<00:04,  1.02s/it]

stan-dev_rstanarm:  99%|████████████████████▊| 413/416 [07:05<00:03,  1.03s/it]

stan-dev_rstanarm: 100%|████████████████████▉| 414/416 [07:06<00:02,  1.03s/it]

stan-dev_rstanarm: 100%|████████████████████▉| 415/416 [07:07<00:01,  1.03s/it]

stan-dev_rstanarm: 100%|█████████████████████| 416/416 [07:08<00:00,  1.03s/it]

stan-dev_rstanarm: 100%|█████████████████████| 416/416 [07:08<00:00,  1.03s/it]

  WARNING: 13 commits could not be retrieved
copasi_copasi-dependencies -> 515 commit sha1s

copasi_copasi-dependencies:   0%|                       | 0/52 [00:00<?, ?it/s]

copasi_copasi-dependencies:   2%|▎              | 1/52 [00:01<00:52,  1.03s/it]

copasi_copasi-dependencies:   4%|▌              | 2/52 [00:02<00:51,  1.04s/it]

copasi_copasi-dependencies:   6%|▊              | 3/52 [00:03<00:50,  1.04s/it]

copasi_copasi-dependencies:   8%|█▏             | 4/52 [00:04<00:49,  1.04s/it]

copasi_copasi-dependencies:  10%|█▍             | 5/52 [00:05<00:48,  1.04s/it]

copasi_copasi-dependencies:  12%|█▋             | 6/52 [00:06<00:47,  1.04s/it]

copasi_copasi-dependencies:  13%|██             | 7/52 [00:07<00:46,  1.04s/it]

copasi_copasi-dependencies:  15%|██▎            | 8/52 [00:08<00:45,  1.04s/it]

copasi_copasi-dependencies:  17%|██▌            | 9/52 [00:09<00:44,  1.04s/it]

copasi_copasi-dependencies:  19%|██▋           | 10/52 [00:10<00:43,  1.04s/it]

copasi_copasi-dependencies:  21%|██▉           | 11/52 [00:11<00:42,  1.04s/it]

copasi_copasi-dependencies:  23%|███▏          | 12/52 [00:12<00:41,  1.04s/it]

copasi_copasi-dependencies:  25%|███▌          | 13/52 [00:13<00:40,  1.04s/it]

copasi_copasi-dependencies:  27%|███▊          | 14/52 [00:14<00:39,  1.04s/it]

copasi_copasi-dependencies:  29%|████          | 15/52 [00:15<00:38,  1.04s/it]

copasi_copasi-dependencies:  31%|████▎         | 16/52 [00:16<00:37,  1.04s/it]

copasi_copasi-dependencies:  33%|████▌         | 17/52 [00:17<00:36,  1.04s/it]

copasi_copasi-dependencies:  35%|████▊         | 18/52 [00:18<00:35,  1.04s/it]

copasi_copasi-dependencies:  37%|█████         | 19/52 [00:19<00:34,  1.04s/it]

copasi_copasi-dependencies:  38%|█████▍        | 20/52 [00:20<00:33,  1.04s/it]

copasi_copasi-dependencies:  40%|█████▋        | 21/52 [00:21<00:32,  1.04s/it]

copasi_copasi-dependencies:  42%|█████▉        | 22/52 [00:22<00:31,  1.04s/it]

copasi_copasi-dependencies:  44%|██████▏       | 23/52 [00:23<00:30,  1.03s/it]

copasi_copasi-dependencies:  46%|██████▍       | 24/52 [00:24<00:28,  1.03s/it]

copasi_copasi-dependencies:  48%|██████▋       | 25/52 [00:25<00:27,  1.04s/it]

copasi_copasi-dependencies:  50%|███████       | 26/52 [00:26<00:26,  1.03s/it]

copasi_copasi-dependencies:  52%|███████▎      | 27/52 [00:27<00:25,  1.03s/it]

copasi_copasi-dependencies:  54%|███████▌      | 28/52 [00:29<00:24,  1.03s/it]

copasi_copasi-dependencies:  56%|███████▊      | 29/52 [00:30<00:23,  1.03s/it]

copasi_copasi-dependencies:  58%|████████      | 30/52 [00:31<00:22,  1.03s/it]

copasi_copasi-dependencies:  60%|████████▎     | 31/52 [00:32<00:21,  1.04s/it]

copasi_copasi-dependencies:  62%|████████▌     | 32/52 [00:33<00:20,  1.04s/it]

copasi_copasi-dependencies:  63%|████████▉     | 33/52 [00:34<00:19,  1.03s/it]

copasi_copasi-dependencies:  65%|█████████▏    | 34/52 [00:35<00:18,  1.03s/it]

copasi_copasi-dependencies:  67%|█████████▍    | 35/52 [00:36<00:17,  1.03s/it]

copasi_copasi-dependencies:  69%|█████████▋    | 36/52 [00:37<00:16,  1.03s/it]

copasi_copasi-dependencies:  71%|█████████▉    | 37/52 [00:38<00:15,  1.03s/it]

copasi_copasi-dependencies:  73%|██████████▏   | 38/52 [00:39<00:14,  1.03s/it]

copasi_copasi-dependencies:  75%|██████████▌   | 39/52 [00:40<00:13,  1.03s/it]

copasi_copasi-dependencies:  77%|██████████▊   | 40/52 [00:41<00:12,  1.03s/it]

copasi_copasi-dependencies:  79%|███████████   | 41/52 [00:42<00:11,  1.03s/it]

copasi_copasi-dependencies:  81%|███████████▎  | 42/52 [00:43<00:10,  1.03s/it]

copasi_copasi-dependencies:  83%|███████████▌  | 43/52 [00:44<00:09,  1.03s/it]

copasi_copasi-dependencies:  85%|███████████▊  | 44/52 [00:45<00:08,  1.03s/it]

copasi_copasi-dependencies:  87%|████████████  | 45/52 [00:46<00:07,  1.03s/it]

copasi_copasi-dependencies:  88%|████████████▍ | 46/52 [00:47<00:06,  1.03s/it]

copasi_copasi-dependencies:  90%|████████████▋ | 47/52 [00:48<00:05,  1.03s/it]

copasi_copasi-dependencies:  92%|████████████▉ | 48/52 [00:49<00:04,  1.03s/it]

copasi_copasi-dependencies:  94%|█████████████▏| 49/52 [00:50<00:03,  1.03s/it]

copasi_copasi-dependencies:  96%|█████████████▍| 50/52 [00:51<00:02,  1.03s/it]

copasi_copasi-dependencies:  98%|█████████████▋| 51/52 [00:52<00:01,  1.03s/it]

copasi_copasi-dependencies: 100%|██████████████| 52/52 [00:53<00:00,  1.03s/it]

copasi_copasi-dependencies: 100%|██████████████| 52/52 [00:53<00:00,  1.03s/it]

almost-matching-exactly_dame-python-package -> 501 commit sha1s

almost-matching-exactly_dame-python-package:   0%|      | 0/51 [00:00<?, ?it/s]

almost-matching-exactly_dame-python-package:   2%| | 1/51 [00:01<00:51,  1.03s/

almost-matching-exactly_dame-python-package:   4%| | 2/51 [00:02<00:50,  1.03s/

almost-matching-exactly_dame-python-package:   6%| | 3/51 [00:03<00:49,  1.04s/

almost-matching-exactly_dame-python-package:   8%| | 4/51 [00:04<00:48,  1.04s/

almost-matching-exactly_dame-python-package:  10%| | 5/51 [00:05<00:47,  1.04s/

almost-matching-exactly_dame-python-package:  12%| | 6/51 [00:06<00:46,  1.04s/

almost-matching-exactly_dame-python-package:  14%|▏| 7/51 [00:07<00:45,  1.04s/

almost-matching-exactly_dame-python-package:  16%|▏| 8/51 [00:08<00:44,  1.04s/

almost-matching-exactly_dame-python-package:  18%|▏| 9/51 [00:09<00:43,  1.04s/

almost-matching-exactly_dame-python-package:  20%|▏| 10/51 [00:10<00:42,  1.04s

almost-matching-exactly_dame-python-package:  22%|▏| 11/51 [00:11<00:41,  1.04s

almost-matching-exactly_dame-python-package:  24%|▏| 12/51 [00:12<00:40,  1.04s

almost-matching-exactly_dame-python-package:  25%|▎| 13/51 [00:13<00:39,  1.04s

almost-matching-exactly_dame-python-package:  27%|▎| 14/51 [00:14<00:38,  1.04s

almost-matching-exactly_dame-python-package:  29%|▎| 15/51 [00:15<00:37,  1.04s

almost-matching-exactly_dame-python-package:  31%|▎| 16/51 [00:16<00:36,  1.04s

almost-matching-exactly_dame-python-package:  33%|▎| 17/51 [00:17<00:35,  1.04s

almost-matching-exactly_dame-python-package:  35%|▎| 18/51 [00:18<00:34,  1.04s

almost-matching-exactly_dame-python-package:  37%|▎| 19/51 [00:19<00:33,  1.04s

almost-matching-exactly_dame-python-package:  39%|▍| 20/51 [00:20<00:32,  1.04s

almost-matching-exactly_dame-python-package:  41%|▍| 21/51 [00:21<00:31,  1.04s

almost-matching-exactly_dame-python-package:  43%|▍| 22/51 [00:22<00:30,  1.04s

almost-matching-exactly_dame-python-package:  45%|▍| 23/51 [00:23<00:29,  1.04s

almost-matching-exactly_dame-python-package:  47%|▍| 24/51 [00:24<00:28,  1.04s

almost-matching-exactly_dame-python-package:  49%|▍| 25/51 [00:25<00:26,  1.04s

almost-matching-exactly_dame-python-package:  51%|▌| 26/51 [00:26<00:25,  1.03s

almost-matching-exactly_dame-python-package:  53%|▌| 27/51 [00:27<00:24,  1.04s

almost-matching-exactly_dame-python-package:  55%|▌| 28/51 [00:29<00:23,  1.03s

almost-matching-exactly_dame-python-package:  57%|▌| 29/51 [00:30<00:22,  1.04s

almost-matching-exactly_dame-python-package:  59%|▌| 30/51 [00:31<00:21,  1.03s

almost-matching-exactly_dame-python-package:  61%|▌| 31/51 [00:32<00:20,  1.04s

almost-matching-exactly_dame-python-package:  63%|▋| 32/51 [00:33<00:19,  1.04s

almost-matching-exactly_dame-python-package:  65%|▋| 33/51 [00:34<00:18,  1.03s

almost-matching-exactly_dame-python-package:  67%|▋| 34/51 [00:35<00:17,  1.03s

almost-matching-exactly_dame-python-package:  69%|▋| 35/51 [00:36<00:16,  1.03s

almost-matching-exactly_dame-python-package:  71%|▋| 36/51 [00:37<00:15,  1.03s

almost-matching-exactly_dame-python-package:  73%|▋| 37/51 [00:38<00:14,  1.04s

almost-matching-exactly_dame-python-package:  75%|▋| 38/51 [00:39<00:13,  1.03s

almost-matching-exactly_dame-python-package:  76%|▊| 39/51 [00:40<00:12,  1.03s

almost-matching-exactly_dame-python-package:  78%|▊| 40/51 [00:41<00:11,  1.03s

almost-matching-exactly_dame-python-package:  80%|▊| 41/51 [00:42<00:10,  1.04s

almost-matching-exactly_dame-python-package:  82%|▊| 42/51 [00:43<00:09,  1.04s

almost-matching-exactly_dame-python-package:  84%|▊| 43/51 [00:44<00:08,  1.04s

almost-matching-exactly_dame-python-package:  86%|▊| 44/51 [00:45<00:07,  1.04s

almost-matching-exactly_dame-python-package:  88%|▉| 45/51 [00:46<00:06,  1.04s

almost-matching-exactly_dame-python-package:  90%|▉| 46/51 [00:47<00:05,  1.04s

almost-matching-exactly_dame-python-package:  92%|▉| 47/51 [00:48<00:04,  1.04s

almost-matching-exactly_dame-python-package:  94%|▉| 48/51 [00:49<00:03,  1.03s

almost-matching-exactly_dame-python-package:  96%|▉| 49/51 [00:50<00:02,  1.03s

almost-matching-exactly_dame-python-package:  98%|▉| 50/51 [00:51<00:01,  1.03s

almost-matching-exactly_dame-python-package: 100%|█| 51/51 [00:52<00:00,  1.03s

almost-matching-exactly_dame-python-package: 100%|█| 51/51 [00:52<00:00,  1.04s

34300 commits saved to gelkhoda_project_summary.csv

## WoC statistics

In [4]:
ts = lambda s: pd.to_datetime(s, unit='s', utc=True).strftime('%Y-%m-%d')
woc_stats = (summary.groupby('project_wocid')
             .agg(ncommits=('commit_sha1', 'nunique'), nauthors=('author', 'nunique'),
                  mintime=('time', 'min'), maxtime=('time', 'max'))
             .reindex(mine['WoC']))
woc_stats['min_date'] = woc_stats['mintime'].map(ts)
woc_stats['max_date'] = woc_stats['maxtime'].map(ts)
woc_stats

,ncommits,nauthors,mintime,maxtime,min_date,max_date
WoC,,,,,,
gsi-cs-co_chart-fx,3633,53,1557246279,1758770120,2019-05-07,2025-09-25
bsaul_inferference,328,16,1404407958,1747234885,2014-07-03,2025-05-14
daohu527_dig-into-apollo,425,7,1554864597,1725447268,2019-04-10,2024-09-04
martin2250_opencncpilot,253,15,1474378401,1759704094,2016-09-20,2025-10-05
usgs-astrogeology_isis3,18318,200,1276037385,1759270719,2010-06-08,2025-09-30
sakov_enkf-c,1772,7,1403133737,1762472241,2014-06-18,2025-11-06
sfc-aqua_quisp,4409,87,1524058198,1761562984,2018-04-18,2025-10-27
stan-dev_rstanarm,4146,64,1373994672,1761779325,2013-07-16,2025-10-29
copasi_copasi-dependencies,515,16,1362398954,1773320863,2013-03-04,2026-03-12
almost-matching-exactly_dame-python-package,501,23,1564697002,1758126548,2019-08-01,2025-09-17

## GitHub statistics (stars, forks, last commit date) + validation

In [5]:
S = requests.Session()
S.headers['Accept'] = 'application/vnd.github+json'
if GH_TOKEN: S.headers['Authorization'] = f'Bearer {GH_TOKEN}'

def gh(path, **params):
    r = S.get('https://api.github.com' + path, params=params)
    if r.status_code == 403 and 'rate limit' in r.text.lower():
        raise RuntimeError('GitHub rate limit hit - set GH_TOKEN and re-run')
    r.raise_for_status(); return r

def last_page(r):   # count items using per_page=1 + Link header
    m = re.search(r'[?&]page=(\d+)>; rel="last"', r.headers.get('Link', ''))
    return int(m.group(1)) if m else len(r.json())

gh_rows, recent = [], []
for _, row in mine.iterrows():
    full = row['GH'].rstrip('/').split('github.com/')[1]
    info = gh(f'/repos/{full}').json()                  # follows renames/transfers
    full = info['full_name']
    c1 = gh(f'/repos/{full}/commits', per_page=1)
    last = c1.json()[0]['commit']['committer']['date'][:10]
    contrib = gh(f'/repos/{full}/contributors', per_page=1, anon=1)
    gh_rows.append({'project_wocid': row['WoC'], 'gh_repo': full,
                    'nstars': info['stargazers_count'], 'nforks': info['forks_count'],
                    'lastGHCommitDate': last, 'gh_ncommits': last_page(c1),
                    'gh_ncontributors': last_page(contrib), 'archived': info.get('archived')})
    for c in gh(f'/repos/{full}/commits', per_page=10).json():   # for RecentThemes (Part 3)
        recent.append({'project_wocid': row['WoC'], 'commit_sha1': c['sha'],
                       'author': f"{c['commit']['author']['name']} <{c['commit']['author']['email']}>",
                       'date': c['commit']['author']['date'], 'commit message': c['commit']['message']})
    time.sleep(1)

gh_stats = pd.DataFrame(gh_rows).set_index('project_wocid')
gh_stats.to_csv(f'{NETID}_gh_stats.csv', sep=';')
pd.DataFrame(recent).to_csv(f'{NETID}_gh_recent_commits.csv', sep=';', index=False)

check = woc_stats[['ncommits', 'nauthors', 'max_date']].join(gh_stats[['gh_ncommits', 'gh_ncontributors', 'lastGHCommitDate']])
check['commit_diff'] = check['gh_ncommits'] - check['ncommits']
check   # WoC stops ~Jan 2025, so GH can legitimately be higher; WoC authors are raw name<email> strings (aliases inflate)

,ncommits,nauthors,max_date,gh_ncommits,gh_ncontributors,lastGHCommitDate,commit_diff
WoC,,,,,,,
gsi-cs-co_chart-fx,3633,53,2025-09-25,1189,34,2026-03-13,-2444
bsaul_inferference,328,16,2025-05-14,317,11,2025-05-14,-11
daohu527_dig-into-apollo,425,7,2024-09-04,409,4,2026-02-03,-16
martin2250_opencncpilot,253,15,2025-10-05,205,6,2025-04-28,-48
usgs-astrogeology_isis3,18318,200,2025-09-30,8532,98,2026-09-24,-9786
sakov_enkf-c,1772,7,2025-11-06,1590,4,2026-09-22,-182
sfc-aqua_quisp,4409,87,2025-10-27,2443,33,2026-03-31,-1966
stan-dev_rstanarm,4146,64,2025-10-29,3390,42,2026-09-21,-756
copasi_copasi-dependencies,515,16,2026-03-12,513,12,2026-09-16,-2
almost-matching-exactly_dame-python-package,501,23,2025-09-17,148,5,2025-07-26,-353

In [6]:
# Paste this output into the text cell below
t = woc_stats.join(gh_stats)
print('| Project | #commits | #authors | min time | max time | stars | forks | last GH commit |')
print('|---|---|---|---|---|---|---|---|')
for p, r in t.iterrows():
    print(f"| {p} | {r.ncommits} | {r.nauthors} | {r.mintime} ({r.min_date}) | {r.maxtime} ({r.max_date}) | {r.nstars} | {r.nforks} | {r.lastGHCommitDate} |")

| Project | #commits | #authors | min time | max time | stars | forks | last GH commit |
|---|---|---|---|---|---|---|---|
| gsi-cs-co_chart-fx | 3633 | 53 | 1557246279 (2019-05-07) | 1758770120 (2025-09-25) | 613 | 110 | 2026-03-13 |
| bsaul_inferference | 328 | 16 | 1404407958 (2014-07-03) | 1747234885 (2025-05-14) | 6 | 2 | 2025-05-14 |
| daohu527_dig-into-apollo | 425 | 7 | 1554864597 (2019-04-10) | 1725447268 (2024-09-04) | 2457 | 714 | 2026-02-03 |
| martin2250_opencncpilot | 253 | 15 | 1474378401 (2016-09-20) | 1759704094 (2025-10-05) | 427 | 124 | 2025-04-28 |
| usgs-astrogeology_isis3 | 18318 | 200 | 1276037385 (2010-06-08) | 1759270719 (2025-09-30) | 245 | 182 | 2026-09-24 |
| sakov_enkf-c | 1772 | 7 | 1403133737 (2014-06-18) | 1762472241 (2025-11-06) | 47 | 25 | 2026-09-22 |
| sfc-aqua_quisp | 4409 | 87 | 1524058198 (2018-04-18) | 1761562984 (2025-10-27) | 109 | 43 | 2026-03-31 |
| stan-dev_rstanarm | 4146 | 64 | 1373994672 (2013-07-16) | 1761779325 (2025-10-29) | 401 | 136 | 2026-09-21 |
| copasi_copasi-dependencies | 515 | 16 | 1362398954 (2013-03-04) | 1773320863 (2026-03-12) | 7 | 3 | 2026-09-16 |
| almost-matching-exactly_dame-python-package | 501 | 23 | 1564697002 (2019-08-01) | 1758126548 (2025-09-17) | 64 | 15 | 2025-07-26 |

## Results (WoC + GitHub)

| Project | #commits | #authors | min time | max time | stars | forks | last GH commit |
|---|---|---|---|---|---|---|---|
| gsi-cs-co_chart-fx | 3633 | 53 | 1557246279 (2019-05-07) | 1758770120 (2025-09-25) | 613 | 110 | 2026-03-13 |
| bsaul_inferference | 328 | 16 | 1404407958 (2014-07-03) | 1747234885 (2025-05-14) | 6 | 2 | 2025-05-14 |
| daohu527_dig-into-apollo | 425 | 7 | 1554864597 (2019-04-10) | 1725447268 (2024-09-04) | 2457 | 714 | 2026-02-03 |
| martin2250_opencncpilot | 253 | 15 | 1474378401 (2016-09-20) | 1759704094 (2025-10-05) | 427 | 124 | 2025-04-28 |
| usgs-astrogeology_isis3 | 18318 | 200 | 1276037385 (2010-06-08) | 1759270719 (2025-09-30) | 245 | 182 | 2026-09-24 |
| sakov_enkf-c | 1772 | 7 | 1403133737 (2014-06-18) | 1762472241 (2025-11-06) | 47 | 25 | 2026-09-22 |
| sfc-aqua_quisp | 4409 | 87 | 1524058198 (2018-04-18) | 1761562984 (2025-10-27) | 109 | 43 | 2026-03-31 |
| stan-dev_rstanarm | 4146 | 64 | 1373994672 (2013-07-16) | 1761779325 (2025-10-29) | 401 | 136 | 2026-09-21 |
| copasi_copasi-dependencies | 515 | 16 | 1362398954 (2013-03-04) | 1773320863 (2026-03-12) | 7 | 3 | 2026-09-16 |
| almost-matching-exactly_dame-python-package | 501 | 23 | 1564697002 (2019-08-01) | 1758126548 (2025-09-17) | 64 | 15 | 2025-07-26 |

**Notes:**
- WoC counts exceed GitHub's for every project. GitHub's count covers only the default branch, while WoC includes commits from all branches and forks linked to the project; the gap is largest for ISIS3 (+9,786), chart-fx (+2,444) and quisp (+1,966).
- WoC data runs to late 2025–early 2026, so GitHub shows newer commits for most projects.
- OpenCNCPilot and DAME have later WoC commits than their last default-branch commit on GitHub, likely from other branches or forks.
- WoC authors are raw `name <email>` identities, so one person using several emails is counted more than once. This is why WoC author counts exceed GitHub contributor counts.
- 33 commits (<0.1%) could not be retrieved from WoC.
- Three repos have moved: chart-fx → fair-acc/chart-fx, ISIS3 → DOI-USGS/ISIS3, DAME → DAME-FLAME-Python-Package.

# Commit this notebook AND the csv files to your fork!